// src/introspect.js — Entity Generator
// Reverse-engineers an existing SQLite database into a .lite schema file.
//
// Usage:
//   litestone introspect ./existing.db --out schema.lite
//   litestone introspect ./existing.db   (prints to stdout)
//
// Handles:
//   - Column types (SQLite → .lite types)
//   - Primary keys, NOT NULL, defaults
//   - Foreign keys → @relation
//   - UNIQUE / multi-column indexes → @@index / @@unique
//   - Soft delete detection (deletedAt column)
//   - Enum detection from CHECK constraints
//   - STRICT tables → @@noStrict absent (STRICT is default in .lite)
//   - camelCase conversion from snake_case table/column names

import { introspect } from '../core/migrate.js'

// ─── Type mapping: SQLite types → .lite types ─────────────────────────────────

const TYPE_MAP = {
  'INTEGER': 'Integer',
  'INT':     'Integer',
  'BIGINT':  'Integer',
  'SMALLINT':'Integer',
  'TINYINT': 'Integer',
  'REAL':    'Real',
  'FLOAT':   'Real',
  'DOUBLE':  'Real',
  'NUMERIC': 'Real',
  'DECIMAL': 'Real',
  'TEXT':    'Text',
  'VARCHAR': 'Text',
  'CHAR':    'Text',
  'CLOB':    'Text',
  'BLOB':    'Blob',
  'BYTES':   'Blob',
  'BOOLEAN': 'Boolean',
  'BOOL':    'Boolean',
}

function sqliteTypeToLite(rawType) {
  if (!rawType) return 'Text'
  const upper = rawType.toUpperCase().split('(')[0].trim()
  return TYPE_MAP[upper] ?? 'Text'
}

// ─── Name helpers ──────────────────────────────────────────────────────────────

function toCamelCase(str) {
  return str.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
}

function toPascalCase(str) {
  const camel = toCamelCase(str)
  return camel.charAt(0).toUpperCase() + camel.slice(1)
}

// Basic singularizer — mirrors the pluralizer in ddl.js
// Used when introspecting a pluralized schema back to singular model names.
function toSingular(word) {
  const irregularsReverse = {
    people: 'person', children: 'child', men: 'man', women: 'woman',
    teeth: 'tooth', feet: 'foot', mice: 'mouse', geese: 'goose',
    oxen: 'ox', leaves: 'leaf', lives: 'life', knives: 'knife',
    indices: 'index', matrices: 'matrix', vertices: 'vertex',
    analyses: 'analysis', bases: 'basis', crises: 'crisis',
    data: 'datum', media: 'medium', criteria: 'criterion',
  }
  const lower = word.toLowerCase()
  if (irregularsReverse[lower]) return word.slice(0, word.length - lower.length) + irregularsReverse[lower]
  if (/ies$/i.test(word))  return word.slice(0, -3) + 'y'
  if (/ses$|xes$|zes$|ches$|shes$/i.test(word)) return word.slice(0, -2)
  if (/s$/i.test(word) && !/ss$/i.test(word))   return word.slice(0, -1)
  return word
}

// Table name → PascalCase singular model name
// "users"             → "User"
// "service_agreements" → "ServiceAgreement"
// "people"            → "Person"
function tableNameToModelName(tableName) {
  return toPascalCase(toSingular(tableName))
}

// ─── Default value rendering ───────────────────────────────────────────────────

function renderDefault(def, liteType) {
  if (def === null || def === undefined) return null
  const s = String(def).trim()

  // SQLite functions
  if (/^(strftime|datetime|date|time|now)\(/i.test(s)) return '@default(now())'
  if (s === 'CURRENT_TIMESTAMP' || s === 'CURRENT_DATE') return '@default(now())'

  if (liteType === 'Boolean') {
    if (s === '0') return '@default(false)'
    if (s === '1') return '@default(true)'
  }

  // Numeric literal
  if (/^-?\d+(\.\d+)?$/.test(s)) return `@default(${s})`

  // String literal — strip surrounding quotes
  const unquoted = s.replace(/^['"]|['"]$/g, '')
  return `@default("${unquoted}")`
}

// ─── Enum detection from CHECK constraints ────────────────────────────────────
// Looks for: CHECK (col IN ('a', 'b', 'c'))

function detectEnumFromCheck(tableSql, columnName) {
  if (!tableSql) return null
  // Match: CHECK("col" IN (...)) or CHECK(col IN (...))
  const re = new RegExp(
    `CHECK\\s*\\(\\s*["'\`]?${columnName}["'\`]?\\s+IN\\s*\\(([^)]+)\\)`,
    'i'
  )
  const m = tableSql.match(re)
  if (!m) return null
  const values = m[1]
    .split(',')
    .map(v => v.trim().replace(/^['"]|['"]$/g, ''))
    .filter(Boolean)
  return values.length >= 2 ? values : null
}

// ─── Generate .lite source ────────────────────────────────────────────────────

export function generateLiteSchema(db, { camelCase = true } = {}) {
  const schema = introspect(db)
  const lines  = [
    '/// Generated by litestone introspect',
    '/// Note: @@allow, @@deny, @allow, @secret, @secret, @@log, @@gate, @@fts',
    '/// and other application-level attributes cannot be reverse-engineered from',
    '/// the SQLite schema — add them manually after reviewing the output.',
    '',
  ]

  // Collect enums discovered from CHECK constraints
  const enumDefs = {}   // enumName → Set<string>
  const columnEnumMap = {}  // `table.column` → enumName

  // First pass — detect enums
  const tableSqls = {}
  for (const tableName of Object.keys(schema)) {
    if (tableName === '__views' || !schema[tableName]?.columns) continue
    const row = db.prepare(
      `SELECT sql FROM sqlite_master WHERE type='table' AND name=?`
    ).get(tableName)
    tableSqls[tableName] = row?.sql ?? ''
  }

  for (const [tableName, tableInfo] of Object.entries(schema)) {
    if (tableName === '__views' || !tableInfo?.columns) continue  // skip metadata keys
    const { columns } = tableInfo
    const modelName = tableNameToModelName(tableName)
    for (const col of columns) {
      const vals = detectEnumFromCheck(tableSqls[tableName], col.name)
      if (!vals) continue
      // Try to name the enum: ModelField
      const fieldName = camelCase ? toCamelCase(col.name) : col.name
      const enumName  = modelName + toPascalCase(fieldName)
      if (!enumDefs[enumName]) {
        enumDefs[enumName] = new Set(vals)
      }
      columnEnumMap[`${tableName}.${col.name}`] = enumName
    }
  }

  // Emit enums
  for (const [name, vals] of Object.entries(enumDefs)) {
    lines.push(`enum ${name} {`)
    for (const v of vals) lines.push(`  ${v}`)
    lines.push('}')
    lines.push('')
  }

  // Second pass — emit models
  for (const [tableName, tableData] of Object.entries(schema)) {
    if (tableName === '__views' || !tableData?.columns) continue
    const { columns, indexes, foreignKeys, strict } = tableData
    const modelName = tableNameToModelName(tableName)

    // Build FK lookup: foreignKey column → { targetTable, targetCol, onDelete }
    const fkByCol = {}
    for (const fk of foreignKeys) {
      const fromCol = Array.isArray(fk.from) ? fk.from[0] : fk.from
      fkByCol[fromCol] = fk
    }

    // Detect soft delete
    const hasSoftDelete = columns.some(c => c.name === 'deletedAt' || c.name === 'deleted_at')

    lines.push(`model ${modelName} {`)

    // Emit relation fields (virtual, above FK columns)
    for (const fk of foreignKeys) {
      const fromCol   = Array.isArray(fk.from) ? fk.from[0] : fk.from
      const toCol     = Array.isArray(fk.to)   ? fk.to[0]   : fk.to
      const refModel  = tableNameToModelName(fk.table)
      const fieldName = camelCase ? toCamelCase(fk.table) : fk.table
      const fromField = camelCase ? toCamelCase(fromCol) : fromCol
      const toField   = camelCase ? toCamelCase(toCol)   : toCol
      const onDelete  = fk.onDelete && fk.onDelete !== 'NO ACTION' ? ` onDelete: ${fk.onDelete}` : ''
      lines.push(`  ${fieldName}  ${refModel}  @relation(fields: [${fromField}], references: [${toField}]${onDelete})`)
    }

    // Emit scalar columns
    for (const col of columns) {
      const fieldName   = camelCase ? toCamelCase(col.name) : col.name
      const isFKCol     = col.name in fkByCol
      const enumKey     = `${tableName}.${col.name}`
      const enumName    = columnEnumMap[enumKey]
      const liteType    = enumName ? enumName : sqliteTypeToLite(col.type)
      const optional    = !col.notnull && !col.pk ? '?' : ''
      const attrs       = []

      if (col.pk)                       attrs.push('@id')
      if (!col.notnull && !col.pk)      {} // optional suffix handles it
      const defAttr = col.default !== null ? renderDefault(col.default, liteType) : null
      if (defAttr)                      attrs.push(defAttr)

      // Check for unique index on this column alone
      const soloUnique = indexes.find(idx => idx.unique && idx.cols.length === 1 && idx.cols[0] === col.name)
      if (soloUnique)                   attrs.push('@unique')

      // camelCase columns that differ from their DB name
      if (camelCase && fieldName !== col.name) {
        attrs.push(`@map("${col.name}")`)
      }

      const attrStr = attrs.length ? '  ' + attrs.join(' ') : ''
      lines.push(`  ${fieldName}  ${liteType}${optional}${attrStr}`)
    }

    // Model-level attributes
    const modelAttrs = []

    if (!strict) modelAttrs.push('  @@noStrict')
    if (hasSoftDelete) modelAttrs.push('  @@softDelete')

    // Multi-column indexes
    for (const idx of indexes) {
      if (idx.cols.length <= 1) continue  // solo ones handled per-column
      const colList = idx.cols.map(c => camelCase ? toCamelCase(c) : c).join(', ')
      if (idx.unique) {
        modelAttrs.push(`  @@unique([${colList}])`)
      } else {
        modelAttrs.push(`  @@index([${colList}])`)
      }
    }

    for (const attr of modelAttrs) lines.push(attr)

    lines.push('}')
    lines.push('')
  }

  return lines.join('\n').trimEnd() + '\n'
}
