// src/typegen.js — TypeScript type generation from .lite schema
//
// Generates a .d.ts file with:
//   - Enum union types
//   - Row types     (what findMany/findFirst returns)
//   - Create types  (what create({ data: ... }) accepts)
//   - Update types  (what update({ data: ... }) accepts — all optional)
//   - Where types   (what where: { ... } accepts)
//   - WhereOp<T>    (gt, gte, lt, lte, in, not, contains, startsWith, endsWith)
//   - Typed LitestoneClient interface

// ─── Helpers ─────────────────────────────────────────────────────────────────

// Model names in .lite are conventionally lowercase (users, posts) or PascalCase (User, Post).
// TypeScript interfaces should always be PascalCase.
function pascal(name) {
  return name.charAt(0).toUpperCase() + name.slice(1)
}

// ─── Entry point ──────────────────────────────────────────────────────────────

/**
 * Generate TypeScript declarations from a parsed Litestone schema.
 *
 * @param {object} schema   parseResult.schema
 * @param {object} [opts]
 * @param {string} [opts.audience='client']   'client' strips @guarded/@secret; 'system' includes all
 * @param {boolean} [opts.includeComments=true]  emit JSDoc comments on fields
 * @returns {string}  contents of a .d.ts file
 */
export function generateTypeScript(schema, opts = {}) {
  const {
    audience        = 'client',
    includeComments = true,
  } = opts

  const lines = []

  // Header
  lines.push(
    `// Generated by @frontierjs/litestone`,
    `// Do not edit — re-run \`litestone types\` to regenerate`,
    ``,
  )

  // ── WhereOp utility type (emitted once at top) ───────────────────────────────
  lines.push(
    `// ── Utility types ────────────────────────────────────────────────────────────`,
    ``,
    `export type WhereOp<T> = {`,
    `  not?:        T | null`,
    `  in?:         T[]`,
    `  notIn?:      T[]`,
    `  lt?:         T`,
    `  lte?:        T`,
    `  gt?:         T`,
    `  gte?:        T`,
    `  contains?:   string`,
    `  startsWith?: string`,
    `  endsWith?:   string`,
    `}`,
    ``,
    `export type OrderDir = 'asc' | 'desc'`,
    ``,
    `/** Base type mixed into every Where interface — adds the $raw escape hatch. */`,
    `export interface WhereBase {`,
    `  /** Raw SQL predicate. Use the sql\`\` tag for safe parameter binding. */`,
    `  $raw?: { _litestoneRaw: true; sql: string; params: unknown[] } | string`,
    `}`,
    ``,
  )

  // ── Enums ────────────────────────────────────────────────────────────────────
  if (schema.enums.length) {
    lines.push(`// ── Enums ────────────────────────────────────────────────────────────────────`, ``)
    for (const en of schema.enums) {
      const values = en.values.map(v => `'${v.name}'`).join(' | ')
      lines.push(`export type ${en.name} = ${values}`, ``)
    }
  }

  // ── Types ────────────────────────────────────────────────────────────────────
  // `type T { ... }` declarations become TypeScript interfaces. They're emitted
  // once at the top level so they can be referenced by every Json @type(T) field
  // and by application code that needs to construct or read these values.
  const modelNames = schema.models.map(m => m.name)
  if (schema.types?.length) {
    lines.push(`// ── Types ────────────────────────────────────────────────────────────────────`, ``)
    for (const t of schema.types) {
      if (includeComments && t.comments?.length) {
        lines.push(`/**`)
        for (const c of t.comments) lines.push(` * ${c}`)
        lines.push(` */`)
      }
      lines.push(`export interface ${pascal(t.name)} {`)
      for (const field of t.fields) {
        const tsType = fieldToTs(field, schema, modelNames, /* nullable */ field.type.optional)
        const optional = field.type.optional
        if (includeComments && field.comments?.length) {
          if (field.comments.length === 1) {
            lines.push(`  /** ${field.comments[0]} */`)
          } else {
            lines.push(`  /**`)
            for (const c of field.comments) lines.push(`   * ${c}`)
            lines.push(`   */`)
          }
        }
        lines.push(`  ${field.name}${optional ? '?' : ''}: ${tsType}`)
      }
      lines.push(`}`, ``)
    }
  }

  // ── FileRef (if any model has File fields) ───────────────────────────────────
  const hasFileFields = schema.models.some(m =>
    m.fields.some(f => f.type.name === 'File' && f.type.kind === 'scalar')
  )
  if (hasFileFields) {
    lines.push(
      `// ── FileRef — stored JSON reference for File fields ─────────────────────────`,
      ``,
      `export interface FileRef {`,
      `  key:        string`,
      `  bucket:     string`,
      `  provider:   string`,
      `  size:       number`,
      `  mime:       string`,
      `  uploadedAt: string`,
      `}`,
      ``,
    )
  }

  // ── Per-model types ──────────────────────────────────────────────────────────
  lines.push(`// ── Models ───────────────────────────────────────────────────────────────────`, ``)

  for (const model of schema.models) {
    const isSoftDelete = model.attributes.some(a => a.kind === 'softDelete')
    const dbAttr       = model.attributes.find(a => a.kind === 'db')
    const dbName       = dbAttr?.name ?? 'main'

    lines.push(`// ─── ${pascal(model.name)} ${'─'.repeat(Math.max(0, 60 - model.name.length))}`)
    lines.push(``)

    // ── Row type ─────────────────────────────────────────────────────────────
    // Model-level doc comment above the Row interface
    if (includeComments && model.comments?.length) {
      lines.push(`/**`)
      for (const c of model.comments) lines.push(` * ${c}`)
      lines.push(` */`)
    }
    lines.push(`export interface ${pascal(model.name)} {`)
    for (const field of model.fields) {
      if (field.type.kind === 'relation') continue
      const spec = fieldRowSpec(field, schema, audience, modelNames)
      if (!spec) continue
      if (includeComments) {
        const docLines = field.comments?.length ? [...field.comments] : []
        if (spec.comment) docLines.push(spec.comment)
        if (docLines.length === 1) {
          lines.push(`  /** ${docLines[0]} */`)
        } else if (docLines.length > 1) {
          lines.push(`  /**`)
          for (const c of docLines) lines.push(`   * ${c}`)
          lines.push(`   */`)
        }
      }
      lines.push(`  ${spec.name}${spec.optional ? '?' : ''}: ${spec.tsType}`)
    }
    lines.push(`}`)
    lines.push(``)

    // ── Create type ──────────────────────────────────────────────────────────
    lines.push(`export interface ${pascal(model.name)}Create {`)
    for (const field of model.fields) {
      if (field.type.kind === 'relation') continue
      const spec = fieldCreateSpec(field, schema, audience, modelNames)
      if (!spec) continue
      if (includeComments && field.comments?.length) {
        if (field.comments.length === 1) {
          lines.push(`  /** ${field.comments[0]} */`)
        } else {
          lines.push(`  /**`)
          for (const c of field.comments) lines.push(`   * ${c}`)
          lines.push(`   */`)
        }
      }
      lines.push(`  ${spec.name}${spec.optional ? '?' : ''}: ${spec.tsType}`)
    }
    lines.push(`}`)
    lines.push(``)

    // ── Update type (all optional) ───────────────────────────────────────────
    lines.push(`export interface ${pascal(model.name)}Update {`)
    for (const field of model.fields) {
      if (field.type.kind === 'relation') continue
      const spec = fieldUpdateSpec(field, schema, audience, modelNames)
      if (!spec) continue
      lines.push(`  ${spec.name}?: ${spec.tsType}`)
    }
    lines.push(`}`)
    lines.push(``)

    // ── Where type ───────────────────────────────────────────────────────────
    lines.push(`export interface ${pascal(model.name)}Where extends WhereBase {`)
    for (const field of model.fields) {
      if (field.type.kind === 'relation') continue
      const spec = fieldWhereSpec(field, schema, modelNames)
      if (!spec) continue
      lines.push(`  ${spec.name}?: ${spec.tsType}`)
    }
    lines.push(`  AND?: ${pascal(model.name)}Where[]`)
    lines.push(`  OR?:  ${pascal(model.name)}Where[]`)
    lines.push(`  NOT?: ${pascal(model.name)}Where`)
    lines.push(`}`)
    lines.push(``)

    // ── OrderBy type ─────────────────────────────────────────────────────────
    lines.push(`export type ${pascal(model.name)}OrderBy =`)
    lines.push(`  | { [K in keyof Omit<${pascal(model.name)}, never>]?: OrderDir }`)
    lines.push(`  | Array<{ [K in keyof Omit<${pascal(model.name)}, never>]?: OrderDir }>`)
    lines.push(``)
  }

  // ── Cursor result ────────────────────────────────────────────────────────────
  lines.push(
    `// ── Cursor pagination result ─────────────────────────────────────────────────`,
    ``,
    `export interface CursorResult<T> {`,
    `  items:      T[]`,
    `  nextCursor: string | null`,
    `  hasMore:    boolean`,
    `}`,
    ``,
  )

  // ── TableClient generic ──────────────────────────────────────────────────────
  lines.push(
    `// ── Table client interface ───────────────────────────────────────────────────`,
    ``,
    `export interface TableClient<TRow, TCreate, TUpdate, TWhere> {`,
    `  findMany(args?: { where?: TWhere; orderBy?: any; limit?: number; offset?: number; include?: any; select?: any; withDeleted?: boolean; onlyDeleted?: boolean }): Promise<TRow[]>`,
    `  findFirst(args?: { where?: TWhere; orderBy?: any; include?: any; select?: any }): Promise<TRow | null>`,
    `  findUnique(args: { where: TWhere; include?: any; select?: any }): Promise<TRow | null>`,
    `  findFirstOrThrow(args?: { where?: TWhere }): Promise<TRow>`,
    `  findUniqueOrThrow(args: { where: TWhere }): Promise<TRow>`,
    `  findManyCursor(args?: { where?: TWhere; orderBy?: any; limit?: number; cursor?: string }): Promise<CursorResult<TRow>>`,
    `  count(args?: { where?: TWhere }): Promise<number>`,
    `  create(args: { data: TCreate; include?: any; select?: any }): Promise<TRow>`,
    `  createMany(args: { data: TCreate[] }): Promise<{ count: number }>`,
    `  update(args: { where: TWhere; data: TUpdate; include?: any; select?: any }): Promise<TRow | null>`,
    `  updateMany(args: { where?: TWhere; data: TUpdate }): Promise<{ count: number }>`,
    `  upsert(args: { where: TWhere; create: TCreate; update: TUpdate; include?: any; select?: any }): Promise<TRow>`,
    `  upsertMany(args: { data: TCreate[]; conflictTarget?: string[]; update?: string[] }): Promise<{ count: number }>`,
    `  remove(args: { where: TWhere }): Promise<TRow | null>`,
    `  removeMany(args?: { where?: TWhere }): Promise<{ count: number }>`,
    `  restore(args: { where: TWhere }): Promise<{ count: number }>`,
    `  delete(args: { where: TWhere }): Promise<TRow | null>`,
    `  deleteMany(args?: { where?: TWhere }): Promise<{ count: number }>`,
    `  search(query: string, args?: { where?: TWhere; limit?: number; offset?: number }): Promise<TRow[]>`,
    `  optimizeFts(): Promise<void>`,
    `}`,
    ``,
  )

  // ── QueryEvent (for onQuery) ──────────────────────────────────────────────────
  lines.push(
    `// ── onQuery event ────────────────────────────────────────────────────────────`,
    ``,
    `export interface QueryEvent {`,
    `  model:     string`,
    `  operation: 'findMany' | 'findFirst' | 'findUnique' | 'findManyCursor' | 'count' | 'search' | 'create' | 'createMany' | 'update' | 'updateMany' | 'upsertMany' | 'remove' | 'removeMany' | 'restore' | 'delete' | 'deleteMany'`,
    `  database:  string`,
    `  actorId:   string | number | null`,
    `  sql:       string`,
    `  params:    unknown[]`,
    `  duration:  number`,
    `  rowCount:  number`,
    `  args:      Record<string, unknown>`,
    `}`,
    ``,
  )

  // ── LitestoneClient interface ────────────────────────────────────────────────
  lines.push(
    `// ── LitestoneClient ──────────────────────────────────────────────────────────`,
    ``,
    `export interface LitestoneClient {`,
  )

  // One entry per model
  for (const model of schema.models) {
    lines.push(
      `  readonly ${model.name}: TableClient<${pascal(model.name)}, ${pascal(model.name)}Create, ${pascal(model.name)}Update, ${pascal(model.name)}Where>`
    )
  }

  lines.push(
    ``,
    `  // Auth scoping`,
    `  asSystem(): LitestoneClient`,
    `  $setAuth(user: Record<string, unknown>): LitestoneClient`,
    ``,
    `  // Transactions`,
    `  $transaction<T>(fn: (tx: LitestoneClient) => Promise<T>): Promise<T>`,
    ``,
    `  // Raw SQL`,
    `  sql(strings: TemplateStringsArray, ...values: unknown[]): Promise<Record<string, unknown>[]>`,
    ``,
    `  // Query tap (temporary capture)`,
    `  $tapQuery(fn: (event: QueryEvent) => void): () => void`,
    ``,
    `  // Utilities`,
    `  $backup(dest: string, opts?: { vacuum?: boolean }): Promise<{ path: string; size: number }>`,
    `  $attach(path: string, alias: string): void`,
    `  $detach(alias: string): void`,
    `  $close(): void`,
    ``,
    `  // Introspection`,
    `  readonly $schema:     Record<string, unknown>`,
    `  readonly $databases:  Record<string, { driver: string; access: string; path: string }>`,
    `  readonly $softDelete: Record<string, boolean>`,
    `  readonly $enums:      Record<string, string[]>`,
    `  readonly $cacheSize:  { read: number; write: number }`,
    `  readonly $attached:   string[]`,
    `}`,
    ``,
  )

  // ── createClient ─────────────────────────────────────────────────────────────
  lines.push(
    `// ── createClient ─────────────────────────────────────────────────────────────`,
    ``,
    `export interface CreateClientOptions {`,
    `  /** Path to a .lite schema file */`,
    `  path?:        string`,
    `  /** Inline schema string */`,
    `  schema?:      string`,
    `  /** Pre-parsed result from parseFile() */`,
    `  parsed?:      Record<string, unknown>`,
    `  db?:          string`,
    `  encryption?:  { key: string }`,
    `  computed?:    Record<string, Record<string, (row: unknown, ctx: unknown) => unknown>> | string`,
    `  plugins?:     unknown[]`,
    `  onQuery?:     (event: QueryEvent) => void | Promise<void>`,
    `  onEvent?:     Record<string, (event: unknown, ctx: unknown) => void>`,
    `  onLog?:       (entry: unknown, ctx: unknown) => Record<string, unknown> | void`,
    `  filters?:     Record<string, Record<string, unknown> | ((ctx: unknown) => Record<string, unknown>)>`,
    `  policyDebug?: boolean | 'verbose'`,
    `  hooks?:       Record<string, unknown>`,
    `  onEvent?:     Record<string, (event: unknown, ctx: unknown) => void>`,
    `}`,
    ``,
    `export declare function createClient(`,
    `  options: CreateClientOptions`,
    `): Promise<LitestoneClient>`,
    ``,
  )

  return lines.join('\n')
}

// ─── Field spec helpers ───────────────────────────────────────────────────────
// Each returns { name, tsType, optional, comment } or null (skip field)

function fieldRowSpec(field, schema, audience, modelNames) {
  const { name, type, attributes } = field

  // Always skip relations — virtual
  if (type.kind === 'relation') return null

  // @guarded(all) / @secret — strip for client audience
  const isGuardedAll = attributes.some(a => a.kind === 'guarded' && a.level === 'all')
                    || attributes.some(a => a.kind === 'secret')
  if (isGuardedAll && audience === 'client') return null

  const tsType  = fieldToTs(field, schema, modelNames)
  const optional = type.optional || isGuardedAll  // guarded fields may be absent even in system reads

  const commentParts = []
  if (attributes.some(a => a.kind === 'guarded'))  commentParts.push('@guarded')
  if (attributes.some(a => a.kind === 'updatedBy')) commentParts.push('@updatedBy')
  if (attributes.some(a => a.kind === 'encrypted')) commentParts.push('@encrypted')
  if (attributes.some(a => a.kind === 'secret'))    commentParts.push('@secret')
  if (attributes.some(a => a.kind === 'computed'))  commentParts.push('@computed')
  if (attributes.some(a => a.kind === 'from'))       commentParts.push('@from')
  if (attributes.some(a => a.kind === 'generated' || a.kind === 'funcCall')) commentParts.push('generated')

  return { name, tsType, optional: type.optional, comment: commentParts.join(' ') || null }
}

function fieldCreateSpec(field, schema, audience, modelNames) {
  const { name, type, attributes } = field

  if (type.kind === 'relation') return null

  // Skip computed / generated — db handles these
  if (attributes.some(a => a.kind === 'computed' || a.kind === 'generated' || a.kind === 'funcCall' || a.kind === 'from')) return null

  // Skip @guarded(all) / @secret for client audience
  const isGuardedAll = attributes.some(a => a.kind === 'guarded' && a.level === 'all')
                    || attributes.some(a => a.kind === 'secret')
  if (isGuardedAll && audience === 'client') return null

  // Skip auto-managed timestamps and @updatedBy (stamped automatically on update)
  if (name === 'createdAt' || name === 'updatedAt' || name === 'deletedAt') return null
  if (attributes.some(a => a.kind === 'updatedBy')) return null

  const isId      = attributes.some(a => a.kind === 'id')
  const hasDefault = attributes.some(a => a.kind === 'default')
  const isAuthDefault = attributes.find(a => a.kind === 'default')?.value?.kind === 'call'
                     && attributes.find(a => a.kind === 'default')?.value?.fn === 'auth'

  const tsType = fieldToTs(field, schema, modelNames, false)

  // Optional in create if: has @default, is nullable, is @id (auto-increment), or auth()-stamped
  const optional = type.optional || isId || (hasDefault && !isAuthDefault)

  return { name, tsType, optional, comment: null }
}

function fieldUpdateSpec(field, schema, audience, modelNames) {
  const { name, type, attributes } = field

  if (type.kind === 'relation') return null
  if (attributes.some(a => a.kind === 'computed' || a.kind === 'generated' || a.kind === 'funcCall' || a.kind === 'from')) return null
  if (name === 'createdAt' || name === 'updatedAt' || name === 'deletedAt') return null

  const isGuardedAll = attributes.some(a => a.kind === 'guarded' && a.level === 'all')
                    || attributes.some(a => a.kind === 'secret')
  if (isGuardedAll && audience === 'client') return null

  const tsType = fieldToTs(field, schema, modelNames, false)
  return { name, tsType, optional: true, comment: null }
}

function fieldWhereSpec(field, schema, modelNames) {
  const { name, type } = field
  if (type.kind === 'relation') return null

  const base = fieldToTs(field, schema, modelNames, false)
  // Where accepts the scalar value OR a WhereOp object
  const tsType = `${base} | WhereOp<${base}> | null`
  return { name, tsType, optional: true, comment: null }
}

// ─── TypeScript type string for a field ──────────────────────────────────────

function fieldToTs(field, schema, modelNames, nullable = true) {
  const { type, attributes } = field
  let base

  // Enum types
  if (type.kind === 'enum' || isEnumName(type.name, schema)) {
    base = pascal(type.name)
  } else {
    switch (type.name) {
      case 'Integer':  base = 'number';  break
      case 'Real':     base = 'number';  break
      case 'Text':     base = 'string';  break
      case 'Boolean':  base = 'boolean'; break
      case 'DateTime': base = 'string';  break   // ISO-8601 string
      case 'Json': {
        // Json @type(T) → use the type's interface name. Otherwise unknown.
        const typeAttr = attributes.find(a => a.kind === 'type')
        if (typeAttr) {
          base = pascal(typeAttr.name)
        } else {
          base = 'unknown'
        }
        break
      }
      case 'Blob':     base = 'Buffer';  break
      case 'File':     base = 'FileRef'; break
      default:
        // Could be a model name (M2M) — use generic
        if (modelNames.includes(type.name)) {
          base = pascal(type.name)
        } else {
          base = 'unknown'
        }
    }
  }

  // @encrypted fields — stored as ciphertext string, returned as string (decrypted by ORM)
  // Keep as string (the ORM handles encrypt/decrypt transparently)

  if (type.array) base = `${base}[]`

  if (nullable && type.optional) base = `${base} | null`

  return base
}

function isEnumName(name, schema) {
  return schema.enums.some(e => e.name === name)
}
