/**
 * tests/routes-snapshot.test.js — the committed route table
 *
 * What these guard is why the file is committed: a route table is a naming
 * convention over a file tree, so every fact in it moves when a file moves and
 * nothing in the app refers to either by name. The assertions are about the
 * facts that are invisible elsewhere — which layout wraps a page, what meta a
 * layout pushed down onto every page under it, and `publishes:`, which turns
 * off the check that refuses to prerender gated data.
 */

import { describe, it, expect } from 'vitest'
import { resolve, dirname }     from 'path'
import { fileURLToPath }        from 'url'

import { scan }                  from '../src/scanner/index.js'
import { renderRoutesSnapshot }  from '../src/tools/routes-snapshot.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FIXTURE   = resolve(__dirname, 'fixtures/basic-spa')

const render = (tree, opts = {}) => renderRoutesSnapshot(tree, {
  source:  'config/sierra.config.js',
  command: 'sierra routes --config config/sierra.config.js',
  ...opts,
})

describe('sierra routes — the snapshot', () => {

  it('names the command that regenerates it, and renders the same bytes twice', async () => {
    const tree  = await scan('src/routes', { cwd: FIXTURE })
    const once  = render(tree)
    const twice = render(await scan('src/routes', { cwd: FIXTURE }))

    // scripts/ci.mjs reads this line and reruns it with --check. A snapshot
    // that does not name its generator cannot be checked by anything.
    expect(once).toContain('<!-- generated by: sierra routes --config config/sierra.config.js -->')
    // A byte compare is the whole mechanism — any instability turns the CI
    // phase into noise everyone learns to ignore.
    expect(twice).toBe(once)
  })

  it('records which layout resolved for a page, which is a directory fact', async () => {
    const tree = await scan('src/routes', { cwd: FIXTURE })
    const out  = render(tree)

    // `/leads/` is wrapped by leads/_module.mesa; `/blog/` by the root one.
    // Moving either _module.mesa rewraps pages and changes nothing else.
    expect(out).toMatch(/\|\s*`\/leads\/`\s*\|[^|]+\|\s*`src\/routes\/leads\/_module\.mesa`/)
    expect(out).toMatch(/\|\s*`\/blog\/`\s*\|[^|]+\|\s*`src\/routes\/_module\.mesa`/)
    // `/login/` declares `reset`, so it is wrapped by nothing — a page opting
    // out of the chrome every other page has, stated in its own frontmatter and
    // visible nowhere else.
    expect(out).toMatch(/\|\s*`\/login\/`\s*\|[^|]+\|\s*—\s*\|/)
    // The layouts section counts what each one wraps, so a boundary in the
    // wrong place is a number that moved.
    expect(out).toContain('## Layouts')
  })

  it('shows meta a layout pushed down onto every page under it', async () => {
    const tree = await scan('src/routes', { cwd: FIXTURE })
    const out  = render(tree)

    // The fixture's leads/_module.meta.js declares meta the pages never mention.
    // Inherited meta is exactly the kind of change that is invisible in the page
    // it affects.
    const leadsLine = out.split('\n').find(l => l.startsWith('- `/leads/`'))
    expect(leadsLine).toBeTruthy()
    expect(leadsLine.length).toBeGreaterThan('- `/leads/` — '.length)
  })

  it('leads a static target with `publishes`, and says so when nothing declares one', async () => {
    const tree = await scan('src/routes', { cwd: FIXTURE })

    const spa    = render(tree, { target: 'spa' })
    const static_ = render(tree, { target: 'static' })

    // On a prerendered target the escape hatch gets its own section, ahead of
    // the routes — the same shape the access snapshot uses for Unrestricted.
    expect(static_).toContain('## Publishes')
    expect(static_).toContain('No route declares one')
    expect(static_.indexOf('## Publishes')).toBeLessThan(static_.indexOf('## Routes'))

    // On an SPA nothing reads `publishes`, so an absent section is correct and a
    // present one would be a claim the target cannot make.
    expect(spa).not.toContain('## Publishes')
  })

  it('drops the system flags a path already shows', async () => {
    const tree = await scan('src/routes', { cwd: FIXTURE })
    const out  = render(tree)

    // `dynamic`, `spread` and `isIndex` are derived from the filename. Restating
    // them beside `/blog/:slug/` is noise that cannot drift, and noise is what
    // stops a diff from being read.
    expect(out).toContain('`/blog/:slug/`')
    expect(out).not.toMatch(/dynamic: `true`/)
    expect(out).not.toMatch(/isIndex: `true`/)
  })
})
