/**
 * widget/index.js — the embed runtime.
 *
 * A widget is one component, built as one self-contained script, mounted on a
 * page this app does not own. That last clause is the whole design:
 *
 *   • **It cannot assume a bundler, a module loader or a framework.** The build
 *     emits IIFE, so the host writes one `<script src>` and nothing else.
 *   • **It cannot leak and cannot be leaked into.** Everything mounts in a
 *     shadow root, so the host page's `* { box-sizing }` and its reset cannot
 *     reach the widget, and the widget's styles cannot reach the host.
 *   • **It cannot choose when it runs.** The script may load before the element
 *     exists, after it, or twice. All three are the same call here.
 *
 * ── Two ways to be found, and why both ────────────────────────────────────
 *
 * A custom element is the better one — `<mt-booking data-pid="42">` upgrades
 * whenever it appears, needs no init call, and gets a teardown hook for free.
 * It is the default and the one to document.
 *
 * A CSS selector is the other, and it is not legacy debt to be ashamed of: a
 * widget's host markup lives on pages the widget's author does not control and
 * often cannot edit — a CMS template, a customer's site, a page generated by
 * somebody else's tool. Those pages say `<div class="mt-booking">`. Declaring
 * `selector` keeps them working while the element form is what new pages use.
 *
 * Both are one mechanism: *find my hosts, mount into each one, exactly once.*
 *
 * ── Props ────────────────────────────────────────────────────────────────
 *
 * `data-*` attributes, camelCased — `data-api-url` → `apiUrl`. That is what a
 * host page can write: HTML attributes are strings, so a widget's props are
 * strings and the widget parses what it needs. JSON in an attribute works
 * (`data-fields='["a","b"]'`) and is the caller's to parse — guessing here would
 * make `data-pid="007"` a number.
 */

import { mount } from '@frontierjs/mesa/runtime'

/**
 * What an unreplaced CSS placeholder starts with — the one definition, which
 * `widget-build.js` builds its full marker from rather than restating.
 *
 * A widget reaches `embed` with the placeholder intact in exactly one case: a
 * dev server, where Vite serves the stylesheet into the document itself. That
 * is recognised HERE rather than in the generated entry, because a comparison
 * there is a constant one and the bundler folds it away before the swap can
 * happen — the first version of this shipped `css: ""` into every widget while
 * every part of it read correctly.
 *
 * **A PREFIX, and that is load-bearing.** This module is bundled INTO the
 * widget, so if it held the whole marker the build's own replacement would hit
 * this constant too — and the widget would then compare its stylesheet against
 * itself, decide it was the placeholder, and drop it. Measured: the CSS was in
 * the file and the element was unstyled.
 */
export const CSS_MARK = '@sierra-widget'

/** Already mounted, keyed by host element. Mounting twice is the common bug. */
const _mounted = new WeakMap()

/** kebab-case, so a component name reaches HTML as a legal tag. */
export function kebab(name) {
  return String(name)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase()
}

/**
 * A custom element name must contain a dash and start with a letter. A widget
 * called `Booking` under the default prefix is `fjs-booking`; one called
 * `booking` with no prefix is not a legal tag, and saying so beats registering
 * nothing and leaving the page blank.
 */
function assertTag(tag) {
  if (!/^[a-z][a-z0-9._]*-[a-z0-9._-]*$/.test(tag)) {
    throw new Error(
      `[Sierra widget] "${tag}" is not a valid custom element name — it must contain a dash ` +
      `and start with a lowercase letter. Set widgets.prefix (e.g. 'mt-') or name the widget ` +
      `with two words.`
    )
  }
  return tag
}

/** `data-api-url="x"` → `{ apiUrl: 'x' }`. The DOM has already camelCased it. */
function propsFrom(el) {
  return { ...el.dataset }
}

/**
 * Mount `Component` into `el`, once.
 *
 * The shadow root is reused when one is already attached — a script that runs
 * twice (two copies on a page, a re-injected tag) must not produce two widgets
 * in one box, and a host that pre-attached a root of its own is honoured.
 */
function mountInto(el, Component, opts) {
  if (_mounted.has(el)) return _mounted.get(el)

  const root = opts.shadow === false
    ? el
    : (el.shadowRoot ?? el.attachShadow({ mode: 'open' }))

  // A host page's element may already hold markup — a spinner, a no-JS
  // fallback, or this widget from a previous mount. Clear it: what renders here
  // is the component, not the component plus whatever was in the way.
  if (opts.shadow === false) el.replaceChildren()

  // The bundle's own stylesheet, folded into the script at build time and put
  // here rather than in the document — see widgetCssPlugin. Mesa's component
  // styles do NOT come through here: mount() registers the shadow root as a
  // style root and they arrive through adoptedStyleSheets. This is everything
  // else the widget imported.
  if (opts.css) {
    const style = document.createElement('style')
    style.textContent = opts.css
    root.appendChild(style)
  }

  const label = document.createComment('widget')
  root.appendChild(label)

  const instance = mount(label, Component, {
    props: { ...opts.props, ...propsFrom(el) },
    // Styles go through adoptedStyleSheets on the shadow root, and event
    // delegation scopes to it. Passing the host element for `shadow: false`
    // keeps both facts true of whatever the root actually is.
    root,
  })

  _mounted.set(el, instance)
  return instance
}

function unmount(el) {
  const instance = _mounted.get(el)
  if (!instance) return
  _mounted.delete(el)
  try { instance.destroy() } catch { /* a host removing the node mid-teardown */ }
}

/**
 * Register a widget and mount it wherever it is asked for.
 *
 * Called by the entry the widget build generates — a widget author writes a
 * `.mesa` file and nothing else. Exported because a hand-written entry is a
 * legitimate thing to have, and because the tests drive it directly.
 *
 * @param {Function} Component        the compiled Mesa component
 * @param {object}   [options]
 * @param {string}   [options.name]     widget name, kebab-cased for the tag
 * @param {string}   [options.prefix]   tag/class prefix, e.g. 'mt-'
 * @param {string}   [options.tag]      the whole tag, overriding prefix+name
 * @param {string}   [options.selector] also mount into elements matching this
 * @param {boolean}  [options.shadow=true]  false mounts in the light DOM
 * @param {object}   [options.props]    defaults, overridden by `data-*`
 * @param {string}   [options.css]      the bundle's stylesheet, injected into
 *                                      each root. The build fills this in
 * @returns {{ tag: string, selector: string|null, mountAll: () => Element[], destroy: () => void }}
 */
export function embed(Component, options = {}) {
  const {
    name = 'widget', prefix = '', selector = null, shadow = true, props = {}, css = '',
  } = options
  const tag = assertTag(options.tag ?? `${prefix}${kebab(name)}`)
  const opts = { shadow, props, css: String(css).startsWith(CSS_MARK) ? '' : css }

  // ── The custom element ────────────────────────────────────────────────
  // Guarded on the registry rather than on a flag of our own: two widget
  // scripts on one page each carry their own copy of this module, so a
  // module-level flag would say "not yet" in both and the second registration
  // would throw where the page is otherwise fine.
  if (typeof customElements !== 'undefined' && !customElements.get(tag)) {
    customElements.define(tag, class extends HTMLElement {
      connectedCallback() { mountInto(this, Component, opts) }
      disconnectedCallback() { unmount(this) }
    })
  }

  // ── The selector form ─────────────────────────────────────────────────
  // Scan now for what is already parsed, and observe for what arrives later —
  // a widget dropped in by a tag manager, a CMS, or a route change on the host
  // page. Without the observer, a `defer` script beats a late-rendered host
  // element and the widget silently never appears.
  let observer = null
  const mountAll = () => {
    if (!selector || typeof document === 'undefined') return []
    const found = [...document.querySelectorAll(selector)]
    for (const el of found) mountInto(el, Component, opts)
    return found
  }

  if (selector && typeof MutationObserver !== 'undefined') {
    mountAll()
    observer = new MutationObserver(() => mountAll())
    // documentElement rather than body: a script in <head> runs before <body>
    // exists, and observing a null target throws.
    observer.observe(document.documentElement, { childList: true, subtree: true })
  }

  return {
    tag,
    selector,
    mountAll,
    /** Stop watching and tear every instance down. Tests and HMR need this. */
    destroy() {
      observer?.disconnect()
      observer = null
      if (selector && typeof document !== 'undefined') {
        for (const el of document.querySelectorAll(selector)) unmount(el)
      }
      if (typeof document !== 'undefined') {
        for (const el of document.querySelectorAll(tag)) unmount(el)
      }
    },
  }
}
