/**
 * llms.js — Generate llms.txt
 *
 * AI-readable site description file.
 *
 * Behavior:
 *   config.llms = false   → never generate (default)
 *   config.llms = true    → generate once, never overwrite
 *   config.llms = 'auto'  → always regenerate
 *
 * public/llms.txt always wins unless config.llms = 'auto'
 */

import { writeFile, access, readFile } from 'fs/promises'
import { join } from 'path'

/**
 * @param {object}   config   — sierra.config.js
 * @param {object}   routeTable — { indexed, tree }
 * @param {string}   outDir
 * @param {string}   root
 * @returns {Promise<string|null>}
 */
export async function generateLlms(config, routeTable, outDir, root) {
  if (!config.llms) return null

  const dest = join(outDir, 'llms.txt')
  const publicSrc = join(root, 'public', 'llms.txt')

  // public/llms.txt wins unless auto
  if (config.llms !== 'auto') {
    try {
      await access(publicSrc)
      // Copy it rather than generating
      const content = await readFile(publicSrc, 'utf8')
      await writeFile(dest, content, 'utf8')
      return 'llms.txt ← public/llms.txt'
    } catch {
      // No public/llms.txt — check if dest already exists (generate once)
      if (config.llms === true) {
        try {
          await access(dest)
          return null  // already exists — don't overwrite
        } catch {
          // Doesn't exist yet — fall through to generate
        }
      }
    }
  }

  const content = buildLlmsTxt(config, routeTable)
  await writeFile(dest, content, 'utf8')
  return 'llms.txt (generated)'
}

function buildLlmsTxt(config, routeTable) {
  const siteName    = config.name ?? config.llmsName ?? 'Site'
  const description = config.description ?? config.llmsDescription ?? ''
  const today       = new Date().toISOString().split('T')[0]

  // Build page list from indexed routes using tree metadata
  const pages = collectPages(routeTable.indexed ?? [], routeTable.tree)

  const lines = [
    `# ${siteName}`,
    ``,
  ]

  if (description) {
    lines.push(`> ${description}`)
    lines.push(``)
  }

  if (pages.length > 0) {
    lines.push(`## Pages`)
    lines.push(``)
    for (const { path, title, description: desc } of pages) {
      // A markdown link target is not free text: a `)` or a space in a slug
      // ends the link early and the rest of the line becomes prose. Same
      // encoder as the sitemap's, for the same reason — the path comes from a
      // `getStaticPaths()` param (`FJS-822`).
      const href  = path.split('/').map(encodeURIComponent).join('/')
      const label = title ? `[${title}](${href})` : href
      const hint  = desc ? `: ${desc}` : ''
      lines.push(`- ${label}${hint}`)
    }
    lines.push(``)
  }

  lines.push(`## Notes`)
  lines.push(``)
  lines.push(`Generated by Sierra on ${today}`)
  lines.push(``)

  return lines.join('\n')
}

/**
 * Collect page info from the route tree for indexed paths.
 */
function collectPages(indexed, tree) {
  if (!tree) return indexed.map(path => ({ path }))

  const nodeMap = new Map()
  flattenTree(tree, nodeMap)

  return indexed.map(path => {
    // Find node by path
    const node = [...nodeMap.values()].find(n => n.path === path)
    return {
      path,
      title:       node?.meta?.title ?? '',
      description: node?.meta?.description ?? '',
    }
  })
}

function flattenTree(node, map) {
  if (node.path) map.set(node.path, node)
  for (const child of node.children ?? []) {
    flattenTree(child, map)
  }
}
