/**
 * redirects.js — Generate _redirects file for Cloudflare/Netlify
 *
 * Format:
 *   /old-path/  /new-path/  301
 *
 * Source: manifest.redirects — [[from, to], ...] pairs
 * from route frontmatter `redirect: /new-path/`
 */

import { writeFile } from 'fs/promises'
import { join } from 'path'

/**
 * @param {Array<[string, string]>} redirects — [[from, to], ...]
 * @param {string} outDir
 * @returns {Promise<string|null>}
 */
export async function generateRedirects(redirects, outDir) {
  if (redirects.length === 0) return null

  const lines = [
    '# _redirects — auto-generated by Sierra',
    '# Cloudflare Pages / Netlify format: FROM  TO  STATUS',
    '',
    ...redirects.map(([from, to]) => `${from}  ${to}  301`),
    '',
  ]

  await writeFile(join(outDir, '_redirects'), lines.join('\n'), 'utf8')
  return `_redirects (${redirects.length} rule${redirects.length === 1 ? '' : 's'})`
}
