// config/routes.js — auto-generated by Sierra — do not edit

// Boot-time tree — metadata only, no component or loader imports
// Component factories are in the 'components' map below
// Loader factories are in the 'loaders' map below
export const tree = {
  id: "root",
  path: "/",
  file: "src/routes/index.mesa",
  companion: null,
  layout: "src/routes/_module.mesa",
  meta: {"siteName":"Kitchen sink","title":"Home","isIndex":true},
  params: [],
  children: [
  {
      id: "cart",
      path: "/cart/",
      file: "src/routes/cart/index.mesa",
      companion: null,
      layout: "src/routes/_module.mesa",
      meta: {"siteName":"Kitchen sink","title":"Basket","isIndex":true},
      params: [],
      children: [],
    },
  {
      id: "customers",
      path: "/customers/",
      file: "src/routes/customers/index.mesa",
      companion: null,
      layout: "src/routes/_module.mesa",
      meta: {"siteName":"Kitchen sink","title":"Customers","isIndex":true},
      params: [],
      children: [],
    },
  {
      id: "inventory",
      path: "/inventory/",
      file: "src/routes/inventory/index.mesa",
      companion: null,
      layout: "src/routes/_module.mesa",
      meta: {"siteName":"Kitchen sink","title":"Inventory","isIndex":true},
      params: [],
      children: [],
    },
  {
      id: "orders",
      path: "/orders/",
      file: "src/routes/orders/index.mesa",
      companion: null,
      layout: "src/routes/_module.mesa",
      meta: {"siteName":"Kitchen sink","title":"Orders","isIndex":true},
      params: [],
      children: [
      {
          id: "orders.create",
          path: "/orders/create/",
          file: "src/routes/orders/create.mesa",
          companion: null,
          layout: "src/routes/_module.mesa",
          meta: {"siteName":"Kitchen sink","title":"New order"},
          params: [],
          children: [],
        },
      {
          id: "orders.[id]",
          path: "/orders/:id/",
          file: "src/routes/orders/[id].mesa",
          companion: null,
          layout: "src/routes/_module.mesa",
          meta: {"siteName":"Kitchen sink","title":"Order","dynamic":true},
          params: ["id"],
          children: [],
        }
      ],
    },
  {
      id: "products",
      path: "/products/",
      file: "src/routes/products/index.mesa",
      companion: null,
      layout: "src/routes/_module.mesa",
      meta: {"siteName":"Kitchen sink","title":"Products","isIndex":true},
      params: [],
      children: [
      {
          id: "products.[id]",
          path: "/products/:id/",
          file: "src/routes/products/[id].mesa",
          companion: null,
          layout: "src/routes/_module.mesa",
          meta: {"siteName":"Kitchen sink","title":"Product","dynamic":true},
          params: ["id"],
          children: [],
        }
      ],
    },
  {
      id: "settings",
      path: "/settings/",
      file: "src/routes/settings/index.mesa",
      companion: null,
      layout: "src/routes/_module.mesa",
      meta: {"siteName":"Kitchen sink","title":"Settings","isIndex":true},
      params: [],
      children: [],
    }
  ],
}

// Component factory map — resolved lazily by the router on navigation
export const components = {
  'root': () => import('../src/routes/index.mesa'),
  'cart': () => import('../src/routes/cart/index.mesa'),
  'customers': () => import('../src/routes/customers/index.mesa'),
  'inventory': () => import('../src/routes/inventory/index.mesa'),
  'orders': () => import('../src/routes/orders/index.mesa'),
  'orders.create': () => import('../src/routes/orders/create.mesa'),
  'orders.[id]': () => import('../src/routes/orders/[id].mesa'),
  'products': () => import('../src/routes/products/index.mesa'),
  'products.[id]': () => import('../src/routes/products/[id].mesa'),
  'settings': () => import('../src/routes/settings/index.mesa'),
}

// Loader factory map — routes with a .meta.js companion
// Only populated for routes that have a companion file
export const loaders = {

}

// Layout factory map — keyed by file path (same as node.layout in the tree).
// All layouts are loaded eagerly by initRouter on boot so resolveChain()
// always has the component factory available when rendering the chain.
export const layouts = {
  "src/routes/_module.mesa": () => import('../src/routes/_module.mesa'),
}

// Flat URL arrays for route table consumers (sitemap, llms.txt, deploys)
export const all = [
  "/",
  "/cart/",
  "/customers/",
  "/inventory/",
  "/orders/",
  "/orders/create/",
  "/orders/:id/",
  "/products/",
  "/products/:id/",
  "/settings/"
]

export const published = [
  "/",
  "/cart/",
  "/customers/",
  "/inventory/",
  "/orders/",
  "/orders/create/",
  "/orders/:id/",
  "/products/",
  "/products/:id/",
  "/settings/"
]

export const indexed = [
  "/",
  "/cart/",
  "/customers/",
  "/inventory/",
  "/orders/",
  "/orders/create/",
  "/products/",
  "/settings/"
]

export const redirects = []

// Default export is the full tree — what the router consumes
export default tree