// config/routes.js — auto-generated by Sierra — do not edit

// Boot-time tree — metadata only, no component or loader imports
// Component factories are in the 'components' map below
// Loader factories are in the 'loaders' map below
export const tree = {
  id: "root",
  path: "/",
  file: null,
  companion: null,
  layout: null,
  meta: {},
  params: [],
  children: [
  {
      id: "catalog",
      path: "/catalog/",
      file: "src/public-site/catalog/index.mesa",
      companion: "src/public-site/catalog/index.meta.js",
      layout: null,
      meta: {"title":"Catalog","render":"static","isIndex":true},
      params: [],
      children: [],
    }
  ],
}

// Component factory map — resolved lazily by the router on navigation
export const components = {
  'catalog': () => import('../src/public-site/catalog/index.mesa'),
}

// Loader factory map — routes with a .meta.js companion
// Only populated for routes that have a companion file
export const loaders = {
  'catalog': () => import('../src/public-site/catalog/index.meta.js'),
}

// Layout factory map — keyed by file path (same as node.layout in the tree).
// All layouts are loaded eagerly by initRouter on boot so resolveChain()
// always has the component factory available when rendering the chain.
export const layouts = {

}

// Flat URL arrays for manifest consumers (sitemap, llms.txt, deploys)
export const all = [
  "/catalog/"
]

export const published = [
  "/catalog/"
]

export const indexed = [
  "/catalog/"
]

export const redirects = []

// Default export is the full tree — what the router consumes
export default tree