import { $ } from '@frontierjs/junction'
// src/jobs/job-run.job.ts
// Executes one Job row — one-shot or triggered — through its server's outpost.
// Caravan handles scheduling, retry backoff and crash recovery; this file is
// the execution logic for a single run.
//
// The word is overloaded here and the two meanings are worth keeping apart: a
// caravan job is a queued unit of work, and a basecamp `Job` is a command a
// person defined against an app. This handler is the first running the second.

import { defineJob }        from '@frontierjs/caravan'
import { runsEitherWay }    from './context.ts'
import { announce }         from '../channels.ts'
import type { BasecampApp } from '../basecamp.types.ts'
// The row this job executes is the schema's own Job, generated by
// `bun run db:types`. What stood here was a hand-written snake_case interface
// left over from the raw-SQL era — `workspace_id`, `timeout_seconds`, and
// `service_id` from before `model service` became `App`. Litestone emits
// columns verbatim camelCase, so every field on it was a name no row has: the
// code read `job.timeoutSeconds` and `job.appId` correctly and the TYPE was
// what was wrong, which is the direction nothing catches until the type comes
// from the schema.
import type { Job } from '../../../db/schema.d.ts'

function runner(app: BasecampApp) {

  // No client for the JOB's own rows (`FJS-384`). They go through the service,
  // which owns them, announces the row after each write and confines the read
  // to the caller where there is one — this is the one handler here dispatched
  // both by a person and by a cron, and `runsEitherWay` below is where it says
  // so.
  //
  // `appServer` is still read as system, deliberately: resolving which machine
  // an app sits on is a placement question, `AppServer` is `@@gate("2.8")`, and
  // a cron fire has no standing to read it with at all.
  const db   = app.db.asSystem()
  const jobs = app.service('jobs')
  const log  = app.logger.child('job-run')

  /** An online server this app is placed on, or null. */
  async function resolveServer(appId: string): Promise<string | null> {
    const placements = await db.appServer.findMany({
      where:   { appId },
      include: { server: true },
    })
    const live = placements.find((p: any) => p.server?.status === 'online')
    return live?.serverId ?? null
  }

  async function executeJob(job: Job): Promise<string> {
    if (!job.command) throw new Error('Job has no command configured')

    const serverId    = job.appId ? await resolveServer(job.appId) : null
    const outpostTarget = serverId ? `outpost:${serverId}` : null

    // No outpost — try local:basecamp sidecar target
    if (!outpostTarget) {
      const local = await app.conduit.resolve('local:basecamp')
      if (!local) throw new Error('No server assigned and no local target registered')

      const result = await app.conduit.send<{ exit_code: number; stdout: string; stderr: string }>({
        target: 'local:basecamp',
        method: 'POST',
        path:   '/exec',
        body:   { command: job.command, timeout_s: job.timeoutSeconds },
      })

      if (result.error) throw new Error(result.error.message)
      if (result.data?.exit_code !== 0) throw new Error(result.data?.stderr ?? 'non-zero exit')
      return result.data?.stdout ?? ''
    }

    const result = await app.conduit.send<{ exit_code: number; stdout: string; stderr: string }>({
      target:     outpostTarget,
      method:     'POST',
      path:       '/exec',
      body:       { command: job.command, timeout_s: job.timeoutSeconds, job_id: job.id },
      timeout_ms: (job.timeoutSeconds + 5) * 1_000,
    })

    if (result.error) throw new Error(result.error.message)
    if (result.data?.exit_code !== 0) throw new Error(result.data?.stderr ?? 'non-zero exit')
    return result.data?.stdout ?? ''
  }

  async function runJob(jobId: string, trigger = 'manual'): Promise<void> {
    const startedAt = Date.now()

    // One call for the row, the run it opens, and the two refusals: a job that
    // has gone, and one this actor may not reach. Whether it should run at all
    // is decided there too — the ROW is the truth about a cancel, not the thing
    // that dispatched it, and a run queued before one is still in the queue.
    let opened: { runnable: boolean; status?: string; runId?: string; job?: Job }
    try {
      opened = await jobs.call('startRun', jobId, { trigger }) as typeof opened
    } catch (err) {
      log.warn('job not startable', { id: jobId, error: (err as Error).message })
      return
    }

    if (!opened.runnable) {
      log.info('job cancelled — run skipped', { job_id: jobId, trigger })
      return
    }

    const job   = opened.job as Job
    const runId = opened.runId as string

    log.info('job started', { job_id: jobId, run_id: runId, name: job.name })

    const startedIso = new Date(startedAt).toISOString()

    try {
      const output = await executeJob(job)
      await jobs.call('finishRun', jobId, { runId, status: 'success', output, startedAt: startedIso })
      log.info('job succeeded', { job_id: jobId, run_id: runId })

    } catch (err: unknown) {
      const msg = (err as Error).message ?? 'unknown error'
      await jobs.call('finishRun', jobId, { runId, status: 'failed', error: msg, startedAt: startedIso })
      log.error('job failed', { job_id: jobId, error: msg })

      // Re-throw so Caravan can apply its retry backoff
      throw err
    }
  }

  return { runJob }
}

// ── The job ───────────────────────────────────────────────────────

export default defineJob<{ id: string; trigger?: string }>('job:run', async (ctx) => {
  // BOTH ways, and the only handler here that is: `jobs.trigger` queues this as
  // the person who clicked, and `job-schedule.ts` fires it off a cron with no
  // actor at all. Declared rather than discovered — the mode decides whether
  // the service confines the read, and a cron fire is the app acting on its own
  // behalf across workspaces.
  const { app } = runsEitherWay(ctx, 'job:run')
  await runner(app).runJob(ctx.data.id, ctx.data.trigger ?? 'manual')
}, {
  queue:       'jobs',
  maxAttempts: 3,
  retryDelay:  [5_000, 30_000, 120_000],  // 5s, 30s, 2m
})
