#!/usr/bin/env bun
// tools/jobs-snapshot.ts
// What this app runs when nobody asked — `junction jobs`.
//
// Every other snapshot here records a surface someone reaches: routes, methods,
// error answers, the DDL. This one records the opposite — work that starts
// because a clock said so, with no request, no caller and no screen.
//
// It exists because that is the one part of an app whose failure is silent by
// construction. A route that stops working is a 404 somebody sees. A schedule
// that stops being registered is *nothing happening*, which looks exactly like
// nothing needing to happen: every scheduled job in one app here stopped firing
// at the first restart, with every row still reading `scheduled` and every
// `nextRunAt` still holding a date (`FJS-327`), and an edited cron was accepted,
// displayed, and never took effect (`FJS-328`). Neither is visible from source —
// a job file registers itself by being autoloaded, a plugin registers timers of
// its own, and `schedule()` can be called from anywhere.
//
// So it is read off a BUILT app, like `junction surface`, and for the same
// reason: what is registered is not what is written down.
//
// TWO REGISTRIES, kept apart on the page, because they are not the same promise
// (`FJS-D36`). `app.jobs` is durable — a row, a retry budget, a principal
// re-resolved when it runs. `app.scheduler` is a bare in-process timer with none
// of that, gone with the process. A reader deciding whether a deploy is safe
// needs to know which list a name is on.
//
// What is deliberately NOT here: `nextRun`, `paused`, `running`, queue depth.
// Those are the clock and the live state, so two boots would disagree and the
// file could not be committed at all. This answers what the app DECLARED.
//
// Usage:
//   junction jobs --app api/app.ts [--services api/services]
//   junction jobs --app api/app.ts --check     ← exit 1 if stale (CI)
//   junction jobs --app api/app.ts --stdout

import { writeFileSync }             from 'node:fs'
import { dirname, relative, resolve } from 'node:path'

import { flag, getFlag, rel, fatal, loadApp, checkSnapshot } from './app-module.ts'
import type { App }                                          from '../src/core/app.ts'

// ─── the two registries ───────────────────────────────────────────────────────

export interface DurableJob {
  name:        string
  queue:       string
  cron:        string | null
  timeZone:    string | null
  maxAttempts: number
  retryDelay:  number[]
  /** `null` means no bound — a handler that never settles holds its slot (`FJS-295`). */
  timeout:     number | null
}

export interface InProcessTimer {
  id:   string
  type: 'interval' | 'cron' | 'once'
  expr: string
}

export interface JobsSurface {
  durable:   DurableJob[]
  timers:    InProcessTimer[]
  /** Absent means the app installed no queue at all — a different fact from an empty one. */
  hasQueue:  boolean
}

// Caravan is an OPTIONAL peer, so both registries are duck-typed rather than
// imported. An app with no queue is a legitimate app and must not fail here;
// what it must not do is render the same as an app whose queue is empty, which
// is why `hasQueue` is a field rather than an inference from `durable.length`.
export function describeJobs(app: App): JobsSurface {
  const jobs = (app as { jobs?: { registrations?: () => DurableJob[] } }).jobs
  const hasQueue = typeof jobs?.registrations === 'function'

  const durable = hasQueue ? jobs!.registrations!() : []

  const scheduler = (app as { scheduler?: { describe?: () => InProcessTimer[] } }).scheduler
  const timers = typeof scheduler?.describe === 'function' ? scheduler.describe() : []

  return { durable, timers, hasQueue }
}

// ─── rendering ────────────────────────────────────────────────────────────────

export function renderJobsSnapshot(s: JobsSurface, meta: { source: string; command: string }): string {
  const out: string[] = []

  out.push('# Jobs snapshot')
  out.push('')
  out.push(`<!-- source: ${meta.source} -->`)
  out.push(`<!-- generated by: ${meta.command} -->`)
  out.push('')
  out.push(`Generated by \`${meta.command}\`. **Do not edit.**`)
  out.push('')
  out.push('What this app runs when nobody asked. Read off a built app, because a job')
  out.push('file registers itself by being autoloaded and a plugin registers timers of its')
  out.push('own — neither is visible in any one source file.')
  out.push('')
  out.push('A schedule that stops being registered is *nothing happening*, which is')
  out.push('indistinguishable from nothing needing to happen. That is what this file is')
  out.push('for: the change becomes a diff.')
  out.push('')
  out.push('Live state is deliberately absent — no next run, no queue depth, nothing')
  out.push('paused. Those move between two boots of identical code and could not be')
  out.push('committed. This is what the app **declared**.')
  out.push('')

  // ── durable ──
  out.push('## Durable work — `app.jobs`')
  out.push('')
  out.push('A row in the queue database, a retry budget, and the principal that asked for')
  out.push('it re-resolved when it runs. Survives a restart.')
  out.push('')

  if (!s.hasQueue) {
    out.push('**No queue is installed.** This app configures no `app.jobs`, so nothing here')
    out.push('is durable — which is a different statement from a queue with no jobs in it,')
    out.push('and the reason this line exists rather than an empty table.')
  } else if (!s.durable.length) {
    out.push('A queue is installed and **no handlers are registered**. Every dispatch this')
    out.push('app makes will find nothing to run it.')
  } else {
    out.push('| Job | Queue | Schedule | Zone | Attempts | Retry delay | Timeout |')
    out.push('| --- | --- | --- | --- | --- | --- | --- |')
    for (const j of s.durable) {
      out.push(
        `| \`${j.name}\` | \`${j.queue}\` | ${j.cron ? `\`${j.cron}\`` : 'on dispatch'} | ` +
        `${j.timeZone ? `\`${j.timeZone}\`` : '—'} | ${j.maxAttempts} | ` +
        `${j.retryDelay.length ? j.retryDelay.join(', ') : 'default'} | ` +
        `${j.timeout == null ? '**none**' : `${j.timeout}ms`} |`
      )
    }
    out.push('')
    const scheduled = s.durable.filter(j => j.cron)
    const unbounded = s.durable.filter(j => j.timeout == null)
    out.push(`${s.durable.length} handler(s), ${scheduled.length} of them on a clock.`)
    if (unbounded.length) {
      out.push('')
      out.push(`**${unbounded.length} with no timeout.** Absent means no bound, honestly — but a`)
      out.push('handler that never settles holds its slot for the life of the process, and on a')
      out.push('single-concurrency queue everything behind it waits (`FJS-295`). Worth knowing')
      out.push('which ones those are, which is why the column is here rather than omitted when')
      out.push('empty.')
    }
  }
  out.push('')

  // ── in-process ──
  out.push('## In-process timers — `app.scheduler`')
  out.push('')
  out.push('No persistence, no retry, no principal; gone with the process, and running in')
  out.push('**every** replica rather than once across them (`FJS-D36`). A timer that')
  out.push('dispatches into the queue belongs on the list above instead — registered with')
  out.push('`app.jobs.schedule()`, which buys the queue\'s durability rather than looking')
  out.push('like it has it.')
  out.push('')

  if (!s.timers.length) {
    out.push('None registered.')
  } else {
    out.push('| Id | Kind | Declared |')
    out.push('| --- | --- | --- |')
    for (const t of s.timers) out.push(`| \`${t.id}\` | ${t.type} | \`${t.expr}\` |`)
    out.push('')
    out.push(`${s.timers.length} timer(s). The ids are assigned in registration order and`)
    out.push('are not names an app chose — a moved id is a registration that moved.')
  }
  out.push('')

  return out.join('\n').replace(/\n+$/, '\n')
}

// ─── main ─────────────────────────────────────────────────────────────────────

if (import.meta.main) {
  const appPath = getFlag('app')
  if (!appPath) fatal('junction jobs needs --app <module> — the module exposing the app or a factory for it')

  const exportName  = getFlag('export')
  const servicesDir = getFlag('services')
  const app         = await loadApp(appPath, exportName, servicesDir)
  const surface     = describeJobs(app)

  // Beside the CWD for the same reason `junction surface` is: an app resolves
  // its queue database and its jobs directory against the cwd its own scripts
  // use, and CI reruns this from the snapshot's own directory.
  const outPath = getFlag('out')
    ? resolve(getFlag('out') as string)
    : resolve(process.cwd(), 'jobs.snapshot.md')

  const from    = dirname(outPath)
  const arg     = (p: string) => relative(from, resolve(p)) || '.'
  const command = `junction jobs --app ${arg(appPath)}` +
                  (exportName  ? ` --export ${exportName}`         : '') +
                  (servicesDir ? ` --services ${arg(servicesDir)}` : '')
  const body    = renderJobsSnapshot(surface, { source: arg(appPath), command })

  if (flag('stdout')) {
    process.stdout.write(body)
  } else if (flag('check')) {
    checkSnapshot(outPath, body, command, 'set of jobs this app runs')
  } else {
    writeFileSync(outPath, body, 'utf8')
    console.log(`  ✓  ${rel(outPath)}`)
    console.log(`  ${surface.durable.length} durable · ${surface.timers.length} in-process timer(s)`)
  }

  // Same reason as `junction surface`: an app built for description is holding a
  // database and a poller nobody asked to stop, and a tool that never exits
  // fails CI as a timeout rather than as an answer.
  await app.stop?.().catch(() => {})
  process.exit(0)
}
