#!/usr/bin/env bun
// tools/notifications-snapshot.ts
// What this app can tell somebody — `junction notifications`.
//
// The sibling of `junction jobs`, and it exists for the same failure. A job
// that stops being registered is nothing happening; a NOTIFICATION that stops
// being registered is nothing arriving — and it is worse in one way, because
// the send does not go quiet, it throws at the moment somebody was owed a
// message, in a job, hours after the deploy that dropped it.
//
// Nothing in an app's source says which notifications it has. A definition is a
// file that registers itself by being autoloaded, the type it answers to comes
// from that file's NAME, and the directory it is found in is probed unless the
// app declares one. So this is read off a BUILT app, like `junction jobs` and
// `junction surface`, and for the same reason: what is registered is not what
// is written down.
//
// `app.notifications` is duck-typed and never imported. @frontierjs/notifications
// is not a dependency of this package and must not become one — an app that
// installs no notifications is a legitimate app and renders here as a stated
// absence, which is a different fact from an app that installs the plugin and
// declares nothing.
//
// What is deliberately NOT here: anything a payload decides. `via` is a
// function of (payload, recipient), so *which* transports a given send actually
// uses is a runtime answer and two boots would agree on it only by accident.
// This is the set a definition CAN format for — which is what a preferences
// screen offers and what a missing driver is graded against.
//
// Usage:
//   junction notifications --app api/app.ts
//   junction notifications --app api/app.ts --check     ← exit 1 if stale (CI)
//   junction notifications --app api/app.ts --stdout

import { writeFileSync }             from 'node:fs'
import { dirname, relative, resolve } from 'node:path'

import { flag, getFlag, rel, fatal, loadApp, checkSnapshot } from './app-module.ts'
import type { App }                                          from '../src/core/app.ts'

// ─── what a definition answers ────────────────────────────────────────────────

export interface DeclaredNotification {
  /** The string written to `notifications.type` and read back by the browser. */
  type:       string
  /** Transports it can format for, in declaration order. */
  transports: string[]
}

export interface NotificationsSurface {
  declared: DeclaredNotification[]
  /** Absent means the plugin was never configured — not the same as configured
   *  and empty, and the reason this is a field rather than `declared.length`. */
  installed: boolean
}

type Registry = ReadonlyMap<string, { type?: string; transports?: readonly string[] }>

export function describeNotifications(app: App): NotificationsSurface {
  const reg = (app as { notifications?: Registry }).notifications
  const installed = !!reg && typeof reg.forEach === 'function'

  if (!installed) return { declared: [], installed: false }

  const declared: DeclaredNotification[] = []
  for (const [key, f] of reg!) {
    declared.push({
      // The map is keyed by the type, and the factory carries it too. Reading
      // the key means a registry built by anything is describable here.
      type:       f?.type ?? key,
      transports: [...(f?.transports ?? [])],
    })
  }

  // Sorted, because the loader walks the directory and the file system's order
  // is not a fact about the app. A committed file whose rows move when nothing
  // changed is a diff nobody can read.
  declared.sort((a, b) => a.type.localeCompare(b.type))
  return { declared, installed: true }
}

// ─── rendering ────────────────────────────────────────────────────────────────

export function renderNotificationsSnapshot(
  s: NotificationsSurface,
  meta: { source: string; command: string },
): string {
  const out: string[] = []

  out.push('# Notifications snapshot')
  out.push('')
  out.push(`<!-- source: ${meta.source} -->`)
  out.push(`<!-- generated by: ${meta.command} -->`)
  out.push('')
  out.push(`Generated by \`${meta.command}\`. **Do not edit.**`)
  out.push('')
  out.push('What this app can tell somebody. Read off a built app, because a notification')
  out.push('registers itself by being autoloaded and takes its type from its own file name —')
  out.push('neither is visible in any one source file.')
  out.push('')
  out.push('A notification that stops being registered does not go quiet: it throws at the')
  out.push('moment somebody was owed a message, usually inside a job, long after the deploy')
  out.push('that dropped it. That is what this file is for — the change becomes a diff.')
  out.push('')
  out.push('**The type is persisted.** It is written into `notifications.type` and read back')
  out.push('by the browser to choose a renderer, so a type that moves here orphans every row')
  out.push('already written under the old string. Renaming the file renames the type; `type:`')
  out.push('on the definition is what holds it still.')
  out.push('')

  if (!s.installed) {
    out.push('**No notifications plugin is configured.** This app has no `app.notifications`,')
    out.push('so nothing here can send — which is a different statement from a plugin that is')
    out.push('configured and found no definitions, and the reason this line exists rather than')
    out.push('an empty table.')
    out.push('')
    return out.join('\n').replace(/\n+$/, '\n')
  }

  if (!s.declared.length) {
    out.push('The plugin is configured and **no notifications are registered**. Every')
    out.push('`app.notify` this app makes will throw, naming a definition the loader never saw.')
    out.push('')
    return out.join('\n').replace(/\n+$/, '\n')
  }

  out.push('| Type | Transports |')
  out.push('| --- | --- |')
  for (const n of s.declared) {
    out.push(`| \`${n.type}\` | ${n.transports.length ? n.transports.map(t => `\`${t}\``).join(' · ') : '**none**'} |`)
  }
  out.push('')
  out.push(`${s.declared.length} notification(s).`)

  // A definition with no formatter cannot be constructed — defineNotification
  // refuses it — so an empty row here means a registry built some other way,
  // and every send of it will be NotificationTransportNotImplementedError.
  const empty = s.declared.filter(n => !n.transports.length)
  if (empty.length) {
    out.push('')
    out.push(`**${empty.length} with no transport.** Every send of one is refused before`)
    out.push('delivery, naming the transport `via` asked for and the type. `defineNotification`')
    out.push('cannot produce this, so a row here is a registry built some other way.')
  }
  out.push('')
  out.push('Which transports a given send *uses* is not here: `via` is a function of the')
  out.push('payload and the recipient, so it is a runtime answer. This is the set each')
  out.push('definition can format for.')
  out.push('')

  return out.join('\n').replace(/\n+$/, '\n')
}

// ─── main ─────────────────────────────────────────────────────────────────────

if (import.meta.main) {
  const appPath = getFlag('app')
  if (!appPath) fatal('junction notifications needs --app <module> — the module exposing the app or a factory for it')

  const exportName  = getFlag('export')
  const servicesDir = getFlag('services')
  const app         = await loadApp(appPath, exportName, servicesDir)
  const surface     = describeNotifications(app)

  const outPath = getFlag('out')
    ? resolve(getFlag('out') as string)
    : resolve(process.cwd(), 'notifications.snapshot.md')

  const from    = dirname(outPath)
  const arg     = (p: string) => relative(from, resolve(p)) || '.'
  const command = `junction notifications --app ${arg(appPath)}` +
                  (exportName  ? ` --export ${exportName}`         : '') +
                  (servicesDir ? ` --services ${arg(servicesDir)}` : '')
  const body    = renderNotificationsSnapshot(surface, { source: arg(appPath), command })

  if (flag('stdout')) {
    process.stdout.write(body)
  } else if (flag('check')) {
    checkSnapshot(outPath, body, command, 'set of notifications this app declares')
  } else {
    writeFileSync(outPath, body, 'utf8')
    console.log(`  ✓  ${rel(outPath)}`)
    console.log(`  ${surface.declared.length} notification(s)`)
  }

  // Same reason as `junction jobs`: an app built for description is holding a
  // database and a poller nobody asked to stop.
  await app.stop?.().catch(() => {})
  process.exit(0)
}
