#!/usr/bin/env bun
// tools/principal-snapshot.ts
// Who a caller ARRIVES as, and who they BECOME — `junction principal`.
//
// `db/access.snapshot.md` commits the predicate every tenancy rule compiles
// into, and the `snapshots` CI phase fails a stale one. It does not commit the
// predicate's INPUT. Who emits `auth().workspaceId`, off which part of the
// request, verified against which model and column — none of that is in any
// committed file, so a resolver that emits the WRONG tenant leaves every
// artefact byte-identical, CI green, and every read answering somebody else's
// rows (`FJS-514`).
//
// Read off a BUILT app, like `junction surface` and `junction jobs`, and for
// the same reason: a resolver is wired in application code and no file tree can
// answer which one an app ended up with.
//
// What is deliberately NOT here:
//
//   VALUES. A claim's name is a fact about the app; a claim's value is a
//   caller. `describe()` answers names only, and the tenancy declaration's own
//   column and claim are already public in the schema.
//
//   The value→level MAPPING. A standing is graded by `getLevel`, a function an
//   app hands to `GatePlugin`, and a client exposes plugin names rather than
//   instances. The column and its declared values are here because a diff can
//   grade those; the mapping is named as app code and the thing that executes
//   it is litestone's `verifyGateLadder`. A second, guessed answer to a question
//   that already has an executed one is worse than a gap.
//
// Usage:
//   junction principal --app api/app.ts [--services api/services]
//   junction principal --app api/app.ts --check     ← exit 1 if stale (CI)
//   junction principal --app api/app.ts --stdout

import { writeFileSync }              from 'node:fs'
import { dirname, relative, resolve } from 'node:path'

import { flag, getFlag, rel, fatal, loadApp, checkSnapshot } from './app-module.ts'
import { describePrincipalRealm }                           from '../src/core/litestone.ts'
import type { PrincipalRealm }                              from '../src/core/litestone.ts'
import type { App }                                         from '../src/core/app.ts'

// ─── rendering ────────────────────────────────────────────────────────────────

export function renderPrincipalSnapshot(
  p: PrincipalRealm | null,
  meta: { source: string; command: string },
): string {
  const out: string[] = []

  out.push('# Principal snapshot')
  out.push('')
  out.push(`<!-- source: ${meta.source} -->`)
  out.push(`<!-- generated by: ${meta.command} -->`)
  out.push('')
  out.push(`Generated by \`${meta.command}\`. **Do not edit.**`)
  out.push('')
  out.push('Who a caller **arrives as**, and who they **become** before the Data boundary.')
  out.push('')
  out.push('`db/access.snapshot.md` is the other half and it commits the predicate —')
  out.push('`workspaceId != auth().workspaceId`. This commits the predicate\'s **input**.')
  out.push('A resolver that emits the wrong tenant changes no line of that file, so')
  out.push('without this one the whole API half of tenancy has no diffable face.')
  out.push('')
  out.push('No values anywhere below. A claim\'s NAME is a fact about the application; a')
  out.push('claim\'s VALUE is a caller.')
  out.push('')

  if (!p) {
    out.push('This app declares no tenancy and installs no principal resolver, so every')
    out.push('caller is exactly the session `IAuth` verified and nothing is merged onto it.')
    out.push('')
    return out.join('\n').replace(/\n+$/, '\n')
  }

  // ── 1. tenancy ──
  out.push('## Tenancy')
  out.push('')
  if (!p.tenancy) {
    out.push('**No `tenancy { }` block.** Nothing here is scoped to a tenant by declaration;')
    out.push('an app doing it in service where-clauses instead has no rule this file can read.')
  } else {
    out.push('| | |')
    out.push('| --- | --- |')
    out.push(`| Strategy | \`${p.tenancy.strategy}\` |`)
    out.push(`| Column | ${p.tenancy.column ? `\`${p.tenancy.column}\`` : '—'} |`)
    out.push(`| Claim on the principal | ${p.tenancy.claim ? `\`${p.tenancy.claim}\`` : '—'} |`)
    // Which of the two answers is OPERATIVE depends on the strategy, and
    // printing the wrong one is worse than printing neither. `resolve` is read
    // by the tenant registry, which only exists under `strategy database`;
    // under `strategy row` nothing consults it and the resolver decides.
    const named = p.tenancy.strategy === 'database'
      ? (p.tenancy.resolve ?? '**nothing declared** — no `resolve` in the block')
      : (p.resolver?.described?.namedBy
          ?? (p.resolver ? `the resolver's \`tenantFrom\` — a function, so not committed here` : null)
          ?? '**nothing** — the claim must already be on the session (`sessionFields`)')
    out.push(`| A request names its tenant by | ${named} |`)
    out.push('')
    if (p.tenancy.strategy === 'row')
      out.push('Under `strategy row` the tenant is a value on the principal, so **the claim is')
    else
      out.push('Under `strategy database` the tenant is a file, so **the resolution is')
    out.push(p.tenancy.strategy === 'row'
      ? 'the whole mechanism** — a caller holding none reads nothing, with a 200.'
      : 'the whole mechanism** — no query can reach two tenants because no connection holds two.')
  }
  out.push('')

  // ── 2. resolver ──
  out.push('## Resolver — `createApp({ principal })`')
  out.push('')
  if (!p.resolver) {
    out.push('**None installed.** Every claim on the principal comes from the session, which')
    out.push('is `sessionFields` at sign-in — one tenant for the life of that session. An app')
    out.push('whose people belong to several tenants cannot express that here.')
  } else if (!p.resolver.described) {
    out.push(`\`${p.resolver.name}\` — a hand-written resolver, which describes nothing about`)
    out.push('itself. The name is the whole of what is committed, so a change to which model')
    out.push('proves membership is invisible in this diff. Give it a `describe()` returning')
    out.push('`{ kind, model, subject, tenant, standing, claims, include }` and the rows below')
    out.push('fill in.')
  } else {
    const d = p.resolver.described
    out.push('| | |')
    out.push('| --- | --- |')
    out.push(`| Kind | \`${d.kind}\` |`)
    out.push(`| Function | \`${p.resolver.name}\` |`)
    if (d.model) {
      out.push(`| Membership proved by | \`${d.model}\` |`)
      out.push(`| Caller column | ${d.subject ? `\`${d.subject}\`` : '—'} |`)
      out.push(`| Tenant column | ${d.tenant ? `\`${d.tenant}\`` : '—'} |`)
      out.push(`| Standing column | ${d.standing ? `\`${d.standing}\`` : '— (no standing on the row)'} |`)
      out.push(`| Read alongside | ${d.include.length ? d.include.map(i => `\`${i}\``).join(', ') : '—'} |`)
    }
    out.push('')

    // The rows above are membership's, and their absence is the substance for
    // any other kind rather than a gap: a resolver that reads no row is making
    // a different promise, and five empty cells say the opposite.
    if (d.model) {
      out.push('**No row is no claim.** A caller naming a tenant they do not belong to comes out')
      out.push('holding nothing — an empty screen and a gate that grades them a stranger — rather')
      out.push('than a full principal belonging to somebody else. That is the one line the whole')
      out.push('arrangement rests on.')
    } else {
      out.push('**This resolver reads no row**, so it verifies nothing and does not claim to.')
      out.push('That is correct for a capability the REQUEST already proves — a bearer token')
      out.push('matches the rows carrying it, and a token nobody issued matches none. It would')
      out.push('be a hole for a tenancy claim, which scopes a stranger INTO a tenant when')
      out.push('asserted without proof. Which of the two this is, is the `Kind` row above.')
    }
  }
  out.push('')

  // ── 3. claims ──
  out.push('## Claims')
  out.push('')
  out.push('What this resolver may merge onto the principal, by name.')
  out.push('')
  const claims = p.resolver?.described?.claims ?? []
  if (!claims.length) {
    out.push('None described.')
  } else {
    out.push('| Claim | |')
    out.push('| --- | --- |')
    const standingClaim = p.standing?.claim ?? null
    for (const c of claims) {
      const what = p.tenancy?.claim === c
        ? 'the tenant — read by the desugared `@@deny` on every scoped model'
        : standingClaim === c
          ? 'a standing, graded by the app\'s own `getLevel`'
          : 'a capability — read by whatever row policy names it, and by nothing else'
      out.push(`| \`${c}\` | ${what} |`)
    }
    out.push('')
    if (p.tenancy?.claim && !claims.includes(p.tenancy.claim)) {
      out.push(`**The resolver emits no \`${p.tenancy.claim}\`, and the schema's tenancy rules read that name.**`)
      out.push('Every scoped model will filter against a claim nothing sets, which is an empty')
      out.push('result with a 200 on every screen.')
      out.push('')
    }
  }
  out.push('`userId` and `id` are refused by name: a claim says what a caller HOLDS for this')
  out.push('request, never who they are. Identity is `IAuth`\'s and nothing else\'s.')
  out.push('')

  // ── 4. standing ──
  out.push('## Standing')
  out.push('')
  if (!p.standing) {
    out.push('The resolver emits no standing, so every caller is graded by the session alone —')
    out.push('`getLevel` over what `IAuth` issued.')
  } else {
    out.push(`Read from \`${p.standing.column}\`, carried as \`${p.standing.claim}\`.`)
    out.push('')
    if (!p.standing.values.length) {
      out.push('The column is not an enum, so its values are not declared anywhere this can read.')
    } else {
      out.push('| Declared value |')
      out.push('| --- |')
      for (const v of p.standing.values) out.push(`| \`${v}\` |`)
      out.push('')
      out.push(`${p.standing.values.length} value(s).`)
    }
    out.push('')
    out.push('**The value→level mapping is not here and is not derivable.** `getLevel` is a')
    out.push('function the app hands to `GatePlugin`, and a client answers plugin names rather')
    out.push('than instances. What this file can grade is the SET: a value added to the ladder')
    out.push('and not to `getLevel` is a caller silently graded at whatever the default answers,')
    out.push('and the enum gaining a member is the visible edge of that. The mapping itself is')
    out.push('executed by litestone\'s `verifyGateLadder`.')
  }
  out.push('')

  // ── 5. exemptions ──
  out.push('## What the tenant rules reach')
  out.push('')
  if (!p.hasSchema) {
    out.push('**Not applicable, and not missing.** Under `strategy database` a tenant is a')
    out.push('SQLite file: there is no per-model predicate to break down, because there is no')
    out.push('query that reaches two tenants and no connection that holds two. The client is')
    out.push('per request, so nothing app-wide holds a schema to read either — and opening a')
    out.push('tenant to get one would make a description tool create a database.')
    out.push('')
    out.push('What proves that strategy is a drive holding the registry, not a rule: two')
    out.push('shops, two files, and a token issued by one that is not a session at the other.')
    out.push('')
  } else {
  out.push('| | Count | Models |')
  out.push('| --- | --- | --- |')
  out.push(`| Scoped by column | ${p.scoped.length} | ${p.scoped.length ? p.scoped.map(m => `\`${m}\``).join(' · ') : '—'} |`)
  out.push(`| Scoped by delegation | ${p.delegated.length} | ${p.delegated.length ? p.delegated.map(m => `\`${m}\``).join(' · ') : '—'} |`)
  out.push(`| Exempt — \`@@tenant(none)\` | ${p.exempt.length} | ${p.exempt.length ? p.exempt.map(m => `\`${m}\``).join(' · ') : '—'} |`)
  out.push('')
  out.push('An exemption is a decision, so it is listed by name rather than counted. A model')
  out.push('moving into this row is a model every tenant can now read.')
  out.push('')
  out.push('Whether these rules HOLD is a separate question with an executed answer —')
  out.push('litestone\'s `verifyTenantIsolation()`, which seeds a row for one tenant and has')
  out.push('another try to reach it.')
  out.push('')
  }

  // ── 6. refusals ──
  out.push('## Refusals')
  out.push('')
  out.push('Three ways a caller ends up with no tenant claim, and they are three different')
  out.push('sentences. `tenantClaimGuard` tells them apart by whether a resolver ran at all.')
  out.push('')
  out.push('| Situation | Status | Whose problem |')
  out.push('| --- | --- | --- |')
  out.push('| Nothing in this app emits the claim | 403 | the developer\'s — no resolver is configured |')
  out.push('| The request named no tenant | 403 | the caller\'s — the request is incomplete |')
  out.push('| The request named one they do not belong to | 403 | the caller\'s — refused |')
  out.push('')
  out.push('**403 in every branch, and 401 in none.** 401 means *you have not proved who you')
  out.push('are*, and the caller has — every client treats it as a dead token, so a member of')
  out.push('A following a link into B was not refused, they were signed out of A (`FJS-383`).')
  out.push('')

  // ── 7. config ──
  out.push('## Per-tenant configuration')
  out.push('')
  out.push('The allow-list of configuration keys a tenant may override.')
  out.push('')
  if (p.tenantConfigKeys === null) {
    out.push('**None. This app installs no `createApp({ tenantConfig })`**, so everything it is')
    out.push('configured with resolves once at boot and is the same for every tenant: the mail')
    out.push('transport and its from-address, a bucket, a timezone, a locale, a branding value,')
    out.push('a rate limit.')
    out.push('')
    out.push('That is a legitimate app. What it cannot do is be one deployment that several')
    out.push('customers each experience as theirs, where the customer-facing half of *theirs* is')
    out.push('mostly not rows.')
  } else if (!p.tenantConfigKeys.length) {
    out.push('**A resolver is installed and names no keys**, so nothing it answers can apply and')
    out.push('every tenant reads the floor. Junction refuses this at boot, so seeing it here')
    out.push('means the list was emptied after the app was built.')
  } else {
    out.push('| Path | |')
    out.push('| --- | --- |')
    for (const k of p.tenantConfigKeys) out.push(`| \`${k}\` | a tenant may set this |`)
    out.push('')
    out.push(`${p.tenantConfigKeys.length} path(s). **Everything else is the floor**, and a`)
    out.push('resolver answering a path not on this list is refused by name rather than dropped.')
    out.push('')
    out.push('This list is the half that makes the feature safe rather than the half that makes')
    out.push('it work, which is why it is committed. A path arriving here is a value a tenant')
    out.push('can now change about every other tenant\'s experience of this deployment — read')
    out.push('the diff as that, not as configuration.')
    out.push('')
    out.push('`port`, `host`, `database`, `http`, `auth`, `apiPrefix` and `logging` are refused')
    out.push('at boot and can never appear: a database path handed to a tenant is every other')
    out.push('tenant\'s rows, and the rest are read at boot with no tenant in scope.')
  }
  out.push('')

  return out.join('\n').replace(/\n+$/, '\n')
}

// ─── main ─────────────────────────────────────────────────────────────────────

if (import.meta.main) {
  const appPath = getFlag('app')
  if (!appPath) fatal('junction principal needs --app <module> — the module exposing the app or a factory for it')

  const exportName  = getFlag('export')
  const servicesDir = getFlag('services')
  const app         = await loadApp(appPath, exportName, servicesDir) as App & { db?: unknown }
  const realm       = describePrincipalRealm(app, (app as { db?: unknown }).db)

  const outPath = getFlag('out')
    ? resolve(getFlag('out') as string)
    : resolve(process.cwd(), 'principal.snapshot.md')

  const from    = dirname(outPath)
  const arg     = (p: string) => relative(from, resolve(p)) || '.'
  const command = `junction principal --app ${arg(appPath)}` +
                  (exportName  ? ` --export ${exportName}`         : '') +
                  (servicesDir ? ` --services ${arg(servicesDir)}` : '')
  const body    = renderPrincipalSnapshot(realm, { source: arg(appPath), command })

  if (flag('stdout')) {
    process.stdout.write(body)
  } else if (flag('check')) {
    checkSnapshot(outPath, body, command, 'principal a caller resolves to')
  } else {
    writeFileSync(outPath, body, 'utf8')
    console.log(`  ✓  ${rel(outPath)}`)
    console.log(`  ${realm?.scoped.length ?? 0} scoped · ${realm?.delegated.length ?? 0} delegated · ${realm?.exempt.length ?? 0} exempt`)
  }

  // Same reason as `junction surface`: an app built for description holds a
  // database and a poller nobody asked to stop.
  await app.stop?.().catch(() => {})
  process.exit(0)
}
