#!/usr/bin/env bun
// tools/surface.ts
// The API surface as a committed file — `junction surface`.
//
// The Data realm has two of these already (`litestone access`, `litestone ddl`).
// This is the API realm's: what services exist, what each will answer, which
// hooks run around it in what ORDER, what it broadcasts on, and every path the
// router actually mounted.
//
// None of that is derivable from the source text. `collectCustomMethods` decides at
// construction whether a key is an option or an action, `svc.pipelines()`
// resolves the chain, `apiPrefix` moves every route the app registers, and a
// plugin mounts paths nobody wrote down. So the surface is read off a BUILT
// app — `describe()` and `buildRoutes()`, the declared owners — rather than
// scanned, which is the one thing that makes the file worth committing.
//
// Usage:
//   junction surface --app src/core/app.ts [--export buildApp]
//   junction surface --app src/core/app.ts --check     ← exit 1 if stale (CI)
//   junction surface --app src/core/app.ts --stdout
//
// The app module must expose the app WITHOUT listening: a built `App`, or a
// factory returning one. That is the same contract `@frontierjs/testing` takes
// as `api:`, and an entry that calls `app.start()` at module scope satisfies
// neither — guard it with `import.meta.main`.

import { writeFileSync }             from 'node:fs'
import { dirname, relative, resolve } from 'node:path'

// The loader, the arg helpers and the `--check` compare are shared with
// `junction jobs` — see tools/app-module.ts. The MODEL is shared with every
// other register — see src/core/app-model.ts. This file renders and nothing
// else.
import { flag, getFlag, rel, fatal, loadApp, checkSnapshot } from './app-module.ts'

import { describeSurface }              from '../src/core/app-model.ts'
import type { Surface }                 from '../src/core/app-model.ts'
import type { CustomMethodGrade }       from '../src/core/litestone.ts'


// ─── rendering ────────────────────────────────────────────────────────────────
//
// Ordering is the whole point in two places and must not be sorted away: a hook
// chain runs in the order it is listed, and the plugin list is configure order,
// which `requires:` is checked against.

// Run order, not declaration order: `around` wraps everything (the derived
// `gateAuth` lives there), then before, then validated, then after.
const PHASES = ['around', 'before', 'validated', 'after', 'error'] as const

// Who may call a custom method, in the words a reader acts on. The mechanism
// is `customMethodGrade`; this is only the sentence. A floor is a PRESENCE
// check, so the dangerous row is a floor above 0 on a method that writes
// through `asSystem()` — the Data boundary never sees who asked.
function gradeSentence(g: CustomMethodGrade): string {
  if (g.source === 'unchecked')
    return '**nothing at the API boundary** — the model declares no `@@gate`' +
      (g.level !== null ? `, so the declared \`gate: ${g.level}\` is not enforced` : '')
  if (g.source === 'declared')
    return g.level === 0 ? 'anyone, a stranger included — declared `gate: 0`'
                         : `standing ${g.level} or above — declared \`gate: ${g.level}\``
  if (g.level === 0) return 'anyone, a stranger included — floor, the model\'s read gate is 0'
  if (g.level === null) return '**presence only** — floor, the model\'s read gate; standing not graded'
  return `**any signed-in caller** — floor, read gate ${g.level}; standing not graded`
}

const ungraded = (g: CustomMethodGrade): boolean =>
  g.source === 'unchecked' || (g.source === 'floor' && g.level !== 0)

function hookRows(map: Record<string, Record<string, string[]>>): string[] {
  const rows: string[] = []
  for (const phase of PHASES) {
    for (const [method, chain] of Object.entries(map[phase] ?? {})) {
      if (!chain?.length) continue
      rows.push(`| ${phase} | \`${method}\` | ${chain.map(h => `\`${h}\``).join(' → ')} |`)
    }
  }
  return rows
}

export function renderSurfaceSnapshot(surface: Surface, opts: { source?: string; command?: string } = {}): string {
  const { source = 'app.ts', command = `junction surface --app ${source}` } = opts
  const out: string[] = []

  out.push('# API surface snapshot')
  out.push('')
  // The machine half: scripts/ci.mjs reads this line and reruns the command
  // with --check from this file's own directory.
  out.push(`<!-- generated by: ${command} -->`)
  out.push('')
  out.push(`Generated from \`${source}\` by \`junction surface\`. **Do not edit.**`)
  out.push('')
  out.push('What the API answers, read off a BUILT app rather than scanned: the methods')
  out.push('each service will serve, its custom methods, the hook chain in the order it runs,')
  out.push('and every path the router actually mounted. None of it is visible in the source —')
  out.push('an option key and a method look identical, `apiPrefix` moves every route, and')
  out.push('a plugin mounts paths nobody wrote. Regenerate after a change and read the diff.')
  out.push('')
  out.push('```')
  out.push(`${surface.services.length} services · ${surface.routes.length} routes · ` +
           `${surface.plugins.length} plugins · prefix ${surface.prefix || '(none)'}`)
  out.push('```')
  out.push('')

  // ── Custom methods nobody grades ──
  const loose = surface.services.flatMap(svc =>
    Object.entries(svc.methodGrades).filter(([, g]) => ungraded(g)).map(([m, g]) => ({ svc: svc.name, m, g })))
  out.push('## Custom methods whose caller\'s standing is not graded')
  out.push('')
  out.push('A custom method with no `gate:` in `methods:` takes the model\'s read gate as a')
  out.push('FLOOR, and a floor checks only that a caller is signed in (`FJS-826`). A method')
  out.push('that writes through `asSystem()` from here is open to every caller who can sign')
  out.push('in, whatever the row policies say, because the Data boundary never sees who')
  out.push('asked. Each row below is either meant — a read-shaped method, a scoped write —')
  out.push('or wants `methods: [{ method, gate }]`.')
  out.push('')
  if (loose.length) {
    out.push('| Method | Who may call it |')
    out.push('| --- | --- |')
    for (const { svc, m, g } of loose) out.push(`| \`${svc}.${m}\` | ${gradeSentence(g)} |`)
  } else {
    out.push('None — every custom method declares its level or is open by a read gate of 0.')
  }
  out.push('')

  // ── App hooks ──
  const appRows = hookRows(surface.appHooks)
  out.push('## App hooks')
  out.push('')
  out.push('Run around EVERY service call, machine-facing endpoints included. `all` is not')
  out.push('a method — it applies to each one.')
  out.push('')
  if (appRows.length) {
    out.push('| Phase | Method | Chain |')
    out.push('| --- | --- | --- |')
    out.push(...appRows)
  } else {
    out.push('The app declares none.')
  }
  out.push('')

  // ── Services ──
  out.push('## Services')
  out.push('')
  out.push('`methods` is policy-applied — what the service will answer, not what it')
  out.push('defines. A custom method is a non-CRUD one `collectCustomMethods` resolved at')
  out.push('construction; a name that stopped being one is a line that disappears here.')
  out.push('`model` is what the service reports for the result envelope, which is its own')
  out.push('name when it declares none.')
  out.push('')

  for (const svc of surface.services) {
    out.push(`### \`${svc.name}\`${svc.model ? ` · model \`${svc.model}\`` : ''}`)
    out.push('')
    out.push(`- **methods** — ${svc.methods.length ? svc.methods.map(m => `\`${m}\``).join(', ') : '(none)'}`)
    if (svc.customMethods.length) out.push(`- **custom methods** — ${svc.customMethods.map(a => `\`${a}\``).join(', ')}`)
    if (svc.aliases.length)       out.push(`- **also answers to** — ${svc.aliases.map(a => `\`${a}\``).join(', ')}`)
    // A declared input is a fact about the wire that is written in a service
    // file and readable nowhere else.
    for (const [method, type] of Object.entries(svc.inputs).sort())
      out.push(`- **input** — \`${method}\` takes \`${type}\``)
    const grades = Object.entries(svc.methodGrades)
    if (grades.length) {
      out.push('- **who may call** —')
      for (const [method, g] of grades) out.push(`  - \`${method}\` — ${gradeSentence(g)}`)
    }
    if (svc.channel.length)       out.push(`- **broadcasts on** — ${svc.channel.map(c => `\`${c}\``).join(', ')}`)
    if (svc.transactional.length) out.push(`- **transactional** — ${svc.transactional.map(m => `\`${m}\``).join(', ')}`)
    if (svc.softDelete)           out.push(`- **soft delete** — \`${svc.softDelete}\``)
    if (svc.cache)                out.push('- **cached**')
    if (svc.idField !== 'id')     out.push(`- **id field** — \`${svc.idField}\``)
    if (svc.allowBulk)            out.push(`- **bulk** — allowed, max ${svc.bulkMax} rows per filtered write`)
    out.push('')

    const rows = hookRows(svc.hooks)
    if (rows.length) {
      out.push('| Phase | Method | Chain |')
      out.push('| --- | --- | --- |')
      out.push(...rows)
      out.push('')
    }
  }

  // ── Routes ──
  out.push('## Routes')
  out.push('')
  out.push('Read off the router, so a path appears here whether or not anything meant to')
  out.push('mount it. A `{service}` path is the CRUD handler and names every service at')
  out.push('once; everything else was registered by hand or by a plugin.')
  out.push('')
  out.push('| Method | Path | Kind |')
  out.push('| --- | --- | --- |')
  for (const r of surface.routes) out.push(`| ${r.method} | \`${r.path}\` | ${r.kind} |`)
  out.push('')

  // ── Plugins ──
  out.push('## Plugins')
  out.push('')
  out.push('In configure order, which is what `requires:` is checked against.')
  out.push('')
  for (const [i, name] of surface.plugins.entries()) out.push(`${i + 1}. \`${name}\``)
  out.push('')

  return out.join('\n').replace(/\n+$/, '\n')
}

// ─── main ─────────────────────────────────────────────────────────────────────

if (import.meta.main) {
  const appPath = getFlag('app')
  if (!appPath) fatal('junction surface needs --app <module> — the module exposing the app or a factory for it')

  const exportName  = getFlag('export')
  const servicesDir = getFlag('services')
  const app         = await loadApp(appPath, exportName, servicesDir)
  const surface     = describeSurface(app)

  // Default beside the CWD, not beside the app module. An app is built with the
  // cwd its own scripts use — a database path, a config file and the autoload
  // directory are all resolved against it — and CI reruns this from the
  // snapshot's directory, so the two have to be the same place. That is the app
  // root, which is where `bun run api` is run from.
  const outPath = getFlag('out')
    ? resolve(getFlag('out') as string)
    : resolve(process.cwd(), 'surface.snapshot.md')

  const from    = dirname(outPath)
  const arg     = (p: string) => relative(from, resolve(p)) || '.'
  const command = `junction surface --app ${arg(appPath)}` +
                  (exportName  ? ` --export ${exportName}`      : '') +
                  (servicesDir ? ` --services ${arg(servicesDir)}` : '')
  const body    = renderSurfaceSnapshot(surface, { source: arg(appPath), command })

  if (flag('stdout')) {
    process.stdout.write(body)
  } else if (flag('check')) {
    checkSnapshot(outPath, body, command, 'API surface')
  } else {
    writeFileSync(outPath, body, 'utf8')
    console.log(`  ✓  ${rel(outPath)}`)
    console.log(`  ${surface.services.length} services · ${surface.routes.length} routes · ${surface.plugins.length} plugins`)
  }

  // An app built for description holds whatever its plugins opened — a database,
  // a job poller, a scheduler. Nothing here asked them to stop, and a tool that
  // never exits fails CI as a timeout rather than as an answer.
  await app.stop?.().catch(() => {})
  process.exit(0)
}
