// ─── call-argv.test.js — which app `fli call` boots, from where, with what ─────
//
// `callArgv` decides everything the command does before it spawns, so it is
// tested here with no bun, no app and no boot. What `junction call` does with
// the argv is junction's own suite (`test/call-tool.test.ts`).
//
// The trees are real directories: the entry comes out of a snapshot header on
// disk and junction is resolved through a package.json on disk, and a fake of
// either would pass while the real lookup found nothing.

import { describe, test, expect, beforeEach, afterEach } from 'bun:test'
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir }                                        from 'node:os'
import { join, resolve, dirname }                        from 'node:path'
import { fileURLToPath }                                 from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const { callArgv } = await import(resolve(ROOT, 'core/app-entry.js'))

let root
beforeEach(() => { root = mkdtempSync(join(tmpdir(), 'fli-call-')) })
afterEach(() => rmSync(root, { recursive: true, force: true }))

function write(rel, body) {
  mkdirSync(dirname(join(root, rel)), { recursive: true })
  writeFileSync(join(root, rel), body)
}

// Junction installed the way an app installs it, so the bin resolves through
// the package's own manifest.
function installJunction() {
  write('node_modules/@frontierjs/junction/package.json',
    JSON.stringify({ name: '@frontierjs/junction', bin: { junction: 'tools/cli.ts' } }))
  write('node_modules/@frontierjs/junction/tools/cli.ts', '')
  return join(root, 'node_modules/@frontierjs/junction/tools/cli.ts')
}

describe('callArgv — which app', () => {
  test('without --app, the entry and its flags come from the surface snapshot header, run from its directory', () => {
    const bin = installJunction()
    write('api/surface.snapshot.md', '# API surface snapshot\n\n<!-- generated by: junction surface --app src/app.ts --services src/services -->\n')

    const plan = callArgv(root, { words: ['orders.find', '{"$limit":1}'], as: 'sam@shop.test', tenant: 'flagship' })

    expect(plan.cwd).toBe(join(root, 'api'))
    expect(plan.argv).toEqual([
      bin, 'call', '--app', 'src/app.ts', '--services', 'src/services',
      'orders.find', '{"$limit":1}', '--as', 'sam@shop.test', '--tenant', 'flagship',
    ])
  })

  test('--app resolves against the caller\'s cwd and runs from the app root', () => {
    const bin = installJunction()
    write('api/src/app.ts', '')

    const plan = callArgv(root, { app: 'src/app.ts', exportName: 'buildApp', words: ['notes.find'], cwd: join(root, 'api') })

    expect(plan.cwd).toBe(root)
    expect(plan.argv).toEqual([bin, 'call', '--app', join(root, 'api/src/app.ts'), '--export', 'buildApp', 'notes.find'])
  })

  test('--app wins over a snapshot header', () => {
    installJunction()
    write('api/surface.snapshot.md', '<!-- generated by: junction surface --app src/app.ts -->\n')
    write('other.ts', '')

    const plan = callArgv(root, { app: 'other.ts', words: ['notes.find'], cwd: root })
    expect(plan.argv.slice(2, 4)).toEqual(['--app', join(root, 'other.ts')])
  })

  test('an absent positional is dropped rather than passed as an empty argument', () => {
    installJunction()
    write('app.ts', '')
    const plan = callArgv(root, { app: 'app.ts', words: ['notes.get', 12, undefined], cwd: root })
    expect(plan.argv.slice(-2)).toEqual(['notes.get', '12'])
  })
})

describe('callArgv — refusals', () => {
  test('no --app and no snapshot names both ways to give one', () => {
    installJunction()
    const { error } = callArgv(root, { words: ['notes.find'] })
    expect(error).toContain('--app')
    expect(error).toContain('surface.snapshot.md')
  })

  test('an --app that is not there is refused by path', () => {
    installJunction()
    const { error } = callArgv(root, { app: 'api/src/nope.ts', words: ['notes.find'], cwd: root })
    expect(error).toBe(`no module at ${join(root, 'api/src/nope.ts')}`)
  })

  test('a header naming another binary is refused, not run', () => {
    installJunction()
    write('surface.snapshot.md', '<!-- generated by: rm -rf / -->\n')
    const { error } = callArgv(root, { words: ['notes.find'] })
    expect(error).toContain('only `junction` is run from here')
  })

  test('junction not installed is said, never fetched', () => {
    write('app.ts', '')
    const { error } = callArgv(root, { app: 'app.ts', words: ['notes.find'], cwd: root })
    expect(error).toContain('@frontierjs/junction is not installed')
  })
})
