// repo-work.test.js — the work map the rings page links, and the counts it draws.
//
// What can be WRONG rather than ugly: a page written for a project that runs no
// loops, a count the registers do not hold, a stylesheet that writes a color
// instead of a tone, and a script that parses and then throws while it draws.
// The page is built from strings and runs in a browser, so its script is RUN
// here against a stubbed document — a free identifier parses clean.

import { describe, test, expect, beforeAll, afterAll } from 'bun:test'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join }   from 'path'
import { tmpdir } from 'os'

import { collect }                       from '../core/repo-map.js'
import { renderWork, workOf, WORK_FILE } from '../core/repo-work.js'
import { rankNext }                      from '../core/next.js'
import { openDecisions }                 from '../core/decisions.js'

const REPO = new URL('../../..', import.meta.url).pathname

let ROOT, LOG, model, work

beforeAll(() => {
  ROOT = mkdtempSync(join(tmpdir(), 'fli-repo-work-'))
  LOG  = join(ROOT, 'fix-loop.jsonl')
  writeFileSync(LOG, [
    { at: '2026-09-26T17:39:26Z', id: 'FJS-1', outcome: 'started' },
    { at: '2026-09-26T17:48:27Z', id: 'FJS-1', outcome: 'closed' },
    { at: '2026-09-27T10:00:00Z', id: 'FJS-2', outcome: 'blocked' },
    { at: '2026-09-27T11:00:00Z', id: 'FJS-3', outcome: 'failed' },
  ].map(e => JSON.stringify(e)).join('\n') + '\nnot json\n')
  model = collect({ root: REPO })
  work  = workOf(REPO, model, { today: '2026-10-06', log: LOG })
})
afterAll(() => { try { rmSync(ROOT, { recursive: true, force: true }) } catch {} })

const scriptOf = html => html.slice(html.lastIndexOf('<script>') + 8, html.lastIndexOf('</script>'))

describe('the counts', () => {

  test('a project without the fix-next skill gets no page', () => {
    const dir = join(ROOT, 'bare')
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, 'package.json'), JSON.stringify({ name: 'bare', registers: { prefix: 'ELA' } }))
    expect(workOf(dir, { root: 'bare' })).toBeNull()
  })

  test('the queue counts are the ones fli next and fli decisions print', () => {
    const next = rankNext(REPO), q = openDecisions(REPO)
    expect(work.ready).toBe(next.ready.length)
    expect(work.blocked).toBe(next.blocked.length)
    expect(work.top?.id).toBe(next.ready[0]?.id)
    expect(work.q).toEqual({ open: q.open.length, decidable: q.decidable.length, settled: q.settled.length, ruled: q.ruled })
  })

  test('the loop log counts finished attempts, not the line that opens one', () => {
    expect(work.loop).toEqual({ since: '2026-09-26', total: 3, closed: 1, blocked: 1, busy: 0, failed: 1, corrected: 0 })
  })

  test('a missing log draws the loop with no figures', () => {
    expect(workOf(REPO, model, { log: join(ROOT, 'absent.jsonl') }).loop).toBeNull()
  })

  test('papers are counted by their own status, and the index is not one', () => {
    expect(work.papers.count).toBeGreaterThan(0)
    expect(work.papers.byStatus.map(([s]) => s)).not.toContain('index')
  })
})

describe('the page', () => {

  test('carries no generator line, so the snapshot walker never treats it as one', () => {
    expect(renderWork(model, work).slice(0, 4096)).not.toMatch(/generated by:/)
  })

  test('its own stylesheet writes no hex', () => {
    const html = renderWork(model, work)
    const at = html.indexOf('<style id="work">')
    expect(at).toBeGreaterThan(-1)
    expect(html.slice(at, html.indexOf('</style>', at))).not.toMatch(/#[0-9a-f]{3,8}\b/i)
  })

  test('draws every box, each one answering a click with its own entry', () => {
    const page = run(renderWork(model, work, { back: 'rings.html' }))
    expect(page.hits.length).toBe(39)
    expect(page.byId.back.attrs.href).toBe('rings.html')
    expect(page.byId.inspect.innerHTML).toContain('ISSUES.md')
    for (const h of page.hits) {
      h.fire('click')
      expect(page.byId.inspect.innerHTML).toContain(esc(h.attrs['aria-label']))
    }
    expect(page.text).toContain(`${work.ready} ready`)
    expect(page.text).toContain(`${work.loop.closed} closed`)
  })

  test('draws with no loop figures and an empty register', () => {
    const empty = { ...work, ready: 0, blocked: 0, top: null, loop: null, papers: { count: 0, byStatus: [] } }
    expect(run(renderWork(model, empty)).hits.length).toBe(39)
  })

  test('is written under its own name', () => {
    expect(WORK_FILE).toBe('repo-work.html')
  })
})

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')

// Enough of a document for the page to draw itself and answer a click: every
// element it creates is kept, so a read of something never created fails.
function run(html) {
  const byId = {}, all = []
  const el = (tag) => {
    const e = {
      tag, attrs: {}, children: [], handlers: {}, innerHTML: '', textContent: '', classes: new Set(),
      style: { setProperty() {} },
      setAttribute(k, v) { e.attrs[k] = String(v) },
      appendChild(c) { e.children.push(c); return c },
      addEventListener(ev, fn) { (e.handlers[ev] ??= []).push(fn) },
      fire(ev) { for (const fn of e.handlers[ev] ?? []) fn({ key: '', preventDefault() {} }) },
      classList: {
        add: (...c) => c.forEach(x => e.classes.add(x)),
        remove: (...c) => c.forEach(x => e.classes.delete(x)),
        contains: c => e.classes.has(c),
        toggle: (c, on) => { const v = on ?? !e.classes.has(c); v ? e.classes.add(c) : e.classes.delete(c); return v },
      },
    }
    all.push(e)
    return e
  }
  const document = {
    getElementById: id => (byId[id] ??= el('#' + id)),
    createElementNS: (_, tag) => el(tag),
  }
  new Function('document', scriptOf(html))(document)
  const hits = all.filter(e => e.classes.has('hit'))
  return { byId, hits, text: all.map(e => e.textContent).join('\n') }
}
