// snapshots.test.js — finding and validating committed snapshots.
//
// The engine behind both `fli test:snapshots` and the framework repo's own CI
// phase. These tests cover the half that decides WHETHER to run something: the
// header parse, the binary allow-list and the argument shape. The half that
// runs it is exercised for real every time either caller runs — and cannot be
// faked here without spawning a subprocess that would reach the network.
//
// The rule the refusals encode: a header is data, and data this executes is a
// supply chain.

import { describe, test, expect, beforeAll, afterAll } from 'bun:test'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join }   from 'path'
import { tmpdir } from 'os'

import { findSnapshots, missingSnapshots, formatSnapshotResults, binCommand, SNAPSHOT_BINS } from '../core/snapshots.js'
import { readdirSync, readFileSync } from 'fs'

let ROOT

function tree(name, files) {
  const dir = join(ROOT, name)
  for (const [path, body] of Object.entries(files)) {
    const full = join(dir, path)
    mkdirSync(join(full, '..'), { recursive: true })
    writeFileSync(full, body)
  }
  return dir
}

const find = (dir) => findSnapshots({ root: dir })
const only = (dir) => find(dir)[0]

beforeAll(() => { ROOT = mkdtempSync(join(tmpdir(), 'fli-snapshots-')) })
afterAll(()  => { try { rmSync(ROOT, { recursive: true, force: true }) } catch {} })

describe('finding snapshots', () => {

  test('reads the generator out of a markdown header', () => {
    const dir = tree('md', {
      'db/access.snapshot.md': '# Access snapshot\n\n<!-- generated by: litestone access --schema schema.lite -->\n\nprose\n',
    })
    expect(only(dir).argv).toEqual(['litestone', 'access', '--schema', 'schema.lite'])
    expect(only(dir).dir).toBe('db')
  })

  test('reads it out of a SQL comment too — the extension is the renderer’s choice', () => {
    const dir = tree('sql', {
      'db/ddl.snapshot.sql': '-- Schema snapshot — DDL\n--\n-- generated by: litestone ddl --schema schema.lite\n--\nCREATE TABLE x (id INTEGER);\n',
    })
    expect(only(dir).argv).toEqual(['litestone', 'ddl', '--schema', 'schema.lite'])
  })

  test('and out of a JSON string, where a comment cannot go', () => {
    const dir = tree('json', {
      'db/x.snapshot.json': '{\n  "$comment": "generated by: litestone access --schema schema.lite",\n  "a": 1\n}\n',
    })
    expect(only(dir).argv).toEqual(['litestone', 'access', '--schema', 'schema.lite'])
  })

  test('finds every snapshot in the tree, sorted, and nothing else', () => {
    const dir = tree('many', {
      'db/access.snapshot.md':  '<!-- generated by: litestone access --schema schema.lite -->\n',
      'web/routes.snapshot.md': '<!-- generated by: sierra routes --config config/sierra.config.js -->\n',
      'db/schema.lite':         'model User { id Int @id }\n',
      'README.md':              '# not a snapshot\n',
    })
    expect(find(dir).map(s => s.file)).toEqual(['db/access.snapshot.md', 'web/routes.snapshot.md'])
  })

  test('skips node_modules — another package’s snapshot is that package’s gate', () => {
    const dir = tree('vendor', {
      'db/access.snapshot.md': '<!-- generated by: litestone access --schema schema.lite -->\n',
      'node_modules/@frontierjs/thing/db/access.snapshot.md': '<!-- generated by: litestone access --schema schema.lite -->\n',
    })
    expect(find(dir).map(s => s.file)).toEqual(['db/access.snapshot.md'])
  })
})

describe('refusing to run the wrong thing', () => {

  test('a snapshot naming no generator is an error, not a skip', () => {
    const dir = tree('bare', { 'db/a.snapshot.md': '# Snapshot\n\nno header here\n' })
    const s = only(dir)
    expect(s.argv).toBeNull()
    // A generated file nothing can recheck looks like a guarantee in review and
    // holds nobody to anything — so it fails rather than being counted as fine.
    expect(s.error).toContain('names no generator')
  })

  test('a generator outside the allow-list is refused by name', () => {
    const dir = tree('evil', { 'db/b.snapshot.md': '<!-- generated by: rm -rf / -->\n' })
    const s = only(dir)
    expect(s.argv).toBeNull()
    expect(s.error).toContain('`rm`')
    expect(SNAPSHOT_BINS.has('rm')).toBe(false)
  })

  test('shell syntax in an argument is refused', () => {
    const dir = tree('shell', { 'db/c.snapshot.md': '<!-- generated by: litestone access --schema $(evil) -->\n' })
    const s = only(dir)
    expect(s.argv).toBeNull()
    expect(s.error).toContain('$(evil)')
  })

  test('every allowed binary is a framework CLI, not a shell', () => {
    // The list is the whole protection. A general-purpose runner here (`bash`,
    // `node`, `npx`) would make the header arbitrary code.
    expect([...SNAPSHOT_BINS.keys()].sort()).toEqual(['fli', 'junction', 'litestone', 'sierra'])
  })
})

describe('snapshots an app does not have yet', () => {

  const SCAFFOLD = {
    'db/schema.lite':                 'model User { id Int @id }\n',
    'api/src/app.ts':                 'export const app = {}\n',
    'web/config/sierra.config.js':    'export default {}\n',
    'package.json':                   '{ "dependencies": { "@frontierjs/junction": "*" } }\n',
  }
  const missing = (dir) => missingSnapshots({ root: dir }).map(m => m.file)

  test('a fresh app is missing every register its layout calls for', () => {
    const dir = tree('fresh', SCAFFOLD)
    expect(missing(dir)).toEqual([
      'db/access.snapshot.md', 'db/ddl.snapshot.sql', 'db/release.snapshot.md', 'db/jsonschema.snapshot.md',
      'surface.snapshot.md', 'jobs.snapshot.md', 'principal.snapshot.md',
      'web/routes.snapshot.md',
    ])
    // Seeded at the app root, where `.env` is — the app module refuses to load without it.
    expect(missingSnapshots({ root: dir }).find(m => m.file === 'surface.snapshot.md'))
      .toMatchObject({ dir: '.', argv: ['junction', 'surface', '--app', 'api/src/app.ts'] })
  })

  test('a register committed under api/ is not missing — the file header owns it from then on', () => {
    const dir = tree('under-api', {
      ...SCAFFOLD,
      'api/surface.snapshot.md': '<!-- generated by: junction surface --app src/app.ts -->\n',
    })
    expect(missing(dir)).not.toContain('surface.snapshot.md')
    // The control: the rows beside it are still reported.
    expect(missing(dir)).toContain('jobs.snapshot.md')
  })

  test('notifications only when the app depends on the package', () => {
    const without = tree('no-notify', SCAFFOLD)
    const withPkg = tree('notify', {
      ...SCAFFOLD,
      'package.json': '{ "dependencies": { "@frontierjs/notifications": "*" } }\n',
    })
    expect(missing(without)).not.toContain('notifications.snapshot.md')
    expect(missing(withPkg)).toContain('notifications.snapshot.md')
  })

  test('outside an app root nothing is expected — the repo CI phase stays a pure recheck', () => {
    const dir = tree('not-an-app', { 'packages/x/README.md': '# x\n' })
    expect(missing(dir)).toEqual([])
  })
})

describe('reporting', () => {

  test('a failure prints the command that fixes it, with its directory', () => {
    const out = formatSnapshotResults([
      { file: 'db/ddl.snapshot.sql', dir: 'db', argv: ['litestone', 'ddl', '--schema', 'schema.lite'], ok: false, error: 'no longer matches its source' },
      { file: 'db/access.snapshot.md', dir: 'db', argv: ['litestone', 'access'], ok: true, error: null },
    ])
    expect(out.join('\n')).toContain('cd db && bunx litestone ddl --schema schema.lite')
    // A passing snapshot prints nothing — a green line beside a red one is how a
    // failure gets read as noise.
    expect(out.join('\n')).not.toContain('access')
  })
})

// The commands that build a shell string run the app's installed copy of a
// framework bin, never `bunx`, which on a machine with no install fetches
// whatever the registry holds under the bare name (FJS-1586).
describe('a framework bin as a shell prefix', () => {

  test('resolves through the installed package, under the interpreter its shebang names', () => {
    const dir = tree('bin-installed', {
      'node_modules/@frontierjs/litestone/package.json': JSON.stringify({ name: '@frontierjs/litestone', bin: { litestone: 'src/cli.js' } }),
      'node_modules/@frontierjs/litestone/src/cli.js':   '#!/usr/bin/env bun\n',
      'node_modules/@frontierjs/sierra/package.json':    JSON.stringify({ name: '@frontierjs/sierra', bin: { sierra: 'src/cli.js' } }),
      'node_modules/@frontierjs/sierra/src/cli.js':      '#!/usr/bin/env node\n',
    })
    expect(binCommand('litestone', dir)).toBe(`bun ${JSON.stringify(join(dir, 'node_modules/@frontierjs/litestone/src/cli.js'))}`)
    expect(binCommand('sierra', dir)).toBe(`node ${JSON.stringify(join(dir, 'node_modules/@frontierjs/sierra/src/cli.js'))}`)
  })

  test('not installed is null, never a fetch', () => {
    const dir = tree('bin-missing', { 'package.json': JSON.stringify({ name: 'app' }) })
    expect(binCommand('litestone', dir)).toBeNull()
  })

  // The refusal half: a command body that EXECUTES `bunx litestone|sierra|junction`.
  // A scaffolded package.json script, a string printed for a person to type and
  // a `docker exec` into an installed image are not a fetch fli makes, and are
  // not matched: the pattern is an exec'd command string.
  test('no fli command executes one through bunx', () => {
    const cli  = join(import.meta.dir, '..')
    const exec = /(command:|execSync\().*bunx (litestone|sierra|junction)/
    const hits = []
    for (const top of ['commands', 'core']) {
      for (const rel of readdirSync(join(cli, top), { recursive: true })) {
        if (!/\.(md|js)$/.test(rel)) continue
        readFileSync(join(cli, top, rel), 'utf8').split('\n').forEach((line, i) => {
          if (exec.test(line)) hits.push(`${top}/${rel}:${i + 1}`)
        })
      }
    }
    expect(hits).toEqual([])
  })
})
