// Generated by @frontierjs/litestone
// Do not edit — re-run `litestone types` to regenerate

// ── Utility types ────────────────────────────────────────────────────────────

export type WhereOp<T> = {
  not?:        T | null
  in?:         T[]
  notIn?:      T[]
  lt?:         T
  lte?:        T
  gt?:         T
  gte?:        T
  contains?:   string
  startsWith?: string
  endsWith?:   string
}

export type OrderDir = 'asc' | 'desc'

/** Base type mixed into every Where interface — adds the $raw escape hatch. */
export interface WhereBase {
  /** Raw SQL predicate. Use the sql`` tag for safe parameter binding. */
  $raw?: { _litestoneRaw: true; sql: string; params: unknown[] } | string
}

// ── Enums ────────────────────────────────────────────────────────────────────

export type VerificationPurpose = 'passwordReset' | 'emailVerify' | 'oauthLink'

export type AccountType = 'individual' | 'organization'

export type WorkspaceType = 'personal' | 'team' | 'enterprise'

export type WorkspaceRole = 'viewer' | 'billing' | 'developer' | 'admin' | 'owner'

export type UserKind = 'human' | 'bot' | 'ai'

export type UserStatus = 'pending_verification' | 'active' | 'suspended'

export type WorkspaceStatus = 'active' | 'suspended'

export type SecretKind = 'ssh_key' | 'provider_key' | 'registry_auth' | 'tls_cert' | 'notification' | 'generic'

export type ServerStatus = 'pending' | 'provisioning' | 'installing' | 'ready' | 'online' | 'unreachable' | 'draining' | 'stopped' | 'destroyed'

export type ServerRole = 'general' | 'build' | 'database' | 'gateway' | 'worker'

export type ProviderKind = 'custom' | 'hetzner'

export type EnvironmentTier = 'development' | 'test' | 'preview' | 'staging' | 'production'

export type AppType = 'container' | 'worker' | 'database' | 'daemon' | 'cron' | 'static' | 'function'

export type AppStatus = 'unknown' | 'stopped' | 'starting' | 'running' | 'stopping' | 'deploying' | 'error'

export type DeployStatus = 'pending' | 'building' | 'pushing' | 'deploying' | 'success' | 'failed' | 'cancelled' | 'rolled_back'

export type StepStatus = 'pending' | 'running' | 'success' | 'failed' | 'skipped'

export type JobKind = 'one_shot' | 'scheduled' | 'triggered' | 'workflow'

export type JobStatus = 'pending' | 'running' | 'failed' | 'cancelled'

export type RunStatus = 'pending' | 'running' | 'success' | 'failed' | 'timeout'

export type AlertSeverity = 'info' | 'warning' | 'critical'

export type AlertSubject = 'server' | 'volume'

export type ActorKind = 'user' | 'api_key' | 'system'

export type ChannelKind = 'slack' | 'pagerduty' | 'email' | 'webhook'

export type FlagType = 'boolean' | 'variant'

export type WidgetKind = 'server_fleet' | 'server_health' | 'app_status' | 'deploy_feed' | 'job_history' | 'activity_feed' | 'alert_status' | 'service_health' | 'stat_counter'

export type ParamGenerator = 'random_hex_16' | 'random_hex_32' | 'random_hex_64'

export type BackupKind = 'manual' | 'scheduled'

export type BackupDestination = 'local' | 's3'

export type NotificationKind = 'deploy_success' | 'deploy_failed' | 'alert_firing' | 'alert_resolved' | 'member_joined' | 'job_failed' | 'weekly_digest'

export type Capability = 'Environment.create' | 'Environment.delete' | 'Environment.update' | 'Environment.variables' | 'Server.create' | 'Server.delete' | 'Server.drain' | 'Server.reboot' | 'Server.undrain' | 'Server.update'

// ── Models ───────────────────────────────────────────────────────────────────

// ─── Credential ──────────────────────────────────────────────────

export interface Credential {
  id: string
  userId: string
  type: string
  /** @guarded */
  value: string
  label?: string | null
  /** @guarded @encrypted @secret */
  accessToken?: string | null
  /** @guarded @encrypted @secret */
  refreshToken?: string | null
  tokenExpiresAt?: string | null
  scope?: string | null
  createdAt: string
}

export interface CredentialCreate {
  id?: string
  userId: string
  type: string
  value: string
  label?: string | null
  accessToken?: string | null
  refreshToken?: string | null
  tokenExpiresAt?: string | null
  scope?: string | null
}

export interface CredentialUpdate {
  id?: string
  userId?: string
  type?: string
  value?: string
  label?: string | null
  accessToken?: string | null
  refreshToken?: string | null
  tokenExpiresAt?: string | null
  scope?: string | null
}

export interface CredentialWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  userId?: string | WhereOp<string> | null
  type?: string | WhereOp<string> | null
  value?: string | WhereOp<string> | null
  label?: string | WhereOp<string> | null
  accessToken?: string | WhereOp<string> | null
  refreshToken?: string | WhereOp<string> | null
  tokenExpiresAt?: string | WhereOp<string> | null
  scope?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  AND?: CredentialWhere[]
  OR?:  CredentialWhere[]
  NOT?: CredentialWhere
}

export type CredentialOrderBy =
  | { [K in keyof Omit<Credential, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Credential, never>]?: OrderDir }>

// ─── Session ─────────────────────────────────────────────────────

export interface Session {
  id: string
  userId: string
  /** @guarded */
  token: string
  expiresAt: string
  ipAddress?: string | null
  userAgent?: string | null
  createdAt: string
}

export interface SessionCreate {
  id?: string
  userId: string
  token: string
  expiresAt: string
  ipAddress?: string | null
  userAgent?: string | null
}

export interface SessionUpdate {
  id?: string
  userId?: string
  token?: string
  expiresAt?: string
  ipAddress?: string | null
  userAgent?: string | null
}

export interface SessionWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  userId?: string | WhereOp<string> | null
  token?: string | WhereOp<string> | null
  expiresAt?: string | WhereOp<string> | null
  ipAddress?: string | WhereOp<string> | null
  userAgent?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  AND?: SessionWhere[]
  OR?:  SessionWhere[]
  NOT?: SessionWhere
}

export type SessionOrderBy =
  | { [K in keyof Omit<Session, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Session, never>]?: OrderDir }>

// ─── Verification ────────────────────────────────────────────────

export interface Verification {
  id: string
  purpose: VerificationPurpose
  /**
   * The address being proved. Required, and every purpose has one — that is
   * the test for whether something belongs in this table at all.
   */
  identifier: string
  /**
   * The secret the caller presents, and what the row is found by. One meaning
   * on every row.
   * @guarded
   */
  value: string
  /**
   * oauthLink only: which identity is waiting to be attached once the address
   * answers for itself. Null for the other two, which attach nothing.
   */
  provider?: string | null
  subject?: string | null
  expiresAt: string
  createdAt: string
}

export interface VerificationCreate {
  id?: string
  purpose: VerificationPurpose
  /**
   * The address being proved. Required, and every purpose has one — that is
   * the test for whether something belongs in this table at all.
   */
  identifier: string
  /**
   * The secret the caller presents, and what the row is found by. One meaning
   * on every row.
   */
  value: string
  /**
   * oauthLink only: which identity is waiting to be attached once the address
   * answers for itself. Null for the other two, which attach nothing.
   */
  provider?: string | null
  subject?: string | null
  expiresAt: string
}

export interface VerificationUpdate {
  id?: string
  purpose?: VerificationPurpose
  identifier?: string
  value?: string
  provider?: string | null
  subject?: string | null
  expiresAt?: string
}

export interface VerificationWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  purpose?: VerificationPurpose | WhereOp<VerificationPurpose> | null
  identifier?: string | WhereOp<string> | null
  value?: string | WhereOp<string> | null
  provider?: string | WhereOp<string> | null
  subject?: string | WhereOp<string> | null
  expiresAt?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  AND?: VerificationWhere[]
  OR?:  VerificationWhere[]
  NOT?: VerificationWhere
}

export type VerificationOrderBy =
  | { [K in keyof Omit<Verification, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Verification, never>]?: OrderDir }>

// ─── OauthFlow ───────────────────────────────────────────────────

/**
 * An authorization in flight.
 * 
 * `Oauth` and not `OAuth`, for the reason basecamp's `ThreeCX` is not `3CX`:
 * the accessor is the model name with its first character lowered and nothing
 * else, so `OAuthFlow` would be reached as `db.oAuthFlow`.
 * 
 * NOT a Verification, and the reuse was the mistake: nobody is proving
 * anything here, there is no address yet and there may be no account at the
 * end of it. `state` is a CSRF token echoed back by a redirect rather than a
 * secret sent to a person, its life is minutes rather than hours, and it
 * carries a PKCE verifier that no other row in this schema has a use for.
 * Three different answers to what a column means is three tables wearing one
 * name.
 */
export interface OauthFlow {
  id: string
  /**
   * Half of the browser binding. The other half is a cookie, and a flow found
   * by this value ALONE is login CSRF — RFC 9700 requires the token be bound
   * to the user agent, which a database row cannot do by itself.
   * @guarded
   */
  state: string
  provider: string
  /**
   * PKCE code_verifier. Never leaves this process — it goes to the token
   * endpoint and nowhere else.
   * @guarded
   */
  verifier: string
  /**
   * Already checked against the app's allow-list when the flow started, so
   * what is stored here is known good and the way back decides nothing.
   */
  returnTo?: string | null
  expiresAt: string
  createdAt: string
}

export interface OauthFlowCreate {
  id?: string
  /**
   * Half of the browser binding. The other half is a cookie, and a flow found
   * by this value ALONE is login CSRF — RFC 9700 requires the token be bound
   * to the user agent, which a database row cannot do by itself.
   */
  state: string
  provider: string
  /**
   * PKCE code_verifier. Never leaves this process — it goes to the token
   * endpoint and nowhere else.
   */
  verifier: string
  /**
   * Already checked against the app's allow-list when the flow started, so
   * what is stored here is known good and the way back decides nothing.
   */
  returnTo?: string | null
  expiresAt: string
}

export interface OauthFlowUpdate {
  id?: string
  state?: string
  provider?: string
  verifier?: string
  returnTo?: string | null
  expiresAt?: string
}

export interface OauthFlowWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  state?: string | WhereOp<string> | null
  provider?: string | WhereOp<string> | null
  verifier?: string | WhereOp<string> | null
  returnTo?: string | WhereOp<string> | null
  expiresAt?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  AND?: OauthFlowWhere[]
  OR?:  OauthFlowWhere[]
  NOT?: OauthFlowWhere
}

export type OauthFlowOrderBy =
  | { [K in keyof Omit<OauthFlow, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<OauthFlow, never>]?: OrderDir }>

// ─── User ────────────────────────────────────────────────────────

export interface User {
  id: string
  email: string
  name?: string | null
  emailVerified: boolean
  role: string
  accountId?: string | null
  kind: UserKind
  status: UserStatus
  username?: string | null
  displayName?: string | null
  avatarUrl?: string | null
  scopes: unknown
  isSystemAdmin: boolean
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface UserCreate {
  id?: string
  email: string
  name?: string | null
  emailVerified?: boolean
  role?: string
  accountId?: string | null
  kind?: UserKind
  status?: UserStatus
  username?: string | null
  displayName?: string | null
  avatarUrl?: string | null
  scopes?: unknown
  isSystemAdmin?: boolean
}

export interface UserUpdate {
  id?: string
  email?: string
  name?: string | null
  emailVerified?: boolean
  role?: string
  accountId?: string | null
  kind?: UserKind
  status?: UserStatus
  username?: string | null
  displayName?: string | null
  avatarUrl?: string | null
  scopes?: unknown
  isSystemAdmin?: boolean
}

export interface UserWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  email?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  emailVerified?: boolean | WhereOp<boolean> | null
  role?: string | WhereOp<string> | null
  accountId?: string | WhereOp<string> | null
  kind?: UserKind | WhereOp<UserKind> | null
  status?: UserStatus | WhereOp<UserStatus> | null
  username?: string | WhereOp<string> | null
  displayName?: string | WhereOp<string> | null
  avatarUrl?: string | WhereOp<string> | null
  scopes?: unknown | WhereOp<unknown> | null
  isSystemAdmin?: boolean | WhereOp<boolean> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: UserWhere[]
  OR?:  UserWhere[]
  NOT?: UserWhere
}

export type UserOrderBy =
  | { [K in keyof Omit<User, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<User, never>]?: OrderDir }>

// ─── Account ─────────────────────────────────────────────────────

export interface Account {
  id: string
  type: AccountType
  status: string
  slug: string
  displayName: string
  avatarUrl?: string | null
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface AccountCreate {
  id?: string
  type?: AccountType
  status?: string
  slug: string
  displayName: string
  avatarUrl?: string | null
}

export interface AccountUpdate {
  id?: string
  type?: AccountType
  status?: string
  slug?: string
  displayName?: string
  avatarUrl?: string | null
}

export interface AccountWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  type?: AccountType | WhereOp<AccountType> | null
  status?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  displayName?: string | WhereOp<string> | null
  avatarUrl?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: AccountWhere[]
  OR?:  AccountWhere[]
  NOT?: AccountWhere
}

export type AccountOrderBy =
  | { [K in keyof Omit<Account, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Account, never>]?: OrderDir }>

// ─── Workspace ───────────────────────────────────────────────────

export interface Workspace {
  id: string
  accountId: string
  name: string
  slug: string
  type: WorkspaceType
  ownerId: string
  settings: unknown
  status: WorkspaceStatus
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface WorkspaceCreate {
  id?: string
  accountId: string
  name: string
  slug: string
  type?: WorkspaceType
  ownerId: string
  settings?: unknown
  status?: WorkspaceStatus
}

export interface WorkspaceUpdate {
  id?: string
  accountId?: string
  name?: string
  slug?: string
  type?: WorkspaceType
  ownerId?: string
  settings?: unknown
  status?: WorkspaceStatus
  version: number
}

export interface WorkspaceWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  accountId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  type?: WorkspaceType | WhereOp<WorkspaceType> | null
  ownerId?: string | WhereOp<string> | null
  settings?: unknown | WhereOp<unknown> | null
  status?: WorkspaceStatus | WhereOp<WorkspaceStatus> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: WorkspaceWhere[]
  OR?:  WorkspaceWhere[]
  NOT?: WorkspaceWhere
}

export type WorkspaceOrderBy =
  | { [K in keyof Omit<Workspace, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Workspace, never>]?: OrderDir }>

// ─── WorkspaceMember ─────────────────────────────────────────────

export interface WorkspaceMember {
  id: string
  workspaceId: string
  userId: string
  /** This caller's authority in this workspace. Nobody may change their own. */
  role: WorkspaceRole
  /**
   * What this membership may do on the models that declare @@capabilities —
   * the grid that runs BESIDE the ladder rather than under it (`FJS-D146`).
   * Stamped from the role at every write through `grantsFor()`; a role is the
   * default set and not a synonym for one, so an operator may take a grant
   * away from one person without inventing a role for them.
   * 
   * Read onto the principal as `auth().capabilities` by `membershipClaim`,
   * per request and per workspace — the same person holds a different set in
   * each, which is why it is a column here and not a field on the session.
   */
  capabilities: Capability[]
  invitedBy?: string | null
  invitedAt?: string | null
  acceptedAt?: string | null
  createdAt: string
  updatedAt: string
}

export interface WorkspaceMemberCreate {
  id?: string
  workspaceId: string
  userId: string
  /** This caller's authority in this workspace. Nobody may change their own. */
  role?: WorkspaceRole
  /**
   * What this membership may do on the models that declare @@capabilities —
   * the grid that runs BESIDE the ladder rather than under it (`FJS-D146`).
   * Stamped from the role at every write through `grantsFor()`; a role is the
   * default set and not a synonym for one, so an operator may take a grant
   * away from one person without inventing a role for them.
   * 
   * Read onto the principal as `auth().capabilities` by `membershipClaim`,
   * per request and per workspace — the same person holds a different set in
   * each, which is why it is a column here and not a field on the session.
   */
  capabilities?: Capability[]
  invitedBy?: string | null
  invitedAt?: string | null
  acceptedAt?: string | null
}

export interface WorkspaceMemberUpdate {
  id?: string
  workspaceId?: string
  userId?: string
  role?: WorkspaceRole
  capabilities?: Capability[]
  invitedBy?: string | null
  invitedAt?: string | null
  acceptedAt?: string | null
}

export interface WorkspaceMemberWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  userId?: string | WhereOp<string> | null
  role?: WorkspaceRole | WhereOp<WorkspaceRole> | null
  capabilities?: Capability[] | WhereOp<Capability[]> | null
  invitedBy?: string | WhereOp<string> | null
  invitedAt?: string | WhereOp<string> | null
  acceptedAt?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  AND?: WorkspaceMemberWhere[]
  OR?:  WorkspaceMemberWhere[]
  NOT?: WorkspaceMemberWhere
}

export type WorkspaceMemberOrderBy =
  | { [K in keyof Omit<WorkspaceMember, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<WorkspaceMember, never>]?: OrderDir }>

// ─── Invitation ──────────────────────────────────────────────────

export interface Invitation {
  id: string
  workspaceId: string
  email: string
  role: WorkspaceRole
  /** @guarded */
  token: string
  expiresAt: string
  invitedBy?: string | null
  createdAt: string
  updatedAt: string
}

export interface InvitationCreate {
  id?: string
  workspaceId: string
  email: string
  role?: WorkspaceRole
  token: string
  expiresAt: string
  invitedBy?: string | null
}

export interface InvitationUpdate {
  id?: string
  workspaceId?: string
  email?: string
  role?: WorkspaceRole
  token?: string
  expiresAt?: string
  invitedBy?: string | null
}

export interface InvitationWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  email?: string | WhereOp<string> | null
  role?: WorkspaceRole | WhereOp<WorkspaceRole> | null
  token?: string | WhereOp<string> | null
  expiresAt?: string | WhereOp<string> | null
  invitedBy?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  AND?: InvitationWhere[]
  OR?:  InvitationWhere[]
  NOT?: InvitationWhere
}

export type InvitationOrderBy =
  | { [K in keyof Omit<Invitation, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Invitation, never>]?: OrderDir }>

// ─── Secret ──────────────────────────────────────────────────────

export interface Secret {
  id: string
  workspaceId: string
  name: string
  kind: SecretKind
  /** @encrypted */
  data: string
  isVerified: boolean
  createdBy?: string | null
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface SecretCreate {
  id?: string
  workspaceId: string
  name: string
  kind?: SecretKind
  data?: string
  isVerified?: boolean
  createdBy?: string | null
}

export interface SecretUpdate {
  id?: string
  workspaceId?: string
  name?: string
  kind?: SecretKind
  data?: string
  isVerified?: boolean
  createdBy?: string | null
  version: number
}

export interface SecretWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  kind?: SecretKind | WhereOp<SecretKind> | null
  data?: string | WhereOp<string> | null
  isVerified?: boolean | WhereOp<boolean> | null
  createdBy?: string | WhereOp<string> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: SecretWhere[]
  OR?:  SecretWhere[]
  NOT?: SecretWhere
}

export type SecretOrderBy =
  | { [K in keyof Omit<Secret, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Secret, never>]?: OrderDir }>

// ─── ApiKey ──────────────────────────────────────────────────────

export interface ApiKey {
  id: string
  workspaceId: string
  userId: string
  credentialId?: string | null
  name: string
  tokenHint: string
  scopes: string[]
  expiresAt?: string | null
  revokedAt?: string | null
  lastUsedAt?: string | null
  totalUses: number
  usageDate?: string | null
  usesOnDate: number
  createdBy?: string | null
  createdAt: string
  updatedAt: string
}

export interface ApiKeyCreate {
  id?: string
  workspaceId: string
  userId: string
  credentialId?: string | null
  name: string
  tokenHint: string
  scopes?: string[]
  expiresAt?: string | null
  revokedAt?: string | null
  lastUsedAt?: string | null
  totalUses?: number
  usageDate?: string | null
  usesOnDate?: number
  createdBy?: string | null
}

export interface ApiKeyUpdate {
  id?: string
  workspaceId?: string
  userId?: string
  credentialId?: string | null
  name?: string
  tokenHint?: string
  scopes?: string[]
  expiresAt?: string | null
  revokedAt?: string | null
  lastUsedAt?: string | null
  totalUses?: number
  usageDate?: string | null
  usesOnDate?: number
  createdBy?: string | null
}

export interface ApiKeyWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  userId?: string | WhereOp<string> | null
  credentialId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  tokenHint?: string | WhereOp<string> | null
  scopes?: string[] | WhereOp<string[]> | null
  expiresAt?: string | WhereOp<string> | null
  revokedAt?: string | WhereOp<string> | null
  lastUsedAt?: string | WhereOp<string> | null
  totalUses?: number | WhereOp<number> | null
  usageDate?: string | WhereOp<string> | null
  usesOnDate?: number | WhereOp<number> | null
  createdBy?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  AND?: ApiKeyWhere[]
  OR?:  ApiKeyWhere[]
  NOT?: ApiKeyWhere
}

export type ApiKeyOrderBy =
  | { [K in keyof Omit<ApiKey, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<ApiKey, never>]?: OrderDir }>

// ─── Server ──────────────────────────────────────────────────────

export interface Server {
  id: string
  workspaceId: string
  name: string
  slug: string
  status: ServerStatus
  role: ServerRole
  providerKind: ProviderKind
  providerId?: string | null
  providerServerId?: string | null
  registerMethod: string
  region: string
  ipAddress?: string | null
  ipv6Address?: string | null
  sshPort: number
  sshUser: string
  sshKeyId?: string | null
  outpostVersion?: string | null
  outpostUrl?: string | null
  lastHeartbeatAt?: string | null
  plan: unknown
  actualSpecs?: unknown | null
  health?: unknown | null
  dockerState?: unknown | null
  labels: unknown
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface ServerCreate {
  id?: string
  workspaceId: string
  name: string
  slug: string
  status?: ServerStatus
  role?: ServerRole
  providerKind?: ProviderKind
  providerId?: string | null
  providerServerId?: string | null
  registerMethod?: string
  region?: string
  ipAddress?: string | null
  ipv6Address?: string | null
  sshPort?: number
  sshUser?: string
  sshKeyId?: string | null
  outpostVersion?: string | null
  outpostUrl?: string | null
  lastHeartbeatAt?: string | null
  plan?: unknown
  actualSpecs?: unknown | null
  health?: unknown | null
  dockerState?: unknown | null
  labels?: unknown
}

export interface ServerUpdate {
  id?: string
  workspaceId?: string
  name?: string
  slug?: string
  status?: ServerStatus
  role?: ServerRole
  providerKind?: ProviderKind
  providerId?: string | null
  providerServerId?: string | null
  registerMethod?: string
  region?: string
  ipAddress?: string | null
  ipv6Address?: string | null
  sshPort?: number
  sshUser?: string
  sshKeyId?: string | null
  outpostVersion?: string | null
  outpostUrl?: string | null
  lastHeartbeatAt?: string | null
  plan?: unknown
  actualSpecs?: unknown | null
  health?: unknown | null
  dockerState?: unknown | null
  labels?: unknown
}

export interface ServerWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  status?: ServerStatus | WhereOp<ServerStatus> | null
  role?: ServerRole | WhereOp<ServerRole> | null
  providerKind?: ProviderKind | WhereOp<ProviderKind> | null
  providerId?: string | WhereOp<string> | null
  providerServerId?: string | WhereOp<string> | null
  registerMethod?: string | WhereOp<string> | null
  region?: string | WhereOp<string> | null
  ipAddress?: string | WhereOp<string> | null
  ipv6Address?: string | WhereOp<string> | null
  sshPort?: number | WhereOp<number> | null
  sshUser?: string | WhereOp<string> | null
  sshKeyId?: string | WhereOp<string> | null
  outpostVersion?: string | WhereOp<string> | null
  outpostUrl?: string | WhereOp<string> | null
  lastHeartbeatAt?: string | WhereOp<string> | null
  plan?: unknown | WhereOp<unknown> | null
  actualSpecs?: unknown | WhereOp<unknown> | null
  health?: unknown | WhereOp<unknown> | null
  dockerState?: unknown | WhereOp<unknown> | null
  labels?: unknown | WhereOp<unknown> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: ServerWhere[]
  OR?:  ServerWhere[]
  NOT?: ServerWhere
}

export type ServerOrderBy =
  | { [K in keyof Omit<Server, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Server, never>]?: OrderDir }>

// ─── ServerEvent ─────────────────────────────────────────────────

export interface ServerEvent {
  id: string
  serverId: string
  kind: string
  message: string
  metadata: unknown
  createdAt: string
}

export interface ServerEventCreate {
  id?: string
  serverId: string
  kind: string
  message: string
  metadata?: unknown
}

export interface ServerEventUpdate {
  id?: string
  serverId?: string
  kind?: string
  message?: string
  metadata?: unknown
}

export interface ServerEventWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  serverId?: string | WhereOp<string> | null
  kind?: string | WhereOp<string> | null
  message?: string | WhereOp<string> | null
  metadata?: unknown | WhereOp<unknown> | null
  createdAt?: string | WhereOp<string> | null
  AND?: ServerEventWhere[]
  OR?:  ServerEventWhere[]
  NOT?: ServerEventWhere
}

export type ServerEventOrderBy =
  | { [K in keyof Omit<ServerEvent, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<ServerEvent, never>]?: OrderDir }>

// ─── OutpostNonce ────────────────────────────────────────────────

export interface OutpostNonce {
  nonce: string
  seenAt: string
}

export interface OutpostNonceCreate {
  nonce?: string
  seenAt?: string
}

export interface OutpostNonceUpdate {
  nonce?: string
  seenAt?: string
}

export interface OutpostNonceWhere extends WhereBase {
  nonce?: string | WhereOp<string> | null
  seenAt?: string | WhereOp<string> | null
  AND?: OutpostNonceWhere[]
  OR?:  OutpostNonceWhere[]
  NOT?: OutpostNonceWhere
}

export type OutpostNonceOrderBy =
  | { [K in keyof Omit<OutpostNonce, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<OutpostNonce, never>]?: OrderDir }>

// ─── Volume ──────────────────────────────────────────────────────

export interface Volume {
  id: string
  serverId: string
  name: string
  driver: string
  mountPoint?: string | null
  sizeBytes: number
  inUse: boolean
  containers: string[]
  createdOnServer?: string | null
  discoveredAt: string
  lastSeenAt: string
}

export interface VolumeCreate {
  id?: string
  serverId: string
  name: string
  driver?: string
  mountPoint?: string | null
  sizeBytes?: number
  inUse?: boolean
  containers?: string[]
  createdOnServer?: string | null
  discoveredAt?: string
  lastSeenAt?: string
}

export interface VolumeUpdate {
  id?: string
  serverId?: string
  name?: string
  driver?: string
  mountPoint?: string | null
  sizeBytes?: number
  inUse?: boolean
  containers?: string[]
  createdOnServer?: string | null
  discoveredAt?: string
  lastSeenAt?: string
}

export interface VolumeWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  serverId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  driver?: string | WhereOp<string> | null
  mountPoint?: string | WhereOp<string> | null
  sizeBytes?: number | WhereOp<number> | null
  inUse?: boolean | WhereOp<boolean> | null
  containers?: string[] | WhereOp<string[]> | null
  createdOnServer?: string | WhereOp<string> | null
  discoveredAt?: string | WhereOp<string> | null
  lastSeenAt?: string | WhereOp<string> | null
  AND?: VolumeWhere[]
  OR?:  VolumeWhere[]
  NOT?: VolumeWhere
}

export type VolumeOrderBy =
  | { [K in keyof Omit<Volume, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Volume, never>]?: OrderDir }>

// ─── Network ─────────────────────────────────────────────────────

export interface Network {
  id: string
  workspaceId: string
  name: string
  slug: string
  type: string
  cidr: string
  provider: string
  config: unknown
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface NetworkCreate {
  id?: string
  workspaceId: string
  name: string
  slug: string
  type?: string
  cidr?: string
  provider?: string
  config?: unknown
}

export interface NetworkUpdate {
  id?: string
  workspaceId?: string
  name?: string
  slug?: string
  type?: string
  cidr?: string
  provider?: string
  config?: unknown
  version: number
}

export interface NetworkWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  type?: string | WhereOp<string> | null
  cidr?: string | WhereOp<string> | null
  provider?: string | WhereOp<string> | null
  config?: unknown | WhereOp<unknown> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: NetworkWhere[]
  OR?:  NetworkWhere[]
  NOT?: NetworkWhere
}

export type NetworkOrderBy =
  | { [K in keyof Omit<Network, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Network, never>]?: OrderDir }>

// ─── ServerNetwork ───────────────────────────────────────────────

export interface ServerNetwork {
  id: string
  serverId: string
  networkId: string
  ipAddress?: string | null
  joinedAt: string
}

export interface ServerNetworkCreate {
  id?: string
  serverId: string
  networkId: string
  ipAddress?: string | null
  joinedAt?: string
}

export interface ServerNetworkUpdate {
  id?: string
  serverId?: string
  networkId?: string
  ipAddress?: string | null
  joinedAt?: string
}

export interface ServerNetworkWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  serverId?: string | WhereOp<string> | null
  networkId?: string | WhereOp<string> | null
  ipAddress?: string | WhereOp<string> | null
  joinedAt?: string | WhereOp<string> | null
  AND?: ServerNetworkWhere[]
  OR?:  ServerNetworkWhere[]
  NOT?: ServerNetworkWhere
}

export type ServerNetworkOrderBy =
  | { [K in keyof Omit<ServerNetwork, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<ServerNetwork, never>]?: OrderDir }>

// ─── Project ─────────────────────────────────────────────────────

export interface Project {
  id: string
  workspaceId: string
  name: string
  slug: string
  description?: string | null
  status: string
  tags: unknown
  metadata: unknown
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface ProjectCreate {
  id?: string
  workspaceId: string
  name: string
  slug: string
  description?: string | null
  status?: string
  tags?: unknown
  metadata?: unknown
}

export interface ProjectUpdate {
  id?: string
  workspaceId?: string
  name?: string
  slug?: string
  description?: string | null
  status?: string
  tags?: unknown
  metadata?: unknown
  version: number
}

export interface ProjectWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  description?: string | WhereOp<string> | null
  status?: string | WhereOp<string> | null
  tags?: unknown | WhereOp<unknown> | null
  metadata?: unknown | WhereOp<unknown> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: ProjectWhere[]
  OR?:  ProjectWhere[]
  NOT?: ProjectWhere
}

export type ProjectOrderBy =
  | { [K in keyof Omit<Project, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Project, never>]?: OrderDir }>

// ─── Environment ─────────────────────────────────────────────────

export interface Environment {
  id: string
  projectId: string
  workspaceId: string
  name: string
  slug: string
  tier: EnvironmentTier
  isProtected: boolean
  /**
   * The environment's variables — a separate grant from editing the
   * environment itself. Renaming a staging environment and reading its
   * secrets are the same `update` to the gate and are not the same act.
   */
  variables: unknown
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface EnvironmentCreate {
  id?: string
  projectId: string
  workspaceId: string
  name: string
  slug: string
  tier?: EnvironmentTier
  isProtected?: boolean
  /**
   * The environment's variables — a separate grant from editing the
   * environment itself. Renaming a staging environment and reading its
   * secrets are the same `update` to the gate and are not the same act.
   */
  variables?: unknown
}

export interface EnvironmentUpdate {
  id?: string
  projectId?: string
  workspaceId?: string
  name?: string
  slug?: string
  tier?: EnvironmentTier
  isProtected?: boolean
  variables?: unknown
  version: number
}

export interface EnvironmentWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  projectId?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  tier?: EnvironmentTier | WhereOp<EnvironmentTier> | null
  isProtected?: boolean | WhereOp<boolean> | null
  variables?: unknown | WhereOp<unknown> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: EnvironmentWhere[]
  OR?:  EnvironmentWhere[]
  NOT?: EnvironmentWhere
}

export type EnvironmentOrderBy =
  | { [K in keyof Omit<Environment, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Environment, never>]?: OrderDir }>

// ─── App ─────────────────────────────────────────────────────────

export interface App {
  id: string
  workspaceId: string
  environmentId: string
  name: string
  slug: string
  type: AppType
  status: AppStatus
  source: unknown
  config: unknown
  port?: number | null
  isPublic: boolean
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface AppCreate {
  id?: string
  workspaceId: string
  environmentId: string
  name: string
  slug: string
  type?: AppType
  status?: AppStatus
  source?: unknown
  config?: unknown
  port?: number | null
  isPublic?: boolean
}

export interface AppUpdate {
  id?: string
  workspaceId?: string
  environmentId?: string
  name?: string
  slug?: string
  type?: AppType
  status?: AppStatus
  source?: unknown
  config?: unknown
  port?: number | null
  isPublic?: boolean
}

export interface AppWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  environmentId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  type?: AppType | WhereOp<AppType> | null
  status?: AppStatus | WhereOp<AppStatus> | null
  source?: unknown | WhereOp<unknown> | null
  config?: unknown | WhereOp<unknown> | null
  port?: number | WhereOp<number> | null
  isPublic?: boolean | WhereOp<boolean> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: AppWhere[]
  OR?:  AppWhere[]
  NOT?: AppWhere
}

export type AppOrderBy =
  | { [K in keyof Omit<App, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<App, never>]?: OrderDir }>

// ─── Domain ──────────────────────────────────────────────────────

export interface Domain {
  id: string
  workspaceId: string
  appId: string
  hostname: string
  isPrimary: boolean
  redirectTo?: string | null
  port: number
  proxied: boolean
  sslMode: string
  certSecretId?: string | null
  certKind?: string | null
  certIssuedAt?: string | null
  certExpiresAt?: string | null
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface DomainCreate {
  id?: string
  workspaceId: string
  appId: string
  hostname: string
  isPrimary?: boolean
  redirectTo?: string | null
  port?: number
  proxied?: boolean
  sslMode?: string
  certSecretId?: string | null
  certKind?: string | null
  certIssuedAt?: string | null
  certExpiresAt?: string | null
}

export interface DomainUpdate {
  id?: string
  workspaceId?: string
  appId?: string
  hostname?: string
  isPrimary?: boolean
  redirectTo?: string | null
  port?: number
  proxied?: boolean
  sslMode?: string
  certSecretId?: string | null
  certKind?: string | null
  certIssuedAt?: string | null
  certExpiresAt?: string | null
  version: number
}

export interface DomainWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  appId?: string | WhereOp<string> | null
  hostname?: string | WhereOp<string> | null
  isPrimary?: boolean | WhereOp<boolean> | null
  redirectTo?: string | WhereOp<string> | null
  port?: number | WhereOp<number> | null
  proxied?: boolean | WhereOp<boolean> | null
  sslMode?: string | WhereOp<string> | null
  certSecretId?: string | WhereOp<string> | null
  certKind?: string | WhereOp<string> | null
  certIssuedAt?: string | WhereOp<string> | null
  certExpiresAt?: string | WhereOp<string> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: DomainWhere[]
  OR?:  DomainWhere[]
  NOT?: DomainWhere
}

export type DomainOrderBy =
  | { [K in keyof Omit<Domain, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Domain, never>]?: OrderDir }>

// ─── AppServer ───────────────────────────────────────────────────

export interface AppServer {
  id: string
  appId: string
  serverId: string
  replicaIndex: number
  status: string
  containerId?: string | null
  assignedAt: string
  startedAt?: string | null
  stoppedAt?: string | null
}

export interface AppServerCreate {
  id?: string
  appId: string
  serverId: string
  replicaIndex?: number
  status?: string
  containerId?: string | null
  assignedAt?: string
  startedAt?: string | null
  stoppedAt?: string | null
}

export interface AppServerUpdate {
  id?: string
  appId?: string
  serverId?: string
  replicaIndex?: number
  status?: string
  containerId?: string | null
  assignedAt?: string
  startedAt?: string | null
  stoppedAt?: string | null
}

export interface AppServerWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  appId?: string | WhereOp<string> | null
  serverId?: string | WhereOp<string> | null
  replicaIndex?: number | WhereOp<number> | null
  status?: string | WhereOp<string> | null
  containerId?: string | WhereOp<string> | null
  assignedAt?: string | WhereOp<string> | null
  startedAt?: string | WhereOp<string> | null
  stoppedAt?: string | WhereOp<string> | null
  AND?: AppServerWhere[]
  OR?:  AppServerWhere[]
  NOT?: AppServerWhere
}

export type AppServerOrderBy =
  | { [K in keyof Omit<AppServer, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<AppServer, never>]?: OrderDir }>

// ─── AppNetwork ──────────────────────────────────────────────────

export interface AppNetwork {
  id: string
  appId: string
  networkId: string
  ipAddress?: string | null
  dnsName?: string | null
  joinedAt: string
}

export interface AppNetworkCreate {
  id?: string
  appId: string
  networkId: string
  ipAddress?: string | null
  dnsName?: string | null
  joinedAt?: string
}

export interface AppNetworkUpdate {
  id?: string
  appId?: string
  networkId?: string
  ipAddress?: string | null
  dnsName?: string | null
  joinedAt?: string
}

export interface AppNetworkWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  appId?: string | WhereOp<string> | null
  networkId?: string | WhereOp<string> | null
  ipAddress?: string | WhereOp<string> | null
  dnsName?: string | WhereOp<string> | null
  joinedAt?: string | WhereOp<string> | null
  AND?: AppNetworkWhere[]
  OR?:  AppNetworkWhere[]
  NOT?: AppNetworkWhere
}

export type AppNetworkOrderBy =
  | { [K in keyof Omit<AppNetwork, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<AppNetwork, never>]?: OrderDir }>

// ─── Deployment ──────────────────────────────────────────────────

export interface Deployment {
  id: string
  appId: string
  environmentId?: string | null
  workspaceId: string
  status: DeployStatus
  trigger: string
  fromImage?: string | null
  toImage?: string | null
  commitSha?: string | null
  commitMessage?: string | null
  branch?: string | null
  author?: string | null
  builtImage?: string | null
  previousDeploymentId?: string | null
  configSnapshot: unknown
  triggeredBy?: string | null
  queuedAt: string
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
  createdAt: string
  updatedAt: string
}

export interface DeploymentCreate {
  id?: string
  appId: string
  environmentId?: string | null
  workspaceId: string
  status?: DeployStatus
  trigger?: string
  fromImage?: string | null
  toImage?: string | null
  commitSha?: string | null
  commitMessage?: string | null
  branch?: string | null
  author?: string | null
  builtImage?: string | null
  previousDeploymentId?: string | null
  configSnapshot?: unknown
  triggeredBy?: string | null
  queuedAt?: string
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface DeploymentUpdate {
  id?: string
  appId?: string
  environmentId?: string | null
  workspaceId?: string
  status?: DeployStatus
  trigger?: string
  fromImage?: string | null
  toImage?: string | null
  commitSha?: string | null
  commitMessage?: string | null
  branch?: string | null
  author?: string | null
  builtImage?: string | null
  previousDeploymentId?: string | null
  configSnapshot?: unknown
  triggeredBy?: string | null
  queuedAt?: string
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface DeploymentWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  appId?: string | WhereOp<string> | null
  environmentId?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  status?: DeployStatus | WhereOp<DeployStatus> | null
  trigger?: string | WhereOp<string> | null
  fromImage?: string | WhereOp<string> | null
  toImage?: string | WhereOp<string> | null
  commitSha?: string | WhereOp<string> | null
  commitMessage?: string | WhereOp<string> | null
  branch?: string | WhereOp<string> | null
  author?: string | WhereOp<string> | null
  builtImage?: string | WhereOp<string> | null
  previousDeploymentId?: string | WhereOp<string> | null
  configSnapshot?: unknown | WhereOp<unknown> | null
  triggeredBy?: string | WhereOp<string> | null
  queuedAt?: string | WhereOp<string> | null
  startedAt?: string | WhereOp<string> | null
  finishedAt?: string | WhereOp<string> | null
  durationMs?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  AND?: DeploymentWhere[]
  OR?:  DeploymentWhere[]
  NOT?: DeploymentWhere
}

export type DeploymentOrderBy =
  | { [K in keyof Omit<Deployment, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Deployment, never>]?: OrderDir }>

// ─── DeploymentStep ──────────────────────────────────────────────

export interface DeploymentStep {
  id: string
  deploymentId: string
  name: string
  status: StepStatus
  output?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface DeploymentStepCreate {
  id?: string
  deploymentId: string
  name: string
  status?: StepStatus
  output?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface DeploymentStepUpdate {
  id?: string
  deploymentId?: string
  name?: string
  status?: StepStatus
  output?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface DeploymentStepWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  deploymentId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  status?: StepStatus | WhereOp<StepStatus> | null
  output?: string | WhereOp<string> | null
  startedAt?: string | WhereOp<string> | null
  finishedAt?: string | WhereOp<string> | null
  durationMs?: number | WhereOp<number> | null
  AND?: DeploymentStepWhere[]
  OR?:  DeploymentStepWhere[]
  NOT?: DeploymentStepWhere
}

export type DeploymentStepOrderBy =
  | { [K in keyof Omit<DeploymentStep, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<DeploymentStep, never>]?: OrderDir }>

// ─── Job ─────────────────────────────────────────────────────────

export interface Job {
  id: string
  workspaceId: string
  appId?: string | null
  environmentId?: string | null
  name: string
  kind: JobKind
  status: JobStatus
  command?: string | null
  cronExpression?: string | null
  nextRunAt?: string | null
  trigger: string
  triggerConfig: unknown
  timeoutSeconds: number
  retryLimit: number
  retryCount: number
  lastRunAt?: string | null
  lastRunStatus?: string | null
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface JobCreate {
  id?: string
  workspaceId: string
  appId?: string | null
  environmentId?: string | null
  name: string
  kind?: JobKind
  status?: JobStatus
  command?: string | null
  cronExpression?: string | null
  nextRunAt?: string | null
  trigger?: string
  triggerConfig?: unknown
  timeoutSeconds?: number
  retryLimit?: number
  retryCount?: number
  lastRunAt?: string | null
  lastRunStatus?: string | null
}

export interface JobUpdate {
  id?: string
  workspaceId?: string
  appId?: string | null
  environmentId?: string | null
  name?: string
  kind?: JobKind
  status?: JobStatus
  command?: string | null
  cronExpression?: string | null
  nextRunAt?: string | null
  trigger?: string
  triggerConfig?: unknown
  timeoutSeconds?: number
  retryLimit?: number
  retryCount?: number
  lastRunAt?: string | null
  lastRunStatus?: string | null
}

export interface JobWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  appId?: string | WhereOp<string> | null
  environmentId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  kind?: JobKind | WhereOp<JobKind> | null
  status?: JobStatus | WhereOp<JobStatus> | null
  command?: string | WhereOp<string> | null
  cronExpression?: string | WhereOp<string> | null
  nextRunAt?: string | WhereOp<string> | null
  trigger?: string | WhereOp<string> | null
  triggerConfig?: unknown | WhereOp<unknown> | null
  timeoutSeconds?: number | WhereOp<number> | null
  retryLimit?: number | WhereOp<number> | null
  retryCount?: number | WhereOp<number> | null
  lastRunAt?: string | WhereOp<string> | null
  lastRunStatus?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: JobWhere[]
  OR?:  JobWhere[]
  NOT?: JobWhere
}

export type JobOrderBy =
  | { [K in keyof Omit<Job, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Job, never>]?: OrderDir }>

// ─── JobRun ──────────────────────────────────────────────────────

export interface JobRun {
  id: string
  jobId: string
  status: RunStatus
  trigger: string
  startedAt: string
  finishedAt?: string | null
  durationMs?: number | null
  exitCode?: number | null
  error?: string | null
  output: unknown
  createdAt: string
}

export interface JobRunCreate {
  id?: string
  jobId: string
  status?: RunStatus
  trigger?: string
  startedAt?: string
  finishedAt?: string | null
  durationMs?: number | null
  exitCode?: number | null
  error?: string | null
  output?: unknown
}

export interface JobRunUpdate {
  id?: string
  jobId?: string
  status?: RunStatus
  trigger?: string
  startedAt?: string
  finishedAt?: string | null
  durationMs?: number | null
  exitCode?: number | null
  error?: string | null
  output?: unknown
}

export interface JobRunWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  jobId?: string | WhereOp<string> | null
  status?: RunStatus | WhereOp<RunStatus> | null
  trigger?: string | WhereOp<string> | null
  startedAt?: string | WhereOp<string> | null
  finishedAt?: string | WhereOp<string> | null
  durationMs?: number | WhereOp<number> | null
  exitCode?: number | WhereOp<number> | null
  error?: string | WhereOp<string> | null
  output?: unknown | WhereOp<unknown> | null
  createdAt?: string | WhereOp<string> | null
  AND?: JobRunWhere[]
  OR?:  JobRunWhere[]
  NOT?: JobRunWhere
}

export type JobRunOrderBy =
  | { [K in keyof Omit<JobRun, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<JobRun, never>]?: OrderDir }>

// ─── Recipe ──────────────────────────────────────────────────────

export interface Recipe {
  id: string
  workspaceId: string
  name: string
  slug: string
  description?: string | null
  script: string
  timeoutSeconds: number
  lastRunAt?: string | null
  runCount: number
  createdBy?: string | null
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface RecipeCreate {
  id?: string
  workspaceId: string
  name: string
  slug: string
  description?: string | null
  script: string
  timeoutSeconds?: number
  lastRunAt?: string | null
  runCount?: number
  createdBy?: string | null
}

export interface RecipeUpdate {
  id?: string
  workspaceId?: string
  name?: string
  slug?: string
  description?: string | null
  script?: string
  timeoutSeconds?: number
  lastRunAt?: string | null
  runCount?: number
  createdBy?: string | null
}

export interface RecipeWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  description?: string | WhereOp<string> | null
  script?: string | WhereOp<string> | null
  timeoutSeconds?: number | WhereOp<number> | null
  lastRunAt?: string | WhereOp<string> | null
  runCount?: number | WhereOp<number> | null
  createdBy?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: RecipeWhere[]
  OR?:  RecipeWhere[]
  NOT?: RecipeWhere
}

export type RecipeOrderBy =
  | { [K in keyof Omit<Recipe, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Recipe, never>]?: OrderDir }>

// ─── RecipeRun ───────────────────────────────────────────────────

export interface RecipeRun {
  id: string
  recipeId: string
  serverId: string
  status: RunStatus
  script: string
  requestedBy?: string | null
  exitCode?: number | null
  stdout?: string | null
  stderr?: string | null
  error?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
  createdAt: string
}

export interface RecipeRunCreate {
  id?: string
  recipeId: string
  serverId: string
  status?: RunStatus
  script: string
  requestedBy?: string | null
  exitCode?: number | null
  stdout?: string | null
  stderr?: string | null
  error?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface RecipeRunUpdate {
  id?: string
  recipeId?: string
  serverId?: string
  status?: RunStatus
  script?: string
  requestedBy?: string | null
  exitCode?: number | null
  stdout?: string | null
  stderr?: string | null
  error?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface RecipeRunWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  recipeId?: string | WhereOp<string> | null
  serverId?: string | WhereOp<string> | null
  status?: RunStatus | WhereOp<RunStatus> | null
  script?: string | WhereOp<string> | null
  requestedBy?: string | WhereOp<string> | null
  exitCode?: number | WhereOp<number> | null
  stdout?: string | WhereOp<string> | null
  stderr?: string | WhereOp<string> | null
  error?: string | WhereOp<string> | null
  startedAt?: string | WhereOp<string> | null
  finishedAt?: string | WhereOp<string> | null
  durationMs?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  AND?: RecipeRunWhere[]
  OR?:  RecipeRunWhere[]
  NOT?: RecipeRunWhere
}

export type RecipeRunOrderBy =
  | { [K in keyof Omit<RecipeRun, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<RecipeRun, never>]?: OrderDir }>

// ─── DiskUsage ───────────────────────────────────────────────────

export interface DiskUsage {
  id: string
  serverId: string
  imagesTotal: number
  imagesUnused: number
  imagesDangling: number
  imageBytes: number
  imagesReclaimableBytes: number
  containersRunning: number
  containersStopped: number
  containersReclaimableBytes: number
  buildCacheBytes: number
  buildCacheReclaimableBytes: number
  reportedAt: string
}

export interface DiskUsageCreate {
  id?: string
  serverId: string
  imagesTotal?: number
  imagesUnused?: number
  imagesDangling?: number
  imageBytes?: number
  imagesReclaimableBytes?: number
  containersRunning?: number
  containersStopped?: number
  containersReclaimableBytes?: number
  buildCacheBytes?: number
  buildCacheReclaimableBytes?: number
  reportedAt?: string
}

export interface DiskUsageUpdate {
  id?: string
  serverId?: string
  imagesTotal?: number
  imagesUnused?: number
  imagesDangling?: number
  imageBytes?: number
  imagesReclaimableBytes?: number
  containersRunning?: number
  containersStopped?: number
  containersReclaimableBytes?: number
  buildCacheBytes?: number
  buildCacheReclaimableBytes?: number
  reportedAt?: string
}

export interface DiskUsageWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  serverId?: string | WhereOp<string> | null
  imagesTotal?: number | WhereOp<number> | null
  imagesUnused?: number | WhereOp<number> | null
  imagesDangling?: number | WhereOp<number> | null
  imageBytes?: number | WhereOp<number> | null
  imagesReclaimableBytes?: number | WhereOp<number> | null
  containersRunning?: number | WhereOp<number> | null
  containersStopped?: number | WhereOp<number> | null
  containersReclaimableBytes?: number | WhereOp<number> | null
  buildCacheBytes?: number | WhereOp<number> | null
  buildCacheReclaimableBytes?: number | WhereOp<number> | null
  reportedAt?: string | WhereOp<string> | null
  AND?: DiskUsageWhere[]
  OR?:  DiskUsageWhere[]
  NOT?: DiskUsageWhere
}

export type DiskUsageOrderBy =
  | { [K in keyof Omit<DiskUsage, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<DiskUsage, never>]?: OrderDir }>

// ─── CleanupRun ──────────────────────────────────────────────────

export interface CleanupRun {
  id: string
  serverId: string
  status: RunStatus
  targets: string[]
  keepImages: number
  requestedBy?: string | null
  freedBytes: number
  detail: unknown
  error?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
  createdAt: string
}

export interface CleanupRunCreate {
  id?: string
  serverId: string
  status?: RunStatus
  targets?: string[]
  keepImages?: number
  requestedBy?: string | null
  freedBytes?: number
  detail?: unknown
  error?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface CleanupRunUpdate {
  id?: string
  serverId?: string
  status?: RunStatus
  targets?: string[]
  keepImages?: number
  requestedBy?: string | null
  freedBytes?: number
  detail?: unknown
  error?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface CleanupRunWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  serverId?: string | WhereOp<string> | null
  status?: RunStatus | WhereOp<RunStatus> | null
  targets?: string[] | WhereOp<string[]> | null
  keepImages?: number | WhereOp<number> | null
  requestedBy?: string | WhereOp<string> | null
  freedBytes?: number | WhereOp<number> | null
  detail?: unknown | WhereOp<unknown> | null
  error?: string | WhereOp<string> | null
  startedAt?: string | WhereOp<string> | null
  finishedAt?: string | WhereOp<string> | null
  durationMs?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  AND?: CleanupRunWhere[]
  OR?:  CleanupRunWhere[]
  NOT?: CleanupRunWhere
}

export type CleanupRunOrderBy =
  | { [K in keyof Omit<CleanupRun, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<CleanupRun, never>]?: OrderDir }>

// ─── FeatureFlag ─────────────────────────────────────────────────

export interface FeatureFlag {
  id: string
  workspaceId: string
  key: string
  description?: string | null
  type: FlagType
  tags: string[]
  variants: unknown
  isEnabled: boolean
  rollout: number
  createdBy?: string | null
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface FeatureFlagCreate {
  id?: string
  workspaceId: string
  key: string
  description?: string | null
  type?: FlagType
  tags?: string[]
  variants?: unknown
  isEnabled?: boolean
  rollout?: number
  createdBy?: string | null
}

export interface FeatureFlagUpdate {
  id?: string
  workspaceId?: string
  key?: string
  description?: string | null
  type?: FlagType
  tags?: string[]
  variants?: unknown
  isEnabled?: boolean
  rollout?: number
  createdBy?: string | null
  version: number
}

export interface FeatureFlagWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  key?: string | WhereOp<string> | null
  description?: string | WhereOp<string> | null
  type?: FlagType | WhereOp<FlagType> | null
  tags?: string[] | WhereOp<string[]> | null
  variants?: unknown | WhereOp<unknown> | null
  isEnabled?: boolean | WhereOp<boolean> | null
  rollout?: number | WhereOp<number> | null
  createdBy?: string | WhereOp<string> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: FeatureFlagWhere[]
  OR?:  FeatureFlagWhere[]
  NOT?: FeatureFlagWhere
}

export type FeatureFlagOrderBy =
  | { [K in keyof Omit<FeatureFlag, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<FeatureFlag, never>]?: OrderDir }>

// ─── FlagOverride ────────────────────────────────────────────────

export interface FlagOverride {
  id: string
  flagId: string
  environmentId: string
  isEnabled: boolean
  rollout: number
  variantKey?: string | null
  createdAt: string
  updatedAt: string
}

export interface FlagOverrideCreate {
  id?: string
  flagId: string
  environmentId: string
  isEnabled?: boolean
  rollout?: number
  variantKey?: string | null
}

export interface FlagOverrideUpdate {
  id?: string
  flagId?: string
  environmentId?: string
  isEnabled?: boolean
  rollout?: number
  variantKey?: string | null
}

export interface FlagOverrideWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  flagId?: string | WhereOp<string> | null
  environmentId?: string | WhereOp<string> | null
  isEnabled?: boolean | WhereOp<boolean> | null
  rollout?: number | WhereOp<number> | null
  variantKey?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  AND?: FlagOverrideWhere[]
  OR?:  FlagOverrideWhere[]
  NOT?: FlagOverrideWhere
}

export type FlagOverrideOrderBy =
  | { [K in keyof Omit<FlagOverride, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<FlagOverride, never>]?: OrderDir }>

// ─── NotificationChannel ─────────────────────────────────────────

export interface NotificationChannel {
  id: string
  workspaceId: string
  name: string
  kind: ChannelKind
  config: unknown
  secretId?: string | null
  isActive: boolean
  lastTestAt?: string | null
  lastDeliveryAt?: string | null
  createdBy?: string | null
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface NotificationChannelCreate {
  id?: string
  workspaceId: string
  name: string
  kind: ChannelKind
  config?: unknown
  secretId?: string | null
  secret?: string | null
  isActive?: boolean
  lastTestAt?: string | null
  lastDeliveryAt?: string | null
  createdBy?: string | null
}

export interface NotificationChannelUpdate {
  id?: string
  workspaceId?: string
  name?: string
  kind?: ChannelKind
  config?: unknown
  secretId?: string | null
  secret?: string | null
  isActive?: boolean
  lastTestAt?: string | null
  lastDeliveryAt?: string | null
  createdBy?: string | null
  version: number
}

export interface NotificationChannelWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  kind?: ChannelKind | WhereOp<ChannelKind> | null
  config?: unknown | WhereOp<unknown> | null
  secretId?: string | WhereOp<string> | null
  isActive?: boolean | WhereOp<boolean> | null
  lastTestAt?: string | WhereOp<string> | null
  lastDeliveryAt?: string | WhereOp<string> | null
  createdBy?: string | WhereOp<string> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: NotificationChannelWhere[]
  OR?:  NotificationChannelWhere[]
  NOT?: NotificationChannelWhere
}

export type NotificationChannelOrderBy =
  | { [K in keyof Omit<NotificationChannel, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<NotificationChannel, never>]?: OrderDir }>

// ─── AlertRule ───────────────────────────────────────────────────

export interface AlertRule {
  id: string
  workspaceId: string
  name: string
  description?: string | null
  severity: AlertSeverity
  metricName: string
  condition: unknown
  isActive: boolean
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
}

export interface AlertRuleCreate {
  id?: string
  workspaceId: string
  name: string
  description?: string | null
  severity?: AlertSeverity
  metricName: string
  condition?: unknown
  isActive?: boolean
}

export interface AlertRuleUpdate {
  id?: string
  workspaceId?: string
  name?: string
  description?: string | null
  severity?: AlertSeverity
  metricName?: string
  condition?: unknown
  isActive?: boolean
  version: number
}

export interface AlertRuleWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  description?: string | WhereOp<string> | null
  severity?: AlertSeverity | WhereOp<AlertSeverity> | null
  metricName?: string | WhereOp<string> | null
  condition?: unknown | WhereOp<unknown> | null
  isActive?: boolean | WhereOp<boolean> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  AND?: AlertRuleWhere[]
  OR?:  AlertRuleWhere[]
  NOT?: AlertRuleWhere
}

export type AlertRuleOrderBy =
  | { [K in keyof Omit<AlertRule, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<AlertRule, never>]?: OrderDir }>

// ─── AlertRuleChannel ────────────────────────────────────────────

export interface AlertRuleChannel {
  id: string
  ruleId: string
  channelId: string
  createdAt: string
}

export interface AlertRuleChannelCreate {
  id?: string
  ruleId: string
  channelId: string
}

export interface AlertRuleChannelUpdate {
  id?: string
  ruleId?: string
  channelId?: string
}

export interface AlertRuleChannelWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  ruleId?: string | WhereOp<string> | null
  channelId?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  AND?: AlertRuleChannelWhere[]
  OR?:  AlertRuleChannelWhere[]
  NOT?: AlertRuleChannelWhere
}

export type AlertRuleChannelOrderBy =
  | { [K in keyof Omit<AlertRuleChannel, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<AlertRuleChannel, never>]?: OrderDir }>

// ─── AlertEvent ──────────────────────────────────────────────────

export interface AlertEvent {
  id: string
  ruleId: string
  status: string
  severity: AlertSeverity
  subjectType: AlertSubject
  subjectId: string
  valueAtTrigger: number
  message: string
  firedAt: string
  resolvedAt?: string | null
  acknowledgedBy?: string | null
  acknowledgedAt?: string | null
}

export interface AlertEventCreate {
  id?: string
  ruleId: string
  status?: string
  severity: AlertSeverity
  subjectType: AlertSubject
  subjectId: string
  valueAtTrigger?: number
  message: string
  firedAt?: string
  resolvedAt?: string | null
  acknowledgedBy?: string | null
  acknowledgedAt?: string | null
}

export interface AlertEventUpdate {
  id?: string
  ruleId?: string
  status?: string
  severity?: AlertSeverity
  subjectType?: AlertSubject
  subjectId?: string
  valueAtTrigger?: number
  message?: string
  firedAt?: string
  resolvedAt?: string | null
  acknowledgedBy?: string | null
  acknowledgedAt?: string | null
}

export interface AlertEventWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  ruleId?: string | WhereOp<string> | null
  status?: string | WhereOp<string> | null
  severity?: AlertSeverity | WhereOp<AlertSeverity> | null
  subjectType?: AlertSubject | WhereOp<AlertSubject> | null
  subjectId?: string | WhereOp<string> | null
  valueAtTrigger?: number | WhereOp<number> | null
  message?: string | WhereOp<string> | null
  firedAt?: string | WhereOp<string> | null
  resolvedAt?: string | WhereOp<string> | null
  acknowledgedBy?: string | WhereOp<string> | null
  acknowledgedAt?: string | WhereOp<string> | null
  AND?: AlertEventWhere[]
  OR?:  AlertEventWhere[]
  NOT?: AlertEventWhere
}

export type AlertEventOrderBy =
  | { [K in keyof Omit<AlertEvent, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<AlertEvent, never>]?: OrderDir }>

// ─── Dashboard ───────────────────────────────────────────────────

export interface Dashboard {
  id: string
  workspaceId: string
  name: string
  slug: string
  description?: string | null
  icon?: string | null
  isPinned: boolean
  createdBy?: string | null
  /** @version */
  version: number
  createdAt: string
  updatedAt: string
  deletedAt?: string | null
}

export interface DashboardCreate {
  id?: string
  workspaceId: string
  name: string
  slug: string
  description?: string | null
  icon?: string | null
  isPinned?: boolean
  createdBy?: string | null
}

export interface DashboardUpdate {
  id?: string
  workspaceId?: string
  name?: string
  slug?: string
  description?: string | null
  icon?: string | null
  isPinned?: boolean
  createdBy?: string | null
  version: number
}

export interface DashboardWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  description?: string | WhereOp<string> | null
  icon?: string | WhereOp<string> | null
  isPinned?: boolean | WhereOp<boolean> | null
  createdBy?: string | WhereOp<string> | null
  version?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  deletedAt?: string | WhereOp<string> | null
  AND?: DashboardWhere[]
  OR?:  DashboardWhere[]
  NOT?: DashboardWhere
}

export type DashboardOrderBy =
  | { [K in keyof Omit<Dashboard, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Dashboard, never>]?: OrderDir }>

// ─── DashboardWidget ─────────────────────────────────────────────

export interface DashboardWidget {
  id: string
  dashboardId: string
  kind: WidgetKind
  serverId?: string | null
  appId?: string | null
  config: unknown
  cols: number
  position: number
  createdAt: string
  updatedAt: string
}

export interface DashboardWidgetCreate {
  id?: string
  dashboardId: string
  kind: WidgetKind
  serverId?: string | null
  appId?: string | null
  config?: unknown
  cols?: number
  position?: number
}

export interface DashboardWidgetUpdate {
  id?: string
  dashboardId?: string
  kind?: WidgetKind
  serverId?: string | null
  appId?: string | null
  config?: unknown
  cols?: number
  position?: number
}

export interface DashboardWidgetWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  dashboardId?: string | WhereOp<string> | null
  kind?: WidgetKind | WhereOp<WidgetKind> | null
  serverId?: string | WhereOp<string> | null
  appId?: string | WhereOp<string> | null
  config?: unknown | WhereOp<unknown> | null
  cols?: number | WhereOp<number> | null
  position?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  AND?: DashboardWidgetWhere[]
  OR?:  DashboardWidgetWhere[]
  NOT?: DashboardWidgetWhere
}

export type DashboardWidgetOrderBy =
  | { [K in keyof Omit<DashboardWidget, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<DashboardWidget, never>]?: OrderDir }>

// ─── AuditEvent ──────────────────────────────────────────────────

export interface AuditEvent {
  id: string
  workspaceId?: string | null
  actorId?: string | null
  actorType: ActorKind
  action: string
  subjectType: string
  subjectId: string
  diff?: unknown | null
  createdAt: string
}

export interface AuditEventCreate {
  id?: string
  workspaceId?: string | null
  actorId?: string | null
  actorType?: ActorKind
  action: string
  subjectType: string
  subjectId: string
  diff?: unknown | null
}

export interface AuditEventUpdate {
  id?: string
  workspaceId?: string | null
  actorId?: string | null
  actorType?: ActorKind
  action?: string
  subjectType?: string
  subjectId?: string
  diff?: unknown | null
}

export interface AuditEventWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  actorId?: string | WhereOp<string> | null
  actorType?: ActorKind | WhereOp<ActorKind> | null
  action?: string | WhereOp<string> | null
  subjectType?: string | WhereOp<string> | null
  subjectId?: string | WhereOp<string> | null
  diff?: unknown | WhereOp<unknown> | null
  createdAt?: string | WhereOp<string> | null
  AND?: AuditEventWhere[]
  OR?:  AuditEventWhere[]
  NOT?: AuditEventWhere
}

export type AuditEventOrderBy =
  | { [K in keyof Omit<AuditEvent, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<AuditEvent, never>]?: OrderDir }>

// ─── Blueprint ───────────────────────────────────────────────────

export interface Blueprint {
  id: string
  slug: string
  name: string
  category: string
  description: string
  version: string
  image: string
  icon?: string | null
  brandColor?: string | null
  appType: AppType
  port?: number | null
  persistent: boolean
  volumePath?: string | null
  healthCheck?: string | null
  replicas: number
  cpuLimit?: string | null
  memLimit?: string | null
  notes?: string | null
  links: unknown
  deprecatedAt?: string | null
  createdAt: string
  updatedAt: string
  /** @version */
  revision: number
}

export interface BlueprintCreate {
  id?: string
  slug: string
  name: string
  category: string
  description: string
  version: string
  image: string
  icon?: string | null
  brandColor?: string | null
  appType?: AppType
  port?: number | null
  persistent?: boolean
  volumePath?: string | null
  healthCheck?: string | null
  replicas?: number
  cpuLimit?: string | null
  memLimit?: string | null
  notes?: string | null
  links?: unknown
  deprecatedAt?: string | null
}

export interface BlueprintUpdate {
  id?: string
  slug?: string
  name?: string
  category?: string
  description?: string
  version?: string
  image?: string
  icon?: string | null
  brandColor?: string | null
  appType?: AppType
  port?: number | null
  persistent?: boolean
  volumePath?: string | null
  healthCheck?: string | null
  replicas?: number
  cpuLimit?: string | null
  memLimit?: string | null
  notes?: string | null
  links?: unknown
  deprecatedAt?: string | null
  revision: number
}

export interface BlueprintWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  slug?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  category?: string | WhereOp<string> | null
  description?: string | WhereOp<string> | null
  version?: string | WhereOp<string> | null
  image?: string | WhereOp<string> | null
  icon?: string | WhereOp<string> | null
  brandColor?: string | WhereOp<string> | null
  appType?: AppType | WhereOp<AppType> | null
  port?: number | WhereOp<number> | null
  persistent?: boolean | WhereOp<boolean> | null
  volumePath?: string | WhereOp<string> | null
  healthCheck?: string | WhereOp<string> | null
  replicas?: number | WhereOp<number> | null
  cpuLimit?: string | WhereOp<string> | null
  memLimit?: string | WhereOp<string> | null
  notes?: string | WhereOp<string> | null
  links?: unknown | WhereOp<unknown> | null
  deprecatedAt?: string | WhereOp<string> | null
  createdAt?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  revision?: number | WhereOp<number> | null
  AND?: BlueprintWhere[]
  OR?:  BlueprintWhere[]
  NOT?: BlueprintWhere
}

export type BlueprintOrderBy =
  | { [K in keyof Omit<Blueprint, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Blueprint, never>]?: OrderDir }>

// ─── BlueprintParam ──────────────────────────────────────────────

export interface BlueprintParam {
  id: string
  blueprintId: string
  key: string
  label: string
  hint?: string | null
  defaultValue?: string | null
  required: boolean
  secret: boolean
  generate?: ParamGenerator | null
  position: number
}

export interface BlueprintParamCreate {
  id?: string
  blueprintId: string
  key: string
  label: string
  hint?: string | null
  defaultValue?: string | null
  required?: boolean
  secret?: boolean
  generate?: ParamGenerator | null
  position?: number
}

export interface BlueprintParamUpdate {
  id?: string
  blueprintId?: string
  key?: string
  label?: string
  hint?: string | null
  defaultValue?: string | null
  required?: boolean
  secret?: boolean
  generate?: ParamGenerator | null
  position?: number
}

export interface BlueprintParamWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  blueprintId?: string | WhereOp<string> | null
  key?: string | WhereOp<string> | null
  label?: string | WhereOp<string> | null
  hint?: string | WhereOp<string> | null
  defaultValue?: string | WhereOp<string> | null
  required?: boolean | WhereOp<boolean> | null
  secret?: boolean | WhereOp<boolean> | null
  generate?: ParamGenerator | WhereOp<ParamGenerator> | null
  position?: number | WhereOp<number> | null
  AND?: BlueprintParamWhere[]
  OR?:  BlueprintParamWhere[]
  NOT?: BlueprintParamWhere
}

export type BlueprintParamOrderBy =
  | { [K in keyof Omit<BlueprintParam, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<BlueprintParam, never>]?: OrderDir }>

// ─── RegistryImage ───────────────────────────────────────────────

export interface RegistryImage {
  id: string
  workspaceId: string
  repository: string
  tag: string
  digest: string
  sizeBytes: number
  inUse: boolean
  pushedAt?: string | null
  pushedBy?: string | null
  observedAt: string
}

export interface RegistryImageCreate {
  id?: string
  workspaceId: string
  repository: string
  tag: string
  digest: string
  sizeBytes?: number
  inUse?: boolean
  pushedAt?: string | null
  pushedBy?: string | null
  observedAt?: string
}

export interface RegistryImageUpdate {
  id?: string
  workspaceId?: string
  repository?: string
  tag?: string
  digest?: string
  sizeBytes?: number
  inUse?: boolean
  pushedAt?: string | null
  pushedBy?: string | null
  observedAt?: string
}

export interface RegistryImageWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  workspaceId?: string | WhereOp<string> | null
  repository?: string | WhereOp<string> | null
  tag?: string | WhereOp<string> | null
  digest?: string | WhereOp<string> | null
  sizeBytes?: number | WhereOp<number> | null
  inUse?: boolean | WhereOp<boolean> | null
  pushedAt?: string | WhereOp<string> | null
  pushedBy?: string | WhereOp<string> | null
  observedAt?: string | WhereOp<string> | null
  AND?: RegistryImageWhere[]
  OR?:  RegistryImageWhere[]
  NOT?: RegistryImageWhere
}

export type RegistryImageOrderBy =
  | { [K in keyof Omit<RegistryImage, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<RegistryImage, never>]?: OrderDir }>

// ─── Backup ──────────────────────────────────────────────────────

export interface Backup {
  id: string
  kind: BackupKind
  status: RunStatus
  destination: BackupDestination
  sizeBytes?: number | null
  location?: string | null
  error?: string | null
  requestedBy?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
  createdAt: string
}

export interface BackupCreate {
  id?: string
  kind?: BackupKind
  status?: RunStatus
  destination?: BackupDestination
  sizeBytes?: number | null
  location?: string | null
  error?: string | null
  requestedBy?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface BackupUpdate {
  id?: string
  kind?: BackupKind
  status?: RunStatus
  destination?: BackupDestination
  sizeBytes?: number | null
  location?: string | null
  error?: string | null
  requestedBy?: string | null
  startedAt?: string | null
  finishedAt?: string | null
  durationMs?: number | null
}

export interface BackupWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  kind?: BackupKind | WhereOp<BackupKind> | null
  status?: RunStatus | WhereOp<RunStatus> | null
  destination?: BackupDestination | WhereOp<BackupDestination> | null
  sizeBytes?: number | WhereOp<number> | null
  location?: string | WhereOp<string> | null
  error?: string | WhereOp<string> | null
  requestedBy?: string | WhereOp<string> | null
  startedAt?: string | WhereOp<string> | null
  finishedAt?: string | WhereOp<string> | null
  durationMs?: number | WhereOp<number> | null
  createdAt?: string | WhereOp<string> | null
  AND?: BackupWhere[]
  OR?:  BackupWhere[]
  NOT?: BackupWhere
}

export type BackupOrderBy =
  | { [K in keyof Omit<Backup, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<Backup, never>]?: OrderDir }>

// ─── HubConfig ───────────────────────────────────────────────────

export interface HubConfig {
  id: string
  name: string
  baseUrl: string
  adminEmail: string
  heartbeatTimeoutSeconds: number
  sessionTtlHours: number
  requireTwoFactorForOwners: boolean
  allowApiKeyAuth: boolean
  allowBotUsers: boolean
  backupEnabled: boolean
  backupCron: string
  backupDestination: BackupDestination
  mailFromAddress?: string | null
  mailFromName?: string | null
  updatedAt: string
  /** @version */
  version: number
}

export interface HubConfigCreate {
  id?: string
  name?: string
  baseUrl: string
  adminEmail: string
  heartbeatTimeoutSeconds?: number
  sessionTtlHours?: number
  requireTwoFactorForOwners?: boolean
  allowApiKeyAuth?: boolean
  allowBotUsers?: boolean
  backupEnabled?: boolean
  backupCron?: string
  backupDestination?: BackupDestination
  mailFromAddress?: string | null
  mailFromName?: string | null
}

export interface HubConfigUpdate {
  id?: string
  name?: string
  baseUrl?: string
  adminEmail?: string
  heartbeatTimeoutSeconds?: number
  sessionTtlHours?: number
  requireTwoFactorForOwners?: boolean
  allowApiKeyAuth?: boolean
  allowBotUsers?: boolean
  backupEnabled?: boolean
  backupCron?: string
  backupDestination?: BackupDestination
  mailFromAddress?: string | null
  mailFromName?: string | null
  version: number
}

export interface HubConfigWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  name?: string | WhereOp<string> | null
  baseUrl?: string | WhereOp<string> | null
  adminEmail?: string | WhereOp<string> | null
  heartbeatTimeoutSeconds?: number | WhereOp<number> | null
  sessionTtlHours?: number | WhereOp<number> | null
  requireTwoFactorForOwners?: boolean | WhereOp<boolean> | null
  allowApiKeyAuth?: boolean | WhereOp<boolean> | null
  allowBotUsers?: boolean | WhereOp<boolean> | null
  backupEnabled?: boolean | WhereOp<boolean> | null
  backupCron?: string | WhereOp<string> | null
  backupDestination?: BackupDestination | WhereOp<BackupDestination> | null
  mailFromAddress?: string | WhereOp<string> | null
  mailFromName?: string | WhereOp<string> | null
  updatedAt?: string | WhereOp<string> | null
  version?: number | WhereOp<number> | null
  AND?: HubConfigWhere[]
  OR?:  HubConfigWhere[]
  NOT?: HubConfigWhere
}

export type HubConfigOrderBy =
  | { [K in keyof Omit<HubConfig, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<HubConfig, never>]?: OrderDir }>

// ─── NotificationPreference ──────────────────────────────────────

export interface NotificationPreference {
  id: string
  userId: string
  kind: NotificationKind
  email: boolean
  inApp: boolean
  updatedAt: string
}

export interface NotificationPreferenceCreate {
  id?: string
  userId: string
  kind: NotificationKind
  email?: boolean
  inApp?: boolean
}

export interface NotificationPreferenceUpdate {
  id?: string
  userId?: string
  kind?: NotificationKind
  email?: boolean
  inApp?: boolean
}

export interface NotificationPreferenceWhere extends WhereBase {
  id?: string | WhereOp<string> | null
  userId?: string | WhereOp<string> | null
  kind?: NotificationKind | WhereOp<NotificationKind> | null
  email?: boolean | WhereOp<boolean> | null
  inApp?: boolean | WhereOp<boolean> | null
  updatedAt?: string | WhereOp<string> | null
  AND?: NotificationPreferenceWhere[]
  OR?:  NotificationPreferenceWhere[]
  NOT?: NotificationPreferenceWhere
}

export type NotificationPreferenceOrderBy =
  | { [K in keyof Omit<NotificationPreference, never>]?: OrderDir }
  | Array<{ [K in keyof Omit<NotificationPreference, never>]?: OrderDir }>

// ── Services ─────────────────────────────────────────────────────────────────

/**
 * Service name → the row it answers. Feeds @frontierjs/junction's ServiceTypes
 * registry, so `client.service('posts')` needs no type argument.
 */
export interface ServiceTypes {
  credentials: Credential
  sessions: Session
  verifications: Verification
  oauthFlows: OauthFlow
  users: User
  accounts: Account
  workspaces: Workspace
  workspaceMembers: WorkspaceMember
  invitations: Invitation
  secrets: Secret
  apiKeys: ApiKey
  servers: Server
  serverEvents: ServerEvent
  outpostNonces: OutpostNonce
  volumes: Volume
  networks: Network
  serverNetworks: ServerNetwork
  projects: Project
  environments: Environment
  apps: App
  domains: Domain
  appServers: AppServer
  appNetworks: AppNetwork
  deployments: Deployment
  deploymentSteps: DeploymentStep
  jobs: Job
  jobRuns: JobRun
  recipes: Recipe
  recipeRuns: RecipeRun
  diskUsages: DiskUsage
  cleanupRuns: CleanupRun
  featureFlags: FeatureFlag
  flagOverrides: FlagOverride
  notificationChannels: NotificationChannel
  alertRules: AlertRule
  alertRuleChannels: AlertRuleChannel
  alertEvents: AlertEvent
  dashboards: Dashboard
  dashboardWidgets: DashboardWidget
  auditEvents: AuditEvent
  blueprints: Blueprint
  blueprintParams: BlueprintParam
  registryImages: RegistryImage
  backups: Backup
  hubConfigs: HubConfig
  notificationPreferences: NotificationPreference
}

// ── Cursor pagination result ─────────────────────────────────────────────────

export interface TransitionOption {
  name:    string | null
  field:   string
  from:    string | null
  to:      string
  gate:    number | null
  allowed: boolean
}

export interface CursorResult<T> {
  items:      T[]
  nextCursor: string | null
  hasMore:    boolean
}

// ── Table client interface ───────────────────────────────────────────────────

export interface TableClient<TRow, TCreate, TUpdate, TWhere> {
  findMany(args?: { where?: TWhere; orderBy?: any; limit?: number; offset?: number; include?: any; select?: any; withDeleted?: boolean; onlyDeleted?: boolean }): Promise<TRow[]>
  findFirst(args?: { where?: TWhere; orderBy?: any; include?: any; select?: any }): Promise<TRow | null>
  findUnique(args: { where: TWhere; include?: any; select?: any }): Promise<TRow | null>
  findFirstOrThrow(args?: { where?: TWhere }): Promise<TRow>
  findUniqueOrThrow(args: { where: TWhere }): Promise<TRow>
  findManyCursor(args?: { where?: TWhere; orderBy?: any; limit?: number; cursor?: string }): Promise<CursorResult<TRow>>
  count(args?: { where?: TWhere }): Promise<number>
  create(args: { data: TCreate; include?: any; select?: any }): Promise<TRow>
  createMany(args: { data: TCreate[] }): Promise<{ count: number }>
  update(args: { where: TWhere; data: TUpdate; include?: any; select?: any }): Promise<TRow | null>
  updateMany(args: { where?: TWhere; data: TUpdate }): Promise<{ count: number }>
  upsert(args: { where: TWhere; create: TCreate; update: TUpdate; include?: any; select?: any }): Promise<TRow>
  upsertMany(args: { data: TCreate[]; conflictTarget?: string[]; update?: string[] }): Promise<{ count: number }>
  remove(args: { where: TWhere }): Promise<TRow | null>
  removeMany(args?: { where?: TWhere }): Promise<{ count: number }>
  restore(args: { where: TWhere }): Promise<{ count: number }>
  delete(args: { where: TWhere }): Promise<TRow | null>
  deleteMany(args?: { where?: TWhere }): Promise<{ count: number }>
  search(query: string, args?: { where?: TWhere; limit?: number; offset?: number }): Promise<TRow[]>
  optimizeFts(): Promise<{ optimized: boolean; table: string }>

  // Reads whose shape is not one row or a count. Emitted because an app
  // calls them: leaving one out types a real call as an error, which is
  // the failure that makes a generated .d.ts worse than no types at all.
  findManyAndCount(args?: { where?: TWhere; orderBy?: any; limit?: number; offset?: number; include?: any; select?: any }): Promise<{ rows: TRow[]; total: number }>
  exists(args?: { where?: TWhere }): Promise<boolean>
  aggregate(args?: Record<string, unknown>): Promise<Record<string, any>>
  groupBy(args: Record<string, unknown>): Promise<Record<string, any>[]>
  query(args?: Record<string, unknown>): Promise<any>
  /** @@transitions — [] on a model that declares none. */
  transitions(idOrRow: TRow | string | number): Promise<TransitionOption[]>
}

// ── onQuery event ────────────────────────────────────────────────────────────

export interface QueryEvent {
  model:     string
  operation: 'findMany' | 'findFirst' | 'findUnique' | 'findManyCursor' | 'count' | 'search' | 'create' | 'createMany' | 'update' | 'updateMany' | 'upsertMany' | 'remove' | 'removeMany' | 'restore' | 'delete' | 'deleteMany'
  database:  string
  actorId:   string | number | null
  sql:       string
  params:    unknown[]
  duration:  number
  rowCount:  number
  args:      Record<string, unknown>
}

// ── write event ($tapEvents / onEvent) ───────────────────────────────────────

export interface WriteEvent {
  event:       'create' | 'update' | 'remove' | 'transition'
  model:       string
  operation?:  'create' | 'update' | 'remove'
  result?:     unknown
  transition?: string
  field?:      string
  from?:       string
  to?:         string
  record?:     unknown
}

// ── LitestoneClient ──────────────────────────────────────────────────────────

export interface LitestoneClient {
  readonly credential: TableClient<Credential, CredentialCreate, CredentialUpdate, CredentialWhere>
  readonly session: TableClient<Session, SessionCreate, SessionUpdate, SessionWhere>
  readonly verification: TableClient<Verification, VerificationCreate, VerificationUpdate, VerificationWhere>
  readonly oauthFlow: TableClient<OauthFlow, OauthFlowCreate, OauthFlowUpdate, OauthFlowWhere>
  readonly user: TableClient<User, UserCreate, UserUpdate, UserWhere>
  readonly account: TableClient<Account, AccountCreate, AccountUpdate, AccountWhere>
  readonly workspace: TableClient<Workspace, WorkspaceCreate, WorkspaceUpdate, WorkspaceWhere>
  readonly workspaceMember: TableClient<WorkspaceMember, WorkspaceMemberCreate, WorkspaceMemberUpdate, WorkspaceMemberWhere>
  readonly invitation: TableClient<Invitation, InvitationCreate, InvitationUpdate, InvitationWhere>
  readonly secret: TableClient<Secret, SecretCreate, SecretUpdate, SecretWhere>
  readonly apiKey: TableClient<ApiKey, ApiKeyCreate, ApiKeyUpdate, ApiKeyWhere>
  readonly server: TableClient<Server, ServerCreate, ServerUpdate, ServerWhere>
  readonly serverEvent: TableClient<ServerEvent, ServerEventCreate, ServerEventUpdate, ServerEventWhere>
  readonly outpostNonce: TableClient<OutpostNonce, OutpostNonceCreate, OutpostNonceUpdate, OutpostNonceWhere>
  readonly volume: TableClient<Volume, VolumeCreate, VolumeUpdate, VolumeWhere>
  readonly network: TableClient<Network, NetworkCreate, NetworkUpdate, NetworkWhere>
  readonly serverNetwork: TableClient<ServerNetwork, ServerNetworkCreate, ServerNetworkUpdate, ServerNetworkWhere>
  readonly project: TableClient<Project, ProjectCreate, ProjectUpdate, ProjectWhere>
  readonly environment: TableClient<Environment, EnvironmentCreate, EnvironmentUpdate, EnvironmentWhere>
  readonly app: TableClient<App, AppCreate, AppUpdate, AppWhere>
  readonly domain: TableClient<Domain, DomainCreate, DomainUpdate, DomainWhere>
  readonly appServer: TableClient<AppServer, AppServerCreate, AppServerUpdate, AppServerWhere>
  readonly appNetwork: TableClient<AppNetwork, AppNetworkCreate, AppNetworkUpdate, AppNetworkWhere>
  readonly deployment: TableClient<Deployment, DeploymentCreate, DeploymentUpdate, DeploymentWhere>
  readonly deploymentStep: TableClient<DeploymentStep, DeploymentStepCreate, DeploymentStepUpdate, DeploymentStepWhere>
  readonly job: TableClient<Job, JobCreate, JobUpdate, JobWhere>
  readonly jobRun: TableClient<JobRun, JobRunCreate, JobRunUpdate, JobRunWhere>
  readonly recipe: TableClient<Recipe, RecipeCreate, RecipeUpdate, RecipeWhere>
  readonly recipeRun: TableClient<RecipeRun, RecipeRunCreate, RecipeRunUpdate, RecipeRunWhere>
  readonly diskUsage: TableClient<DiskUsage, DiskUsageCreate, DiskUsageUpdate, DiskUsageWhere>
  readonly cleanupRun: TableClient<CleanupRun, CleanupRunCreate, CleanupRunUpdate, CleanupRunWhere>
  readonly featureFlag: TableClient<FeatureFlag, FeatureFlagCreate, FeatureFlagUpdate, FeatureFlagWhere>
  readonly flagOverride: TableClient<FlagOverride, FlagOverrideCreate, FlagOverrideUpdate, FlagOverrideWhere>
  readonly notificationChannel: TableClient<NotificationChannel, NotificationChannelCreate, NotificationChannelUpdate, NotificationChannelWhere>
  readonly alertRule: TableClient<AlertRule, AlertRuleCreate, AlertRuleUpdate, AlertRuleWhere>
  readonly alertRuleChannel: TableClient<AlertRuleChannel, AlertRuleChannelCreate, AlertRuleChannelUpdate, AlertRuleChannelWhere>
  readonly alertEvent: TableClient<AlertEvent, AlertEventCreate, AlertEventUpdate, AlertEventWhere>
  readonly dashboard: TableClient<Dashboard, DashboardCreate, DashboardUpdate, DashboardWhere>
  readonly dashboardWidget: TableClient<DashboardWidget, DashboardWidgetCreate, DashboardWidgetUpdate, DashboardWidgetWhere>
  readonly auditEvent: TableClient<AuditEvent, AuditEventCreate, AuditEventUpdate, AuditEventWhere>
  readonly blueprint: TableClient<Blueprint, BlueprintCreate, BlueprintUpdate, BlueprintWhere>
  readonly blueprintParam: TableClient<BlueprintParam, BlueprintParamCreate, BlueprintParamUpdate, BlueprintParamWhere>
  readonly registryImage: TableClient<RegistryImage, RegistryImageCreate, RegistryImageUpdate, RegistryImageWhere>
  readonly backup: TableClient<Backup, BackupCreate, BackupUpdate, BackupWhere>
  readonly hubConfig: TableClient<HubConfig, HubConfigCreate, HubConfigUpdate, HubConfigWhere>
  readonly notificationPreference: TableClient<NotificationPreference, NotificationPreferenceCreate, NotificationPreferenceUpdate, NotificationPreferenceWhere>

  // Auth scoping
  asSystem(): LitestoneClient
  $setAuth(user: Record<string, unknown>): LitestoneClient
  $scopedBy(scope: Record<string, unknown>): LitestoneClient

  // Is this key filterable / sortable? Asked rather than copied — every
  // flavor of client answers, because it is a fact about the schema.
  $checkWhere(accessor: string, where: Record<string, unknown>): { key: string; suggestion?: string; allowed?: string[] }[]
  $checkOrderBy(accessor: string, orderBy: unknown): { key: string; reason: string; suggestion?: string; sortable?: string[]; message?: string }[]
  // Which columns must never be written down in plain text — asked for the
  // same reason, by an application keeping a trail of its own.
  $protectedFields(accessor: string): Record<string, 'guarded' | 'encrypted' | 'hashed'>

  // Transactions
  $transaction<T>(fn: (tx: LitestoneClient) => Promise<T>): Promise<T>

  // Raw SQL
  sql(strings: TemplateStringsArray, ...values: unknown[]): Promise<Record<string, unknown>[]>

  // Query tap (temporary capture)
  $tapQuery(fn: (event: QueryEvent) => void): () => void

  // Write-event tap — onEvent's post-construction half
  $tapEvents(fn: (event: WriteEvent) => void): () => void

  // Utilities
  $backup(dest: string, opts?: { vacuum?: boolean }): Promise<{ path: string; size: number }>
  $attach(path: string, alias: string): void
  $detach(alias: string): void
  $rotateKey(newKey: string): Promise<Record<string, { rows: number; fields: number }>>
  $close(): void

  // Introspection
  readonly $schema:     Record<string, unknown>
  readonly $databases:  Record<string, { driver: string; access: string; path: string }>
  readonly $softDelete: Record<string, boolean>
  readonly $enums:      Record<string, string[]>
  readonly $cacheSize:  { read: number; write: number }
  readonly $attached:   string[]
  readonly $rawDbs:     Record<string, unknown>
  readonly $walStatus:  Record<string, unknown>
  /** Is a transaction open on this connection right now? */
  readonly $inTransaction: boolean
}

// ── createClient ─────────────────────────────────────────────────────────────

export interface CreateClientOptions {
  /** Path to a .lite schema file */
  path?:        string
  /** Inline schema string */
  schema?:      string
  /** Pre-parsed result from parseFile() */
  parsed?:      Record<string, unknown>
  /** MAIN's path. Overrides a declared `database main`; a second declared database keeps its own. */
  db?:            string
  /** ':memory:' moves every declared database, jsonl and logger included. */
  databases?:     string | Record<string, { path?: string }>
  /** 64 hex characters = 32 bytes. Required for @encrypted / @secret. */
  encryptionKey?: string
  computed?:      Record<string, Record<string, (row: unknown, ctx: unknown) => unknown>> | string
  plugins?:       unknown[]
  onQuery?:       (event: QueryEvent) => void | Promise<void>
  onEvent?:       Record<string, (event: unknown, ctx: unknown) => void>
  onLog?:         (entry: unknown, ctx: unknown) => Record<string, unknown> | void
  filters?:       Record<string, Record<string, unknown> | ((ctx: unknown) => Record<string, unknown>)>
  policyDebug?:   boolean | 'verbose'
  hooks?:         Record<string, unknown>
  access?:        Record<string, string>
  readOnly?:      boolean
  pluralize?:     boolean
  scopes?:        Record<string, Record<string, unknown>>
  now?:           () => Date | string
}

export declare function createClient(
  options: CreateClientOptions
): Promise<LitestoneClient>
