// tests/errors-snapshot.test.ts
//
// `junction errors` — what a thrown value becomes, as a committed file.
//
// The snapshot is executed rather than written down, so these tests are about
// the two things a renderer could get wrong in a way that would still look
// right: reporting a class's declared status instead of what the boundary
// actually answers, and rendering a row for a class it could not construct.
// Both produce a plausible table that is a second opinion rather than an
// observation.

import { describe, expect, it } from 'bun:test'
import { renderErrorsSnapshot } from '../tools/errors-snapshot.ts'

describe('junction errors — the snapshot', () => {

  it('names the command that regenerates it, and renders the same bytes twice', async () => {
    const once  = await renderErrorsSnapshot()
    const twice = await renderErrorsSnapshot()

    // scripts/ci.mjs reads this line and reruns it with --check.
    expect(once).toContain('<!-- generated by: junction errors -->')
    // A byte compare is the whole mechanism.
    expect(twice).toBe(once)
  })

  it('records the answer the boundary gives, not the status a class declares', async () => {
    const body = await renderErrorsSnapshot()

    // A numeric `status` outside 400–599 is not a status. Reading the field and
    // believing it would render 200 here.
    expect(body).toMatch(/a status outside 400–599 \| `GeneralError` \| 500/)
    // A status with no class of its own keeps the STATUS and loses the class.
    expect(body).toMatch(/a status with no class of its own \| `GeneralError` \| 423/)
    // A string `code` is an error code, not a status — the `code` field is
    // checked for a NUMBER, and this is the shape that makes that visible.
    expect(body).toMatch(/a string `code`[^|]*\| `GeneralError` \| 500/)
  })

  it('runs Litestone\'s real error classes through, constructed', async () => {
    const body = await renderErrorsSnapshot()

    // Constructed, not synthesised from the name: `status` and `retryable` are
    // set in the constructor, so a row built from a name alone would report
    // every one of these as a 500 with no retryable — which is what the first
    // draft did for the two classes whose constructors take arguments.
    expect(body).toContain('| `TransitionViolationError` | status 409 · retryable false | `Conflict` | 409 | false |')
    expect(body).toContain('| `VersionConflictError` | status 409 · retryable true | `Conflict` | 409 | true |')

    // FJS-255, asserted still open: the lock errors declare `retryable` and no
    // status, so they reach a caller as 500. Fixing that turns this red, which
    // is the point — the row has to be promoted rather than left stale.
    expect(body).toContain('| `LockNotAcquiredError` | retryable true | `GeneralError` | 500 | true |')
  })
})
