// tests/surface-snapshot.test.ts
//
// `junction surface` — the API surface as a committed file.
//
// What these guard is the reason the file is committed at all: every fact in it
// is one nothing in the source text can answer. `collectCustomMethods` decides at
// construction whether `pay` is an action or an option key, `svc.pipelines()`
// resolves a hook chain whose ORDER is behaviour, and `apiPrefix` moves routes
// registered by plugins that never mention it. A renderer that read source, or
// one that sorted a hook chain, would produce a plausible file that is wrong —
// so the assertions below are about provenance and ordering, not formatting.

import { describe, expect, it } from 'bun:test'
import { createApp, createService, healthPlugin, defaultConfig } from '../index.ts'
import { describeSurface, renderSurfaceSnapshot } from '../tools/surface.ts'

async function buildApp() {
  const app = createApp({
    config: {
      port:     3397,
      apiPrefix: '/api',
      database: { url: '', log: false },
      services: { dir: '/nonexistent' },
      http:     { ...defaultConfig.http, drainTimeout: 200 },
    },
  })

  app.configure(healthPlugin())

  // Named hooks, because the snapshot reports a hook by its function name and
  // an app that uses arrows gets `anonymous` — true, and the reason a chain
  // worth diffing is a chain of named functions.
  function requireAuth() {}
  function stampOwner() {}
  function audit() {}

  const orders = createService({
    name:    'orders',
    model:   'Order',
    channel: 'orders',
    methods: ['find', 'get', 'create', 'pay'],
    async find()   { return { data: [], total: 0, limit: 10, skip: 0 } },
    async get()    { return {} },
    async create() { return {} },
    async pay()    { return {} },
  })

  orders.hooks({
    before: { create: [requireAuth, stampOwner] },
    after:  { all: [audit] },
  })

  app.services.register(orders)
  await app._startForTest()
  return app
}

describe('junction surface', () => {

  it('reports custom methods as construction resolved them, not as the source reads', async () => {
    const app = await buildApp()
    const svc = describeSurface(app).services.find(s => s.name === 'orders')!

    // `pay` is a function key beside `find`/`get`/`create`. Nothing in the file
    // says which of them is CRUD; `collectCustomMethods` is what knows.
    expect(svc.customMethods).toEqual(['pay'])
    expect(svc.methods).toContain('pay')
    expect(svc.channel).toEqual(['orders'])
    expect(svc.model).toBe('Order')

    await app.stop()
  })

  it('keeps a hook chain in the order it runs', async () => {
    const app = await buildApp()
    const svc = describeSurface(app).services.find(s => s.name === 'orders')!

    // Order is behaviour: stamping the owner before the auth check is a
    // different app. A sorted or set-collapsed chain would render identically
    // for both, which is what makes this the assertion worth having.
    //
    // The derived hooks a declared `model` brings are part of the chain, and
    // which PHASE each is in is the ordering rule: `gateAuth` wraps everything
    // as an around hook (FJS-403), `autoValidate` leads the before chain. That
    // they run at all is invisible in the service file, which is half of why
    // this file is worth committing.
    expect(svc.hooks.around.all).toEqual(['gateAuth'])
    expect(svc.hooks.before.create).toEqual(['autoValidate', 'requireAuth', 'stampOwner'])
    expect(svc.hooks.after.all).toEqual(['audit'])

    await app.stop()
  })

  it('reads routes off the router, prefix applied', async () => {
    const app = await buildApp()
    const surface = describeSurface(app)

    expect(surface.prefix).toBe('/api')
    const paths = surface.routes.map(r => `${r.method} ${r.path}`)
    // Registered by the health plugin, which never mentions the prefix — the
    // one owner (`app.get`) applies it, and this is where that is visible.
    expect(paths).toContain('GET /api/health')
    expect(paths.some(p => p.includes('/{service}'))).toBe(true)

    await app.stop()
  })

  it('renders a snapshot that names the command regenerating it, and is stable', async () => {
    const app = await buildApp()
    const surface = describeSurface(app)

    const opts = { source: 'api/app.ts', command: 'junction surface --app api/app.ts' }
    const once  = renderSurfaceSnapshot(surface, opts)
    const twice = renderSurfaceSnapshot(describeSurface(app), opts)

    // scripts/ci.mjs reads this line and reruns it with --check. A snapshot
    // that does not name its generator cannot be checked by anything.
    expect(once).toContain('<!-- generated by: junction surface --app api/app.ts -->')
    expect(once).toContain('`requireAuth` → `stampOwner`')
    // A byte compare is the whole mechanism: any instability — a Set iteration,
    // a timestamp — turns the CI phase into noise everyone learns to ignore.
    expect(twice).toBe(once)

    await app.stop()
  })
})
