-- Schema snapshot — DDL
--
-- generated by: litestone ddl --schema deploy.lite
--
-- The DDL this schema emits — the tables, indexes, triggers and views a fresh
-- database is given. Do not edit; regenerate and read the diff. Columns are
-- emitted verbatim camelCase and DateTime as ISO-8601 TEXT, so hand-written SQL
-- binds to exactly these names and nothing else in an app can see one move.
-- Fragments an app merges at runtime are not in this file.
--
-- 5 models · 1 database

-- ─── database main · sqlite ──────────────────────────────────────────────
PRAGMA foreign_keys = ON;

-- The file's own header row, and the only row in this model.
-- 
-- A journal format is a replay contract: a resumed transition replays rows a
-- previous version wrote, so a reader has to be able to ask what wrote them
-- before it parses any. Terraform carries the same field for the same reason
-- and pays the same way — newer state is unreadable by an older binary, which
-- is a refusal to design rather than a surprise to discover.
-- 
-- `app` and `host` are here so that pointing `fli` at the wrong `deploy.db`
-- is a refusal rather than a history of somebody else's machine.
-- 
-- The single-row rule is DECLARED, and it takes two constraints to say it: the
-- `@check` refuses any other id and the primary key refuses a second row of
-- this one. Model-level `@@check` would say it in one line and does not exist
-- (`FJS-534`), which is why it reads as two.
CREATE TABLE IF NOT EXISTS "journal" (
  "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'journal' CHECK (id = 'journal'),
  "formatVersion" INTEGER NOT NULL DEFAULT 1,
  "app" TEXT NOT NULL,
  "host" TEXT NOT NULL,
  "createdAt" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

-- One immutable artefact-plus-bindings, addressed by its own content.
-- 
-- Two builds of an unchanged tree mint the same id, which is what makes
-- *promote a digest* and *revert to a known thing* one operation rather than
-- two that can disagree.
CREATE TABLE IF NOT EXISTS "release" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "app" TEXT NOT NULL,
  "environment" TEXT NOT NULL,
  "digest" TEXT,
  "imageRef" TEXT,
  "bindingsHash" TEXT NOT NULL,
  "generation" INTEGER NOT NULL,
  "schemaHash" TEXT NOT NULL,
  "pivot" TEXT NOT NULL DEFAULT 'unknown',
  "pivotDeclared" INTEGER NOT NULL DEFAULT 0,
  "pivotFindings" TEXT NOT NULL DEFAULT '[]',
  "retentionUntil" TEXT,
  "audienceKey" TEXT NOT NULL DEFAULT 'everyone',
  "createdAt" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "createdBy" TEXT,
  CHECK ("pivot" IN ('expand', 'contract', 'unknown'))
) STRICT;
CREATE INDEX IF NOT EXISTS "idx_release_app_environment_createdAt" ON "release" ("app", "environment", "createdAt");
CREATE INDEX IF NOT EXISTS "idx_release_retentionUntil" ON "release" ("retentionUntil");

-- The bindings an Environment provides, as they stood at one generation.
-- 
-- Mutable but generational: serving state is the pair (Release, Generation),
-- and reverting a Release onto today's bindings is the documented failure this
-- separation exists to refuse.
CREATE TABLE IF NOT EXISTS "binding_set" (
  "id" TEXT NOT NULL PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "app" TEXT NOT NULL,
  "environment" TEXT NOT NULL,
  "generation" INTEGER NOT NULL,
  "hash" TEXT NOT NULL,
  "values" TEXT NOT NULL DEFAULT '{}',
  "secretRefs" TEXT NOT NULL DEFAULT '{}',
  "createdAt" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "createdBy" TEXT,
  UNIQUE ("app", "environment", "generation")
) STRICT;
CREATE INDEX IF NOT EXISTS "idx_binding_set_app_environment_hash" ON "binding_set" ("app", "environment", "hash");

-- One attempt to move serving state — a deploy or a revert.
CREATE TABLE IF NOT EXISTS "transition" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "kind" TEXT NOT NULL,
  "app" TEXT NOT NULL,
  "environment" TEXT NOT NULL,
  "releaseId" TEXT NOT NULL,
  "fromReleaseId" TEXT,
  "generation" INTEGER NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'planned',
  "crossesPivot" INTEGER NOT NULL DEFAULT 0,
  "plan" TEXT NOT NULL DEFAULT '[]',
  "actor" TEXT,
  "startedAt" TEXT,
  "finishedAt" TEXT,
  CHECK ("kind" IN ('deploy', 'revert')),
  CHECK ("status" IN ('planned', 'running', 'succeeded', 'failed')),
  FOREIGN KEY ("releaseId") REFERENCES "release" ("id")
) STRICT;
CREATE INDEX IF NOT EXISTS "idx_transition_app_environment_startedAt" ON "transition" ("app", "environment", "startedAt");
CREATE INDEX IF NOT EXISTS "idx_transition_releaseId" ON "transition" ("releaseId");
CREATE INDEX IF NOT EXISTS "idx_transition_status" ON "transition" ("status");

-- One step of one transition.
CREATE TABLE IF NOT EXISTS "transition_step" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "transitionId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "ordinal" INTEGER NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "precondition" TEXT NOT NULL DEFAULT '{}',
  "output" TEXT,
  "startedAt" TEXT,
  "finishedAt" TEXT,
  "durationMs" INTEGER,
  CHECK ("status" IN ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  UNIQUE ("transitionId", "ordinal"),
  FOREIGN KEY ("transitionId") REFERENCES "transition" ("id") ON DELETE CASCADE
) STRICT;
CREATE INDEX IF NOT EXISTS "idx_transition_step_transitionId" ON "transition_step" ("transitionId");
