/*
 * view.spec.mjs — opening a page the workspace committed.
 *
 * `fli ws:atlas` writes two pages describing this workspace, and both are
 * ordinary runnable rows: the GUI could always press the button that
 * regenerates one and had no way to READ it. A `file://` link from an http page
 * is refused by every browser, so the server serves them and the row carries a
 * link.
 *
 * `tests/server.test.js` covers the route and its refusals. What only a browser
 * can answer is the half that made the feature necessary: that the link is on
 * the row, that it is there without anything running, and that following it
 * lands on the page rather than on the GUI's own catch-all — which serves the
 * dashboard for any path it does not recognise, so a wrong route reads as a
 * working link right up until somebody looks at what loaded.
 */
export const name = 'a committed page opens from the row that regenerates it'

export async function run(t) {
  /* ── the link is on the row, and only on the rows that have a page ────── */

  const rows = await t.evaluate(`
    const viewable = dashRows.filter(r => r.viewable);
    const other    = dashRows.find(r => r.kind === 'snapshot' && !r.viewable);
    const li       = viewable[0] && document.querySelector('#dash-groups [data-id="' + viewable[0].id + '"]');
    const otherLi  = other && document.querySelector('#dash-groups [data-id="' + other.id + '"]');
    const link     = li && [...li.querySelectorAll('a')].find(a => a.textContent.trim() === 'view');
    return {
      count:  viewable.length,
      id:     viewable[0] ? viewable[0].id : null,
      href:   link ? link.getAttribute('href') : null,
      hidden: link ? link.hasAttribute('hidden') : null,
      onOther: otherLi ? [...otherLi.querySelectorAll('a')].some(a => a.textContent.trim() === 'view') : null,
    };
  `)

  t.ok(rows.count > 0, `the workspace commits ${rows.count} page(s) a row can open`)
  t.ok(rows.href, `the row carries a view link — ${rows.href}`)

  // Not `data-open`, which is hidden until the row answers on its port. A file
  // is there whether or not anything is running, and a link that appeared only
  // while a server was up would be absent exactly when somebody wants to read
  // what the tree looks like.
  t.is(rows.hidden, false, 'and it is shown without anything running')

  // The negative control. A `.md` or a `.sql` snapshot is a diff, not a page,
  // and a link on every snapshot row would look identical to one that works.
  t.is(rows.onOther, false, 'a snapshot that is not a page carries no view link')

  /* ── following it lands on the page, not on the dashboard ─────────────── */

  const fetched = await t.evaluate(`
    const res  = await fetch(${JSON.stringify('')} + document.querySelector('#dash-groups [data-id="' + ${JSON.stringify(rows.id)} + '"] a[href*="/api/page/"]').href);
    const body = await res.text();
    return { status: res.status, type: res.headers.get('content-type'), body: body.slice(0, 400) };
  `)

  t.is(fetched.status, 200, 'the link answers 200')
  t.ok(/text\/html/.test(fetched.type ?? ''), `and answers html — ${fetched.type}`)

  // The GUI serves its own dashboard for any path it does not recognise, so
  // *something came back* is not the assertion — WHICH page came back is.
  t.ok(/generated by: fli ws:atlas/.test(fetched.body),
    'and the bytes are the generated page, not the GUI falling through to itself')
}
