// AUTO-GENERATED by @frontierjs/jetty — do not edit.
import App from "/home/j/code/FRONTIER/frontierjs/example/extension/src/dock/App.mesa"
import { connectHarbor, mount } from "/home/j/code/FRONTIER/frontierjs/packages/jetty/src/runtime/index.js"
import { _registerActivePort } from "/home/j/code/FRONTIER/frontierjs/packages/jetty/src/resources/index.js"

const root = document.getElementById('app')
if (!root) throw new Error('[jetty] #app not found in dock index.html')

// Top-level await: open port, register it for resources, then mount.
// The port becomes available to:
//   - Mesa components via the `harbor` prop
//   - jetty's resources module via _registerActivePort (mirror of Sierra's getClient)
// In dev mode, the `__jettyHmrFirstRun &&` guard skips re-running these
// when the entry is dynamic-imported by dev-client for an HMR swap.
if (true) {
  const harbor = await connectHarbor({ type: "dock", id: "dock" })
  _registerActivePort(harbor)
  await mount(root, App, { harbor })
}
