// AUTO-GENERATED by @frontierjs/jetty — do not edit.
// --- jetty dev client (auto-injected in dev mode) ---
import { startDevClient as __jettyStartDev } from "/home/j/code/FRONTIER/frontierjs/packages/jetty/src/dev/dev-client.js"
if (!globalThis.__JETTY_DEV_CLIENT_STARTED__) {
  globalThis.__JETTY_DEV_CLIENT_STARTED__ = true
  __jettyStartDev({ port: 8410, clientType: "dock" })
}
// --- end jetty dev client ---
// --- jetty HMR sentinel (skip remount on re-import) ---
const __jettyHmrFirstRun = !globalThis.__JETTY_MOUNTED_DOCK__
globalThis.__JETTY_MOUNTED_DOCK__ = true
import App, { __mesaOrigFn, __setMark } from "/home/j/code/FRONTIER/frontierjs/example/extension/src/dock/App.mesa"
import { connectHarbor, mount } from "/home/j/code/FRONTIER/frontierjs/packages/jetty/src/runtime/index.js"
import { _registerActivePort } from "/home/j/code/FRONTIER/frontierjs/packages/jetty/src/resources/index.js"

// Publish App reference for HMR. On a hot-update re-import this captures
// the NEW component fn; dev-client reads it and calls __jettyMesa.hot_update.
// Attach named exports as properties so hot_update can find them via App.
if (typeof __mesaOrigFn === 'function') App.__mesaOrigFn = __mesaOrigFn
if (typeof __setMark === 'function')   App.__setMark   = __setMark
globalThis.__JETTY_HMR_APPS = globalThis.__JETTY_HMR_APPS || {}
globalThis.__JETTY_HMR_APPS["dock"] = App
const root = document.getElementById('app')
if (!root) throw new Error('[jetty] #app not found in dock index.html')

// Top-level await: open port, register it for resources, then mount.
// The port becomes available to:
//   - Mesa components via the `harbor` prop
//   - jetty's resources module via _registerActivePort (mirror of Sierra's getClient)
// In dev mode, the `__jettyHmrFirstRun &&` guard skips re-running these
// when the entry is dynamic-imported by dev-client for an HMR swap.
if (__jettyHmrFirstRun && true) {
  const harbor = await connectHarbor({ type: "dock", id: "dock" })
  _registerActivePort(harbor)
  await mount(root, App, { harbor })
}
