// core/app-entry.js
// The committed API surface: where it is, what wrote it, and what it says.
//
// Two commands ask different questions of one file and neither is the other's
// subset (`FJS-D240`). `project:map` PARSES it — the services, the hook chain,
// the routes, the plugins. `app:atlas` reads only the HEADER, because the header
// names the entry module, the services directory and the directory the generator
// was run from, which is everything needed to boot the app and run a different
// presentation over it.
//
// One owner for both, because the two halves were written twice and had already
// drifted: the same missing-file sentence read `Services are read off a built
// app` in one copy and `The app is read off a built app` in the other. A format
// with two parsers grows two answers, and nothing here compared them.
//
// So the entry is never probed. Guessing `api/src/app.ts` is wrong for an app
// that boots from its root (`packages/basecamp`), wrong for one that names an
// `--export`, and silently wrong rather than absent — it would describe an app
// that boots on junction's defaults. The committed snapshot already carries the
// answer, and the `snapshots` CI phase already trusts it the same way: it reruns
// each generator, named in the file's own header, from the file's own directory.
//
// The command travels as ARGV and never through a shell, and the binary is
// checked against a list — the string comes out of a file, and a file in a repo
// is not the same trust level as a string somebody typed.

import { existsSync, readFileSync } from 'node:fs'
import { resolve, dirname }         from 'node:path'
import { spawnSync }                from 'node:child_process'

export const SURFACE_FILE = 'surface.snapshot.md'

// In order. A snapshot belongs in the surface it describes, so `api/` is the
// answer and is looked for first; the app root stays a candidate because an app
// whose isolation is by cwd keeps them there. First hit wins.
export const SURFACE_DIRS = ['api', '.']

export function surfaceFile(root) {
  for (const dir of SURFACE_DIRS) {
    const file = resolve(root, dir, SURFACE_FILE)
    if (existsSync(file)) return file
  }
  return null
}

/** The `generated by:` line of a snapshot, or null. */
export function generatedBy(file) {
  return readFileSync(file, 'utf8').split('\n')
    .find(l => l.includes('generated by:'))
    ?.replace(/^.*generated by:\s*/, '')
    .replace(/-->\s*$/, '')
    .trim() ?? null
}

// The only binary a header here may name. A generator is `junction <sub> …`; a
// header naming anything else is refused rather than run.
const ALLOWED_BIN = 'junction'

/**
 * Everything needed to run another presentation over the same built app.
 *
 * `{ file, dir, args }` — `dir` is where the generator was run from, `args` the
 * flags after the subcommand, verbatim. Null when there is no snapshot, and it
 * THROWS when there is one whose header cannot be trusted: an unreadable header
 * is a different problem from an absent file and must not read as one.
 */
export function appEntry(root) {
  const file = surfaceFile(root)
  if (!file) return null

  const command = generatedBy(file)
  if (!command) throw new Error(`${file} names no generator in its header — regenerate it with \`junction surface --app <entry>\``)

  const argv = command.split(/\s+/).filter(Boolean)
  if (argv[0] !== ALLOWED_BIN) {
    throw new Error(`${file} names \`${argv[0]}\` as its generator, and only \`${ALLOWED_BIN}\` is run from here`)
  }

  return { file, dir: dirname(file), args: argv.slice(2) }
}

/** The one sentence every caller says when there is no snapshot. */
export const surfaceMissingHint = (root) =>
  `no ${SURFACE_FILE} under ${root} (looked in ${SURFACE_DIRS.join(', ')}) — run ` +
  '`junction surface --app <entry>` from the API surface to write one. ' +
  'Services are read off a built app, never scanned (FJS-254).'

// ─── readApiSurface ───────────────────────────────────────────────────────────
//
// What the API answers, READ off the committed snapshot rather than re-derived
// from service source.
//
// This replaces a scanner (`FJS-254`), and the reason is not that the scanner was
// buggy. It could not have been right: junction decides at CONSTRUCTION whether a
// key is an option or a method (`collectCustomMethods`, read back through
// `svc.describe()` — Invariant 4), `svc.pipelines()` resolves the hook chain, and
// `apiPrefix` moves every route. None of those answers is a fact about how a file
// reads. An action assigned from a module-level const takes no visible `ctx`, a
// `methods:` list built from a variable is not a literal to match, and a hook
// added by a plugin or by `app.hooks()` appears in no service file at all — so
// the scan drew a confident picture with nothing able to contradict it.
//
// `junction surface` writes the snapshot off a BUILT app and the `snapshots` CI
// phase fails a stale one, so what is read here is current or CI is red.
//
// **Absent means absent.** No snapshot returns null and the callers say so,
// naming the command; falling back to a scan is how a viewer ends up confidently
// wrong again, and a missing section is a question a person can answer.

// `\`a\` → \`b\` → \`c\`` — a hook chain in run order. Also the bullet lists,
// which are the same backticked-and-comma-separated shape.
const backticked = (text) => [...text.matchAll(/`([^`]+)`/g)].map(m => m[1])

// | before | `find` | `gateAuth` → `autoFilter` |
const HOOK_ROW = /^\|\s*(before|after|around|error)\s*\|\s*`([^`]+)`\s*\|\s*(.*?)\s*\|\s*$/

/** The whole snapshot parsed, or null when there is none. */
export function readApiSurface(root) {
  const file = surfaceFile(root)
  if (!file) return null

  const lines = readFileSync(file, 'utf8').split('\n')

  const services = []
  const appHooks = { before: {}, after: {}, around: {}, error: {} }
  const routes   = []
  const plugins  = []

  let section = null
  let svc     = null

  for (const line of lines) {
    if (line.startsWith('## ')) { section = line.slice(3).trim(); svc = null; continue }

    if (section === 'App hooks') {
      const m = line.match(HOOK_ROW)
      if (m) appHooks[m[1]][m[2]] = backticked(m[3])
      continue
    }

    if (section === 'Services') {
      // ### `alerts` · model `AlertRule`
      const head = line.match(/^###\s*`([^`]+)`(?:\s*·\s*model\s*`([^`]+)`)?/)
      if (head) {
        svc = {
          name:          head[1],
          model:         head[2] ?? head[1],
          methods:       [],
          customMethods: [],
          channel:       null,
          hooks:         { before: {}, after: {}, around: {}, error: {} },
        }
        services.push(svc)
        continue
      }
      if (!svc) continue

      const bullet = line.match(/^-\s*\*\*([^*]+)\*\*\s*—\s*(.*)$/)
      if (bullet) {
        const values = backticked(bullet[2])
        if (bullet[1] === 'methods')        svc.methods       = values
        if (bullet[1] === 'custom methods') svc.customMethods = values
        if (bullet[1] === 'broadcasts on')  svc.channel       = values[0] ?? null
        continue
      }

      const hook = line.match(HOOK_ROW)
      if (hook) svc.hooks[hook[1]][hook[2]] = backticked(hook[3])
      continue
    }

    if (section === 'Routes') {
      // | GET | `/api/{service}` | service |
      const m = line.match(/^\|\s*([A-Z]+)\s*\|\s*`([^`]+)`\s*\|\s*(\w+)\s*\|\s*$/)
      if (m) routes.push({ method: m[1], path: m[2], kind: m[3] })
      continue
    }

    if (section === 'Plugins') {
      const m = line.match(/^\d+\.\s*`([^`]+)`/)
      if (m) plugins.push(m[1])
    }
  }

  // `generatedBy` re-reads the file for one line. That is the price of the
  // header having exactly one reader — `appEntry` needs it without any of the
  // above, and two extractions of one line is how the two came to disagree.
  return { file, generatedBy: generatedBy(file), services, appHooks, routes, plugins }
}

// ─── the model itself ─────────────────────────────────────────────────────────
//
// One owner for *how do you get the app model*, because there are two callers —
// `app:atlas`, which renders it, and `project:map`, which folds three of its
// four halves into a page built from files. Two spawns of one command is how the
// two come to disagree about which app they described.
//
// It ANSWERS a failure rather than throwing one, because for `project:map` this
// is one section of a report whose others are read from files: a missing bun or
// an app that will not build must cost three sections and never the command.
// Only the caller knows which of those it is, and `app:atlas` — which has
// nothing else to render — treats the same answer as fatal.

/**
 * Boot the app once and read `describeAppModel` off it.
 *
 * `{ model, entry }` on success, `{ error, entry }` otherwise — never a throw.
 * `entry` is null when there was no snapshot to find the app with.
 *
 * `{ run }` swaps the spawner, which is what lets this be tested with no bun,
 * no app and no boot — the same reason outpost injects its runner.
 */
export function readAppAtlas(root, { run: runner = spawnSync } = {}) {
  let entry = null
  try {
    entry = appEntry(root)
  } catch (err) {
    return { entry: null, error: err.message }
  }
  if (!entry) return { entry: null, error: surfaceMissingHint(root) }

  // argv, never a shell: the flags come out of a file's header, and a file in a
  // repo is not the same trust level as a string somebody typed. Run from the
  // snapshot's own directory, because the app resolves its database and its
  // services against the cwd its own scripts use.
  const run = runner('bunx', ['junction', 'atlas', ...entry.args], {
    cwd:       entry.dir,
    encoding:  'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })

  if (run.error?.code === 'ENOENT') {
    return { entry, error: 'bunx not found — junction is Bun-only, so reading the app model needs bun on PATH' }
  }
  if (run.status !== 0) {
    const tail = (run.stderr ?? '').trim().split('\n').slice(-6).join('\n')
    return { entry, error: `junction atlas failed under ${entry.dir}${tail ? `\n${tail}` : ''}` }
  }
  try {
    return { entry, model: JSON.parse(run.stdout) }
  } catch {
    return { entry, error: 'junction atlas did not answer JSON — something wrote to its stdout' }
  }
}
