// core/app-entry.js
// Where an app's committed API surface is, and the command that wrote it.
//
// Two callers need the same two facts and for different reasons. `project:map`
// and `project:view` PARSE the file. `app:atlas` does not read it at all — it
// reads the header, because the header names the entry module, the services
// directory and the directory the generator was run from, which is everything
// needed to run a DIFFERENT presentation over the same app.
//
// So the entry is never probed. Guessing `api/src/app.ts` is wrong for an app
// that boots from its root (`packages/basecamp`), wrong for one that names an
// `--export`, and silently wrong rather than absent — it would describe an app
// that boots on junction's defaults. The committed snapshot already carries the
// answer, and the `snapshots` CI phase already trusts it the same way: it reruns
// each generator, named in the file's own header, from the file's own directory.
//
// The command travels as ARGV and never through a shell, and the binary is
// checked against a list — the string comes out of a file, and a file in a repo
// is not the same trust level as a string somebody typed.

import { existsSync, readFileSync } from 'node:fs'
import { resolve, dirname }         from 'node:path'

export const SURFACE_FILE = 'surface.snapshot.md'

// In order. A snapshot belongs in the surface it describes, so `api/` is the
// answer and is looked for first; the app root stays a candidate because an app
// whose isolation is by cwd keeps them there. First hit wins.
export const SURFACE_DIRS = ['api', '.']

export function surfaceFile(root) {
  for (const dir of SURFACE_DIRS) {
    const file = resolve(root, dir, SURFACE_FILE)
    if (existsSync(file)) return file
  }
  return null
}

/** The `generated by:` line of a snapshot, or null. */
export function generatedBy(file) {
  return readFileSync(file, 'utf8').split('\n')
    .find(l => l.includes('generated by:'))
    ?.replace(/^.*generated by:\s*/, '')
    .replace(/-->\s*$/, '')
    .trim() ?? null
}

// The only binary a header here may name. A generator is `junction <sub> …`; a
// header naming anything else is refused rather than run.
const ALLOWED_BIN = 'junction'

/**
 * Everything needed to run another presentation over the same built app.
 *
 * `{ file, dir, args }` — `dir` is where the generator was run from, `args` the
 * flags after the subcommand, verbatim. Null when there is no snapshot, and it
 * THROWS when there is one whose header cannot be trusted: an unreadable header
 * is a different problem from an absent file and must not read as one.
 */
export function appEntry(root) {
  const file = surfaceFile(root)
  if (!file) return null

  const command = generatedBy(file)
  if (!command) throw new Error(`${file} names no generator in its header — regenerate it with \`junction surface --app <entry>\``)

  const argv = command.split(/\s+/).filter(Boolean)
  if (argv[0] !== ALLOWED_BIN) {
    throw new Error(`${file} names \`${argv[0]}\` as its generator, and only \`${ALLOWED_BIN}\` is run from here`)
  }

  return { file, dir: dirname(file), args: argv.slice(2) }
}

/** The one sentence every caller says when there is no snapshot. */
export const surfaceMissingHint = (root) =>
  `no ${SURFACE_FILE} under ${root} (looked in ${SURFACE_DIRS.join(', ')}) — run ` +
  '`junction surface --app <entry>` from the API surface to write one. ' +
  'The app is read off a built app, never scanned (FJS-254).'
