// core/app-entry.js
// Where an app's committed API surface is, and the command that wrote it.
//
// Two callers need the same two facts and for different reasons. `project:map`
// PARSES the file. `app:atlas` does not read it at all — it reads the header,
// because the header names the entry module, the services directory and the
// directory the generator was run from, which is everything needed to run a
// DIFFERENT presentation over the same app.
//
// So `commands/project/_module.md` carries a second copy of the walk below —
// `SURFACE_FILE`, `SURFACE_DIRS`, `surfaceFile` and the `generated by:` parse.
// Two readers of one file drift into two confident answers; whether the two
// commands merge is `FJS-D240`.
//
// So the entry is never probed. Guessing `api/src/app.ts` is wrong for an app
// that boots from its root (`packages/basecamp`), wrong for one that names an
// `--export`, and silently wrong rather than absent — it would describe an app
// that boots on junction's defaults. The committed snapshot already carries the
// answer, and the `snapshots` CI phase already trusts it the same way: it reruns
// each generator, named in the file's own header, from the file's own directory.
//
// The command travels as ARGV and never through a shell, and the binary is
// checked against a list — the string comes out of a file, and a file in a repo
// is not the same trust level as a string somebody typed.

import { existsSync, readFileSync } from 'node:fs'
import { resolve, dirname }         from 'node:path'
import { spawnSync }                from 'node:child_process'

export const SURFACE_FILE = 'surface.snapshot.md'

// In order. A snapshot belongs in the surface it describes, so `api/` is the
// answer and is looked for first; the app root stays a candidate because an app
// whose isolation is by cwd keeps them there. First hit wins.
export const SURFACE_DIRS = ['api', '.']

export function surfaceFile(root) {
  for (const dir of SURFACE_DIRS) {
    const file = resolve(root, dir, SURFACE_FILE)
    if (existsSync(file)) return file
  }
  return null
}

/** The `generated by:` line of a snapshot, or null. */
export function generatedBy(file) {
  return readFileSync(file, 'utf8').split('\n')
    .find(l => l.includes('generated by:'))
    ?.replace(/^.*generated by:\s*/, '')
    .replace(/-->\s*$/, '')
    .trim() ?? null
}

// The only binary a header here may name. A generator is `junction <sub> …`; a
// header naming anything else is refused rather than run.
const ALLOWED_BIN = 'junction'

/**
 * Everything needed to run another presentation over the same built app.
 *
 * `{ file, dir, args }` — `dir` is where the generator was run from, `args` the
 * flags after the subcommand, verbatim. Null when there is no snapshot, and it
 * THROWS when there is one whose header cannot be trusted: an unreadable header
 * is a different problem from an absent file and must not read as one.
 */
export function appEntry(root) {
  const file = surfaceFile(root)
  if (!file) return null

  const command = generatedBy(file)
  if (!command) throw new Error(`${file} names no generator in its header — regenerate it with \`junction surface --app <entry>\``)

  const argv = command.split(/\s+/).filter(Boolean)
  if (argv[0] !== ALLOWED_BIN) {
    throw new Error(`${file} names \`${argv[0]}\` as its generator, and only \`${ALLOWED_BIN}\` is run from here`)
  }

  return { file, dir: dirname(file), args: argv.slice(2) }
}

/** The one sentence every caller says when there is no snapshot. */
export const surfaceMissingHint = (root) =>
  `no ${SURFACE_FILE} under ${root} (looked in ${SURFACE_DIRS.join(', ')}) — run ` +
  '`junction surface --app <entry>` from the API surface to write one. ' +
  'The app is read off a built app, never scanned (FJS-254).'

// ─── the model itself ─────────────────────────────────────────────────────────
//
// One owner for *how do you get the app model*, because there are two callers —
// `app:atlas`, which renders it, and `project:map`, which folds three of its
// four halves into a page built from files. Two spawns of one command is how the
// two come to disagree about which app they described.
//
// It ANSWERS a failure rather than throwing one. `project:map`'s whole property
// is that it needs no bun and no boot — it reads files — so a missing bun or an
// app that will not build has to degrade that page rather than end it, and only
// the caller knows which of those it is.

/**
 * Boot the app once and read `describeAppModel` off it.
 *
 * `{ model, entry }` on success, `{ error, entry }` otherwise — never a throw.
 * `entry` is null when there was no snapshot to find the app with.
 *
 * `{ run }` swaps the spawner, which is what lets this be tested with no bun,
 * no app and no boot — the same reason outpost injects its runner.
 */
export function readAppAtlas(root, { run: runner = spawnSync } = {}) {
  let entry = null
  try {
    entry = appEntry(root)
  } catch (err) {
    return { entry: null, error: err.message }
  }
  if (!entry) return { entry: null, error: surfaceMissingHint(root) }

  // argv, never a shell: the flags come out of a file's header, and a file in a
  // repo is not the same trust level as a string somebody typed. Run from the
  // snapshot's own directory, because the app resolves its database and its
  // services against the cwd its own scripts use.
  const run = runner('bunx', ['junction', 'atlas', ...entry.args], {
    cwd:       entry.dir,
    encoding:  'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })

  if (run.error?.code === 'ENOENT') {
    return { entry, error: 'bunx not found — junction is Bun-only, so reading the app model needs bun on PATH' }
  }
  if (run.status !== 0) {
    const tail = (run.stderr ?? '').trim().split('\n').slice(-6).join('\n')
    return { entry, error: `junction atlas failed under ${entry.dir}${tail ? `\n${tail}` : ''}` }
  }
  try {
    return { entry, model: JSON.parse(run.stdout) }
  } catch {
    return { entry, error: 'junction atlas did not answer JSON — something wrote to its stdout' }
  }
}
