// core/derived-paths.js
// Where fli writes the things it DERIVES from an app's seed.
//
// One owner, because four commands write or read the JSON Schema — `db:push`
// regenerates it after applying a change, `db:jsonschema` writes it on demand,
// `validate` regenerates it and reads it back, and `project:view` tests whether
// it is there. Four literals is four chances for two of them to disagree, and
// the way that shows up is the worst kind: `validate` regenerating one file and
// reading another, which is a clean pass over a schema nobody looked at.
//
// ─── Why a dot-directory, and why it is not committed ─────────────────────
//
// The JSON Schema is a document to be copied OUT — into an editor, a request
// validator, a client generator. It is not a snapshot: it carries no
// `generated by:` header, it is not named `*.snapshot.*`, and so the CI
// snapshots phase never rechecks it. Committing it therefore commits a file
// that everything can outdate and nothing grades, next to
// `db/jsonschema.snapshot.md`, which holds the same information in the form
// that IS gated.
//
// `.json/` is this repo's existing mark for that — the same one
// `api/src/emails/.preview/` wears — and it is gitignored for the same reason.

import { resolve } from 'node:path'

/**
 * The JSON Schema this app derives from its seed.
 *
 * Stated as a FILE path and never as a directory: `litestone jsonschema`
 * treats `--out` as a directory only when that directory already EXISTS, so
 * `--out <db>/.json` writes a file literally named `.json` on a fresh clone.
 */
export function jsonSchemaPath(dbDir) {
  return resolve(dbDir, '.json', 'schema.json')
}

/** The directory above it — for a caller that wants to clear or list it. */
export function derivedJsonDir(dbDir) {
  return resolve(dbDir, '.json')
}
