/**
 * core/edge.js — what the EDGE of a deployed app is: the nginx server blocks in
 * front of it, and the origin its browser build names for the API.
 *
 * One owner, three readers: `_steps-setup/05-nginx` writes the file,
 * `_steps-docker/03-build-web` inlines the API origin into the web build, and
 * `_steps-setup/07-report` prints both. A domain read three ways is a vhost for
 * one name and a bundle calling another, which is a CORS error on the first
 * page load and nothing earlier (`FJS-1089`).
 *
 * ── Two shapes ─────────────────────────────────────────────────────────────
 *
 * **One origin** — `deploy.web.domain` alone. One server block serves the SPA
 * and proxies `/api/` and `/ws` to the container, so the page and the API share
 * an origin and `junction.url` defaulting to `location.origin` is correct.
 *
 * **Two origins** — `deploy.api.domain` as well (`api.example.com` beside
 * `app.example.com`). The web block serves the SPA and proxies nothing; the API
 * block proxies every path. The web build is run with `VITE_API_URL` set to the
 * API's origin, which is the name every surface's sierra config reads.
 *
 * ── The path reaches the app unchanged ────────────────────────────────────
 *
 * `proxy_pass` carries no URI in either shape. With one — `…:3000/` — nginx
 * replaces the matched `location` prefix, so `/api/orders` arrived as `/orders`
 * at an app whose routes are registered under `apiPrefix: '/api'`, and every
 * call through the edge was a 404 the app could not explain (`FJS-1100`). The
 * dev server's proxy rewrites nothing either, so dev and the edge agree.
 *
 * Pure functions over strings. Nothing here runs a command.
 */

import { nginxGuard } from './pause.js'

export class EdgeError extends Error {}

// A hostname, and nothing a shell or an nginx config could read as syntax:
// the value is interpolated into both.
const HOSTNAME = /^(?=.{1,253}$)[a-z0-9](?:[a-z0-9-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)*$/i

/**
 * The two sides' names and certificates, graded.
 *
 * @returns {{ web: Side, api: Side }} where Side is `{ domain, sslCert, sslKey }`
 * @throws {EdgeError} naming the key
 */
export function edgeNames(deployConf) {
  const side = (name) => {
    const conf   = deployConf?.[name] ?? {}
    const domain = conf.domain ?? null
    if (domain !== null && !HOSTNAME.test(String(domain)))
      throw new EdgeError(`deploy.${name}.domain is ${JSON.stringify(domain)}, which is not a hostname. It is written into an nginx config and a shell line, so it is refused rather than quoted.`)
    return { domain, sslCert: conf.ssl?.cert ?? null, sslKey: conf.ssl?.key ?? null }
  }
  const web = side('web')
  const api = side('api')

  if (api.domain && api.domain === web.domain)
    throw new EdgeError(`deploy.api.domain is the web domain. One origin is what leaving it unset means — the web vhost already proxies /api/ and /ws.`)

  return { web, api }
}

/** The API's public origin under two origins; null under one, where the page's own origin is right. */
export function apiOrigin(names) {
  return names.api.domain ? `https://${names.api.domain}` : null
}

/**
 * The file `deploy:setup` writes to `vhostPath(appId)`: one server block, or two.
 *
 * The pause guard goes into EVERY block, ahead of the https redirect — a paused
 * app whose API origin still answered would let every open tab go on writing
 * through the migration the pause exists for.
 */
export function edgeVhost({ appId, serverPath, apiPort, web, api }) {
  const split = Boolean(api?.domain)

  const blocks = [serverBlock({
    appId, serverPath, logName: appId,
    serverName: web.domain ?? '_',
    tls:        web,
    body:       webBody({ serverPath }) + (split ? '' : apiLocations({ apiPort, prefix: '/api/' })),
  })]

  if (split) blocks.push(serverBlock({
    appId, serverPath, logName: `${appId}-api`,
    serverName: api.domain,
    tls:        api,
    body:       apiLocations({ apiPort, prefix: '/' }),
  }))

  return `# FrontierJS — ${appId}
# Generated by fli deploy:setup
${blocks.join('\n\n')}
`
}

// ─── pieces ───────────────────────────────────────────────────────────────────

function serverBlock({ appId, serverPath, logName, serverName, tls, body }) {
  const listen = (tls.sslCert && tls.sslKey) ? `
  listen 443 ssl;
  ssl_certificate     ${tls.sslCert};
  ssl_certificate_key ${tls.sslKey};

  # Redirect HTTP → HTTPS
  if ($scheme = http) {
    return 301 https://$host$request_uri;
  }
` : `
  listen 80;
`
  // A vhost with no access_log is a working config and every app on the
  // machine writing into nginx's own default, with nothing in a line saying
  // which one served the request. The path carries the app id and stays under
  // /var/log/nginx/ ending .log, which is what the packaged logrotate rule
  // bounds. `combined` is stated because it is what an analyser reads unasked;
  // a custom log_format is http-level and cannot be declared in a server block.
  return `server {
  server_name ${serverName};

${nginxGuard(serverPath)}
${listen}
  access_log /var/log/nginx/${logName}.access.log combined;
  error_log  /var/log/nginx/${logName}.error.log;
${body}
  gzip on;
  gzip_types text/plain text/css application/json application/javascript image/svg+xml;
  gzip_vary on;
}`
}

function webBody({ serverPath }) {
  return `
  # Web — SPA with fallback
  root ${serverPath}/current;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
`
}

function apiLocations({ apiPort, prefix }) {
  return `
  # API. No URI on proxy_pass, so the path reaches the app as the browser sent it.
  location ${prefix} {
    proxy_pass http://127.0.0.1:${apiPort};
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    # APPENDS to whatever the client already sent, so the rightmost entry is
    # what nginx observed and everything left of it is the caller's claim. The
    # app has to be told there is one proxy in front of it -- set
    # http.trustProxy to true in junction.config.js -- or it keys every caller
    # on this machine's address.
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # WebSocket (Junction)
  location /ws {
    proxy_pass http://127.0.0.1:${apiPort};
    proxy_http_version 1.1;
    proxy_set_header Upgrade    $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host       $host;
  }
`
}
