// ─── register-atlas.js — the registers as one page somebody works from ───────
//
// `fli register:atlas`. The three registers, the question queue and the
// ranking, crossed on one page for ANY project that declares `registers` in
// its package.json — a client app with `.project/` as much as this workspace.
// `ws:atlas` carries the registers too, but as a claim-only index inside a deck
// of package plates, and it needs a workspace to exist at all.
//
// ── What is read, and from where ─────────────────────────────────────────────
//
//   issues, rulings, ideas  ← core/registers.js `readRegisters`
//   the question queue      ← core/decisions.js `readDecisions`
//   ruling sections         ← core/decisions.js `rulingSections`
//   the ranking             ← core/next.js `rankNext`
//
// Nothing here parses a register file. A record this module cannot place is a
// defect in one of those readers, and fixing it there fixes `register:check`,
// `fli next` and the GUI in the same commit.
//
// ── Why the page is not a snapshot ───────────────────────────────────────────
//
// `rankNext` scores a row up when code it names was touched in recent commits,
// so two runs over one register differ by git history alone. The page carries
// no `generated by:` line and nothing gates it — regenerate it, never commit it.
//
// ── Links ────────────────────────────────────────────────────────────────────
//
// A link in a register is relative to the FILE it is written in — `../api/…`
// in `.project/ISSUES.md`, `../../web/…` in `.project/IDEAS/x.md` — so every
// one is resolved against its own file and then re-expressed relative to where
// the page is written. `edit` is an absolute `vscode://file/` URL with the
// line, which is the link that is actually clicked.

import { readFileSync }                         from 'node:fs'
import { dirname, relative, resolve, basename } from 'node:path'

import { readRegisters, registerLayout } from './registers.js'
import { readDecisions, rulingSections } from './decisions.js'
import { rankNext, blockedBy }           from './next.js'
import { THEMES, THEME_LIGHT, THEME_DARK, FALLBACK } from './terms.js'
import { CDN_STYLESHEET }                  from './assets.js'

// ─── collect ──────────────────────────────────────────────────────────────────

/**
 * The page's model. `outDir` is where the page will be written — every `href`
 * is relative to it. `touched` is handed to `rankNext`, for a test.
 */
export function collectRegisterAtlas(root, { outDir = null, touched = null } = {}) {
  const layout = registerLayout(root)
  const doc    = readRegisters(root)
  const out    = outDir ?? layout.dir

  const where = (file, line) => {
    const abs = resolve(root, file)
    return { file, line: line ?? null, href: rel(out, abs), edit: editUrl(abs, line) }
  }

  // A record's links are relative to the file that holds it.
  const links = (record) => (record.files ?? []).map(link => {
    const abs = resolve(dirname(resolve(root, record.file)), link.replace(/\/$/, ''))
    return { label: relative(root, abs) || '.', href: rel(out, abs), edit: editUrl(abs, null) }
  })

  const ranking = rankNext(root, { touched })
  const rank    = new Map()
  ranking.ready.forEach((r, i) => rank.set(r.id, { n: i + 1, score: r.score, terms: r.terms.map(t => t.note ?? t.term) }))
  for (const r of ranking.blocked) rank.set(r.id, { n: null, score: r.score, terms: r.terms.map(t => t.note ?? t.term) })

  const issues = doc.issues.map(r => ({
    id:        r.id,
    aliases:   r.aliases ?? [],
    pkg:       r.pkg ?? [],
    title:     r.title,
    status:    r.status,
    severity:  r.severity,
    verified:  r.verified ?? '',
    closed:    !!r.closed,
    // The reader flattens the whole row, so the body opens on the title.
    body:      withoutLead(r.body ?? '', r.title),
    refs:      (r.refs ?? []).filter(id => id !== r.id),
    blockedBy: r.closed ? [] : blockedBy(r),
    rank:      rank.get(r.id) ?? null,
    links:     links(r),
    at:        where(r.file, r.line),
  }))

  const rulings = doc.decisions.map(r => ({
    id:           r.id,
    date:         r.date ?? '',
    section:      r.section ?? '',
    title:        r.title ?? '',
    status:       r.status ?? '',
    supersededBy: r.supersededBy ?? null,
    body:         r.body ?? '',
    refs:         (r.refs ?? []).filter(id => id !== r.id),
    links:        links(r),
    at:           where(r.file, r.line),
  }))

  const questions = readDecisions(root).map(q => ({
    id:        q.id,
    source:    q.source,
    question:  q.question,
    state:     q.state,
    options:   q.options,
    recommend: q.recommend,
    paper:     q.paper?.id ?? null,
    at:        where(q.file, q.line),
  }))

  const asked = new Map()
  for (const q of questions) if (q.paper && q.state !== 'ruled') asked.set(q.paper, (asked.get(q.paper) ?? 0) + 1)

  const ideas = doc.ideas.map(r => ({
    id:        r.id,
    title:     r.title,
    status:    r.status,
    dated:     r.dated ?? '',
    body:      r.body ?? '',
    refs:      r.refs ?? [],
    questions: asked.get(r.id) ?? 0,
    links:     links(r),
    at:        where(r.file, r.line),
  }))

  return {
    name:       projectName(root),
    prefix:     doc.prefix,
    dir:        relative(root, layout.dir) || '.',
    sources:    doc.sources,
    unparsed:   doc.unparsed,
    duplicates: doc.ids.duplicates,
    sections:   rulingSections(root),
    ready:      ranking.ready.map(r => r.id),
    blocked:    ranking.blocked.map(r => r.id),
    issues,
    rulings,
    ideas,
    questions,
  }
}

// ─── render ───────────────────────────────────────────────────────────────────

/** The page. `css` is the vendored stylesheet, or null to link the published one. */
export function renderRegisterAtlas(model, css = null) {
  const light = css ? THEME_LIGHT : FALLBACK.light
  const dark  = css ? THEME_DARK  : FALLBACK.dark
  const json  = JSON.stringify(model).replace(/</g, '\\u003c')
  const title = `${model.name} — registers`

  return [
    '<!doctype html>',
    // No `generated by:` line: the ranking reads git, so this is never a snapshot.
    '<!-- fli register:atlas · not a snapshot -->',
    `<html lang="en" class="theme-${light}"><head><meta charset="utf-8">`,
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${esc(title)}</title>`,
    css
      ? `<style id="fjs-css">${css}</style>`
      : `<link rel="stylesheet" href="${CDN_STYLESHEET}">`,
    `<style id="ratlas">${STYLE}</style>`,
    `<script>${headScript(light, dark)}</script>`,
    '</head><body class="app">',
    `<header class="topbar">
      <strong>${esc(model.name)}</strong>
      <span class="text-xs text-muted">${esc(model.prefix ?? 'no prefix')} · ${esc(model.dir)}</span>
      <input id="q" class="field" type="search" placeholder="filter this tab…  /" aria-label="Filter">
      <span class="pill" id="hits"></span>
      <label class="ra-theme"><span class="text-xs text-muted">theme</span>
        <select class="field" id="theme" aria-label="Theme">
          ${(css ? ['field', ...THEMES] : THEMES).map(t => `<option value="${t}">${t}</option>`).join('')}
        </select>
      </label>
    </header>`,
    '<main class="screen stack">',
    '<div id="warn"></div>',
    `<div class="tabs">
      <div class="tablist" role="tablist" aria-label="Registers">
        ${TABS.map(([key, label]) => `<a class="tab" role="tab" href="#/${key}" data-tab="${key}" aria-selected="false">${label} <span class="pill" data-count="${key}"></span></a>`).join('')}
      </div>
      <div class="cluster gap-2xs ra-facets" id="facets"></div>
      <article class="view stack" role="tabpanel" id="view"></article>
    </div>`,
    '</main>',
    `<footer class="bar"><span class="text-xs text-muted">fli register:atlas · regenerate, never commit</span></footer>`,
    `<script type="application/json" id="model">${json}</script>`,
    `<script>${SCRIPT}</script>`,
    '</body></html>',
    '',
  ].join('\n')
}

export const TABS = [
  ['next',    'Next'],
  ['decide',  'Decide'],
  ['issues',  'Issues'],
  ['rulings', 'Rulings'],
  ['ideas',   'Ideas'],
  ['closed',  'Closed'],
]

// ─── helpers ──────────────────────────────────────────────────────────────────

function projectName(root) {
  try { return JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8')).name || basename(root) }
  catch { return basename(root) }
}

function withoutLead(body, title) {
  return title && body.startsWith(title) ? body.slice(title.length).trim() : body
}

function rel(from, abs) {
  return relative(from, abs) || '.'
}

function editUrl(abs, line) {
  return `vscode://file${abs}${line ? `:${line}` : ''}`
}

function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// Runs before the body is parsed, so a dark reader gets no white flash.
const headScript = (light, dark) => `
try {
  var saved = localStorage.getItem('fli.registers.theme')
  var wants = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
  document.documentElement.className = 'theme-' + (saved || (wants ? '${dark}' : '${light}'))
} catch (e) {}
`

// ─── style ────────────────────────────────────────────────────────────────────

const STYLE = `
.topbar { gap: var(--space-md); flex-wrap: wrap }
.topbar #q { flex: 1; min-width: 12rem; max-width: 32rem }
.ra-theme { display: flex; align-items: center; gap: var(--space-2xs); margin-left: auto }
.tablist a.tab { text-decoration: none }
.ra-facets { padding-block: var(--space-sm) }
.ra-facets:empty { display: none }
.ra-row { border-bottom: 1px solid var(--border, currentColor) }
.ra-row > summary { display: flex; gap: var(--space-sm); align-items: baseline; cursor: pointer; padding-block: var(--space-xs); list-style: none }
.ra-row > summary::-webkit-details-marker { display: none }
.ra-row > summary .ra-title { flex: 1; min-width: 0 }
.ra-row[open] > summary .ra-title { font-weight: 600 }
.ra-id { font-family: var(--font-mono, monospace); white-space: nowrap }
.ra-meta { white-space: nowrap }
.ra-body { padding: 0 0 var(--space-md) var(--space-lg); display: grid; gap: var(--space-xs) }
.ra-body p { margin: 0; white-space: pre-wrap; overflow-wrap: anywhere }
.ra-opts { margin: 0; padding: 0; list-style: none; display: grid; gap: var(--space-2xs) }
.ra-opts li.is-rec { font-weight: 600 }
.ra-cmd { font-family: var(--font-mono, monospace); width: 100% }
.ra-row.is-flash > summary { outline: 2px solid currentColor; outline-offset: 2px }
.hidden { display: none !important }
@media (max-width: 640px) { .ra-meta { display: none } .ra-body { padding-left: 0 } }
`

// ─── script ───────────────────────────────────────────────────────────────────
//
// The page renders from the embedded model, so a register of 1,400 rows costs
// one JSON parse rather than 1,400 rows of markup in the file.

const SCRIPT = `
const M=JSON.parse(document.getElementById('model').textContent)
const $=id=>document.getElementById(id)
const view=$('view'),facets=$('facets'),q=$('q'),hits=$('hits'),themePick=$('theme')
const byId=new Map()
for(const r of M.issues){ byId.set(r.id.toLowerCase(),['issue',r]); for(const a of r.aliases) byId.set(a.toLowerCase(),['issue',r]) }
for(const r of M.rulings) if(r.id) byId.set(r.id.toLowerCase(),['ruling',r])
for(const r of M.ideas) byId.set(r.id.toLowerCase(),['idea',r])

function esc(s){ return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;') }

// ── theme ──
function setTheme(name){
  document.documentElement.className='theme-'+name
  themePick.value=name
  try{ localStorage.setItem('fli.registers.theme',name) }catch{}
}
themePick.value=document.documentElement.className.replace('theme-','')
themePick.addEventListener('change',()=>setTheme(themePick.value))

// ── what each tab holds ──
const open=M.issues.filter(r=>!r.closed)
const SETS={
  next:    ()=>[...M.ready,...M.blocked].map(id=>byId.get(id.toLowerCase())?.[1]).filter(Boolean),
  decide:  ()=>M.questions.filter(x=>x.state!=='ruled'),
  issues:  ()=>open,
  rulings: ()=>M.rulings,
  ideas:   ()=>M.ideas,
  closed:  ()=>M.issues.filter(r=>r.closed),
}
for(const [k,f] of Object.entries(SETS)){ const el=document.querySelector('[data-count="'+k+'"]'); if(el) el.textContent=f().length }

// A facet is a dimension, a record's value for it, and the choices in file order.
const FACETS={
  issues:  [['severity',r=>r.severity],['area',r=>r.pkg],['status',r=>r.status]],
  closed:  [['area',r=>r.pkg]],
  rulings: [['section',r=>r.section],['status',r=>r.status||'in force']],
  ideas:   [['status',r=>r.status]],
  decide:  [['state',x=>x.state]],
  next:    [['severity',r=>r.severity],['area',r=>r.pkg]],
}
const picked={}

function drawFacets(tab){
  const dims=FACETS[tab]||[]
  facets.innerHTML=dims.map(([dim,get])=>{
    const seen=new Map()
    for(const r of SETS[tab]()) for(const v of [].concat(get(r)||[])) seen.set(v,(seen.get(v)||0)+1)
    if(seen.size<2) return ''
    const now=picked[tab+':'+dim]||''
    return '<label class="text-xs text-muted">'+dim+' <select class="field" data-dim="'+dim+'"><option value="">any</option>'
      +[...seen].map(([v,n])=>'<option value="'+esc(v)+'"'+(v===now?' selected':'')+'>'+esc(v)+' ('+n+')</option>').join('')
      +'</select></label>'
  }).join('')
  if(tab==='decide') facets.insertAdjacentHTML('beforeend',sectionPicker())
  for(const s of facets.querySelectorAll('[data-dim]')) s.addEventListener('change',()=>{ picked[tab+':'+s.dataset.dim]=s.value; draw() })
  const sec=facets.querySelector('#section')
  if(sec) sec.addEventListener('change',()=>{ try{ localStorage.setItem('fli.registers.section',sec.value) }catch{}; draw() })
}

function sectionPicker(){
  if(!M.sections.length) return ''
  let saved=''; try{ saved=localStorage.getItem('fli.registers.section')||'' }catch{}
  return '<label class="text-xs text-muted">file rulings under <select class="field" id="section">'
    +M.sections.map(s=>'<option'+(s===saved?' selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label>'
}

// ── rows ──
const tone=s=>s==='S1'||s==='S2'?'danger':s==='S3'?'warning':s==='decision'?'info':'muted'
const ideaTone=s=>s==='shipped'?'success':s==='partial'?'info':s==='withdrawn'||s==='superseded-by'?'muted':'warning'

function refChips(refs){
  return refs.length?'<div class="cluster gap-2xs">'+refs.map(id=>byId.has(id.toLowerCase())
    ?'<a class="chip link" href="#/id/'+esc(id)+'">'+esc(id)+'</a>'
    :'<span class="chip">'+esc(id)+'</span>').join('')+'</div>':''
}
function linkChips(links){
  return links.length?'<div class="cluster gap-2xs">'+links.map(l=>'<a class="chip link" href="'+esc(l.edit)+'" title="open in editor">'+esc(l.label)+'</a>').join('')+'</div>':''
}
function source(at){
  return '<div class="text-xs text-muted"><a class="link" href="'+esc(at.edit)+'">edit '+esc(at.file)+(at.line?':'+at.line:'')+'</a> · <a class="link" href="'+esc(at.href)+'">view</a></div>'
}

function issueRow(r){
  const rank=r.rank&&r.rank.n?'#'+r.rank.n:''
  return '<details class="ra-row" data-id="'+esc(r.id)+'"><summary>'
    +'<span class="badge '+tone(r.severity)+'">'+esc(r.severity)+'</span>'
    +'<span class="ra-id">'+esc(r.id)+'</span>'
    +'<span class="ra-title">'+esc(r.title)+'</span>'
    +(r.blockedBy.length?'<span class="badge warning">blocked by '+esc(r.blockedBy.join(', '))+'</span>':'')
    +'<span class="ra-meta text-xs text-muted">'+esc([].concat(r.pkg).join(', '))+' · '+esc(r.status)+(r.verified?' · '+esc(r.verified):'')+'</span>'
    +(rank?'<span class="pill">'+rank+'</span>':'')
    +'</summary><div class="ra-body">'
    +(r.rank?'<div class="text-xs text-muted">score '+r.rank.score+' — '+esc(r.rank.terms.join(' · '))+'</div>':'')
    +'<p class="text-sm">'+esc(r.body)+'</p>'+refChips(r.refs)+linkChips(r.links)+source(r.at)+'</div></details>'
}

function rulingRow(r){
  return '<details class="ra-row" data-id="'+esc(r.id||'')+'"><summary>'
    +'<span class="ra-meta text-xs text-muted">'+esc(r.date)+'</span>'
    +(r.id?'<span class="badge info">'+esc(r.id)+'</span>':'')
    +'<span class="ra-title">'+esc(r.title)+'</span>'
    +(r.status?'<span class="badge muted">'+esc(r.status)+(r.supersededBy?' '+esc(r.supersededBy):'')+'</span>':'')
    +'<span class="ra-meta text-xs text-muted">'+esc(r.section)+'</span>'
    +'</summary><div class="ra-body"><p class="text-sm">'+esc(r.body)+'</p>'+refChips(r.refs)+linkChips(r.links)+source(r.at)+'</div></details>'
}

function ideaRow(r){
  return '<details class="ra-row" data-id="'+esc(r.id)+'"><summary>'
    +'<span class="badge '+ideaTone(r.status)+'">'+esc(r.status||'?')+'</span>'
    +'<span class="ra-title">'+esc(r.title)+'</span>'
    +(r.questions?'<a class="pill" href="#/decide/'+esc(r.id)+'" title="open questions">'+r.questions+' ?</a>':'')
    +'<span class="ra-meta text-xs text-muted">'+esc(r.id)+(r.dated?' · '+esc(r.dated):'')+'</span>'
    +'</summary><div class="ra-body"><p class="text-sm">'+esc(r.body)+'</p>'+refChips(r.refs)+linkChips(r.links)+source(r.at)+'</div></details>'
}

// \`fli decide\` is the one writer, so the page hands out its exact command.
function decideCmd(x,letter){
  const sec=$('section')?.value||''
  const rec=x.recommend&&x.recommend.letter===letter
  return 'fli decide '+x.id+' '+letter+(sec?' --section "'+sec.replace(/"/g,'\\\\"')+'"':'')+(rec?'':' --why ""')
}

function questionRow(x){
  const opts=x.options.map(o=>{
    const rec=x.recommend&&x.recommend.letter===o.letter
    return '<li class="'+(rec?'is-rec':'')+'"><strong>'+esc(o.letter)+'</strong> — '+esc(o.text)
      +' <button class="btn ghost" data-copy="'+esc(x.id)+'" data-letter="'+esc(o.letter)+'">copy fli decide</button></li>'
  }).join('')
  return '<details class="ra-row" data-id="'+esc(x.id)+'" data-paper="'+esc(x.paper||'')+'"'+(x.state==='decidable'?' open':'')+'><summary>'
    +'<span class="badge '+(x.state==='decidable'?'success':'muted')+'">'+esc(x.state)+'</span>'
    +'<span class="ra-title">'+esc(x.question)+'</span>'
    +'<span class="ra-meta text-xs text-muted">'+esc(x.paper||x.source)+'</span>'
    +'</summary><div class="ra-body">'
    +(opts?'<ul class="ra-opts dense">'+opts+'</ul>':'<p class="text-sm text-muted">No lettered options yet — write **A** / **B** sub-bullets and a **Recommend X** line to make it pickable.</p>')
    +(x.recommend?'<p class="text-sm">★ Recommend '+esc(x.recommend.letter)+' — '+esc(x.recommend.why)+'</p>':'')
    +'<input class="field ra-cmd hidden" readonly>'
    +source(x.at)+'</div></details>'
}

const ROW={ next:issueRow, issues:issueRow, closed:issueRow, rulings:rulingRow, ideas:ideaRow, decide:questionRow }

// ── the view ──
let tab='next'
function draw(){
  const f=q.value.trim().toLowerCase()
  const dims=FACETS[tab]||[]
  let list=SETS[tab]()
  for(const [dim,get] of dims){
    const want=picked[tab+':'+dim]
    if(want) list=list.filter(r=>[].concat(get(r)||[]).includes(want))
  }
  if(f) list=list.filter(r=>JSON.stringify(r).toLowerCase().includes(f))
  const total=SETS[tab]().length
  hits.textContent=list.length===total?total:list.length+' / '+total
  view.innerHTML=list.length?list.map(ROW[tab]).join(''):'<div class="empty"><div class="empty-title">Nothing here</div><div class="empty-text">'+(total?'Nothing matches the filter.':'This register holds no records of this kind.')+'</div></div>'
}

function show(next,focus){
  tab=SETS[next]?next:'next'
  for(const t of document.querySelectorAll('[data-tab]')) t.setAttribute('aria-selected',String(t.dataset.tab===tab))
  drawFacets(tab)
  draw()
  if(focus) flash(focus)
}

function flash(key){
  const el=[...view.querySelectorAll('[data-id],[data-paper]')].find(d=>d.dataset.id===key||d.dataset.paper===key)
  if(!el) return
  el.open=true
  el.classList.add('is-flash')
  el.scrollIntoView({block:'center'})
  setTimeout(()=>el.classList.remove('is-flash'),1500)
}

// \`#/issues\` is a tab, \`#/id/ELA-004\` is a record wherever it lives, and
// \`#/decide/<paper>\` is a tab opened on that paper's questions.
function route(){
  const [head,...rest]=decodeURIComponent(location.hash.replace(/^#\\/?/,'')).split('/')
  const arg=rest.join('/')
  if(head==='id'){
    const hit=byId.get(arg.toLowerCase())
    if(!hit) return show(tab)
    const [kind,r]=hit
    q.value=''
    return show(kind==='ruling'?'rulings':kind==='idea'?'ideas':r.closed?'closed':'issues',r.id)
  }
  show(head||'next',arg||null)
}
addEventListener('hashchange',route)

q.addEventListener('input',draw)
addEventListener('keydown',e=>{
  if(e.key!=='/'||/^(input|textarea|select)$/i.test(e.target.tagName)) return
  e.preventDefault(); q.focus()
})

view.addEventListener('click',async e=>{
  const b=e.target.closest('[data-copy]')
  if(!b) return
  e.preventDefault()
  const x=M.questions.find(y=>y.id===b.dataset.copy)
  const cmd=decideCmd(x,b.dataset.letter)
  const box=b.closest('.ra-body').querySelector('.ra-cmd')
  box.value=cmd; box.classList.remove('hidden'); box.select()
  try{ await navigator.clipboard.writeText(cmd); b.textContent='copied' }catch{ b.textContent='select + copy' }
  setTimeout(()=>{ b.textContent='copy fli decide' },1500)
})

// ── what the readers could not place ──
const warn=[]
if(M.unparsed.length) warn.push(M.unparsed.length+' line(s) have a record\\'s shape and parsed to nothing — first at '+M.unparsed[0].file+':'+M.unparsed[0].line+'. Run fli register:check.')
if(M.duplicates.length) warn.push(M.duplicates.length+' id(s) issued twice — '+M.duplicates.map(d=>d.id).slice(0,5).join(', ')+'. Run fli register:check.')
if(!M.prefix) warn.push('package.json declares no registers prefix, so no issue row or ruling can be read.')
if(warn.length) $('warn').innerHTML='<article class="alert warning"><div class="alert-content"><strong>The registers disagree with themselves</strong><p class="text-sm">'+warn.map(esc).join('<br>')+'</p></div></article>'

route()
`
