// ─── repo-live.js — the two facts a committed page cannot hold ───────────────
//
// The atlas and the map are snapshots: byte-compared in CI, so nothing in them
// may vary between two runs over one tree. That rules out exactly the two
// things a person most often wants to know about a package — when anyone last
// touched it, and whether what is on the registry is what is in the tree.
//
// So they live here, behind `--live`, and the page they produce is deliberately
// NOT a snapshot: a different filename, no `generated by:` header, and a
// timestamp printed on it. Nothing checks it, because there is nothing stable
// to check.
//
// ── Why the registry half matters ────────────────────────────────────────────
//
// `FJS-252`: a user's experience is a function of the tree AND the registry,
// and those drift independently. Every id in the open register is a statement
// about the tree, so the whole class is invisible from inside it. One column
// saying *local 0.15.1, published 0.15.0* is the cheapest possible view of it.
//
// Zero dependencies, plain ESM. Everything here can fail — no git, no network,
// a package never published — and every failure is a null rather than a throw:
// a page that renders without the registry is worth more than no page.

import { spawnSync } from 'node:child_process'

const GIT_TIMEOUT = 10_000
const NPM_TIMEOUT = 20_000

// ─── collectLive ──────────────────────────────────────────────────────────────
//
//   collectLive({ root, packages, registry })  → { git, rows, at }
//
// `at` is the only timestamp anything here produces, and it is why the output
// cannot be a snapshot. `rows` is one per package, in the order given.

export function collectLive({ root, packages, registry = true, now = new Date() }) {
  const rows = packages.map(pkg => {
    const dir = pkg.claimed ? `packages/${pkg.folder}` : `packages/${pkg.folder}`
    const published = registry && pkg.name && !pkg.private ? publishedVersion(pkg.name) : null

    return {
      folder:    pkg.folder,
      name:      pkg.name ?? pkg.folder,
      version:   pkg.version ?? null,
      published,
      ahead:     pkg.version && published ? compareVersions(pkg.version, published) > 0 : false,
      behind:    pkg.version && published ? compareVersions(pkg.version, published) < 0 : false,
      lastCommit: gitOut(root, ['log', '-1', '--format=%cs', '--', dir]),
      lastSubject: gitOut(root, ['log', '-1', '--format=%s', '--', dir]),
      commits90: countLines(gitOut(root, ['log', '--since=90.days', '--format=%h', '--', dir])),
      dirty:     countLines(gitOut(root, ['status', '--porcelain', '--', dir])),
    }
  })

  return {
    at:  now.toISOString().replace('T', ' ').slice(0, 16),
    git: {
      branch: gitOut(root, ['rev-parse', '--abbrev-ref', 'HEAD']),
      head:   gitOut(root, ['rev-parse', '--short', 'HEAD']),
      dirty:  countLines(gitOut(root, ['status', '--porcelain'])),
    },
    rows,
  }
}

// ─── git ──────────────────────────────────────────────────────────────────────
//
// A pathspec on every question, because in a single-repo workspace a git
// question asked without one answers for the whole repo — which is how sixteen
// packages once reported each other's state.

function gitOut(root, argv) {
  const run = spawnSync('git', argv, {
    cwd: root, encoding: 'utf8', shell: false, timeout: GIT_TIMEOUT,
    env: { ...process.env, GIT_OPTIONAL_LOCKS: '0' },
  })
  if (run.error || run.status !== 0) return null
  const out = (run.stdout ?? '').trim()
  return out === '' ? null : out
}

function countLines(text) {
  return text ? text.split('\n').filter(Boolean).length : 0
}

// ─── the registry ─────────────────────────────────────────────────────────────
//
// `npm view` rather than a fetch: it already knows the registry, the auth and
// the proxy this machine is configured for. A package that has never been
// published answers with an error, which is a null here and *not published* on
// the page — a different thing from behind.

function publishedVersion(name) {
  const run = spawnSync('npm', ['view', name, 'version'], {
    encoding: 'utf8', shell: false, timeout: NPM_TIMEOUT,
  })
  if (run.error || run.status !== 0) return null
  const out = (run.stdout ?? '').trim()
  return /^\d/.test(out) ? out : null
}

/** Numeric-segment compare; a prerelease suffix is ignored, which is enough to say ahead. */
export function compareVersions(a, b) {
  const pa = String(a).split('-')[0].split('.').map(Number)
  const pb = String(b).split('-')[0].split('.').map(Number)

  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const x = pa[i] ?? 0, y = pb[i] ?? 0
    if (x !== y) return x > y ? 1 : -1
  }
  return 0
}
