// ─── snapshots.js — committed generated artefacts, rechecked ─────────────────
//
// A snapshot is a generated file committed beside its source, so a change
// nothing else in the app can see arrives as a diff: the access rules a gate
// enforces below the API, the DDL every hand-written statement binds to, the
// JSON Schema three packages validate against, the route table a file rename
// moves, what a thrown value becomes.
//
// Each one names the command that wrote it, in its own header:
//
//   <!-- generated by: litestone access --schema schema.lite -->
//   -- generated by: litestone ddl --schema schema.lite
//
// This finds them and reruns that command with `--check` appended, from the
// snapshot's own directory — which is why a header names its schema by basename
// and not by a path. Adding a KIND of snapshot therefore costs nothing here; it
// costs a generator that answers `--check`.
//
// ── One engine, two callers ──────────────────────────────────────────────────
//
// `fli test:snapshots` runs this over a client app. `scripts/ci.mjs` runs it
// over this repo. Same reason `checks.js` is shared: a framework that publishes
// a generator and keeps the gate to itself has shipped half a feature, and two
// implementations of one rule is how the halves drift.
//
// So: zero dependencies, plain ESM, node or bun. `ci.mjs` imports it by relative
// path and runs before anything is installed.
//
// ── Why the command is restricted ────────────────────────────────────────────
//
// The command comes out of a file in the repo and this executes it. A header is
// data, and data that CI executes is a supply chain — so the binary must be one
// of a known few and every argument a plain flag or path, no shell.

import { spawnSync }                              from 'node:child_process'
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { join, dirname, relative }                from 'node:path'

/**
 * Binaries a snapshot header may name, and the package that ships each one. A
 * new one is a deliberate edit here.
 *
 * The package matters because the generator is resolved THROUGH it — the way
 * the app's own code resolves the framework — and never off PATH. `bunx <name>`
 * finds a global install on the machine of anyone who has run `bun add -g`, and
 * on a machine with none it downloads a STRANGER's package of that name from
 * the registry: a CI runner fetched an unrelated `junction`, wrote a lockfile
 * and failed with `could not determine executable to run for package junction`
 * (FJS-009). Locally the same check had been grading the tree against whatever
 * global build happened to be installed.
 */
export const SNAPSHOT_BINS = new Map([
  ['litestone', '@frontierjs/litestone'],
  ['junction',  '@frontierjs/junction'],
  ['sierra',    '@frontierjs/sierra'],
  ['fli',       '@frontierjs/cli'],
])

/** `generated by: <command>` — in an HTML comment, a `--` SQL comment, or a JSON string. */
const GENERATOR = /generated by:\s*`?([A-Za-z0-9][^\n`"]*?)`?\s*(?:-->|\*\/|"|$)/m

/** A plain flag or path. Anything else is shell syntax and is refused by name. */
const ARG = /^[A-Za-z0-9._/@=,:-]+$/

/** A snapshot is `<anything>.snapshot.<ext>` — the extension is the renderer's choice. */
const SNAPSHOT = /\.snapshot\.[^./]+$/

const SKIP = new Set(['node_modules', 'dist', 'build', '.git', 'coverage', '.output', '.vite'])

// The header lives near the top by convention; reading a slice keeps a large
// generated file from being parsed in full.
const HEAD_BYTES = 4096

// ─── findSnapshots ────────────────────────────────────────────────────────────
//
//   findSnapshots({ root })  → [{ file, dir, argv, error }]
//
// `file` is repo-relative. `argv` is the generator, already validated; `error`
// says why there is none, and a snapshot with an error is a FAILURE rather than
// a skip — a generated file nothing can recheck is a document wearing a gate's
// clothes.

export function findSnapshots({ root, depth = 6 } = {}) {
  const found = []

  walk(root, depth, (dir) => {
    for (const name of safeRead(dir)) {
      if (!SNAPSHOT.test(name)) continue
      const abs = join(dir, name)
      try { if (!statSync(abs).isFile()) continue } catch { continue }
      found.push(describe(abs, root))
    }
  })

  return found.sort((a, b) => a.file.localeCompare(b.file))
}

function describe(abs, root) {
  const file = relative(root, abs).split('\\').join('/')
  const entry = { file, dir: dirname(file) || '.', argv: null, error: null }

  let head = ''
  try { head = readFileSync(abs, 'utf8').slice(0, HEAD_BYTES) } catch (err) {
    entry.error = `unreadable — ${err.message}`
    return entry
  }

  const match = head.match(GENERATOR)
  if (!match) {
    entry.error =
      'names no generator, so nothing can check it. Add a `generated by: <command>` line ' +
      'to its header — the command that writes it, with its source named by basename.'
    return entry
  }

  const argv = match[1].trim().split(/\s+/)

  if (!SNAPSHOT_BINS.has(argv[0])) {
    entry.error =
      `names generator \`${argv[0]}\`, which will not be run. Allowed: ` +
      `${[...SNAPSHOT_BINS.keys()].join(', ')}. That list is what stops a committed file from ` +
      'choosing what CI executes.'
    return entry
  }

  const bad = argv.slice(1).find(a => !ARG.test(a))
  if (bad) {
    entry.error = `passes \`${bad}\` to its generator — arguments are plain flags and paths, no shell syntax.`
    return entry
  }

  entry.argv = argv
  return entry
}

// ─── checkSnapshots ───────────────────────────────────────────────────────────
//
//   checkSnapshots({ root })  → { results, checked, failed }
//
// Each result is `{ file, ok, error, stdout, stderr }`. The generator is run
// from the snapshot's OWN directory, and through `bunx` rather than a path into
// the framework, because a consuming app runs this same check with the packages
// installed from the registry.

// ─── resolving a generator ───────────────────────────────────────────────────
//
// Walk up from the snapshot's own directory for the package that ships the
// binary — as itself, when a package generates its own snapshot, or under a
// node_modules. That is the resolution the app's own imports get, so this repo
// and a consuming app grade against the same build of the generator, and
// neither answer can come from a global install or from the registry.
//
// `bun` runs it rather than process.execPath: junction's bin is a `.ts` file and
// ci.mjs runs under node.

function resolveGenerator(bin, from) {
  const pkgName = SNAPSHOT_BINS.get(bin)
  const nested  = ['node_modules', ...pkgName.split('/'), 'package.json']

  let dir = from
  for (;;) {
    const found = binEntry(join(dir, 'package.json'), pkgName, bin)
                ?? binEntry(join(dir, ...nested),     pkgName, bin)
                ?? workspaceMember(dir, pkgName, bin)
    if (found) return found

    const up = dirname(dir)
    if (up === dir) return null
    dir = up
  }
}

// The workspace's own members, read off its `workspaces` globs. Needed because
// bun does not link a `workspace:*` member into the root `node_modules` here at
// all — so in this repo the four generators resolve by no other means, and
// before this the check ran whatever `bunx` found, which was a GLOBAL install of
// unknown vintage.
function workspaceMember(dir, pkgName, bin) {
  let root
  try { root = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) } catch { return null }

  const globs = Array.isArray(root.workspaces) ? root.workspaces : root.workspaces?.packages
  if (!Array.isArray(globs)) return null

  for (const glob of globs) {
    // `packages/*` and a literal path are the two shapes a workspace uses here;
    // anything cleverer is not worth a glob engine in a zero-dependency module.
    const dirs = glob.endsWith('/*')
      ? listDirs(join(dir, glob.slice(0, -2)))
      : [join(dir, glob)]

    for (const member of dirs) {
      const found = binEntry(join(member, 'package.json'), pkgName, bin)
      if (found) return found
    }
  }

  return null
}

function listDirs(parent) {
  try {
    return readdirSync(parent).map(name => join(parent, name)).filter(p => statSync(p).isDirectory())
  } catch { return [] }
}

function binEntry(manifestPath, pkgName, bin) {
  if (!existsSync(manifestPath)) return null

  let manifest
  try { manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) } catch { return null }
  if (manifest.name !== pkgName) return null

  const declared = typeof manifest.bin === 'string' ? manifest.bin : manifest.bin?.[bin]
  if (!declared) return null

  const file = join(dirname(manifestPath), declared)
  return existsSync(file) ? file : null
}

export function checkSnapshots({ root, only = null, timeoutMs = 15 * 60 * 1000, maxBuffer = 64 * 1024 * 1024 } = {}) {
  const entries = findSnapshots({ root }).filter(e => !only || only.includes(e.file))
  const results = []

  for (const entry of entries) {
    if (entry.error) {
      results.push({ ...entry, ok: false, stdout: '', stderr: '' })
      continue
    }

    const generator = resolveGenerator(entry.argv[0], join(root, entry.dir))
    if (!generator) {
      results.push({
        ...entry,
        ok:    false,
        error: `names generator \`${entry.argv[0]}\`, and ${SNAPSHOT_BINS.get(entry.argv[0])} does not ` +
               `resolve from ${entry.dir}. Install it — a generator is resolved through its package, ` +
               'never off PATH.',
        stdout: '', stderr: '',
      })
      continue
    }

    const run = spawnSync('bun', [generator, ...entry.argv.slice(1), '--check'], {
      cwd:        join(root, entry.dir),
      encoding:   'utf8',
      shell:      false,
      maxBuffer,
      timeout:    timeoutMs,
      killSignal: 'SIGKILL',
      env:        { ...process.env, CI: '1', FORCE_COLOR: '0' },
    })

    if (run.error) {
      results.push({ ...entry, ok: false, error: `could not run \`${entry.argv.join(' ')}\` — ${run.error.message}`, stdout: '', stderr: '' })
      continue
    }

    results.push({
      ...entry,
      ok:     run.status === 0,
      error:  run.status === 0 ? null : 'no longer matches its source',
      stdout: run.stdout ?? '',
      stderr: run.stderr ?? '',
    })
  }

  return { results, checked: results.length, failed: results.filter(r => !r.ok).length }
}

// ─── formatSnapshotResults ────────────────────────────────────────────────────
//
// The rerun command is printed with its directory, because that is the whole
// remedy and a reader should not have to reconstruct it.

export function formatSnapshotResults(results) {
  const out = []
  for (const r of results) {
    if (r.ok) continue
    out.push(`  ✗  ${r.file} ${r.error}`)
    if (r.argv) out.push(`       cd ${r.dir} && bunx ${r.argv.join(' ')}`)
  }
  return out
}

// ─── reading the tree ─────────────────────────────────────────────────────────

function safeRead(dir) {
  try { return readdirSync(dir).sort() } catch { return [] }
}

function walk(dir, depth, fn) {
  if (depth < 0 || !existsSync(dir)) return
  try { fn(dir) } catch { /* an unreadable directory is not a finding */ }
  for (const name of safeRead(dir)) {
    if (SKIP.has(name) || name.startsWith('.')) continue
    const child = join(dir, name)
    try { if (statSync(child).isDirectory()) walk(child, depth - 1, fn) } catch { /* dangling link */ }
  }
}
