// ─── terms.js — what vocabulary does this workspace ask a newcomer to learn? ──
//
// One model, three presentations. The question it answers is the size and the
// shape of the vocabulary: how many words must somebody hold to read this repo,
// which of them the doctrine blesses, and which of them nothing has ever named.
//
// ── Three vocabularies, never one number ─────────────────────────────────────
//
// A single frequency count mixes things that are learned three different ways
// and the average describes none of them.
//
//   concept   — Model, Service, Resource, Release. A mental model is built from
//               these. Tens of them. This is the one worth auditing.
//   language  — what a `.lite` or `.mesa` file may hold. Declared, countable,
//               and already gated for `.lite` (`catalog.snapshot.md`).
//   api       — identifiers a developer types. Looked up, not memorized, so the
//               count that matters is how far each one SPREADS.
//
// ── Classification, never a silent exclude ───────────────────────────────────
//
// Measured before this was written: the noise in a prose scan is not stop words
// — it is proper nouns. `Vite`, `Chrome`, `Java` and `Prisma` all outrank
// `Resource`. So nothing is dropped. Every term is CLASSIFIED and the classes
// that are not concepts can be looked at, because a word landing in the wrong
// class is the failure this file can actually have, and a dropped word leaves
// nothing behind to notice.
//
// ── Spread over count ────────────────────────────────────────────────────────
//
// A term in twelve packages is core vocabulary. A term with three hundred hits
// in one file is local jargon. Raw frequency ranks the second above the first.
//
// ── Not a snapshot ───────────────────────────────────────────────────────────
//
// The written page carries no `generated by:` line and is not named
// `*.snapshot.*`, so the `snapshots` CI phase does not adopt it. That is
// deliberate while the exclude lists are still being refined — a gated artifact
// would fail the build on every tuning pass. The gated `ws:dictionary` is the
// thing this becomes once `ARCHITECT.md` § 2 settles ([FJS-1211](ISSUES.md)).

import { readdirSync, readFileSync, existsSync } from 'fs'
import { join, relative, sep }                   from 'path'
import { singularize }                           from '@frontierjs/toolbelt/inflect'
import { splitFrontmatter }                      from '@frontierjs/toolbelt/frontmatter'

// ─── corpus ───────────────────────────────────────────────────────────────────
//
// Generated files are excluded from the PROSE corpus on purpose. A snapshot is
// this repo quoting itself, so counting it would report the vocabulary of the
// generators as the vocabulary of the framework.

const SKIP_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', 'out', 'coverage', '.bun', '.cache',
  '.next', '.svelte-kit', 'tmp', '.vscode-test', 'vendor',
  // A running fli's compiled commands: a copy of every .md it ran, deleted
  // when that process exits, so a walk racing it dies on ENOENT.
  '.fli-tmp',
  // Retired change logs (FJS-D675): the vocabulary of a tree that has moved on,
  // and one owner for 24 packages' words, so every term in them reads as spread.
  'changes-archive',
])

// ─── what the corpus is made of ───────────────────────────────────────────────
//
// Four KINDS, because *is this word in the documents or in the code* is a
// different question from *which package says it*, and the page lets a reader
// subtract either. A term written about at length and named by nothing is the
// shape worth finding, and it is invisible while the corpus is markdown alone.
//
// **A source file is read WHOLE**, comments and code together. That is a
// deliberate trade and it costs something: `Map`, `Set` and every class name
// rank as concepts, and a term the api lens already counts is counted here too.
// The page says so where the numbers are, rather than leaving a reader to
// wonder why `String` outranks `Resource`.
const KIND_BY_EXT = new Map([
  ['.md',    'markdown'],
  ['.ts',    'code'],  ['.js',   'code'], ['.mjs', 'code'], ['.mts', 'code'],
  ['.mesa',  'framework'], ['.lite', 'framework'],
  ['.css',   'web'],  ['.html', 'web'],
])
export const KINDS = ['markdown', 'code', 'framework', 'web']

const DOC_EXT    = new Set(['.md'])
const SOURCE_EXT = new Set(['.js', '.ts', '.mjs', '.mts'])

// Output this workspace WROTE is not prose somebody wrote, and reading it is the
// measurement grading its own input — which is already why VOCABULARY.md is out
// of the corpus. There is no single marker, so three are asked: the committed
// snapshots carry `.snapshot.` in the name, `ws:atlas --live` carries a
// generator line and not the name, and THIS COMMAND'S OWN PAGE carries neither
// by design — it is ungated, so it has no generator line to be rechecked by.
// At ~2 MB that page is the largest file in the tree matching a corpus
// extension, and every term on it would be counted a second time.
const GENERATED_FILES = new Set(['repo-terms.html', 'registers.html'])

function isGenerated(rel, raw) {
  return /\.snapshot\./.test(rel)
      || GENERATED_FILES.has(rel)
      || /generated by:/.test(raw.slice(0, 400))
}

function walk(dir, out = []) {
  let entries
  try { entries = readdirSync(dir, { withFileTypes: true }) } catch { return out }

  for (const entry of entries) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) {
      // The skip list names OUTPUT directories, and one of them is a legal
      // source directory name: sierra's compile-time rewriters live in
      // `src/build/`, so skipping `build` everywhere hid `mesa:slot` and every
      // identifier that package declares there.
      if (SKIP_DIRS.has(entry.name) && !/[\\/]src[\\/]/.test(`${path}/`)) continue
      walk(path, out)
      continue
    }
    if (!entry.isFile()) continue
    const dot = entry.name.lastIndexOf('.')
    if (dot < 0) continue
    out.push(path)
  }
  return out
}

// Which package a file belongs to. The bucket is what `spread` counts, so a
// file outside any package still needs one — `root` is a real answer and an
// empty string would silently merge every such file into one.
function ownerOf(root, path) {
  const rel   = relative(root, path)
  const parts = rel.split(sep)
  if (parts[0] === 'packages' && parts.length > 1) return parts[1]
  if (parts.length > 1) return parts[0]
  return 'root'
}

// ─── the prose reader ─────────────────────────────────────────────────────────
//
// Everything a reader would not say out loud comes out first. A term inside a
// code span is an identifier and belongs to the api lens, not the concept one —
// counting it in both is how `createResource` would rank as a concept.

function proseOf(text) {
  return splitFrontmatter(text).body
    .replace(/```[\s\S]*?```/g, ' ')                 // fenced code
    .replace(/~~~[\s\S]*?~~~/g, ' ')
    .replace(/`[^`\n]*`/g, ' ')                      // inline code
    .replace(/<!--[\s\S]*?-->/g, ' ')                // html comments
    .replace(/\]\([^)\s]*\)/g, '] ')                 // link targets, not labels
    .replace(/https?:\/\/\S+/g, ' ')
    .replace(/<[^>]+>/g, ' ')                        // raw html
}

// Mid-sentence capitalization is the signal. A word at a sentence start is
// capitalized by grammar and says nothing; one in the middle was capitalized by
// somebody meaning a Thing. Requiring a lowercase second character drops the
// house style's SHOUTED emphasis, which is not vocabulary either.
//
// Only a lowercase letter, a digit, a comma or a close bracket may precede. A
// dash, colon or semicolon was tried and reverted: this house writes them to
// open a new clause, so the word after one is capitalized by grammar and the
// scan filled with `An`, `Whether` and `For`.
const TERM_RX = /[a-z0-9),]\s+([A-Z][a-z][A-Za-z]*)\b/g

// A pair the prose writes as one thing: a capitalized head and the word after
// it, either capitalized (`Data Realm`) or an ordinary noun (`Gate ladder`).
// Candidates only — what makes a pair a TERM is somebody saying so.
const PAIR_RX = /\b([A-Z][a-z][A-Za-z]*)\s+([A-Z][a-z][A-Za-z]*|[a-z]{3,})\b/g

// A pair whose second half is doing something is a sentence, not a term:
// `Litestone emits`, `Verified against`, `Derived rather`. Participles and
// adverbs are shape; the joiners are a short list because the frequent ones are
// already dropped English.
const JOINERS = new Set([
  'against', 'rather', 'than', 'toward', 'towards', 'via', 'per', 'unless',
  'until', 'though', 'although', 'upon', 'onto', 'within', 'across', 'beyond',
  'despite', 'during', 'whenever', 'wherever', 'whereas', 'therefore', 'instead',
])

function verbish(word) {
  return /(?:ed|ing|ly)$/.test(word) && word === word.toLowerCase()
}

// One drop test for both scans. A plural is dropped with its singular, since
// the fold merges into a HOST row and a dropped word leaves none.
function dropped(word) {
  const lower = word.toLowerCase()
  return DROPPED.has(lower) || DROPPED.has(singularize(lower))
}

// ─── dropped ──────────────────────────────────────────────────────────────────
//
// Ordinary English that reaches the scan because grammar capitalized it, and
// that carries no vocabulary in any class. These are removed BEFORE
// classification rather than classed, because a class is a row somebody has to
// read past and the reason for reading one — a word in the wrong class — cannot
// apply to `the`. The count of what was dropped is reported, so the list can be
// found to be eating a real term rather than only suspected of it.
const DROPPED = new Set([
  'the', 'every', 'an', 'two', 'three', 'one', 'this', 'set', 'everything', 'it',
  'each', 'found', 'not', 'run', 'nothing', 'no', 'add', 'both', 'all', 'these',
  'use', 'that', 'where', 'zero', 'seven', 'four', 'for', 'read', 'enter', 'when',
  'five', 'view', 'what', 'in', 'none', 'if', 'only', 'explore', 'there', 'kept',
  'multi', 'write', 'better', 'same', 'to', 'request', 'out', 'with', 'at', 'new',
  'on', 'they', 'without', 'do', 'eight', 'first', 'some', 'because', 'left', 'or',
  'after', 'before', 'by', 'from', 'is', 'last', 'most', 'once', 'take', 'was',
  'next', 'you', 'here', 'keep', 'and', 'another', 'anything', 'between', 'give', 'how',
  'less', 'let', 'make', 'more', 'nobody', 'of', 'over', 'real', 'right', 'say',
  'second', 'somebody', 'still', 'then', 'those', 'who', 'why',
  // Calendar names. They arrive through cron expressions and date examples, so
  // they are frequent and never vocabulary.
  'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday',
  'january', 'february', 'march', 'april', 'may', 'june', 'july', 'august',
  'september', 'october', 'november', 'december',
  'mon', 'tue', 'tues', 'wed', 'thu', 'thurs', 'fri', 'sat', 'sun',
  'jan', 'feb', 'mar', 'apr', 'jun', 'jul', 'aug', 'sep', 'sept', 'oct', 'nov', 'dec',
  // Generic programming English. Every one reads as a noun and none of them
  // is this framework's: they would be the same words in any repository,
  // which is the test. A word § 2 blesses or forbids is NOT here — dropping
  // a forbidden word takes the drift column with it, and dropping a blessed
  // one hides dead doctrine.
  'action', 'activity', 'append', 'async', 'await', 'batch', 'binary', 'buffer', 'buffers',
  'class', 'cleanup', 'column', 'compile', 'compiled', 'compilation', 'composition', 'constraint', 'constraints',
  'debug', 'delete', 'effect', 'effects', 'expression', 'factory', 'filter', 'flag', 'flags',
  'graph', 'instance', 'integer', 'interface', 'log', 'method', 'module', 'number', 'operation',
  'operations', 'package', 'packages', 'prototype', 'result', 'retry', 'scope', 'section', 'source',
  'static', 'test', 'tests', 'timing', 'type', 'types', 'variable', 'verification', 'version',
  'versions', 'virtual',
  // `data` alone: 19 packages and no meaning anybody could write down. The
  // terms under it are phrases and are named as such — `Data realm`,
  // `Data boundary` — which is what a VOCABULARY.md row can hold and a
  // single word here could not.
  'data',
  // `Writable` is never written alone here: all five uses are the head of
  // `Writable derived`, which is the term and is a VOCABULARY.md row.
  'writable',
])

// ─── classes ──────────────────────────────────────────────────────────────────
//
// `external` is a judgement and is therefore a list somebody maintains. It is
// here rather than in a config file because it is short and because a term
// moving into it should be a diff somebody reads.

const EXTERNAL = new Set([
  // runtimes, tools, browsers
  'Bun', 'Node', 'Deno', 'Vite', 'Rollup', 'Esbuild', 'Chrome', 'Chromium',
  'Firefox', 'Safari', 'Docker', 'Git', 'GitHub', 'Linux', 'Windows', 'Mac',
  'MacOS', 'Ubuntu', 'Alpine', 'Nginx', 'Biome', 'Vitest', 'Jest', 'Playwright',
  'Puppeteer', 'Npm', 'Yarn', 'Pnpm', 'Vscode', 'Oxc', 'Wasm', 'Webpack',
  // languages and platforms
  'Java', 'JavaScript', 'TypeScript', 'Python', 'Ruby', 'Rust', 'Swift', 'Kotlin',
  'Html', 'Css', 'Sql', 'Sqlite', 'Postgres', 'Postgres', 'Mysql', 'Redis',
  // ecosystem projects
  'Prisma', 'React', 'Svelte', 'Solid', 'Vue', 'Angular', 'Next', 'Remix',
  'Astro', 'Wasp', 'Redwood', 'Rails', 'Django', 'Laravel', 'Drupal', 'Tailwind',
  'UnoCSS', 'Uno', 'Mjml', 'Netdata', 'Stripe', 'Slack', 'Outlook', 'Gmail',
  'Caprover', 'CapRover', 'Claude', 'Anthropic', 'Cloudflare',
  'Resend', 'Temporal', 'Frappe', 'GoAccess', 'ZenStack', 'Litestream',
  'Prometheus', 'Documenso', 'Dockerfile', 'OpenAPI', 'Markdown', 'SaaS',
  'AsyncLocalStorage', 'NaN', 'Ada',
  // Place names, which arrive through time-zone examples.
  'Greenwich', 'Auckland', 'London', 'Los', 'Angeles', 'Denver', 'Tokyo', 'DigitalOcean', 'Hetzner', 'Fly', 'Vercel', 'Netlify',
  // specs and protocols people name in prose
  'Http', 'Https', 'Websocket', 'WebSocket', 'Json', 'Yaml', 'Toml', 'Oauth', 'Jwt', 'Smtp',
  'Imap', 'Dns', 'Tls', 'Ssh', 'Cdp', 'Opfs', 'Cors', 'Csp', 'Mcp', 'Lsp', 'Mv',
  'Intl', 'Icu', 'Utc', 'Iso', 'Unicode', 'Ascii',
  // Platform globals. They read as nouns in prose and are somebody else's
  // vocabulary, so they belong beside the tools rather than beside Resource.
  'Map', 'Set', 'String', 'Number', 'Boolean', 'Object', 'Array', 'Promise',
  'Symbol', 'Proxy', 'Error', 'Date', 'RegExp', 'WeakMap', 'Blob', 'Buffer',
  'Request', 'Response', 'Headers', 'Worker', 'Element', 'Document',
  'TypeError', 'SyntaxError', 'RangeError',
  // databases, stores and search engines
  'MySQL', 'PostgreSQL', 'MariaDB', 'MongoDB', 'CouchDB', 'DynamoDB', 'DuckDB', 'Snowflake',
  'PlanetScale', 'Supabase', 'Neon', 'Turso', 'Dolt', 'Noms', 'Bitcask', 'Elasticsearch',
  'Meilisearch', 'Typesense', 'Algolia', 'SpatiaLite', 'PostGIS', 'GiST', 'Geopoly', 'PostgREST',
  'Hasura', 'Convex', 'Kysely', 'Drizzle', 'Ecto', 'Eloquent', 'Hibernate', 'Zod',
  'Directus', 'MinIO', 'Backblaze',
  // platforms, hosts and deployment tools
  'Heroku', 'Railway', 'Coolify', 'Dokku', 'Dokploy', 'Kamal', 'Capistrano', 'Porter',
  'Kubernetes', 'ConfigMap', 'Helm', 'Argo', 'Nomad', 'Swarm', 'Terraform', 'NixOS',
  'Nix', 'Debian', 'Homebrew', 'BuildKit', 'Procfile', 'Foreman', 'Overmind', 'Turborepo',
  'Nx', 'Lambda', 'Bedrock', 'Forgejo', 'Tilt',
  // frameworks, libraries and runtimes somebody else ships
  'SvelteKit', 'SolidJS', 'NestJS', 'AdonisJS', 'RedwoodJS', 'FeathersJS', 'Qwik', 'Nuxt',
  'Gatsby', 'Eleventy', 'Jekyll', 'Hugo', 'Phoenix', 'LiveView', 'Livewire', 'Octane',
  'Jetstream', 'Breeze', 'Cashier', 'Socialite', 'Symfony', 'Spring', 'Scala', 'Elixir',
  'Erlang', 'Zig', 'Blazor', 'Electron', 'Capacitor', 'Tauri', 'Relay', 'Apollo',
  'GraphQL', 'Radix', 'Bulma', 'Bootstrap', 'Material', 'Polaris', 'Handlebars', 'Liquid',
  'Sass', 'Babel', 'Pillow', 'Leaflet', 'CodeMirror', 'Storybook', 'Prettier', 'Capybara',
  'Nightwatch', 'Wallaby', 'Schemathesis', 'Sidekiq', 'Oban', 'Silk', 'Ink', 'Malina',
  'Paraglide', 'Noda', 'Turndown', 'TurndownService', 'ThumbHash', 'Emmet', 'Quasar', 'Routify',
  'Remult', 'Encore', 'Pylon', 'Solidus', 'InvenTree', 'Fineract', 'MediaWiki', 'Moodle',
  'WordPress', 'Redmine', 'Ash', 'AshAdmin', 'AshAi', 'Rasa', 'Sonar', 'DefectDojo',
  'SpiceDB', 'Zanzibar', 'Keto', 'Keycloak', 'Okta', 'Entra', 'Clerk', 'OpenID',
  'Xvfb', 'WebKitGTK', 'JavaScriptCore', 'Caddy', 'Apache', 'Vixie', 'Unix', 'Seti',
  // services, vendors and companies
  'Shopify', 'Salesforce', 'ServiceNow', 'QuickBooks', 'HubSpot', 'Zapier', 'Airtable', 'Notion',
  'Calendly', 'Discord', 'Twitter', 'Facebook', 'Microsoft', 'Google', 'Apple', 'Android',
  'Macbook', 'PayPal', 'Twilio', 'SendGrid', 'Postmark', 'Mailgun', 'Postal', 'Shippo',
  'Clearbit', 'Atlassian', 'Atlan', 'MuleSoft', 'Semperis', 'Connecteam', 'HoneyBook', 'Housecall',
  'Productboard', 'Canny', 'AnnounceKit', 'Headway', 'Quickhunt', 'Inkeep', 'Nango', 'Unleash',
  'Infisical', 'OpenAI', 'ChatGPT', 'Ollama', 'Dialogflow', 'Laracasts', 'CodePen', 'Sketch',
  'Figma', 'Excel', 'Lago', 'OpenMRP', 'PowerSync', 'Sentry', 'PostHog', 'Plausible',
  'Umami', 'Matomo', 'Grafana', 'Loki', 'Tempo', 'Opsgenie', 'PagerDuty', 'NetBird',
  'Mastodon', 'Telescope', 'Nova', 'Pinpoint', 'CloudTrail', 'Kafka', 'Jumpstart', 'Iconify',
  'Nominatim', 'GeoBlacklight', 'GeoDjango', 'Zot', 'Pico', 'Sampler', 'Crowd',
  // web platform and language APIs
  'IndexedDB', 'IntersectionObserver', 'MutationObserver', 'BroadcastChannel', 'AbortController', 'ReadableStream', 'ShadowRoot', 'DataTransfer',
  'NodeList', 'FileList', 'TypedArray', 'WeakSet', 'WebCrypto', 'WebP', 'Brotli', 'ActionCable',
  'CommonJS', 'CommonMark', 'OpenTelemetry', 'OpenMetrics', 'OpenSpec', 'PlainDateTime', 'ZonedDateTime', 'LatLng',
  // models and papers, which arrive through examples and prior art
  'Opus', 'Sonnet', 'Haiku', 'Levenshtein', 'Euclidean', 'Hilbert', 'Kahan', 'Fisher',
  'Fowler', 'Rainsberger', 'Barker',
  // people, who arrive through citations and example rows
  'Kent', 'Matt', 'Sam', 'Joe', 'Danny', 'Alex', 'Bob', 'Ann',
  'Richard', 'Robin', 'Smith', 'Mann', 'Brown',
  // places and peoples, which arrive through time zones and example data
  'Berlin', 'Boston', 'Helsinki', 'Nuremberg', 'Falkenstein', 'Kolkata', 'Atlantic', 'Europe',
  'Earth', 'Zimbabwe', 'Paraguay', 'Iraqi', 'Austrian', 'Spanish', 'Slavic', 'Latin',
  'British', 'Guinea', 'Gulf',
  // toolchain and format names that read as ordinary nouns
  'Cargo', 'Cedar', 'Dusk', 'EditorConfig', 'Fabric', 'Orthicon', 'Office',
  // frameworks this repo measures itself against
  'Feathers', 'Meteor', 'Blitz', 'Adonis', 'Nest', 'Express', 'Fastify', 'Hono',
])

// Capitalized English that carries no concept. Kept as a class rather than a
// delete for the same reason as everything else here.
const COMMON = new Set(
  [
    'The',
    'This',
    'That',
    'These',
    'Those',
    'There',
    'Then',
    'Than',
    'And',
    'But',
    'Or',
    'Not',
    'If',
    'It',
    'Its',
    'We',
    'You',
    'They',
    'One',
    'Two',
    'Three',
    'Four',
    'Five',
    'Six',
    'Seven',
    'Eight',
    'Nine',
    'Ten',
    'Every',
    'Each',
    'Any',
    'All',
    'Both',
    'Some',
    'None',
    'Never',
    'Always',
    'Where',
    'When',
    'What',
    'Which',
    'Who',
    'Why',
    'How',
    'Because',
    'Since',
    'While',
    'After',
    'Before',
    'Once',
    'Only',
    'Also',
    'Still',
    'Yet',
    'Just',
    'Now',
    'Here',
    'Read',
    'Run',
    'Use',
    'Add',
    'Write',
    'Keep',
    'Make',
    'Take',
    'Give',
    'Left',
    'Right',
    'Same',
    'Other',
    'Another',
    'Nothing',
    'Something',
    'Anything',
    'Everything',
    'Somebody',
    'Nobody',
    'Everybody',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
    'English',
    'An',
    'As',
    'At',
    'By',
    'For',
    'From',
    'In',
    'Into',
    'Of',
    'On',
    'Out',
    'Over',
    'To',
    'Up',
    'With',
    'Without',
    'No',
    'Yes',
    'Found',
    'Whether',
    'Open',
    'Close',
    'Escape',
    'Above',
    'Below',
    'Beside',
    'Between',
    'Being',
    'Been',
    'Was',
    'Were',
    'Had',
    'Has',
    'Have',
    'Will',
    'Would',
    'Should',
    'Could',
    'Must',
    'Can',
    'Did',
    'Does',
    'Do',
    'Is',
    'Are',
    'Am',
    'Be',
    'Let',
    'Say',
    'Said',
    'Says',
    'Most',
    'More',
    'Less',
    'Least',
    'Best',
    'Worse',
    'Worst',
    'Good',
    'Bad',
    'New',
    'Old',
    'First',
    'Second',
    'Third',
    'Thirteen',
    'Vision',
    'Last',
    'Next',
    'Real',
    'Together',
    'Moved',
    'Kept',
    'Measured',
    'Loosening',
    'Correctness',
    'Ruled',
    'Compressed',
    'Zero',
    'Better',
    'Standard',
    'Conventions',
    'Explore',
    'Multi',
    'American',
    'Ctrl',
    'Enter',
    // Common words:
    'Against',
    'Already',
    'Ambition',
    'Asked',
    'Back',
    'Beyond',
    'Cannot',
    'Center',
    'Clean',
    'Common',
    'Complete',
    'During',
    'Even',
    'Exactly',
    'Facts',
    'Follow',
    'Full',
    'Going',
    'Half',
    'Hard',
    'Hello',
    'Honest',
    'Inside',
    'Know',
    'Learn',
    'Mental',
    'Multiple',
    'Neither',
    'Newest',
    'Normal',
    'Nowhere',
    'Outside',
    'Part',
    'Plain',
    'Previous',
    'Quick',
    'Roughly',
    'Self',
    'Several',
    'So',
    'Soft',
    'Started',
    'Stop',
    'Temporary',
    'Today',
    'Top',
    'Twice',
    'Under',
    'Unknown',
    'Unlike',
    'Useful',
    'Whatever',
    'White',
    'Working',
    'Your',
    // Ruled ordinary English: a Plugin Junction ships is a Plugin (`FJS-D394`),
    // and a CRUD verb is a method name, not a concept.
    'Battery',
    'Batteries',
    'Create',
    // Ruled not terms (`FJS-D633`): an app's `Account` is usually an
    // organization, so the framework saying it for a login would contradict
    // the model a reader has open, and nothing in the tree is a Party.
    'Account',
    'Accounts',
    'Party'
  ].filter((w) => !DROPPED.has(w.toLowerCase()))
)

// ─── ARCHITECT.md § 2, the authored half ──────────────────────────────────────
//
// The Use/Not table is the doctrine and it is read, never restated. A term's
// status against it is the whole audit: blessed-and-unused is dead doctrine,
// used-and-unnamed is vocabulary nobody defined, and a forbidden word in live
// prose is the drift § 2 exists to prevent.

// The § 2 section, cut out at the same boundaries `architectVocabulary` reads
// it by — the heading and the next `## `.
function withoutSectionTwo(text) {
  const parts = text.split(/^## 2\. /m)
  if (parts.length < 2) return text
  const rest = parts[1].split(/^## /m)
  return `${parts[0]}${rest.slice(1).map(s => `## ${s}`).join('')}`
}

export function architectVocabulary(root) {
  const file = join(root, 'ARCHITECT.md')
  const out  = { blessed: [], forbidden: [], clarified: [], notYetNamed: [], found: false }
  if (!existsSync(file)) return out

  const text    = readFileSync(file, 'utf8')
  const section = text.split(/^## 2\. /m)[1]
  if (!section) return out
  out.found = true

  const body       = section.split(/^## /m)[0]
  const notNamedAt = body.indexOf('### Not yet named')
  const head       = notNamedAt < 0 ? body : body.slice(0, notNamedAt)
  const tail       = notNamedAt < 0 ? ''   : body.slice(notNamedAt)

  for (const line of head.split('\n')) {
    const row = line.match(/^\|\s*\*\*([^*]+)\*\*\s*\|([^|]*)\|/)
    if (row) {
      out.blessed.push(row[1].trim())
      for (const alt of row[2].split(',')) {
        const word = alt.trim().replace(/\s*\(.*$/, '')
        if (word && !/^\s*$/.test(word)) out.forbidden.push(word)
      }
      continue
    }
    const bullet = line.match(/^-\s+\*\*([^*]+)\*\*/)
    if (bullet) out.clarified.push(bullet[1].replace(/[`.,]/g, '').trim())
  }

  for (const line of tail.split('\n')) {
    const bullet = line.match(/^-\s+\*\*([^*]+)\*\*/)
    if (bullet) out.notYetNamed.push(bullet[1].replace(/[`.,]/g, '').trim())
  }

  return out
}

// ─── VOCABULARY.md, the authored half ─────────────────────────────────────────
//
// The words somebody has DEFINED, which no scan can produce. Read here and
// joined to the measurements, so a term is defined in one place and counted in
// another. A word that is not a term of this framework is not labelled there —
// it is excluded above, where the classifier can act on it.

export function authoredVocabulary(root) {
  const file = join(root, 'VOCABULARY.md')
  const out  = new Map()
  if (!existsSync(file)) return out

  // Columns are found by the header row's names, so a column added to the
  // file does not shift `means` into `note` for every row below it.
  let cols = null
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    if (!/^\|.*\|\s*$/.test(line)) { cols = null; continue }
    const cells = line.trim().slice(1, -1).split('|').map(c => c.trim())
    if (cells[0] === 'Term') { cols = Object.fromEntries(cells.map((c, i) => [c.toLowerCase(), i])); continue }
    if (!cols) continue
    const at     = (name) => cols[name] == null ? '' : (cells[cols[name]] ?? '')
    const term   = at('term')
    const status = at('status').replace(/`/g, '')
    // A row is a TERM only when its status is one of the four, which is the
    // same test the file asks a reader to apply.
    if (!['blessed', 'refused', 'alias', 'open'].includes(status)) continue
    out.set(term.toLowerCase(), { term, status, home: at('home'), under: at('under'), means: at('means'), note: at('note') })
  }
  return out
}

// ─── a package's own vocabulary ─────────────────────────────────────────────────
//
// `VOCABULARY.md` is the root vocabulary and it is not the only one. A package
// that defines its own terms well enough to CHECK them has named them, and
// reporting those terms as named nowhere is the measurement being wrong about
// the tree — @frontierjs/css defines 56 and every one of them read `unnamed`.
//
// The vocabulary is READ, never copied here. A copy is 56 rows maintained by hand
// and stale the first time css renames one, which is what the root file already
// says about itself: defined in one place, measured in another.
//
// **Named rather than discovered.** A `*/vocabulary.json` glob would adopt any
// file with that name; declaring a term is a claim somebody makes, which is the
// same reason `phrases` is scanned from the two authored halves instead of
// found. One row here is what the next package costs.
const PACKAGE_REGISTERS = [
  { owner: 'css', file: 'packages/css/vocabulary.json', read: readCssVocabulary },
]

// The generated half of `packages/css/vocabulary.js`, which is a classic script
// by necessity and says so in its own header. `build-vocabulary.js` writes the
// JSON and `test/specs/vocabulary.spec.js` grades both against the real CSSOM,
// so what is read here is already held to the stylesheet.
//
// Two shapes, because css names two kinds of word. `terms` is the vocabulary —
// one element and one meaning each. `notATerm`'s KEYS are the axes it declares
// a word can be instead of a term, and those names are vocabulary themselves:
// Invariant 13 is written in them (*a tone, and a treatment*), and `Treatment`
// was the most-used unnamed concept in the package before this read it.
function readCssVocabulary(text) {
  const out = new Map()
  const doc = JSON.parse(text)
  // A tier is css's answer to *what is this inside*, which is the root file's
  // `Under` column; reading it here is what keeps the UI rows' container half
  // from being authored twice and drifting the first time css re-tiers a term.
  for (const t of doc.terms ?? []) {
    if (!t?.term) continue
    out.set(t.term.toLowerCase(), {
      term:  t.term,
      means: t.meaning ?? '',
      note:  t.element ?? '',
      home:  'UI',
      under: t.tier ? `${t.tier} tier` : '',
    })
  }
  // After the terms, so `Heading` keeps the definition rather than the axis —
  // it is both a term and the name of the group css files its own h1–h6 under.
  for (const axis of Object.keys(doc.notATerm ?? {})) {
    const term = axis.replace(/^./, c => c.toUpperCase())
    if (out.has(term.toLowerCase())) continue
    out.set(term.toLowerCase(), {
      term,
      means: `An axis a class can be on instead of being a term — ${(doc.notATerm[axis] ?? []).length} of them`,
      note:  'axis',
    })
  }
  return out
}

// The root row wins, and a package's `Under` fills only a UI row that left
// its own blank. Home is the test for *same sense*: `Table` is a Data row and
// css's `<table>` is not its parent's child, `Surface` is a Framework row and
// css's Base shape is a different word spelled the same, and an authored
// `Under` (Switch under Select task) is a placement css cannot see.
export function placed(root, pkg) {
  if (!root) return pkg ?? null
  if (!pkg || root.under || root.home !== pkg.home || !pkg.under) return root
  return { ...root, under: pkg.under, underFrom: pkg.owner }
}

// Every package vocabulary, joined. A malformed or missing one is SKIPPED rather
// than thrown: this command is exploratory and ungated on purpose (`FJS-1211`),
// so it has to keep running while a vocabulary is being written. What is not
// allowed is skipping quietly — the count each one contributed is carried out
// to the presentation, because a vocabulary that stopped resolving returns every
// one of its terms to `unnamed`, which reads exactly like a package that never
// named anything.
export function packageVocabularies(root) {
  const terms = new Map()
  const read  = []
  for (const reg of PACKAGE_REGISTERS) {
    const file = join(root, reg.file)
    let rows = null
    try {
      rows = existsSync(file) ? reg.read(readFileSync(file, 'utf8')) : null
    } catch {
      rows = null
    }
    read.push({ owner: reg.owner, file: reg.file, terms: rows ? rows.size : 0, found: !!rows })
    if (!rows) continue
    for (const [key, row] of rows) {
      const entry = { ...row, status: 'blessed', source: reg.file, owner: reg.owner }
      if (!terms.has(key)) terms.set(key, entry)
      // The corpus folds a plural into its singular when both were seen, so the
      // row is `Step` where the vocabulary says `Steps` and an exact lookup misses
      // — which is every plural term css ships (`Steps`, `Tabs`, `Facts`) and no
      // singular one, so the gap was invisible from the terms that worked. The
      // alias is the fold's own function, asked here rather than re-spelled.
      const singular = singularize(key)
      if (singular !== key && !terms.has(singular)) terms.set(singular, entry)
    }
  }
  return { terms, read }
}

// ─── the declared languages ───────────────────────────────────────────────────
//
// `.lite` is read from its own committed catalog, which asserts its completeness
// against the parser. Mesa has no catalog, so its words are GREPPED and say so —
// a grep finds `mesa:frobnicate` in a fixture and cannot tell it from a real
// block. The confidence is carried per row rather than averaged away, because
// this gap is the thing FJS-1211 is filed about.

function liteWords(root) {
  const file = join(root, 'packages/litestone/catalog.snapshot.md')
  if (!existsSync(file)) return []
  const out = []
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const cell = line.match(/^\|\s*`([^`]+)`/)
    if (cell) out.push({ word: cell[1], source: 'catalog.snapshot.md', confidence: 'declared', owner: 'litestone' })
  }
  return out
}

function mesaWords(root) {
  const declared = mesaElements(root)
  const dirs = ['packages/mesa/src', 'packages/sierra/src']
    .map(rel => join(root, rel)).filter(existsSync)
  if (!dirs.length) return []

  // Usage counts come from the source; the LIST does not. A grep over prose
  // answers `mesa:frobnicate` — the compiler's own example of a name that does
  // not exist — and `mesa:line`, which is a source location. A vocabulary that
  // holds its own counter-example is worse than one that is short.
  const seen = new Map()
  for (const dir of dirs) {
    for (const path of walk(dir)) {
      const dot = path.lastIndexOf('.')
      if (!SOURCE_EXT.has(path.slice(dot))) continue
      for (const hit of readFileSync(path, 'utf8').matchAll(/\bmesa:([a-zA-Z][a-zA-Z0-9]*)/g)) {
        seen.set(hit[1], (seen.get(hit[1]) ?? 0) + 1)
      }
    }
  }

  if (!declared.length) {
    // Both declarations moved or were renamed. Answering the grep is the honest
    // fallback and `grepped` on every row is what says so on the page — a
    // silently empty language tab would read as Mesa having no words at all.
    return [...seen].map(([name, count]) => ({
      word: `mesa:${name}`, count, source: 'packages/mesa/src', confidence: 'grepped', owner: 'mesa',
    }))
  }

  return declared.map(d => ({
    word: `mesa:${d.name}`,
    count: seen.get(d.name) ?? 0,
    source: d.source,
    confidence: 'declared',
    owner: d.owner,
  }))
}

// The `mesa:` namespace has TWO owners and a grep cannot tell you that.
// `MESA_ELEMENTS` in mesa's compiler is what the compiler knows and is the same
// array its typo error prints; `mesa:slot` is Sierra's, rewritten away before
// the compiler ever sees the tag. Both are read as TEXT rather than imported:
// the cli depends on neither package, and importing a compiler to ask it for
// nine strings would make it depend on both.
function mesaElements(root) {
  const out = []

  const compiler = join(root, 'packages/mesa/src/compiler.js')
  if (existsSync(compiler)) {
    const match = readFileSync(compiler, 'utf8').match(/export const MESA_ELEMENTS = \[([^\]]*)\]/)
    for (const m of match?.[1].matchAll(/'([a-zA-Z][a-zA-Z0-9]*)'/g) ?? []) {
      out.push({ name: m[1], owner: 'mesa', source: 'packages/mesa/src/compiler.js' })
    }
  }

  const slots = join(root, 'packages/sierra/src/build/slot-rewrite.js')
  if (existsSync(slots)) {
    const match = readFileSync(slots, 'utf8').match(/export const MESA_SLOT_TAG = 'mesa:([a-zA-Z][a-zA-Z0-9]*)'/)
    if (match) out.push({ name: match[1], owner: 'sierra', source: 'packages/sierra/src/build/slot-rewrite.js' })
  }

  return out
}

// ─── the api lens ─────────────────────────────────────────────────────────────
//
// Declaration sites only. A re-export would count the same name twice and make
// spread a measure of how many barrels a package has.

const EXPORT_RX = /^export\s+(?:async\s+)?(?:function\*?|const|let|class)\s+([A-Za-z_$][\w$]*)/gm

function apiTerms(root, packages) {
  const rows = new Map()

  for (const pkg of packages) {
    const dir = join(root, 'packages', pkg, 'src')
    const entries = entryTargets(join(root, 'packages', pkg))

    // `@frontierjs/ui` has no `src/` at all — its components ARE the package —
    // so the walk below must not be what decides whether the package is read.
    for (const path of existsSync(dir) ? walk(dir) : []) {
      const dot = path.lastIndexOf('.')
      if (!SOURCE_EXT.has(path.slice(dot))) continue
      if (/\.(test|spec)\./.test(path)) continue

      const rel  = relative(root, path)
      const text = readFileSync(path, 'utf8')
      for (const hit of text.matchAll(EXPORT_RX)) {
        const name = hit[1]
        const row  = rows.get(name) ?? { term: name, count: 0, owners: new Set(), files: [], entry: false, byOwner: new Map() }
        row.count += 1
        row.owners.add(pkg)
        row.byOwner.set(pkg, (row.byOwner.get(pkg) ?? 0) + 1)
        if (row.files.length < 12) row.files.push(rel)
        if (entries.has(rel)) row.entry = true
        rows.set(name, row)
      }
    }

    // A Mesa component is an identifier that is never written as an export: the
    // FILE is the declaration and the caller types the basename. Without this
    // pass `EmptyState`, `StatCard` and `FilterBar` reach the prose scan with
    // nothing to say they are code, and land in the concepts table as though
    // somebody had coined them.
    for (const path of walk(join(root, 'packages', pkg))) {
      if (!path.endsWith('.mesa')) continue
      if (/[\\/](test|tests|fixtures|example)[\\/]/.test(path)) continue
      const name = path.slice(path.lastIndexOf('/') + 1, -'.mesa'.length)
      if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) continue
      const rel = relative(root, path)
      const row = rows.get(name) ?? { term: name, count: 0, owners: new Set(), files: [], entry: false, byOwner: new Map() }
      row.count += 1
      row.owners.add(pkg)
      row.byOwner.set(pkg, (row.byOwner.get(pkg) ?? 0) + 1)
      if (row.files.length < 12) row.files.push(rel)
      rows.set(name, row)
    }
  }

  return [...rows.values()].map(finish)
}

// Every path a package's `exports`/`main`/`bin` map points at. A name declared
// in one of those files is reachable by an app; one declared anywhere else is
// this repo talking to itself, and the two should never be counted as one
// vocabulary.
function entryTargets(pkgDir) {
  const out  = new Set()
  const file = join(pkgDir, 'package.json')
  if (!existsSync(file)) return out

  let pkg
  try { pkg = JSON.parse(readFileSync(file, 'utf8')) } catch { return out }

  const add = (value) => {
    if (typeof value === 'string') {
      const path = join(pkgDir, value.replace(/^\.\//, ''))
      out.add(relative(pkgDir.split(`${sep}packages${sep}`)[0], path))
      return
    }
    if (value && typeof value === 'object') for (const v of Object.values(value)) add(v)
  }

  add(pkg.exports)
  add(pkg.main)
  add(pkg.module)
  add(pkg.bin)
  return out
}

// ─── the model ────────────────────────────────────────────────────────────────

function finish(row) {
  const owners = [...row.owners].sort()
  // A plain object, because the page recomputes spread and count from it when a
  // source is switched off — the model cannot know which sources a reader wants
  // to stop looking at, and rescanning per answer is the thing a page is for.
  const byOwner = Object.fromEntries([...(row.byOwner ?? new Map())].sort((a, b) => b[1] - a[1]))
  // The JOINT breakdown, `owner|kind`. Two separate tallies cannot answer the
  // page's question: switching markdown off has to recompute SPREAD as well as
  // count, and how many packages are left is only decidable from the pair.
  const byCell  = Object.fromEntries([...(row.byCell ?? new Map())].sort((a, b) => b[1] - a[1]))
  const byKind  = {}
  for (const [cell, n] of Object.entries(byCell)) {
    const kind = cell.slice(cell.lastIndexOf('|') + 1)
    byKind[kind] = (byKind[kind] ?? 0) + n
  }
  return { ...row, owners, byOwner, byCell, byKind, spread: owners.length }
}

export function collectTerms({ root }) {
  const architect = architectVocabulary(root)
  const authored  = authoredVocabulary(root)
  const pkgVocab = packageVocabularies(root)
  const blessed   = new Set(architect.blessed.map(w => w.toLowerCase()))
  const clarified = new Set(architect.clarified.map(w => w.toLowerCase()))
  const unnamed   = new Set(architect.notYetNamed.map(w => w.toLowerCase()))

  const packages = existsSync(join(root, 'packages'))
    ? readdirSync(join(root, 'packages'), { withFileTypes: true })
        .filter(e => e.isDirectory() && !SKIP_DIRS.has(e.name)).map(e => e.name)
    : []

  // A package's own name is vocabulary, but it is a NAME — it teaches you what
  // to import, never what a word means. Derived rather than listed so a new
  // package classifies itself.
  const product = new Set(packages.map(p => p[0].toUpperCase() + p.slice(1)))
  product.add('Frontier'); product.add('FrontierJS'); product.add('Fli')

  const language = new Map()
  for (const row of liteWords(root)) language.set(row.word.toLowerCase(), { ...row, lens: 'lite' })
  for (const row of mesaWords(root)) language.set(row.word.toLowerCase(), { ...row, lens: 'mesa' })

  // ── prose pass ──
  //
  // Two things are counted in one read of each file. A second pass per term was
  // tried and is what made this slow: 52 forbidden words over 737 documents is
  // 38,000 reads for an answer the first pass already holds.
  const concepts = new Map()
  const droppedWords = new Map()
  const docs     = []

  // A term can be more than one word — `Data realm` is vocabulary where `data`
  // alone is too generic to be any. Both authored halves may name one: § 2's
  // `Gate ladder` and `Chain of Responsibility`, and any VOCABULARY.md row with
  // a space in it. They are SCANNED rather than discovered, because a phrase is
  // a claim somebody makes; what the scan does on its own is propose
  // candidates, below.
  const phrases = new Map([...new Set([
    ...architect.blessed.filter(w => w.includes(' ')),
    ...[...authored.values()].map(r => r.term).filter(w => w.includes(' ')),
  ])].map(w => [w, { term: w, count: 0, owners: new Set(), byOwner: new Map(), byCell: new Map(), files: new Map() }]))

  // Every adjacent pair the prose actually writes, so a phrase nobody has named
  // can be FOUND rather than thought of. Both halves must survive the drop
  // list, which is what keeps `the Data` and `Data is` out of it.
  const pairs = new Map()

  const byKind = Object.fromEntries(KINDS.map(k => [k, 0]))

  for (const path of walk(root)) {
    const dot  = path.lastIndexOf('.')
    const kind = KIND_BY_EXT.get(path.slice(dot))
    if (!kind) continue
    // The authored vocabulary is a list OF terms, not prose that uses them —
    // counting it would let a word gain spread by being labelled, which is the
    // measurement grading its own input.
    const rel = relative(root, path)
    if (rel === 'VOCABULARY.md') continue

    const raw = readFileSync(path, 'utf8')
    if (isGenerated(rel, raw)) continue

    docs.push(rel)
    byKind[kind] += 1
    const owner = ownerOf(root, path)
    const cell  = `${owner}|${kind}`
    // § 2 is the doctrine's own list OF terms, and a phrase is matched as
    // plain text, so leaving it in lets `Gate ladder` gain a use by being
    // blessed — the same measurement-grades-its-own-input that keeps
    // VOCABULARY.md out of the corpus entirely. The rest of ARCHITECT.md is
    // ordinary prose and stays.
    //
    // `proseOf` strips what a MARKDOWN reader would not say out loud. A source
    // file has no such layer — it is read whole, which is the trade the kind
    // exists to let a reader undo.
    const text = kind === 'markdown'
      ? proseOf(rel === 'ARCHITECT.md' ? withoutSectionTwo(raw) : raw)
      : raw

    for (const [word, phrase] of phrases) {
      const hits = text.match(new RegExp(`\\b${word.replace(/\s+/g, '\\s+')}\\b`, 'gi'))
      if (!hits) continue
      phrase.count += hits.length
      phrase.owners.add(owner)
      phrase.byOwner.set(owner, (phrase.byOwner.get(owner) ?? 0) + hits.length)
      phrase.byCell.set(cell, (phrase.byCell.get(cell) ?? 0) + hits.length)
      phrase.files.set(rel, (phrase.files.get(rel) ?? 0) + hits.length)
    }

    for (const hit of text.matchAll(PAIR_RX)) {
      const head = hit[1]
      const tail = hit[2]
      if (dropped(head) || dropped(tail)) continue
      if (COMMON.has(head) || COMMON.has(tail.replace(/^./, c => c.toUpperCase()))) continue
      if (verbish(tail) || JOINERS.has(tail.toLowerCase())) continue
      const pair = `${head} ${tail}`
      const row  = pairs.get(pair) ?? { term: pair, count: 0, owners: new Set() }
      row.count += 1
      row.owners.add(owner)
      pairs.set(pair, row)
    }

    for (const hit of text.matchAll(TERM_RX)) {
      const term = hit[1]
      // A plural is dropped with its singular. The fold below cannot do it:
      // it merges into a HOST row, and a dropped word leaves none, so `Views`
      // and `Requests` would survive as terms of their own.
      const lower = term.toLowerCase()
      if (dropped(term)) {
        droppedWords.set(term, (droppedWords.get(term) ?? 0) + 1)
        continue
      }
      const row  = concepts.get(term) ?? { term, count: 0, owners: new Set(), files: new Map(), byOwner: new Map(), byCell: new Map() }
      row.count += 1
      row.owners.add(owner)
      row.byOwner.set(owner, (row.byOwner.get(owner) ?? 0) + 1)
      row.byCell.set(cell, (row.byCell.get(cell) ?? 0) + 1)
      row.files.set(rel, (row.files.get(rel) ?? 0) + 1)
      concepts.set(term, row)
    }
  }

  // ── plurals fold into their singular ──
  //
  // `Users`, `Resources` and `Releases` are not separate vocabulary and are not
  // noise either, so neither keeping nor excluding them is right. A plural folds
  // only when the SINGULAR was also seen: `Steps` merges into `Step`, while a
  // word that merely ends in an s and stands alone is left exactly as written.
  for (const [term, row] of [...concepts]) {
    const singular = singularize(term)
    if (singular === term) continue
    const host = concepts.get(singular)
    if (!host) continue
    host.count += row.count
    for (const owner of row.owners) host.owners.add(owner)
    for (const [owner, n] of row.byOwner) host.byOwner.set(owner, (host.byOwner.get(owner) ?? 0) + n)
    for (const [cell,  n] of row.byCell)  host.byCell.set(cell,   (host.byCell.get(cell)  ?? 0) + n)
    for (const [file, n] of row.files) host.files.set(file, (host.files.get(file) ?? 0) + n)
    concepts.delete(term)
  }

  // A named phrase is a term and belongs in the same table as the words. It
  // joins AFTER the fold, which is a rule about a trailing s on one word.
  for (const phrase of phrases.values()) {
    if (!phrase.count) continue
    concepts.set(phrase.term, phrase)
  }

  const api = apiTerms(root, packages)
    .sort((a, b) => b.spread - a.spread || b.count - a.count || a.term.localeCompare(b.term))

  // An identifier is not a concept somebody coined, and a compound is how you
  // tell: `EmptyState` is the component a screen mounts, while `Empty state` is
  // the condition it handles, and only the second is vocabulary. A one-word
  // identifier is left alone — `Plugin`, `Channel` and `Store` are English this
  // framework also happens to export, and § 2 rules two of them.
  const declared = new Set(api.map(r => r.term))
  const compound = term => /[a-z][A-Z]/.test(term)

  const conceptRows = [...concepts.values()].map((row) => {
    const lower = row.term.toLowerCase()
    const klass = row.term.includes(' ')
      ? 'concept'
      : language.has(lower)
      ? 'language'
      : declared.has(row.term) &&
        compound(row.term) &&
        !blessed.has(lower) &&
        !authored.has(lower)
      ? 'api'
      : product.has(row.term)
      ? 'product'
      : EXTERNAL.has(row.term)
      ? 'external'
      : COMMON.has(row.term)
      ? 'common'
      : 'concept'
    // § 2 is the doctrine and outranks the file, which is what the file says
    // about itself: where the two disagree, VOCABULARY.md is the stale one.
    // A package vocabulary is one rung below both, which is §VII's own ladder —
    // invariant, ruling, map, package document — so a word the root file and a
    // package both name is the root file's, and nothing here can widen a term
    // the doctrine already ruled on.
    const label = placed(authored.get(lower), pkgVocab.terms.get(lower))
    const status = blessed.has(lower)
      ? 'blessed'
      : clarified.has(lower)
      ? 'clarified'
      : unnamed.has(lower)
      ? 'not-yet-named'
      : label
      ? label.status
      : 'unnamed'
    const files = [...row.files]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 12)
      .map(([file, count]) => ({ file, count }))
    return finish({ ...row, class: klass, status, files, label })
  }).sort((a, b) => b.spread - a.spread || b.count - a.count || a.term.localeCompare(b.term))

  // ── the forbidden column ──
  //
  // Counted as a TERM, never as a word. A first cut counted every occurrence
  // case-insensitively and reported `table` 2,490 times — markdown tables — and
  // `service`, `state` and `build` in the thousands, which is English and not
  // drift. What § 2 forbids is using the word for the CONCEPT, and this house
  // capitalizes a concept mid-sentence, so that is the only occurrence worth
  // reporting. The lowercase uses are real and are not decidable from here.
  // A word can sit in both columns of § 2 — `Channel` is blessed for a broadcast
  // set and refused for a delivery medium, `Hook` is blessed for the tier that
  // can halt and refused for the two that cannot. The table forbids a SENSE and
  // this scan sees a spelling, so a word § 2 also blesses is not evidence of
  // anything and is left out rather than reported as drift.
  const byTerm = new Map(conceptRows.map(r => [r.term.toLowerCase(), r]))

  // The audit's counts are PROSE counts. Every question in it is about the
  // authored vocabularies, which are prose, and the widened corpus moves all of
  // them at once with nothing saying so — measured on the first run over code:
  // `unlabelled` went 0 → 123, dead doctrine 4 → 0 (a blessed word is never
  // rare once identifiers count), and the forbidden column 18 → 28.
  //
  // A phrase row reaches here before `finish` has run on it, so its breakdown is
  // still a Map. Both shapes are taken rather than converted at the call sites,
  // because a phrase whose count is 0 never enters `concepts` at all and the
  // caller genuinely has the raw row in hand.
  const cellsOf = (row) => {
    const b = row?.byCell
    return b instanceof Map ? [...b] : Object.entries(b ?? {})
  }
  const prose = (row) => {
    let n = 0
    for (const [cell, hits] of cellsOf(row)) if (cell.endsWith('|markdown')) n += hits
    return n
  }
  const proseSpread = (row) => {
    const owners = new Set()
    for (const [cell, hits] of cellsOf(row))
      if (hits > 0 && cell.endsWith('|markdown')) owners.add(cell.slice(0, cell.lastIndexOf('|')))
    return owners.size
  }

  const forbidden = [...new Set(architect.forbidden.map(w => w.toLowerCase()))]
    .filter(w => !blessed.has(w))
    .map((word) => {
      const row = byTerm.get(word)
      return {
        term: word,
        count: prose(row),
        spread: proseSpread(row),
        files: row?.files ?? [],
      }
    })
    .filter(r => r.count > 0)
    .sort((a, b) => b.count - a.count)

  const languageRows = [...language.values()].map(row => ({
    term: row.word, lens: row.lens, source: row.source, confidence: row.confidence,
    count: row.count ?? 1, owner: row.owner,
    // A language word is declared in exactly one package, so its spread is 1 and
    // its breakdown is that package — which is what lets the source toggles
    // reach this tab at all. Without it the rows were inert while every other
    // tab responded, and an inert control reads as a broken one.
    spread: 1, byOwner: { [row.owner]: row.count ?? 1 },
  })).sort((a, b) => a.lens.localeCompare(b.lens) || a.term.localeCompare(b.term))

  const conceptsOnly = conceptRows.filter(r => r.class === 'concept')

  // ── the audit is asked of the PROSE, and stays that way ──
  //
  // Every question in it is about the authored vocabularies, which are prose and
  // were seeded from prose at spread 4. Asking them of the widened corpus would
  // change what each one MEANS with nothing saying so: the first run over code
  // put Math, Record and SessionContext into *not in VOCABULARY.md* and took it
  // from 0 rows to 123, which is not 123 words somebody forgot to define. The
  // audit is the list a reader acts on, so it keeps the corpus it was
  // calibrated on; the tabs beside it are where the wider one is read.
  const conceptsProse = narrowToKinds(conceptsOnly, new Set(['markdown']))

  // Every source a concept was read from, with how much of the prose it is.
  // Ordered by weight, because the one a reader wants to switch off first is
  // usually the loudest — `IDEAS/` is design records for work not started, and
  // its vocabulary is proposals rather than the framework.
  //
  // Counted PER LENS rather than once, because the same chip means different
  // amounts on different tabs and a single number is wrong on two of the three:
  // `IDEAS/` is a fifth of the prose and holds no source file at all, so a chip
  // reading `IDEAS 2431` on the API tab describes nothing the reader is looking
  // at. A lens where a source has nothing is a real answer and the chip says so.
  const tally = new Map()
  const add = (lens, rows) => {
    for (const r of rows) {
      for (const [owner, n] of Object.entries(r.byOwner ?? {})) {
        const row = tally.get(owner) ?? { name: owner, concept: 0, api: 0, language: 0 }
        row[lens] += n
        tally.set(owner, row)
      }
    }
  }
  add('concept', conceptRows)
  add('api', api)
  add('language', languageRows)

  const sources = [...tally.values()]
    .map(r => ({ ...r, total: r.concept + r.api + r.language }))
    .sort((a, b) => b.concept - a.concept || b.total - a.total)

  return {
    root,
    generated: new Date().toISOString(),
    corpus: { docs: docs.length, packages: packages.length, byKind },
    architect,
    counts: {
      concept: conceptsOnly.length,
      product: conceptRows.filter((r) => r.class === 'product').length,
      external: conceptRows.filter((r) => r.class === 'external').length,
      common: conceptRows.filter((r) => r.class === 'common').length,
      language: languageRows.length,
      labelled: conceptRows.filter((r) => r.class === 'concept' && r.label).length,
      authored: authored.size,
      packageNamed: conceptRows.filter((r) => r.class === 'concept' && r.label?.source)
        .length,
      api: api.length,
      apiEntry: api.filter((r) => r.entry).length,
      dropped: droppedWords.size,
      droppedHits: [...droppedWords.values()].reduce((a, b) => a + b, 0)
    },
    sources,
    vocabularies: pkgVocab.read,
    concepts: conceptRows,
    language: languageRows,
    api,
    audit: {
      // Dead doctrine: § 2 blesses the word and the repo barely says it.
      blessedUnused: architect.blessed
        .map((word) => {
          const phrase = phrases.get(word)
          if (phrase) return { term: word, count: prose(phrase), spread: proseSpread(phrase) }
          const row = byTerm.get(word.toLowerCase())
          return { term: word, count: prose(row), spread: proseSpread(row) }
        })
        .filter((r) => r.count < 5),
      // Vocabulary that exists and nobody defined.
      unnamedCommon: conceptsProse
        .filter((r) => r.status === 'unnamed' && r.spread >= 4)
        .slice(0, 60),
      // What a spread-4 term is missing from the authored file. The seed was
      // taken at that bar, so a row here is either a word that has since spread
      // or one somebody deleted from VOCABULARY.md.
      unlabelled: conceptsProse.filter(
        (r) => r.spread >= 4 && !r.label && !blessed.has(r.term.toLowerCase())
      ),
      forbiddenUsed: forbidden.filter((r) => r.count > 0),
      // The root vocabulary has SEEN the word and not decided, and a package
      // vocabulary has. `open` is not an answer — the file says so itself, *seen
      // and not yet decided, the seeded default* — so it outranks a package
      // definition on the ladder while carrying less than one, which is the one
      // place the precedence reads as an answer and is not.
      //
      // Not resolved by letting the package win. Most of these are one spelling
      // over two realms — a Table is a `<table>` in css and a database table in
      // litestone, a Field is a control and a column — which is § 2's own
      // `Channel` case, and a reader needs to be shown both rather than handed
      // whichever vocabulary spoke last.
      undecidedButDefined: conceptsProse
        .filter((r) => r.label?.status === 'open' && pkgVocab.terms.has(r.term.toLowerCase()))
        .map((r) => {
          const pkg = pkgVocab.terms.get(r.term.toLowerCase())
          return {
            term: r.term,
            count: r.count,
            spread: r.spread,
            owner: pkg.owner,
            means: pkg.means
          }
        }),
      // A row the scan can no longer see. Dropping a word is a one-line edit
      // over here and it silently orphans a definition over there — the file
      // goes on carrying a term nothing measures, which is the one failure
      // authored-plus-generated is supposed to make impossible.
      definedUnseen: [...authored.values()]
        .filter((r) => !byTerm.has(r.term.toLowerCase()))
        .map((r) => ({ term: r.term, status: r.status, means: r.means })),
      // Pairs the prose writes as one thing and nobody has named. A candidate
      // list rather than a finding: promoting one is a row in VOCABULARY.md,
      // and until somebody writes that row it is two words that travel
      // together, which is not the same claim.
      phraseCandidates: [...pairs.values()]
        .filter((r) => r.owners.size >= 3 && r.count >= 8 && !phrases.has(r.term))
        // What is left after the shape filters is a sentence wearing a term's
        // clothes: a participle in front (`Verified state`) or a verb behind
        // (`Litestone emits`). A trailing s is only a plural if the singular is
        // a word this repo also uses on its own.
        .filter((r) => {
          const [head, tail] = r.term.split(' ')
          if (/(?:ed|ing)$/.test(head) && !byTerm.has(head.toLowerCase())) return false
          const singular = singularize(tail.toLowerCase())
          return singular === tail.toLowerCase() || byTerm.has(singular)
        })
        .map((r) => ({ term: r.term, count: r.count, spread: r.owners.size }))
        .sort((a, b) => b.spread - a.spread || b.count - a.count)
        .slice(0, 60)
    }
  }
}

// ─── presentation: the terminal ───────────────────────────────────────────────

// Narrowing to a set of file kinds, in the terminal, by the same arithmetic the
// page's chips do — one implementation would be better and cannot be had: that
// one runs in a browser over data attributes. So the two are kept to the same
// shape (recompute count, recompute spread from the owners left) and a change
// to either is owed to the other.
function narrowToKinds(rows, keep) {
  return rows
    .map((row) => {
      const owners = new Set()
      let count = 0
      for (const [cell, n] of Object.entries(row.byCell ?? {})) {
        const bar = cell.lastIndexOf('|')
        if (bar < 0 || !keep.has(cell.slice(bar + 1))) continue
        count += n
        owners.add(cell.slice(0, bar))
      }
      return { ...row, count, spread: owners.size }
    })
    .filter((r) => r.count > 0)
    .sort((a, b) => b.spread - a.spread || b.count - a.count || a.term.localeCompare(b.term))
}

export function renderList(model, { limit = 40, lens = 'concept', kinds = null } = {}) {
  const out = []
  const pad = (s, n) => String(s).padEnd(n)

  out.push('')
  out.push(`  ${model.corpus.docs} doc(s) · ${model.corpus.packages} package(s)`)
  out.push(`  ${KINDS.map((k) => `${k} ${model.corpus.byKind?.[k] ?? 0}`).join(' · ')}`)
  out.push('')
  out.push(
    `  concept ${model.counts.concept}   language ${model.counts.language}   api ${model.counts.api} (${model.counts.apiEntry} at an entry point)`
  )
  out.push(
    `  classified out — product ${model.counts.product} · external ${model.counts.external} · common ${model.counts.common}`
  )
  out.push(
    `  dropped as English — ${model.counts.dropped} word(s), ${model.counts.droppedHits} occurrence(s)`
  )
  out.push(
    `  VOCABULARY.md defines ${model.counts.authored} · ${model.audit.unlabelled.length} term(s) at spread 4+ unlisted`
  )
  // The count per vocabulary, not a total. A vocabulary that stopped resolving
  // returns every one of its terms to `unnamed`, which is what a package that
  // named nothing also looks like — so the number that separates them is
  // printed, and `not found` is printed rather than omitted.
  for (const reg of model.vocabularies ?? [])
    out.push(`  ${reg.file} ${reg.found ? `defines ${reg.terms}` : 'NOT FOUND'}`)
  if (kinds) out.push(`  narrowed to ${[...kinds].join(', ')} — count and spread are RECOMPUTED, not filtered`)
  out.push('')

  // The api and language lenses read DECLARATIONS rather than the corpus, so a
  // file-kind narrowing has nothing to say about them and is not applied.
  const concepts = model.concepts.filter((r) => r.class === 'concept')
  const rows =
    lens === 'api'
      ? model.api
      : lens === 'language'
      ? model.language
      : kinds
      ? narrowToKinds(concepts, kinds)
      : concepts

  if (lens === 'language') {
    out.push(`  ${pad('term', 26)}${pad('lens', 8)}confidence`)
    for (const r of rows.slice(0, limit))
      out.push(`  ${pad(r.term, 26)}${pad(r.lens, 8)}${r.confidence}`)
  } else {
    out.push(
      `  ${pad('term', 26)}${pad('spread', 8)}${pad('count', 8)}${
        lens === 'api' ? 'entry' : 'status'
      }`
    )
    for (const r of rows.slice(0, limit)) {
      out.push(
        `  ${pad(r.term, 26)}${pad(r.spread, 8)}${pad(r.count, 8)}${
          lens === 'api' ? (r.entry ? 'yes' : '') : r.status
        }`
      )
    }
  }

  out.push('')
  out.push(`  ${rows.length} row(s), ${Math.min(limit, rows.length)} shown`)
  out.push('')
  return out.join('\n')
}

export function renderJson(model) {
  return `${JSON.stringify(model, null, 2)}\n`
}

// ─── presentation: the page ───────────────────────────────────────────────────

const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c])

// A path the reader can open. `vscode://file/<absolute>` is the editor's own
// scheme, so the ABSOLUTE path has to be baked in — which means the written page
// is local to the machine that wrote it. That is already true of this page (it
// is ungated and gitignored) and is why the links are here rather than in a
// committed snapshot, where they would point at somebody else's home directory.
//
// No line number: the prose scan reads a document with its code spans and fences
// stripped out, so an offset into what it read is not an offset into the file.
function fileLink(root, rel, text = rel) {
  return `<a class="link" href="vscode://file${esc(root)}/${esc(rel)}">${esc(text)}</a>`
}

function row(cells, attrs = '') {
  return `<tr ${attrs}>${cells.map(c => `<td>${c}</td>`).join('')}</tr>`
}

function badgeFor(status) {
  const tone = status === 'blessed' ? 'success'
             : status === 'refused' ? 'danger'
             : status === 'unnamed' ? 'warning'
             : status === 'open'    ? 'warning'
             : status === 'not-yet-named' ? 'info'
             : ''
  return `<span class="badge ${tone}">${esc(status)}</span>`
}

function conceptTable(rows, root = '') {
  return `<div class="table-wrap"><table class="table striped dense">
    <thead><tr><th>term</th><th>spread</th><th>count</th><th>status</th><th>class</th><th>means</th><th>where</th></tr></thead>
    <tbody>${rows.map(r => row([
      `<strong>${esc(r.term)}</strong>`,
      `<span class="c-spread">${r.spread}</span>`,
      `<span class="c-count">${r.count}</span>`,
      badgeFor(r.status),
      `<span class="badge">${esc(r.class)}</span>`,
      r.label?.means
        ? esc(r.label.means)
        : '<span class="text-xs text-muted">—</span>',
      `<span class="text-xs text-muted">${r.files.slice(0, 3).map(f => fileLink(root, f.file)).join(' · ')}</span>`,
    ], `data-term="${esc(r.term.toLowerCase())}" data-class="${esc(r.class)}" data-status="${esc(r.status)}" data-spread="${r.spread}" data-count="${r.count}" data-owners="${Object.entries(r.byOwner).map(([o, n]) => `${esc(o)}:${n}`).join(';')}" data-cells="${Object.entries(r.byCell ?? {}).map(([c, n]) => `${esc(c)}:${n}`).join(';')}"`)).join('')}</tbody>
  </table></div>`
}

function apiTable(rows, root = '') {
  return `<div class="table-wrap"><table class="table striped dense">
    <thead><tr><th>identifier</th><th>spread</th><th>declared</th><th>entry</th><th>packages</th><th>where</th></tr></thead>
    <tbody>${rows.map(r => row([
      `<code>${esc(r.term)}</code>`,
      `<span class="c-spread">${r.spread}</span>`,
      `<span class="c-count">${r.count}</span>`,
      r.entry ? '<span class="badge success">entry</span>' : '<span class="text-xs text-muted">internal</span>',
      `<span class="text-xs text-muted">${esc(r.owners.join(' · '))}</span>`,
      `<span class="text-xs text-muted">${r.files.slice(0, 2).map(f => fileLink(root, f)).join(' · ')}</span>`,
    ], `data-term="${esc(r.term.toLowerCase())}" data-status="${r.entry ? 'entry' : 'internal'}" data-spread="${r.spread}" data-count="${r.count}" data-owners="${Object.entries(r.byOwner).map(([o, n]) => `${esc(o)}:${n}`).join(';')}"`)).join('')}</tbody>
  </table></div>`
}

function languageTable(rows, root = '') {
  return `<div class="table-wrap"><table class="table striped dense">
    <thead><tr><th>word</th><th>language</th><th>confidence</th><th>source</th></tr></thead>
    <tbody>${rows.map(r => row([
      `<code>${esc(r.term)}</code>`,
      esc(r.lens),
      r.confidence === 'declared'
        ? '<span class="badge success">declared</span>'
        : '<span class="badge warning">grepped</span>',
      `<span class="text-xs text-muted">${r.lens === 'lite'
          ? fileLink(root, `packages/litestone/${r.source}`, r.source)
          : fileLink(root, r.source)}</span>`,
    ], `data-term="${esc(r.term.toLowerCase())}" data-status="${esc(r.confidence)}" data-spread="1" data-count="${r.count ?? 1}" data-owners="${esc(r.owner)}:${r.count ?? 1}"`)).join('')}</tbody>
  </table></div>`
}

function auditPane(model, root = '') {
  const { blessedUnused, unnamedCommon, forbiddenUsed } = model.audit

  const dead = blessedUnused.length
    ? `<div class="table-wrap"><table class="table striped dense">
        <thead><tr><th>blessed by § 2</th><th>count</th><th>spread</th></tr></thead>
        <tbody>${blessedUnused.map(r => row([`<strong>${esc(r.term)}</strong>`, r.count, r.spread])).join('')}</tbody>
      </table></div>`
    : '<p class="text-xs text-muted">every blessed term is in live use.</p>'

  const loose = unnamedCommon.length
    ? conceptTable(unnamedCommon, root)
    : '<p class="text-xs text-muted">every widespread concept is named in § 2.</p>'

  const drift = forbiddenUsed.length
    ? `<div class="table-wrap"><table class="table striped dense">
        <thead><tr><th>forbidden word</th><th>uses</th><th>docs</th><th>top files</th></tr></thead>
        <tbody>${forbiddenUsed.map(r => row([
          `<strong>${esc(r.term)}</strong>`, r.count, r.spread,
          `<span class="text-xs text-muted">${r.files.slice(0, 3).map(f => fileLink(root, f.file, `${f.file} (${f.count})`)).join(' · ')}</span>`,
        ])).join('')}</tbody>
      </table></div>`
    : '<p class="text-xs text-muted">no forbidden word appears in live prose.</p>'

  const orphans = model.audit.definedUnseen.length
    ? `<div class="table-wrap"><table class="table striped dense">
        <thead><tr><th>defined</th><th>status</th><th>means</th></tr></thead>
        <tbody>${model.audit.definedUnseen.map(r => row([
          `<strong>${esc(r.term)}</strong>`, badgeFor(r.status),
          r.means ? esc(r.means) : '<span class="text-xs text-muted">—</span>',
        ])).join('')}</tbody>
      </table></div>`
    : '<p class="text-xs text-muted">every defined term is one the scan still sees.</p>'

  const answered = model.audit.undecidedButDefined.length
    ? `<div class="table-wrap"><table class="table striped dense">
        <thead><tr><th>term</th><th>spread</th><th>count</th><th>defined by</th><th>means</th></tr></thead>
        <tbody>${model.audit.undecidedButDefined
          .map((r) =>
            row(
              [
                `<strong>${esc(r.term)}</strong>`,
                r.spread,
                r.count,
                `<span class="badge">${esc(r.owner)}</span>`,
                r.means ? esc(r.means) : '<span class="text-xs text-muted">—</span>'
              ],
              `data-term="${esc(r.term.toLowerCase())}" data-spread="${
                r.spread
              }" data-count="${r.count}"`
            )
          )
          .join('')}</tbody>
      </table></div>`
    : '<p class="text-xs text-muted">no open row has an answer waiting in a package vocabulary.</p>'

  const pairs = model.audit.phraseCandidates.length
    ? `<div class="table-wrap"><table class="table striped dense">
        <thead><tr><th>phrase</th><th>spread</th><th>count</th></tr></thead>
        <tbody>${model.audit.phraseCandidates.map(r => row([
          `<strong>${esc(r.term)}</strong>`, r.spread, r.count,
        ], `data-term="${esc(r.term.toLowerCase())}" data-spread="${r.spread}" data-count="${r.count}"`)).join('')}</tbody>
      </table></div>`
    : '<p class="text-xs text-muted">no unnamed phrase travels this widely.</p>'

  return `<section class="pane" data-tab="audit" hidden>
    <div class="section-header"><h2 class="h5">Dead doctrine</h2>
      <p class="text-xs text-muted">blessed in ARCHITECT.md § 2, barely said anywhere — fewer than five uses</p></div>
    ${dead}
    <div class="section-header"><h2 class="h5">Vocabulary nobody defined</h2>
      <p class="text-xs text-muted">a concept in four or more packages that § 2 never names</p></div>
    ${loose}
    <div class="section-header"><h2 class="h5">Not in VOCABULARY.md</h2>
      <p class="text-xs text-muted">a term in four or more packages that the authored file does not carry — it spread since the seed, or somebody removed it</p></div>
    ${
      model.audit.unlabelled.length
        ? conceptTable(model.audit.unlabelled, root)
        : '<p class="text-xs text-muted">every widespread term is listed.</p>'
    }
    <div class="section-header"><h2 class="h5">Open here, answered there</h2>
      <p class="text-xs text-muted">VOCABULARY.md says <code>open</code> — seen and not yet decided — and a package vocabulary already defines the word. Most are one spelling over two realms, so the decision is which sense the root file is naming, not whether to copy this one in</p></div>
    ${answered}
    <div class="section-header"><h2 class="h5">Defined here, seen nowhere</h2>
      <p class="text-xs text-muted">a VOCABULARY.md row the scan cannot match — the word left the prose, or it is excluded in terms.js and the definition was orphaned</p></div>
    ${orphans}
    <div class="section-header"><h2 class="h5">Phrases nobody has named</h2>
      <p class="text-xs text-muted">two words the prose writes as one thing, in three or more packages — a candidate for a VOCABULARY.md row, where a word on its own is too generic to be one</p></div>
    ${pairs}
    <div class="section-header"><h2 class="h5">Words § 2 forbids, used as terms</h2>
      <p class="text-xs text-muted">candidates, not verdicts — capitalized mid-sentence only, since the lowercase uses are ordinary English; a word § 2 also blesses is left out</p></div>
    ${drift}
  </section>`
}

// The themes `@frontierjs/css` ships, and the light/dark pair is the package's
// own rather than a guess: `field` is an ink ground written for the pages a
// project generates about itself, and `press` says in its header that it is the
// same discipline on the opposite ground. A theme name is not a luminance claim
// — `midnight` is a LIGHT theme with a purple accent, measured at rgb(245,245,245),
// so picking a dark default by reading the names would have been wrong.
//
// `field` and `press` are only offered when the stylesheet was vendored from the
// workspace; the published bundle lags a release and may not carry them, so the
// fallback pair is the plain inverted neutral and the plain default.
export const THEMES      = ['default', 'dark', 'midnight', 'forest', 'sunset', 'elite', 'basecamp', 'notebook', 'press']
export const THEME_LIGHT = 'press'
export const THEME_DARK  = 'field'
export const FALLBACK    = { light: 'default', dark: 'dark' }

// Runs in <head>, before the body is parsed, because a theme applied after the
// first paint is a white flash on a page somebody opened to read in the dark.
// It writes the class on <html> and not on <body> for the same reason: <body>
// does not exist yet here, and the root is where this house puts the theme.
const headScript = (light, dark) => `
try {
  var saved = localStorage.getItem('fli.terms.theme')
  var wants = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches
  document.documentElement.className = 'theme-' + (saved || (wants ? '${dark}' : '${light}'))
} catch (e) {}
`

export function renderPage(model, css = null) {
  const concepts = model.concepts.filter(r => r.class === 'concept')
  const other    = model.concepts.filter(r => r.class !== 'concept')
  const light    = css ? THEME_LIGHT : FALLBACK.light
  const dark     = css ? THEME_DARK  : FALLBACK.dark

  return [
    '<!doctype html>',
    // No `generated by:` line: this page is exploratory and must not be adopted
    // by the snapshots phase while its exclude lists are still moving.
    '<!-- fli ws:terms · not a snapshot -->',
    `<html lang="en" class="theme-${light}"><head><meta charset="utf-8">`,
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>${esc(model.root)} — vocabulary</title>`,
    css ? `<style id="fjs-css">${css}</style>` : '',
    `<style id="terms">${STYLE}</style>`,
    `<script>${headScript(light, dark)}</script>`,
    '</head><body class="app">',
    `<header class="topbar"><strong>vocabulary</strong>
      <span class="text-xs text-muted">${model.corpus.docs} docs · ${model.corpus.packages} packages</span>
      <input id="q" class="field" type="search" placeholder="filter terms…" autofocus>
      <label class="terms-theme"><span class="text-xs text-muted">theme</span>
        <select class="field" id="theme" aria-label="Theme">
          ${(css ? ['field', ...THEMES] : THEMES).map(t => `<option value="${t}">${t}</option>`).join('')}
        </select>
      </label>
    </header>`,
    '<main class="screen">',
    `<section class="pane">
      <div class="tiles">
        ${tile('concepts', model.counts.concept, 'a mental model is built from these')}
        ${tile('language words', model.counts.language, '.lite and mesa')}
        ${tile('api identifiers', model.counts.api, `${model.counts.apiEntry} at an entry point`)}
        ${tile('defined in VOCABULARY.md', model.counts.authored,
               `${model.audit.unlabelled.length} term(s) at spread 4+ still unlisted`)}
        ${tile('classified out', model.counts.product + model.counts.external + model.counts.common,
               `product ${model.counts.product} · external ${model.counts.external} · common ${model.counts.common}`)}
        ${tile('dropped as English', model.counts.dropped,
               `${model.counts.droppedHits} occurrence(s), never shown`)}
      </div>
      <div class="cluster gap-2xs terms-filters">
        <label class="text-xs text-muted">spread
          <input class="field" id="f-spread" type="number" min="0" step="1" value="0" inputmode="numeric" title="at least">
          <span aria-hidden="true">–</span>
          <input class="field" id="f-spread-max" type="number" min="0" step="1" placeholder="∞" inputmode="numeric" title="at most"></label>
        <label class="text-xs text-muted">count
          <input class="field" id="f-count" type="number" min="0" step="1" value="0" inputmode="numeric" title="at least">
          <span aria-hidden="true">–</span>
          <input class="field" id="f-count-max" type="number" min="0" step="1" placeholder="∞" inputmode="numeric" title="at most"></label>
        <label class="text-xs text-muted">class
          <select class="field" id="f-class">
            <option value="">any</option>
            <option value="concept">concept</option>
            <option value="external">external — somebody else's noun</option>
            <option value="api">api — an identifier, not a coined word</option>
            <option value="product">product</option>
            <option value="common">common</option>
          </select></label>
        <label class="text-xs text-muted">status
          <select class="field" id="f-status">
            <option value="">any</option>
            <optgroup label="concepts">
              <option value="blessed">blessed</option>
              <option value="clarified">clarified</option>
              <option value="not-yet-named">not-yet-named</option>
              <option value="unnamed">unnamed</option>
              <option value="open">open — seen, not decided</option>
              <option value="refused">refused</option>
              <option value="alias">alias</option>
            </optgroup>
            <optgroup label="api">
              <option value="entry">entry</option>
              <option value="internal">internal</option>
            </optgroup>
            <optgroup label="language">
              <option value="declared">declared</option>
              <option value="grepped">grepped</option>
            </optgroup>
          </select></label>
        <button class="btn outlined" id="f-clear">clear</button>
        <span class="text-xs text-muted" id="shown"></span>
      </div>
      <div class="cluster gap-2xs terms-sources">
        <span class="text-xs text-muted">sources</span>
        ${model.sources.map(src => `<label class="chip" data-concept="${src.concept}" data-api="${src.api}" data-language="${src.language}" data-other="${src.concept}" data-audit="${src.concept}"><input type="checkbox" class="src" value="${esc(src.name)}" checked> ${esc(src.name)} <span class="text-xs text-muted src-n">${src.concept}</span></label>`).join('')}
        <button class="btn outlined" id="src-all">all</button>
      </div>
      <div class="cluster gap-2xs terms-kinds" id="kind-row">
        <span class="text-xs text-muted">file kinds</span>
        ${KINDS.map(k => `<label class="chip"><input type="checkbox" class="kind" value="${esc(k)}" checked> ${esc(k)} <span class="text-xs text-muted">${model.corpus.byKind?.[k] ?? 0}</span></label>`).join('')}
        <button class="btn outlined" id="kind-all">all</button>
        <span class="text-xs text-muted">a source file is read WHOLE, so an identifier the API tab already counts is counted here too — switch <strong>code</strong> off for prose alone, or everything but it for what the code itself names</span>
      </div>
      <nav class="cluster gap-2xs terms-tabs">
        <button class="btn outlined is-on" data-go="concept">Concepts</button>
        <button class="btn outlined" data-go="language">Language</button>
        <button class="btn outlined" data-go="api">API</button>
        <button class="btn outlined" data-go="other">Classified out</button>
        <button class="btn outlined" data-go="audit">Audit</button>
      </nav>
    </section>`,
    `<section class="pane" data-tab="concept">${conceptTable(concepts, model.root)}</section>`,
    `<section class="pane" data-tab="language" hidden>${languageTable(model.language, model.root)}</section>`,
    // Every row, uncapped: a table showing 1,200 of the 1,587 the tile counts is
    // a filter answering about a set the reader cannot see, and the page is
    // already the size of the model.
    `<section class="pane" data-tab="api" hidden>${apiTable(model.api, model.root)}</section>`,
    `<section class="pane" data-tab="other" hidden>${conceptTable(other, model.root)}</section>`,
    auditPane(model, model.root),
    '</main>',
    `<footer class="pane text-xs text-muted">read ${esc(model.generated)} · exploratory, not a snapshot · FJS-1211</footer>`,
    `<script>${SCRIPT}</script>`,
    '</body></html>',
    '',
  ].join('\n')
}

// The anatomy is `@frontierjs/css`'s own — label first in the DOM so a screen
// reader hears the subject before the number (packages/css/src/components/tiles.css).
function tile(label, value, note) {
  return `<article class="tile">
    <div class="tile-label">${esc(label)}</div>
    <div class="tile-value">${value}</div>
    <p class="text-xs text-muted">${esc(note)}</p>
  </article>`
}

const STYLE = `
/* Layout only. Every surface, border and radius belongs to @frontierjs/css --
   a literal color or a var() the package does not define is silently dropped,
   which is how the tiles rendered borderless against a token named --border
   that does not exist. */
.topbar{display:flex;align-items:center;gap:var(--space-md);padding:var(--space-md) var(--space-2xl);position:sticky;top:0;z-index:2;background:var(--surface);border-bottom:var(--border-width) solid var(--rule)}
.topbar #q{margin-left:auto;min-width:18rem}
.terms-theme{display:flex;align-items:center;gap:var(--space-2xs)}
.terms-theme .field{width:9rem}
.screen{padding:var(--space-2xl);display:grid;gap:var(--space-2xl)}
.terms-tabs{margin-top:var(--space-2xl)}
.terms-filters{margin-top:var(--space-2xl);flex-wrap:wrap;align-items:center}
.terms-filters label{display:flex;align-items:center;gap:var(--space-2xs)}
.terms-filters input[type=number]{width:5rem}
.terms-filters select{width:10rem}
.terms-sources,.terms-kinds{margin-top:var(--space-sm);flex-wrap:wrap;align-items:center}
.terms-sources .chip,.terms-kinds .chip{display:inline-flex;align-items:center;gap:var(--space-3xs);cursor:pointer}
.terms-sources .chip:has(input:not(:checked)),.terms-kinds .chip:has(input:not(:checked)){opacity:.45}
/* Nothing on this tab comes from here. Dimmed rather than removed: a chip that
   appears and disappears as tabs change reads as a bug, and *this source has
   nothing in this vocabulary* is a real answer worth showing. */
.terms-sources .chip[data-empty="yes"]{opacity:.3}
tr[hidden]{display:none}
`

// Backticks are forbidden in here — this string is itself inside a template
// literal, and one would close it and break the file's PARSE somewhere else.
const SCRIPT = `
const q = document.getElementById('q')
const panes = [...document.querySelectorAll('[data-tab]')]
const themePick = document.getElementById('theme')
const fSpread = document.getElementById('f-spread')
const fCount  = document.getElementById('f-count')
const fSpreadMax = document.getElementById('f-spread-max')
const fCountMax  = document.getElementById('f-count-max')
const fStatus = document.getElementById('f-status')
const fClass  = document.getElementById('f-class')
const shownAt = document.getElementById('shown')
const srcBoxes  = [...document.querySelectorAll('.src')]
const kindBoxes = [...document.querySelectorAll('.kind')]
const kindRow   = document.getElementById('kind-row')

// A row's spread and count are the WHOLE tree's answer. Switching a source off
// has to recompute both from the row's own breakdown rather than hide rows,
// because a term read 40 times in IDEAS/ and twice in packages/ is a different
// term once IDEAS/ is off, and a filter over the old numbers would keep it.
//
// The same is true one dimension over: *which concepts are in the CODE* is what
// switching markdown off asks, and it is a different ranking rather than a
// shorter list. So a concept row carries the JOINT breakdown, owner then kind,
// because spread is a count of owners and how many are left once a kind is off
// cannot be recovered from two separate tallies.
//
// An api or language row carries no kinds and is not a corpus scan at all: those
// lenses read DECLARATIONS, so a file-kind filter has nothing to say about them
// and they fall back to the owner breakdown rather than being emptied by it.
function recount() {
  const off     = new Set(srcBoxes.filter(b => !b.checked).map(b => b.value))
  const kindOff = new Set(kindBoxes.filter(b => !b.checked).map(b => b.value))
  for (const tr of document.querySelectorAll('tr[data-owners]')) {
    const cells = tr.dataset.cells
    const pairs = (cells || tr.dataset.owners || '').split(';').filter(Boolean)
      .map(p => { const at = p.lastIndexOf(':'); return [p.slice(0, at), Number(p.slice(at + 1))] })
    const owners = new Set()
    let count = 0
    for (const [key, n] of pairs) {
      const bar   = key.lastIndexOf('|')
      const owner = bar < 0 ? key : key.slice(0, bar)
      const kind  = bar < 0 ? null : key.slice(bar + 1)
      if (off.has(owner)) continue
      if (kind && kindOff.has(kind)) continue
      count += n
      owners.add(owner)
    }
    const spread = owners.size
    tr.dataset.spread = spread
    tr.dataset.count  = count
    const s = tr.querySelector('.c-spread'), c = tr.querySelector('.c-count')
    if (s) s.textContent = spread
    if (c) c.textContent = count
    // A term left with nothing is not in the reduced tree at all.
    tr.dataset.empty = pairs.length > 0 && count === 0 ? 'yes' : 'no'
  }
}

// The head script has already chosen; this only reflects that choice into the
// control and records a later one. Reading the class rather than the storage
// key keeps the two from disagreeing when nothing was ever saved.
function setTheme(name) {
  document.documentElement.className = 'theme-' + name
  themePick.value = name
  try { localStorage.setItem('fli.terms.theme', name) } catch (e) {}
}
themePick.value = (document.documentElement.className.match(/theme-([a-z]+)/) || [])[1] || themePick.value
themePick.addEventListener('change', () => setTheme(themePick.value))
const tabs  = [...document.querySelectorAll('[data-go]')]

// A chip's number is what that source contributes to the VISIBLE vocabulary.
// The IDEAS folder is a fifth of the prose and holds no source file at all,
// so one number across all three tabs would be wrong on two of them.
function retuneSources(lens) {
  for (const chip of document.querySelectorAll('.terms-sources .chip')) {
    const n = Number(chip.dataset[lens] || 0)
    chip.querySelector('.src-n').textContent = n
    chip.dataset.empty = n === 0 ? 'yes' : 'no'
    chip.title = n === 0 ? 'nothing on this tab comes from here' : ''
  }
}

function show(name) {
  for (const p of panes) p.hidden = p.dataset.tab !== name
  for (const t of tabs) t.classList.toggle('is-on', t.dataset.go === name)
  // The api and language lenses read declarations rather than the corpus, so
  // the kind chips would sit there doing nothing on every row.
  kindRow.hidden = name === 'api' || name === 'language'
  retuneSources(name)
  filter()
}

// One reader for every tab. A row declares term, status, spread and count, so a
// tab that ships a new column costs no filter code — and a tab whose rows have
// no spread declares 0 rather than omitting it, since a missing attribute and a
// zero would otherwise both read as NaN and hide the whole table.
function filter() {
  const needle = q.value.trim().toLowerCase()
  const spread = Number(fSpread.value) || 0
  const count  = Number(fCount.value) || 0
  const spreadMax = fSpreadMax.value === '' ? Infinity : Number(fSpreadMax.value)
  const countMax  = fCountMax.value === ''  ? Infinity : Number(fCountMax.value)
  const status = fStatus.value
  const klass  = fClass.value
  const pane   = panes.find(p => !p.hidden)
  if (!pane) return

  let shown = 0, total = 0
  for (const tr of pane.querySelectorAll('tbody tr')) {
    total++
    const hide =
      (needle.length > 0 && !(tr.dataset.term || '').includes(needle)) ||
      tr.dataset.empty === 'yes' ||
      Number(tr.dataset.spread || 0) < spread ||
      Number(tr.dataset.spread || 0) > spreadMax ||
      Number(tr.dataset.count || 0) < count ||
      Number(tr.dataset.count || 0) > countMax ||
      (status !== '' && tr.dataset.status !== status) ||
      (klass !== '' && tr.dataset.class !== klass)
    tr.hidden = hide
    if (!hide) shown++
  }
  shownAt.textContent = shown === total ? total + ' rows' : shown + ' of ' + total + ' rows'
}

for (const t of tabs) t.addEventListener('click', () => show(t.dataset.go))
for (const el of [q, fSpread, fCount, fSpreadMax, fCountMax, fStatus, fClass]) el.addEventListener('input', filter)
for (const el of [fStatus, fClass]) el.addEventListener('change', filter)
for (const box of srcBoxes)  box.addEventListener('change', () => { recount(); filter() })
for (const box of kindBoxes) box.addEventListener('change', () => { recount(); filter() })
document.getElementById('src-all').addEventListener('click', () => {
  const anyOff = srcBoxes.some(b => !b.checked)
  for (const b of srcBoxes) b.checked = anyOff
  recount(); filter()
})

document.getElementById('kind-all').addEventListener('click', () => {
  const anyOff = kindBoxes.some(b => !b.checked)
  for (const b of kindBoxes) b.checked = anyOff
  recount(); filter()
})
document.getElementById('f-clear').addEventListener('click', () => {
  q.value = ''; fSpread.value = '0'; fCount.value = '0'
  fSpreadMax.value = ''; fCountMax.value = ''; fStatus.value = ''; fClass.value = ''
  filter()
})
document.addEventListener('keydown', (e) => {
  if (e.key === '/' && document.activeElement !== q) { e.preventDefault(); q.focus() }
  if (e.key === 'Escape') { q.value = ''; filter() }
})

// The page opens on Concepts, and a chip that only learns its tab on the first
// tab CHANGE spends that whole first screen showing a number for a lens nobody
// picked.
retuneSources('concept')
filter()
`
