// The pivot classifier — can Release N-1 and Release N serve one database?
//
// Every case below is a change to a schema and the answer the deploy is owed.
// Two rules the suite exists to hold:
//
//   1. A wrong EXPAND is the only answer that costs anything. Where the
//      classifier cannot tell, it says so, and unknown counts as a contract.
//   2. The snapshot holds the surface and never the verdict, so rendering it
//      twice over one schema produces one file. A generated file that depends
//      on its own previous contents cannot be rechecked, and the whole CI phase
//      rests on it being rechecked.

import { describe, it, expect } from 'bun:test'
import { parse } from '../src/core/parser.js'
import { deriveReleaseSurface, renderReleaseSnapshot, classifyPivot, classifyAccess } from '../src/release.js'

const surface = (text: string) => {
  const parsed = parse(text)
  if (!parsed.valid) throw new Error(`fixture does not parse: ${parsed.errors?.join(', ')}`)
  return deriveReleaseSurface(parsed.schema)
}

const verdictOf = (before: string, after: string) => classifyPivot(surface(before), surface(after))

/** The finding for one subject, so a case asserts the sentence it is about. */
const about = (result: any, needle: string) =>
  result.findings.find((f: any) => `${f.subject} ${f.detail}`.includes(needle))

const BASE = `
model Order {
  id        Int      @id
  reference String   @unique
  total     Float    @default(0)
  note      String?
  status    Status   @default("pending")
  @@gate("2.4.4.5")
}

enum Status { pending paid shipped }
`

describe('release surface', () => {
  it('names what a release binds to, sorted so an insert does not shift the file', () => {
    const s = surface(BASE)
    expect(s.models.map(m => m.name)).toEqual(['Order'])
    expect(s.models[0].fields.map(f => f.name)).toEqual(['id', 'note', 'reference', 'status', 'total'])
    expect(s.models[0].table).toBe('order')
    expect(s.models[0].gate).toBe('2.4.4.5')
    expect(s.enums[0].values).toEqual(['paid', 'pending', 'shipped'])
  })

  it('marks the one field shape an N-1 write cannot omit', () => {
    const s = surface(BASE)
    const f = (n: string) => s.models[0].fields.find(x => x.name === n)!

    expect(f('reference').writeRequired).toBe(true)   // NOT NULL, no default
    expect(f('total').writeRequired).toBe(false)      // has a SQL default
    expect(f('note').writeRequired).toBe(false)       // optional
    expect(f('id').writeRequired).toBe(false)         // SQLite assigns it
  })

  it('does not answer nullability or a default for a field with no column', () => {
    const s = surface(`
      model Author { id Int @id  books Book[] }
      model Book   { id Int @id  authorId Int  author Author @relation(fields: [authorId], references: [id]) }
    `)
    const books = s.models.find(m => m.name === 'Author')!.fields.find(f => f.name === 'books')!
    expect(books.kind).toBe('relation')
    expect(books.optional).toBeNull()
    expect(books.default).toBeNull()
  })

  it('renders the same bytes twice, and names its own generator', () => {
    const body = renderReleaseSnapshot(surface(BASE), { source: 'schema.lite' })
    expect(body).toBe(renderReleaseSnapshot(surface(BASE), { source: 'schema.lite' }))
    expect(body).toContain('generated by: litestone release --schema schema.lite')
  })

  it('holds no verdict — the file describes one schema, a verdict is about two', () => {
    const body = renderReleaseSnapshot(surface(BASE), { source: 'schema.lite' }).toLowerCase()
    expect(body).not.toContain('expand —')
    expect(body).not.toContain('contract —')
  })
})

describe('expand — N-1 keeps serving', () => {
  it('an added model', () => {
    const r = verdictOf(BASE, BASE + `\nmodel Refund { id Int @id  amount Float @default(0) }`)
    expect(r.verdict).toBe('expand')
  })

  it('an added optional column', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note String?\n  memo String?'))
    expect(r.verdict).toBe('expand')
  })

  it('an added column with a default — an N-1 insert still lands', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note String?\n  channel String @default("web")'))
    expect(r.verdict).toBe('expand')
    expect(about(r, 'Order.channel')!.severity).toBe('expand')
  })

  it('an added enum member — the CHECK widens', () => {
    const r = verdictOf(BASE, BASE.replace('{ pending paid shipped }', '{ pending paid shipped refunded }'))
    expect(r.verdict).toBe('expand')
    expect(about(r, 'enum Status')!.detail).toContain('no branch for')
  })

  it('an added index — it changes how long a query takes and nothing it answers', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', '@@gate("2.4.4.5")\n  @@index([total])'))
    expect(r.verdict).toBe('expand')
  })

  it('an eased gate', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', '@@gate("0.4.4.5")'))
    expect(r.verdict).toBe('expand')
  })

  it('a removed @unique', () => {
    const r = verdictOf(BASE, BASE.replace('String   @unique', 'String'))
    expect(r.verdict).toBe('expand')
  })

  it('nothing at all', () => {
    const r = verdictOf(BASE, BASE)
    expect(r.verdict).toBe('unchanged')
    expect(r.findings).toEqual([])
  })
})

describe('contract — the deploy is the pivot', () => {
  it('a removed column, which N-1 still reads', () => {
    const r = verdictOf(BASE, BASE.replace('  note      String?\n', ''))
    expect(r.verdict).toBe('contract')
    expect(about(r, 'Order.note')!.detail).toContain('N-1')
  })

  it('a removed model', () => {
    expect(verdictOf(BASE + `\nmodel Refund { id Int @id }`, BASE).verdict).toBe('contract')
  })

  it('an added required column with no default — and it hands back the split', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note String?\n  channel String'))
    expect(r.verdict).toBe('contract')

    const f = about(r, 'Order.channel')!
    expect(f.detail).toContain('refused')
    expect(f.split).toHaveLength(3)
    expect(f.split[0]).toContain('optional')
    expect(f.split[1]).toContain('backfill')
    expect(f.split[2]).toContain('pivot')
  })

  it('a column made required — existing NULLs fail the constraint', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note      String '))
    expect(r.verdict).toBe('contract')
    expect(about(r, 'Order.note')!.split).toHaveLength(3)
  })

  it('a column made optional — this release may write a NULL N-1 has no case for', () => {
    const r = verdictOf(BASE, BASE.replace('total     Float    @default(0)', 'total Float? @default(0)'))
    expect(r.verdict).toBe('contract')
  })

  it('a changed type', () => {
    const r = verdictOf(BASE, BASE.replace('total     Float', 'total     Int  '))
    expect(r.verdict).toBe('contract')
  })

  it('an added @unique — an N-1 write that duplicates is now refused', () => {
    const r = verdictOf(BASE, BASE.replace('total     Float    @default(0)', 'total Float @default(0) @unique'))
    expect(r.verdict).toBe('contract')
  })

  it('an added @@unique', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', '@@gate("2.4.4.5")\n  @@unique([reference, total])'))
    expect(r.verdict).toBe('contract')
  })

  it('a removed enum member — every N-1 write of it is refused', () => {
    const r = verdictOf(BASE, BASE.replace('{ pending paid shipped }', '{ pending paid }'))
    expect(r.verdict).toBe('contract')
  })

  it('a renamed table under a release that binds to the old name', () => {
    const r = verdictOf(BASE, BASE.replace('model Order {', 'model Order {\n  @@map("orders")'))
    expect(r.verdict).toBe('contract')
  })

  it('a raised gate — the half no generic deployer can see', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', '@@gate("4.4.4.5")'))
    expect(r.verdict).toBe('contract')
    expect(about(r, 'model Order')!.detail).toContain('read needs USER')
  })

  it('an added row policy — the failure that arrives as a 200', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', `@@gate("2.4.4.5")\n  @@allow('read', total > 0)`))
    expect(r.verdict).toBe('contract')
    expect(about(r, '@@allow(`read`) added')!.detail).toContain('200')
  })

  it('one policy declaration is one finding, not one per operation it expands to', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', `@@gate("2.4.4.5")\n  @@allow('all', total > 0)`))
    const policy = r.findings.filter((x: any) => x.detail.includes('@@allow'))

    expect(policy).toHaveLength(1)
    expect(policy[0].detail).toContain('read')
    expect(policy[0].detail).toContain('delete')
  })

  it('@@softDelete turned on — delete means something different in the two releases', () => {
    const r = verdictOf(BASE, BASE.replace('  note      String?', '  note String?\n  deletedAt DateTime?').replace('@@gate("2.4.4.5")', '@@gate("2.4.4.5")\n  @@softDelete'))
    expect(r.verdict).toBe('contract')
  })

  it('a protection added — the column leaves every answer N-1 reads', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note String? @guarded(all)'))
    expect(r.verdict).toBe('contract')
    expect(about(r, 'Order.note')!.detail).toContain('@guarded')
  })
})

describe('unknown — counts as a contract, because a wrong "reversible" is the costly answer', () => {
  it('a policy predicate that moved: nothing here can say which way', () => {
    const before = BASE.replace('@@gate("2.4.4.5")', `@@gate("2.4.4.5")\n  @@allow('read', total > 0)`)
    const after  = BASE.replace('@@gate("2.4.4.5")', `@@gate("2.4.4.5")\n  @@allow('read', total > 100)`)
    const r = verdictOf(before, after)
    expect(r.verdict).toBe('unknown')
    expect(about(r, '@@allow(`read`) predicate changed')!.detail).toContain('not decidable')
  })

  it('a value that moved from a column to a computed field', () => {
    const before = BASE
    const after  = BASE.replace('total     Float    @default(0)', 'total Float @computed')
    expect(verdictOf(before, after).verdict).toBe('unknown')
  })
})

describe('the verdict is the worst finding, not the most common one', () => {
  it('nine expands and one contract is a contract', () => {
    const after = BASE
      .replace('note      String?', 'note String?\n  a String?\n  b String?\n  c String?')
      .replace('{ pending paid shipped }', '{ pending paid }')

    const r = verdictOf(BASE, after)
    expect(r.counts.expand).toBeGreaterThan(0)
    expect(r.counts.contract).toBe(1)
    expect(r.verdict).toBe('contract')
    expect(r.findings[0].severity).toBe('contract')   // worst first
  })
})

// ─── the access axis ─────────────────────────────────────────────────────────
//
// The same walk, graded on the other question. The suite's job here is to hold
// the two axes apart: they are not correlated and they are not opposites, and
// the case that proves it is the one below where every widening is an expand.

const accessOf = (before: string, after: string) => classifyAccess(surface(before), surface(after))

const GUARDED = `
model User {
  id            Int      @id
  email         String   @unique
  role          String   @default("user") @allow('write', auth().isAdmin)
  apiKey        String?  @secret
  status        Status   @default("draft")
  @@gate("4.4.5.6")
  @@allow('read', id == auth().id)
  @@transitions(status, publish: draft -> live @gate(5), retire: live -> archived)
}

enum Status { draft live archived }
`

describe('the deploy axis and the access axis disagree, which is why there are two', () => {
  it('every widening in this change is an EXPAND for the deploy', () => {
    const after = GUARDED
      .replace(`@allow('write', auth().isAdmin)`, '')
      .replace('@secret', '')
      .replace('@@gate("4.4.5.6")', '@@gate("2.4.5.6")')
      .replace(`  @@allow('read', id == auth().id)\n`, '')
      .replace('publish: draft -> live @gate(5)', 'publish: draft -> live')

    const access = accessOf(GUARDED, after)
    const pivot  = classifyPivot(surface(GUARDED), surface(after))

    expect(access.verdict).toBe('widens')
    expect(access.counts.widens).toBe(5)

    // The claim, executed: a reviewer handed the deploy severity for these five
    // reads green on all of them.
    const severityOf = (subject: string, detail: string) =>
      pivot.findings.find((f: any) => f.subject === subject && f.detail === detail)!.severity

    for (const w of access.findings.filter((f: any) => f.access === 'widens'))
      expect(severityOf(w.subject, w.detail)).toBe('expand')
  })

  it('the one change that narrows is the one the deploy calls a contract', () => {
    const after = GUARDED.replace('retire: live -> archived', 'retire: live -> archived @gate(6)')
    const r = accessOf(GUARDED, after)
    expect(r.verdict).toBe('narrows')
    expect(about(r, 'status.retire')!.severity).toBe('contract')
  })
})

describe('what a permission diff has to see', () => {
  it('a field-level @allow removed — the shape that guards isSystemAdmin and role', () => {
    const after = GUARDED.replace(`@allow('write', auth().isAdmin)`, '')
    const r = accessOf(GUARDED, after)
    expect(r.verdict).toBe('widens')
    expect(about(r, 'User.role')!.detail).toContain(`@allow('write') removed`)
  })

  it('a field-level @allow whose predicate moved is undecidable, not a widening', () => {
    const after = GUARDED.replace('auth().isAdmin', 'auth().isOwner')
    const r = accessOf(GUARDED, after)
    expect(r.verdict).toBe('unknown')
    expect(about(r, 'User.role')!.detail).toContain('not decidable')
  })

  it('a gate eased per operation names the level it dropped to', () => {
    const r = accessOf(GUARDED, GUARDED.replace('@@gate("4.4.5.6")', '@@gate("0.4.5.6")'))
    expect(about(r, 'gate')!.detail).toContain('read drops to STRANGER')
  })

  it('the FIRST transition on a field narrows it; the second widens', () => {
    const free  = GUARDED.replace(/\n  @@transitions.*/, '')
    const one   = GUARDED.replace(', retire: live -> archived', '')

    expect(accessOf(free, one).verdict).toBe('narrows')      // nothing → one legal move
    expect(accessOf(one, GUARDED).verdict).toBe('widens')    // one → two legal moves
  })

  it('a protection removed widens and a protection added narrows', () => {
    expect(accessOf(GUARDED, GUARDED.replace('@secret', '')).verdict).toBe('widens')
    expect(accessOf(GUARDED.replace('@secret', ''), GUARDED).verdict).toBe('narrows')
  })

  it('carries nothing that is not about access — a dropped column is not a permission change', () => {
    const after = GUARDED.replace('  email         String   @unique\n', '')
    expect(accessOf(GUARDED, after).findings).toHaveLength(0)
    expect(classifyPivot(surface(GUARDED), surface(after)).verdict).toBe('contract')
  })
})

describe('the verdict is the alarming answer, not the common one', () => {
  it('nine narrowings and one widening is a widening', () => {
    const before = GUARDED
    const after  = GUARDED
      .replace(`@allow('write', auth().isAdmin)`, '')                 // widens
      .replace('@@gate("4.4.5.6")', '@@gate("6.6.6.6")')              // narrows, four ops
      .replace('publish: draft -> live @gate(5)', 'publish: draft -> live @gate(7)')

    const r = accessOf(before, after)
    expect(r.counts.narrows).toBeGreaterThan(r.counts.widens)
    expect(r.verdict).toBe('widens')
    expect(r.findings[0].access).toBe('widens')   // worst first
  })
})
