// The pivot classifier — can Release N-1 and Release N serve one database?
//
// Every case below is a change to a schema and the answer the deploy is owed.
// Two rules the suite exists to hold:
//
//   1. A wrong EXPAND is the only answer that costs anything. Where the
//      classifier cannot tell, it says so, and unknown counts as a contract.
//   2. The snapshot holds the surface and never the verdict, so rendering it
//      twice over one schema produces one file. A generated file that depends
//      on its own previous contents cannot be rechecked, and the whole CI phase
//      rests on it being rechecked.

import { describe, it, expect } from 'bun:test'
import { parse } from '../src/core/parser.js'
import { deriveReleaseSurface, renderReleaseSnapshot, classifyPivot, classifyAccess } from '../src/release.js'
import { renderJsonSchemaSnapshot } from '../src/tools/jsonschema-snapshot.js'

const surface = (text: string) => {
  const parsed = parse(text)
  if (!parsed.valid) throw new Error(`fixture does not parse: ${parsed.errors?.join(', ')}`)
  return deriveReleaseSurface(parsed.schema)
}

const verdictOf = (before: string, after: string) => classifyPivot(surface(before), surface(after))

/** The finding for one subject, so a case asserts the sentence it is about. */
const about = (result: any, needle: string) =>
  result.findings.find((f: any) => `${f.subject} ${f.detail}`.includes(needle))

const BASE = `
model Order {
  id        Int      @id
  reference String   @unique
  total     Float    @default(0)
  note      String?
  status    Status   @default("pending")
  @@gate("2.4.4.5")
}

enum Status { pending paid shipped }
`

describe('release surface', () => {
  it('names what a release binds to, sorted so an insert does not shift the file', () => {
    const s = surface(BASE)
    expect(s.models.map(m => m.name)).toEqual(['Order'])
    expect(s.models[0].fields.map(f => f.name)).toEqual(['id', 'note', 'reference', 'status', 'total'])
    expect(s.models[0].table).toBe('order')
    expect(s.models[0].gate).toBe('2.4.4.5')
    expect(s.enums[0].values).toEqual(['paid', 'pending', 'shipped'])
  })

  it('marks the one field shape an N-1 write cannot omit', () => {
    const s = surface(BASE)
    const f = (n: string) => s.models[0].fields.find(x => x.name === n)!

    expect(f('reference').writeRequired).toBe(true)   // NOT NULL, no default
    expect(f('total').writeRequired).toBe(false)      // has a SQL default
    expect(f('note').writeRequired).toBe(false)       // optional
    expect(f('id').writeRequired).toBe(false)         // SQLite assigns it
  })

  it('does not answer nullability or a default for a field with no column', () => {
    const s = surface(`
      model Author { id Int @id  books Book[] }
      model Book   { id Int @id  authorId Int  author Author @relation(fields: [authorId], references: [id]) }
    `)
    const books = s.models.find(m => m.name === 'Author')!.fields.find(f => f.name === 'books')!
    expect(books.kind).toBe('relation')
    expect(books.optional).toBeNull()
    expect(books.default).toBeNull()
  })

  it('renders the same bytes twice, and names its own generator', () => {
    const body = renderReleaseSnapshot(surface(BASE), { source: 'schema.lite' })
    expect(body).toBe(renderReleaseSnapshot(surface(BASE), { source: 'schema.lite' }))
    expect(body).toContain('generated by: litestone release --schema schema.lite')
  })

  it('holds no verdict — the file describes one schema, a verdict is about two', () => {
    const body = renderReleaseSnapshot(surface(BASE), { source: 'schema.lite' }).toLowerCase()
    expect(body).not.toContain('expand —')
    expect(body).not.toContain('contract —')
  })
})

describe('expand — N-1 keeps serving', () => {
  it('an added model', () => {
    const r = verdictOf(BASE, BASE + `\nmodel Refund { id Int @id  amount Float @default(0) }`)
    expect(r.verdict).toBe('expand')
  })

  it('an added optional column', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note String?\n  memo String?'))
    expect(r.verdict).toBe('expand')
  })

  it('an added column with a default — an N-1 insert still lands', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note String?\n  channel String @default("web")'))
    expect(r.verdict).toBe('expand')
    expect(about(r, 'Order.channel')!.severity).toBe('expand')
  })

  it('an added enum member — the CHECK widens', () => {
    const r = verdictOf(BASE, BASE.replace('{ pending paid shipped }', '{ pending paid shipped refunded }'))
    expect(r.verdict).toBe('expand')
    expect(about(r, 'enum Status')!.detail).toContain('no branch for')
  })

  it('an added index — it changes how long a query takes and nothing it answers', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', '@@gate("2.4.4.5")\n  @@index([total])'))
    expect(r.verdict).toBe('expand')
  })

  it('an eased gate', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', '@@gate("0.4.4.5")'))
    expect(r.verdict).toBe('expand')
  })

  it('a removed @unique', () => {
    const r = verdictOf(BASE, BASE.replace('String   @unique', 'String'))
    expect(r.verdict).toBe('expand')
  })

  it('nothing at all', () => {
    const r = verdictOf(BASE, BASE)
    expect(r.verdict).toBe('unchanged')
    expect(r.findings).toEqual([])
  })
})

describe('contract — the deploy is the pivot', () => {
  it('a removed column, which N-1 still reads', () => {
    const r = verdictOf(BASE, BASE.replace('  note      String?\n', ''))
    expect(r.verdict).toBe('contract')
    expect(about(r, 'Order.note')!.detail).toContain('N-1')
  })

  it('a removed model', () => {
    expect(verdictOf(BASE + `\nmodel Refund { id Int @id }`, BASE).verdict).toBe('contract')
  })

  it('an added required column with no default — and it hands back the split', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note String?\n  channel String'))
    expect(r.verdict).toBe('contract')

    const f = about(r, 'Order.channel')!
    expect(f.detail).toContain('refused')
    expect(f.split).toHaveLength(3)
    expect(f.split[0]).toContain('optional')
    expect(f.split[1]).toContain('backfill')
    expect(f.split[2]).toContain('pivot')
  })

  it('a column made required — existing NULLs fail the constraint', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note      String '))
    expect(r.verdict).toBe('contract')
    expect(about(r, 'Order.note')!.split).toHaveLength(3)
  })

  it('a column made optional — this release may write a NULL N-1 has no case for', () => {
    const r = verdictOf(BASE, BASE.replace('total     Float    @default(0)', 'total Float? @default(0)'))
    expect(r.verdict).toBe('contract')
  })

  it('a changed type', () => {
    const r = verdictOf(BASE, BASE.replace('total     Float', 'total     Int  '))
    expect(r.verdict).toBe('contract')
  })

  it('an added @unique — an N-1 write that duplicates is now refused', () => {
    const r = verdictOf(BASE, BASE.replace('total     Float    @default(0)', 'total Float @default(0) @unique'))
    expect(r.verdict).toBe('contract')
  })

  it('an added @@unique', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', '@@gate("2.4.4.5")\n  @@unique([reference, total])'))
    expect(r.verdict).toBe('contract')
  })

  it('a removed enum member — every N-1 write of it is refused', () => {
    const r = verdictOf(BASE, BASE.replace('{ pending paid shipped }', '{ pending paid }'))
    expect(r.verdict).toBe('contract')
  })

  it('a renamed table under a release that binds to the old name', () => {
    const r = verdictOf(BASE, BASE.replace('model Order {', 'model Order {\n  @@map("orders")'))
    expect(r.verdict).toBe('contract')
  })

  it('a raised gate — the half no generic deployer can see', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', '@@gate("4.4.4.5")'))
    expect(r.verdict).toBe('contract')
    expect(about(r, 'model Order')!.detail).toContain('read needs USER')
  })

  it('an added row policy — the failure that arrives as a 200', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', `@@gate("2.4.4.5")\n  @@allow('read', total > 0)`))
    expect(r.verdict).toBe('contract')
    expect(about(r, '@@allow(`read`) added')!.detail).toContain('200')
  })

  it('one policy declaration is one finding, not one per operation it expands to', () => {
    const r = verdictOf(BASE, BASE.replace('@@gate("2.4.4.5")', `@@gate("2.4.4.5")\n  @@allow('all', total > 0)`))
    const policy = r.findings.filter((x: any) => x.detail.includes('@@allow'))

    expect(policy).toHaveLength(1)
    expect(policy[0].detail).toContain('read')
    expect(policy[0].detail).toContain('delete')
  })

  it('@@softDelete turned on — delete means something different in the two releases', () => {
    const r = verdictOf(BASE, BASE.replace('  note      String?', '  note String?\n  deletedAt DateTime?').replace('@@gate("2.4.4.5")', '@@gate("2.4.4.5")\n  @@softDelete'))
    expect(r.verdict).toBe('contract')
  })

  it('a protection added — the column leaves every answer N-1 reads', () => {
    const r = verdictOf(BASE, BASE.replace('note      String?', 'note String? @guarded(all)'))
    expect(r.verdict).toBe('contract')
    expect(about(r, 'Order.note')!.detail).toContain('@guarded')
  })
})

describe('unknown — counts as a contract, because a wrong "reversible" is the costly answer', () => {
  it('a policy predicate that moved: nothing here can say which way', () => {
    const before = BASE.replace('@@gate("2.4.4.5")', `@@gate("2.4.4.5")\n  @@allow('read', total > 0)`)
    const after  = BASE.replace('@@gate("2.4.4.5")', `@@gate("2.4.4.5")\n  @@allow('read', total > 100)`)
    const r = verdictOf(before, after)
    expect(r.verdict).toBe('unknown')
    expect(about(r, '@@allow(`read`) predicate changed')!.detail).toContain('not decidable')
  })

  it('a value that moved from a column to a computed field', () => {
    const before = BASE
    const after  = BASE.replace('total     Float    @default(0)', 'total Float @computed')
    expect(verdictOf(before, after).verdict).toBe('unknown')
  })
})

describe('the verdict is the worst finding, not the most common one', () => {
  it('nine expands and one contract is a contract', () => {
    const after = BASE
      .replace('note      String?', 'note String?\n  a String?\n  b String?\n  c String?')
      .replace('{ pending paid shipped }', '{ pending paid }')

    const r = verdictOf(BASE, after)
    expect(r.counts.expand).toBeGreaterThan(0)
    expect(r.counts.contract).toBe(1)
    expect(r.verdict).toBe('contract')
    expect(r.findings[0].severity).toBe('contract')   // worst first
  })
})

// ─── the access axis ─────────────────────────────────────────────────────────
//
// The same walk, graded on the other question. The suite's job here is to hold
// the two axes apart: they are not correlated and they are not opposites, and
// the case that proves it is the one below where every widening is an expand.

const accessOf = (before: string, after: string) => classifyAccess(surface(before), surface(after))

const GUARDED = `
model User {
  id            Int      @id
  email         String   @unique
  role          String   @default("user") @allow('write', auth().isAdmin)
  apiKey        String?  @secret
  status        Status   @default("draft")
  @@gate("4.4.5.6")
  @@allow('read', id == auth().id)
  @@transitions(status, publish: draft -> live @gate(5), retire: live -> archived)
}

enum Status { draft live archived }
`

describe('the deploy axis and the access axis disagree, which is why there are two', () => {
  it('every widening in this change is an EXPAND for the deploy', () => {
    const after = GUARDED
      .replace(`@allow('write', auth().isAdmin)`, '')
      .replace('@secret', '')
      .replace('@@gate("4.4.5.6")', '@@gate("2.4.5.6")')
      .replace(`  @@allow('read', id == auth().id)\n`, '')
      .replace('publish: draft -> live @gate(5)', 'publish: draft -> live')

    const access = accessOf(GUARDED, after)
    const pivot  = classifyPivot(surface(GUARDED), surface(after))

    expect(access.verdict).toBe('widens')
    expect(access.counts.widens).toBe(5)

    // The claim, executed: a reviewer handed the deploy severity for these five
    // reads green on all of them.
    const severityOf = (subject: string, detail: string) =>
      pivot.findings.find((f: any) => f.subject === subject && f.detail === detail)!.severity

    for (const w of access.findings.filter((f: any) => f.access === 'widens'))
      expect(severityOf(w.subject, w.detail)).toBe('expand')
  })

  it('the one change that narrows is the one the deploy calls a contract', () => {
    const after = GUARDED.replace('retire: live -> archived', 'retire: live -> archived @gate(6)')
    const r = accessOf(GUARDED, after)
    expect(r.verdict).toBe('narrows')
    expect(about(r, 'status.retire')!.severity).toBe('contract')
  })
})

describe('what a permission diff has to see', () => {
  it('a field-level @allow removed — the shape that guards isSystemAdmin and role', () => {
    const after = GUARDED.replace(`@allow('write', auth().isAdmin)`, '')
    const r = accessOf(GUARDED, after)
    expect(r.verdict).toBe('widens')
    expect(about(r, 'User.role')!.detail).toContain(`@allow('write') removed`)
  })

  it('a field-level @allow whose predicate moved is undecidable, not a widening', () => {
    const after = GUARDED.replace('auth().isAdmin', 'auth().isOwner')
    const r = accessOf(GUARDED, after)
    expect(r.verdict).toBe('unknown')
    expect(about(r, 'User.role')!.detail).toContain('not decidable')
  })

  it('a gate eased per operation names the level it dropped to', () => {
    const r = accessOf(GUARDED, GUARDED.replace('@@gate("4.4.5.6")', '@@gate("0.4.5.6")'))
    expect(about(r, 'gate')!.detail).toContain('read drops to STRANGER')
  })

  it('the FIRST transition on a field narrows it; the second widens', () => {
    const free  = GUARDED.replace(/\n  @@transitions.*/, '')
    const one   = GUARDED.replace(', retire: live -> archived', '')

    expect(accessOf(free, one).verdict).toBe('narrows')      // nothing → one legal move
    expect(accessOf(one, GUARDED).verdict).toBe('widens')    // one → two legal moves
  })

  it('a protection removed widens and a protection added narrows', () => {
    expect(accessOf(GUARDED, GUARDED.replace('@secret', '')).verdict).toBe('widens')
    expect(accessOf(GUARDED.replace('@secret', ''), GUARDED).verdict).toBe('narrows')
  })

  it('carries nothing that is not about access — a dropped column is not a permission change', () => {
    const after = GUARDED.replace('  email         String   @unique\n', '')
    expect(accessOf(GUARDED, after).findings).toHaveLength(0)
    expect(classifyPivot(surface(GUARDED), surface(after)).verdict).toBe('contract')
  })
})

describe('the verdict is the alarming answer, not the common one', () => {
  it('nine narrowings and one widening is a widening', () => {
    const before = GUARDED
    const after  = GUARDED
      .replace(`@allow('write', auth().isAdmin)`, '')                 // widens
      .replace('@@gate("4.4.5.6")', '@@gate("6.6.6.6")')              // narrows, four ops
      .replace('publish: draft -> live @gate(5)', 'publish: draft -> live @gate(7)')

    const r = accessOf(before, after)
    expect(r.counts.narrows).toBeGreaterThan(r.counts.widens)
    expect(r.verdict).toBe('widens')
    expect(r.findings[0].access).toBe('widens')   // worst first
  })
})

// ─── value sets ───────────────────────────────────────────────────────────────
//
// A `@values` binding is a rule about which values are legal, declared in one
// place and enforced at the Data boundary — so a column gaining a `required`
// one starts refusing writes N-1 has been making all along, with no column, no
// type and no constraint moving. Nothing else in the surface can see it.
//
// The severity is not a ladder over the three strengths. Only `required`
// refuses: `open` accepts a value outside the set and adds it, and `suggested`
// enforces nothing at all.

const VS = ({ scope = '', where = '', value = 'code', strength = '', second = '' } = {}) => `
model Tag {
  id   Int    @id
  code String @unique
  slug String @unique
  name String
  team String?
  @@label(name)
  @@scope(mine, team == auth().team)
}

valueset TaskTag { source Tag  value ${value}${scope}${where} }
${second}
model Task {
  id    Int     @id
  title String
  tag   String? @values(TaskTag${strength})
}
`

/** The same schema with no binding on `tag` at all. */
const VS_UNBOUND = VS().replace(/ @values\(TaskTag[^)]*\)/, '')

describe('value sets — a rule about legal values, which no other line of the surface carries', () => {
  it('carries the set and the binding', () => {
    const s = surface(VS())
    expect(s.valuesets).toEqual([{ name: 'TaskTag', source: 'Tag', value: 'code', scope: null, where: null }])
    expect(s.models.find(m => m.name === 'Task')!.fields.find(f => f.name === 'tag')!.values)
      .toEqual({ set: 'TaskTag', strength: 'required' })
  })

  it('records the resolved value column, so stating the default is not a change', () => {
    // `value` unstated is the source's own @id. A baseline that omitted it and a
    // schema that spells it out describe one set.
    const implicit = surface(VS().replace('value code', ''))
    const explicit = surface(VS().replace('value code', 'value id'))
    expect(implicit.valuesets[0].value).toBe('id')
    expect(classifyPivot(implicit, explicit).verdict).toBe('unchanged')
  })

  it('binding a column as required is a contract — N-1 writes values it now refuses', () => {
    const v = verdictOf(VS_UNBOUND, VS())
    expect(v.verdict).toBe('contract')
    expect(about(v, 'Task.tag')!.detail).toContain('every N-1 write of a value outside')
  })

  it('binding it weakly is an expand — nothing is refused', () => {
    expect(verdictOf(VS_UNBOUND, VS({ strength: ', suggested' })).verdict).toBe('expand')
    expect(verdictOf(VS_UNBOUND, VS({ strength: ', open' })).verdict).toBe('expand')
  })

  it('removing a binding is an expand', () => {
    expect(verdictOf(VS(), VS_UNBOUND).verdict).toBe('expand')
  })

  it('tightening into required is the pivot; every other move between strengths is not', () => {
    const at = (s: string) => VS({ strength: s ? `, ${s}` : '' })

    expect(verdictOf(at('suggested'), at('')).verdict).toBe('contract')
    expect(verdictOf(at('open'),      at('')).verdict).toBe('contract')

    // `suggested` → `open` starts CREATING rows in the source table and still
    // fails nothing N-1 does, which is why the three are not a ladder.
    expect(verdictOf(at('suggested'), at('open')).verdict).toBe('expand')
    expect(verdictOf(at(''), at('open')).verdict).toBe('expand')
    expect(verdictOf(at(''), at('suggested')).verdict).toBe('expand')
  })

  it('cannot compare two different lists', () => {
    const other = `valueset OtherTags { source Tag  value slug }\n`
    const v = verdictOf(VS({ second: other }), VS({ second: other, strength: '' }).replace('@values(TaskTag)', '@values(OtherTags)'))
    expect(v.verdict).toBe('unknown')
    expect(about(v, 'Task.tag')!.detail).toContain('a different list')
  })

  it('narrowing the set is a contract where something binds it as required', () => {
    const v = verdictOf(VS(), VS({ scope: '  scope mine' }))
    expect(v.verdict).toBe('contract')
    expect(about(v, 'valueset TaskTag')!.detail).toContain('scope `mine` added')

    const w = verdictOf(VS(), VS({ where: '  where "archivedAt IS NULL"' }))
    expect(w.verdict).toBe('contract')
  })

  it('…and an expand where nothing enforces it — a picker offers less and nothing refuses', () => {
    const weak = (o = {}) => VS({ ...o, strength: ', suggested' })
    const v = verdictOf(weak(), weak({ scope: '  scope mine' }))
    expect(v.verdict).toBe('expand')
    expect(about(v, 'valueset TaskTag')!.detail).toContain('nothing binds it as `required`')
  })

  it('widening the set is an expand in either spelling', () => {
    expect(verdictOf(VS({ scope: '  scope mine' }), VS()).verdict).toBe('expand')
    expect(verdictOf(VS({ where: '  where "archivedAt IS NULL"' }), VS()).verdict).toBe('expand')
  })

  it('a predicate that moved is undecidable, like every other predicate here', () => {
    const a = VS({ where: '  where "archivedAt IS NULL"' })
    const b = VS({ where: '  where "archivedAt IS NULL AND team IS NOT NULL"' })
    expect(verdictOf(a, b).verdict).toBe('unknown')
  })

  it('changing which column a record stores is a contract whatever the strength', () => {
    // Not gated on enforcement: the stored form changed, so a value N-1 wrote
    // and a value this release writes stop meaning the same thing.
    const v = verdictOf(VS({ strength: ', suggested' }), VS({ value: 'slug', strength: ', suggested' }))
    expect(v.verdict).toBe('contract')
    expect(about(v, 'valueset TaskTag')!.detail).toContain('value column `code` → `slug`')
  })

  it('declaring a set is an expand, and dropping one refuses nothing', () => {
    const other = `valueset OtherTags { source Tag  value slug }\n`
    expect(verdictOf(VS(), VS({ second: other })).verdict).toBe('expand')
    expect(verdictOf(VS({ second: other }), VS()).verdict).toBe('expand')
  })

  it('is not on the access axis — it narrows by value, identically for every caller', () => {
    // `classifyAccess` grades who may do what. A value set says nothing about
    // who, so a reviewer is not shown a permission change that did not happen.
    expect(classifyAccess(surface(VS_UNBOUND), surface(VS())).verdict).toBe('unchanged')
  })

  it('renders into the snapshot, and rendering twice produces one file', () => {
    const s   = surface(VS({ scope: '  scope mine' }))
    const md  = renderReleaseSnapshot(s)

    expect(md).toContain('## Value sets')
    expect(md).toContain('| `TaskTag` | `Tag` | `code` | `mine` | — |')
    expect(md).toContain('`@values(TaskTag, required)`')
    expect(renderReleaseSnapshot(surface(VS({ scope: '  scope mine' })))).toBe(md)
  })

  it('says nothing about value sets in a schema that declares none', () => {
    expect(renderReleaseSnapshot(surface(BASE))).not.toContain('value set')
  })
})

// ─── what the access axis was blind to ───────────────────────────────────────
//
// Two failures, opposite directions, one walk:
//
//   • **FJS-444** — a model absent from the baseline has no counterpart, so
//     every per-model rule skipped it and it left the access axis entirely. A
//     branch that added nine gated tables to `example` reported *no change to
//     who may do what*. Defensible by the axis's own definition (nobody could
//     do anything with a table that did not exist) and useless to the reviewer
//     who ran the command to ask what the branch did to access.
//
//   • **FJS-380** — an allow→deny inversion is one change that reads as two,
//     and the classifier took the worst half. Measured on basecamp adopting
//     declared tenancy: verdict WIDENS on the safest refactor there is.

const NEWMODEL = (extra = '') => `
model Post {
  id     Int    @id
  title  String
  @@gate("2.4.4.5")
}
${extra}`

describe('a model the baseline never had (FJS-444)', () => {
  it('is reported, with what it declares about access', () => {
    const r = accessOf(NEWMODEL(), NEWMODEL(`
model Secret {
  id    Int    @id
  token String @secret
  @@gate("8.8.8.8")
}`))
    expect(r.verdict).toBe('new')
    expect(r.counts.new).toBe(1)
    const f = r.findings.find((x: any) => x.subject === 'model Secret')!
    expect(f.access).toBe('new')
    expect(f.accessDetail).toContain('@@gate("8.8.8.8")')
    expect(f.accessDetail).toContain('1 protected field')
  })

  it('names the unrestricted case, which is the one worth stopping on', () => {
    const r = accessOf(NEWMODEL(), NEWMODEL(`
model Open {
  id Int @id
}`))
    expect(r.findings.find((x: any) => x.subject === 'model Open')!.accessDetail)
      .toContain('declares neither @@gate nor @@allow — every caller reaches every row')
  })

  it('is ranked below narrows, so a branch that also narrows still reads as narrowing', () => {
    const r = accessOf(NEWMODEL(), NEWMODEL().replace('@@gate("2.4.4.5")', '@@gate("4.4.4.5")') + `
model Extra {
  id Int @id
  @@gate("2.2.2.2")
}`)
    expect(r.verdict).toBe('narrows')
    expect(r.counts.new).toBe(1)
  })

  it('grades the deploy axis as it always did — a new model is an expand', () => {
    const before = surface(NEWMODEL())
    const after  = surface(NEWMODEL(`model Extra { id Int @id }`))
    const p = classifyPivot(before, after)
    expect(p.verdict).toBe('expand')
    expect(p.findings.find((x: any) => x.subject === 'model Extra')!.severity).toBe('expand')
  })

  it('reports a REMOVED model as narrowing — nothing reaches it through the client now', () => {
    const r = accessOf(NEWMODEL(`model Gone { id Int @id  @@gate("2.4.4.5") }`), NEWMODEL())
    expect(r.verdict).toBe('narrows')
    expect(r.findings.find((x: any) => x.subject === 'model Gone')!.access).toBe('narrows')
  })
})

const OWNED = (policy: string) => `
model Doc {
  id          Int    @id
  workspaceId Int
  title       String
  @@gate("2.4.4.5")
${policy}
}
`

describe('an allow→deny inversion (FJS-380)', () => {
  const ALLOW = `  @@allow('all', workspaceId == auth().workspaceId)`
  const DENY  = `  @@deny('all', workspaceId != auth().workspaceId)`

  it('is undecidable, not a widening', () => {
    const r = accessOf(OWNED(ALLOW), OWNED(DENY))
    expect(r.verdict).toBe('unknown')
    expect(r.counts.widens).toBe(0)
  })

  it('is ONE finding on the access axis and two on the deploy one', () => {
    const before = surface(OWNED(ALLOW)), after = surface(OWNED(DENY))
    const a = classifyAccess(before, after)
    const p = classifyPivot(before, after)

    expect(a.findings.filter((x: any) => x.subject === 'model Doc')).toHaveLength(1)
    // The deploy still sees both halves, and they still disagree: removing an
    // allow is an expand, adding a deny is a contract.
    const both = p.findings.filter((x: any) => x.subject === 'model Doc')
    expect(both.map((x: any) => x.severity).sort()).toEqual(['contract', 'expand'])
  })

  it('says what it saw rather than deciding it', () => {
    const f = accessOf(OWNED(ALLOW), OWNED(DENY)).findings[0]
    expect(f.accessDetail).toContain('replaced by a @@deny over the same operations')
    expect(f.accessDetail).toContain('not decidable from the text')
  })

  it('an allow removed with NO deny behind it is still a widening', () => {
    const r = accessOf(OWNED(ALLOW), OWNED(''))
    expect(r.verdict).toBe('widens')
    expect(r.counts.widens).toBe(1)
  })

  it('a deny added with no allow removed is still a narrowing', () => {
    const r = accessOf(OWNED(''), OWNED(DENY))
    expect(r.verdict).toBe('narrows')
  })

  it('a PARTIAL overlap is not an inversion — the bare half is a real widening', () => {
    // Some operations inverted, some left bare. Grading the bare half as
    // undecidable would hide a widening inside a refactor, which is the failure
    // this axis exists to catch.
    const r = accessOf(
      OWNED(`  @@allow('all', workspaceId == auth().workspaceId)`),
      OWNED(`  @@deny('read', workspaceId != auth().workspaceId)`))
    expect(r.counts.widens).toBe(1)
    expect(r.verdict).toBe('widens')
  })
})

// ─── @@check is a compatibility question ─────────────────────────────────────
//
// A row invariant is the one constraint that changes what a WRITE is allowed to
// be without changing what a read answers, so it lands on this axis and on no
// other. The release still serving knows nothing about a new one and keeps
// writing rows it forbids — refusals from a version that was working a minute
// ago, which is the definition of a contract.
describe('@@check in the release surface', () => {
  const surface = (body: string) => deriveReleaseSurface(parse(
    `model B { id String @id  startsAt DateTime  endsAt DateTime${body} }`).schema)

  const BARE  = ''
  const DATES = '\n  @@check("startsAt < endsAt", "an end must come after its start")'

  it('is in the surface, so the committed snapshot carries it', () => {
    expect(surface(DATES).models[0].checks).toEqual(['startsAt < endsAt'])
    expect(renderReleaseSnapshot(surface(DATES))).toContain('@@check(startsAt < endsAt)')
  })

  it('adding one is a contract — the pivot', () => {
    const r = classifyPivot(surface(BARE), surface(DATES))
    expect(r.verdict).toBe('contract')
    expect(r.findings.some(f => f.detail.includes('@@check(startsAt < endsAt) added'))).toBe(true)
  })

  // Every row the old constraint admitted is still admitted, so nothing the
  // previous release can write stops being writable.
  it('removing one is an expand', () => {
    const r = classifyPivot(surface(DATES), surface(BARE))
    expect(r.verdict).toBe('expand')
  })

  // The expression IS the identity: SQLite cannot alter a CHECK in place, and a
  // different expression is a different rule.
  it('editing the expression reads as one removed and one added', () => {
    const r = classifyPivot(surface(DATES), surface('\n  @@check("startsAt <= endsAt")'))
    expect(r.verdict).toBe('contract')
    expect(r.counts.contract).toBe(1)
    expect(r.counts.expand).toBe(1)
  })
})

// ─── @system on a transition ─────────────────────────────────────────────────
//
// The widest narrowing a state machine can make, and for its whole life it
// produced no diff in any committed artefact (`FJS-613`). `@system` says the
// APPLICATION makes the move — from *any caller at the update level, subject to
// the row policies* to *no caller, ever* — and all three surfaces carried the
// `@gate(n)` alone, so `cancel: … @system` and `cancel: …` rendered identically.
//
// The negative control is the measurement the row was filed on: two schemas
// differing in that one token. Every assertion below fails against the code as
// it stood, and the FIRST one is the whole of the defect.

describe('@@transitions — @system reaches the artefacts a reviewer reads', () => {
  const MOVES = (tok: string) => `
model Sub {
  id     Int    @id
  status SubState @default("trialing")
  @@gate("4.4.4.5")
  @@transitions(status, cancel: [trialing, active] -> cancelled${tok})
}

enum SubState { trialing active cancelled }
`
  const OPEN = MOVES(''), SYS = MOVES(' @system')

  it('the release surface holds it, so the snapshot two schemas produce differ', () => {
    expect(renderReleaseSnapshot(surface(OPEN)))
      .not.toBe(renderReleaseSnapshot(surface(SYS)))
    expect(renderReleaseSnapshot(surface(SYS))).toContain('@system')
  })

  // The third artefact, and the one a SCREEN is derived from: `x-transitions`
  // carried `system` all along, so a client rendered no button — and the
  // committed document that exists to make a keyword going away a diff dropped
  // it at render, which is the one place anybody would have noticed.
  it('the jsonschema snapshot carries it, because a client renders no button for one', () => {
    const doc = (text: string) =>
      renderJsonSchemaSnapshot(parse(text).schema, { command: 'litestone jsonschema' })
    expect(doc(OPEN)).not.toBe(doc(SYS))
    expect(doc(SYS)).toContain('`cancel`: trialing|active → cancelled @system')
  })

  it('gaining it narrows, and it is a contract for the deploy', () => {
    const r = accessOf(OPEN, SYS)
    expect(r.verdict).toBe('narrows')
    expect(about(r, 'status.cancel')!.detail).toContain('no caller reaches it at any level')
    expect(classifyPivot(surface(OPEN), surface(SYS)).verdict).toBe('contract')
  })

  it('losing it widens — a move the application owned is handed to a caller', () => {
    const r = accessOf(SYS, OPEN)
    expect(r.verdict).toBe('widens')
    expect(about(r, 'status.cancel')!.detail).toContain('no longer @system')
    expect(classifyPivot(surface(SYS), surface(OPEN)).verdict).toBe('expand')
  })

  // The two COMPOSE — `@system @gate(5)` is a move the engine decides on behalf
  // of a caller senior enough to ask — so folding one into the other loses the
  // distinction exactly where it is hardest to see. basecamp declares four.
  it('is not the gate: @system @gate(5) is distinguishable from @gate(5) alone', () => {
    const gated  = MOVES(' @gate(5)')
    const both   = MOVES(' @system @gate(5)')
    expect(renderReleaseSnapshot(surface(gated))).not.toBe(renderReleaseSnapshot(surface(both)))

    const r = accessOf(gated, both)
    expect(r.verdict).toBe('narrows')
    // The gate did not move, so nothing but the system flag may be reported.
    expect(r.findings).toHaveLength(1)
  })

  // A gate change and a system change on one move are two findings, or the
  // stronger one hides the weaker: raising the gate while making it @system
  // reads as an ordinary level bump.
  it('a gate change beside it is reported separately', () => {
    const r = accessOf(MOVES(''), MOVES(' @system @gate(5)'))
    expect(r.counts.narrows).toBe(2)
  })
})
