-- Schema snapshot — DDL
--
-- generated by: litestone ddl --schema schema.lite
--
-- The DDL this schema emits — the tables, indexes, triggers and views a fresh
-- database is given. Do not edit; regenerate and read the diff. Columns are
-- emitted verbatim camelCase and DateTime as ISO-8601 TEXT, so hand-written SQL
-- binds to exactly these names and nothing else in an app can see one move.
-- Fragments an app merges at runtime are not in this file.
--
-- 4 models · 2 databases

-- ─── database main · sqlite ──────────────────────────────────────────────
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "product" (
  "id" INTEGER NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "sku" TEXT NOT NULL UNIQUE,
  "price" REAL NOT NULL,
  "barcode" TEXT UNIQUE,
  "active" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE TABLE IF NOT EXISTS "customer" (
  "id" INTEGER NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "notes" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE TABLE IF NOT EXISTS "notification" (
  "id" INTEGER NOT NULL PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "contextType" TEXT,
  "contextId" INTEGER,
  "readAt" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
) STRICT;

CREATE TABLE IF NOT EXISTS "order" (
  "id" INTEGER NOT NULL PRIMARY KEY,
  "reference" TEXT NOT NULL UNIQUE,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "total" REAL NOT NULL DEFAULT 0,
  "note" TEXT,
  "customerId" INTEGER NOT NULL,
  "trackingCode" TEXT,
  "createdAt" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CHECK ("status" IN ('pending', 'paid', 'shipped', 'refunded', 'cancelled')),
  FOREIGN KEY ("customerId") REFERENCES "customer" ("id") ON DELETE CASCADE
) STRICT;

-- ─── database audit · logger ─────────────────────────────────────────────
-- No DDL — a logger database has no schema. 0 model(s)
