// AUTO-GENERATED by @frontierjs/jetty — do not edit.
import islandModule from "/home/j/code/FRONTIER/frontierjs/example/extension/src/islands/stock-badge.js"
import { runIsland } from "/home/j/code/FRONTIER/frontierjs/packages/jetty/src/island/index.js"

// MV3 content scripts are loaded as CLASSIC scripts — top-level await
// causes a parse-time SyntaxError ("await is only valid in async functions
// and the top level bodies of modules"). Wrap the bootstrap in an async
// IIFE so the await is inside a function body.
//
// Errors from runIsland are caught and logged but don't propagate; nothing
// catches an unhandled promise rejection at the content-script level
// anyway, so making them visible in the page console is the best we can do.
;(async () => {
  try {
    await runIsland(islandModule, { id: "stock-badge", type: 'island' })
  } catch (err) {
    console.error('[jetty:island:stock-badge] bootstrap failed:', err)
  }
})()
