// ─── ask.test.js — the router, and the traps it was wrong about first ────────
//
// Every case below is a miss the graded set actually produced. They are kept as
// tests rather than as a changelog because each one is a different way for a
// lookup to be CONFIDENTLY wrong, which is the only failure mode that matters
// here: an `ambiguous` sends somebody to read two rows, and a wrong `resolved`
// sends them to the wrong file believing it is the right one.

import { describe, expect, test } from 'bun:test'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'fs'
import { join, dirname }                         from 'path'
import { tmpdir }                                from 'os'

import { ask, classify, scoreQuestions } from '../core/ask.js'
import { QUESTIONS }                     from '../core/questions.js'

const ROOT = mkdtempSync(join(tmpdir(), 'fli-ask-'))

function tree(name, files) {
  const dir = join(ROOT, name)
  for (const [path, body] of Object.entries(files)) {
    const full = join(dir, path)
    mkdirSync(dirname(full), { recursive: true })
    writeFileSync(full, body)
  }
  return dir
}

const SEAMS = (rows) => ({
  'seams.snapshot.md': `<!-- generated by: fli ws:seams -->\n\n## Data → API\n\n| Seam | Owner | Declared in | Other sites |\n| --- | --- | --- | --- |\n${rows}\n`,
})

describe('classify', () => {
  test('owner is asked before locate, because `which file owns` contains `which file`', () => {
    expect(classify('which file owns matchesQuery').intent).toBe('owner')
    expect(classify('which file holds the port formula').intent).toBe('locate')
  })

  test('blast is asked first — `how do i prove` is not a recipe', () => {
    expect(classify('how do i prove a change to the gate').intent).toBe('blast')
    expect(classify('how do i declare a job').intent).toBe('recipe')
  })

  test('the trigger words come back out of the subject', () => {
    expect(classify('who owns $setAuth').subject).toBe('$setauth')
    // `change` and `proves` are scaffolding in every blast question and carry
    // nothing: leaving them in tied `verify:values` against `verify:live`.
    expect(classify('what proves a change to a valueset').subject).toBe('to valueset')
  })
})

describe('matching', () => {
  test('a substring is not a match — `port` is not `transport`', () => {
    const root = tree('ask-sub', {
      ...SEAMS('| `wsSend()` | `packages/junction/src/transport/send-queue.ts` | yes | — |'),
      'CLAUDE.md': '# x\n\n`packages/cli/core/ports.js` is the schema — the formula and the category map.\n',
    })
    const a = ask({ root, text: 'where does the port formula live' })
    expect(a.status).toBe('resolved')
    expect(a.hits[0].cite).toBe('packages/cli/core/ports.js')
  })

  test('a key is compared the way a NAME is — `port` reaches `ports.js`', () => {
    const root = tree('ask-inflect', {
      'CLAUDE.md': '# x\n\n`packages/cli/core/ports.js` owns the allocator.\n',
    })
    expect(ask({ root, text: 'where is the port allocator' }).hits[0].cite)
      .toBe('packages/cli/core/ports.js')
  })

  test('a two-letter name is a name — `ui` was filtered out as noise', () => {
    const root = tree('ask-ui', {
      'packages/ui/CLAUDE.md':        '# ui\n\nMesa component kit.\n',
      'packages/litestone/CLAUDE.md': '# litestone\n\nSchema language and client.\n',
    })
    expect(ask({ root, text: 'how do i contribute a control to the ui kit' }).hits[0].cite)
      .toBe('packages/ui/CLAUDE.md')
  })

  test('a compound matches as a unit — `pay run` may not score against a key of `pay`', () => {
    const root = tree('ask-pair', {
      'DRIVES.md': [
        '| `example`: `verify:pay` | seed | money, and the one caller that is not a person |',
        '| `example`: `verify:payrun` | seed | one period, everybody, and the two documents |',
      ].join('\n') + '\n',
    })
    const a = ask({ root, text: 'what proves a change to a pay run' })
    expect(a.status).toBe('resolved')
    expect(a.hits[0].cite).toBe('example:verify:payrun')
  })

  test('two rows naming one answer are not ambiguous', () => {
    // A drive has a row in each of DRIVES.md's two tables, and they tied with
    // each other — reported as *I cannot choose* about a question with one answer.
    const root = tree('ask-dupe', {
      'DRIVES.md': [
        '| `example`: `verify:values` | seed | a declared valueset and what a picker offers |',
        '| a valueset — `db/schema.lite` | `example`: `verify:values` — the offered list |',
      ].join('\n') + '\n',
    })
    expect(ask({ root, text: 'what proves a change to a valueset' }).status).toBe('resolved')
  })

  test('a real tie is ambiguous and names both — never the likelier one', () => {
    const root = tree('ask-tie', {
      'DRIVES.md': [
        '| `example`: `verify:one` | seed | a widget on a page |',
        '| `example`: `verify:two` | seed | a widget on a page |',
      ].join('\n') + '\n',
    })
    const a = ask({ root, text: 'what proves a change to a widget' })
    expect(a.status).toBe('ambiguous')
    expect(a.hits).toHaveLength(2)
  })

  test('nothing matching is missing, not a guess', () => {
    const root = tree('ask-miss', { ...SEAMS('| `wsSend()` | `packages/junction/src/x.ts` | yes | — |') })
    expect(ask({ root, text: 'who owns the quantum flux capacitor' }).status).toBe('missing')
  })
})

describe('the graded set', () => {
  const root = process.cwd().includes('/packages/cli')
    ? join(process.cwd(), '..', '..')
    : process.cwd()

  test('every citation in the answer key still resolves in the tree', () => {
    // The key is written against the tree, so a citation that stops resolving
    // is the tree having moved — and the score would go on reporting a number
    // for a question nothing could answer.
    const dec = readFileSync(join(root, 'DECISIONS.md'), 'utf8')
    const iss = readFileSync(join(root, 'ISSUES.md'), 'utf8')
    const drv = readFileSync(join(root, 'DRIVES.md'), 'utf8')

    for (const { intent, cite } of QUESTIONS) {
      if (intent === 'ruling')      expect(dec).toContain(`id="${cite.toLowerCase()}"`)
      else if (intent === 'status') expect(iss).toContain(`id="${cite.toLowerCase()}"`)
      else if (intent === 'blast')  {
        const [pkg, ...drive] = cite.split(':')
        expect(drv).toContain(`\`${pkg}\`: \`${drive.join(':')}\``)
      }
      else expect(existsSync(join(root, cite))).toBe(true)
    }
  })

  test('the router answers the set', () => {
    const s = scoreQuestions({ root, questions: QUESTIONS })
    expect(s.intentHits).toBe(s.total)
    expect(s.hits).toBe(s.total)
  })

  test('tokens-to-fact stays small — the whole point of the measurement', () => {
    const s = scoreQuestions({ root, questions: QUESTIONS })
    expect(s.medianRead).toBeLessThan(1200)     // ~300 tokens, a generous ceiling
  })
})
