// doc-audit.test.js — the notes, graded against the tree.
//
// Every rule gets two trees: one that violates it and one that does not. A rule
// with only the first might fire on everything; a rule with only the second
// might fire on nothing, and that one passes — which is the failure this file
// exists to prevent.
//
// The clean tree is deliberately not empty. A document that cites a real file,
// spells a real attribute and states the real count has to come back silent, or
// the rule is measuring the absence of documents rather than their truth.

import { describe, test, expect, beforeAll, afterAll } from 'bun:test'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join }   from 'path'
import { tmpdir } from 'os'

import { docWordUnknown, docCitesDead, docClaimsCount, docInvariantRef,
         docCorpus, maskFences, maskInline, readNumber, invariantCount,
         npmScopes, COUNTABLES } from '../core/doc-audit.js'

let ROOT

function tree(name, files) {
  const dir = join(ROOT, name)
  for (const [path, body] of Object.entries(files)) {
    const full = join(dir, path)
    mkdirSync(join(full, '..'), { recursive: true })
    writeFileSync(full, body)
  }
  return dir
}

// The generated authority every vocabulary rule reads. Two columns matter: the
// word, and the argument cell — `@gate` is legal only inside `@@transitions`
// and lives in the second, which is why the rule reads the table whole.
const CATALOG = `# Litestone language surface

<!-- generated by: litestone catalog --snapshot -->

## Declarations

| word | arity | accepts |
| --- | --- | --- |
| \`model\` | <PascalCaseSingular> { … } |  |
| \`enum\` | <Name> { values… } |  |

## Field attributes

| word | arity | accepts |
| --- | --- | --- |
| \`@id\` |  |  |
| \`@money\` |  |  |
| \`@default\` | (<value>) |  |

## Model attributes

| word | arity | accepts |
| --- | --- | --- |
| \`@@gate\` | ("<n>") |  |
| \`@@transitions\` | (<field>, <from> -> <to> [@gate(N)]) |  |
`

const PKG = JSON.stringify({ name: '@frontierjs/litestone', dependencies: { '@frontierjs/toolbelt': '*' } })

beforeAll(() => { ROOT = mkdtempSync(join(tmpdir(), 'fjs-doc-audit-')) })
afterAll(()  => { rmSync(ROOT, { recursive: true, force: true }) })

// ─── doc-word-unknown ─────────────────────────────────────────────────────────

describe('doc-word-unknown', () => {
  const base = {
    'packages/litestone/catalog.snapshot.md': CATALOG,
    'packages/litestone/package.json':        PKG,
  }

  test('reports a schema word the catalogue does not carry', () => {
    const root = tree('word-bad', { ...base,
      'packages/litestone/docs/traits.md': 'A trait may not hold `@@id([...])` — same reason.\n' })
    const out = docWordUnknown({ root })
    expect(out.findings).toHaveLength(1)
    expect(out.findings[0].message).toContain('@@id')
    expect(out.findings[0].line).toBe(1)
  })

  test('says nothing about words the catalogue carries', () => {
    const root = tree('word-good', { ...base,
      'packages/litestone/docs/schema.md':
        'A column is `@id`, an amount is `@money`, and a move may carry `@gate(5)`.\n' })
    expect(docWordUnknown({ root }).findings).toHaveLength(0)
  })

  test('an npm scope, an at-rule, an address and Mesa are not schema words', () => {
    const root = tree('word-neighbours', { ...base,
      'packages/litestone/docs/a.md':
        'Import `@frontierjs/toolbelt`. CSS has `@starting-style`. Mesa writes `@const`.\n' +
        'A factory seeds `u1@x.com`.\n' })
    expect(docWordUnknown({ root }).findings).toHaveLength(0)
  })

  test('a sentence saying the word does not exist is not a use of it', () => {
    const root = tree('word-denied', { ...base,
      'packages/notifications/README.md': 'Policies are `@@gate` — there is no `@@policy`.\n' })
    expect(docWordUnknown({ root }).findings).toHaveLength(0)
  })

  test('comparative prose about another ORM is left alone', () => {
    const root = tree('word-orm', { ...base,
      'packages/litestone/README.md': 'Prisma supports `@@ignore` to exclude a model.\n' })
    expect(docWordUnknown({ root }).findings).toHaveLength(0)
  })

  test('IDEAS/ proposes words that do not exist yet, and is not graded', () => {
    const root = tree('word-ideas', { ...base,
      'IDEAS/compliance.md': 'A column could declare `@pii` and a database `@retain`.\n' })
    expect(docWordUnknown({ root }).findings).toHaveLength(0)
  })

  test('with no catalogue it skips rather than passing', () => {
    const root = tree('word-nocat', { 'README.md': 'A column is `@nonsense`.\n' })
    expect(docWordUnknown({ root }).skipped).toBeTruthy()
  })
})

// ─── doc-cites-dead ───────────────────────────────────────────────────────────

describe('doc-cites-dead', () => {
  test('reports a link that resolves to nothing', () => {
    const root = tree('cite-link-bad', {
      'packages/auth/package.json': PKG,
      'packages/auth/README.md':    'Wired in [app.ts](../../example/api/app.ts).\n',
    })
    const out = docCitesDead({ root })
    expect(out.findings).toHaveLength(1)
    expect(out.findings[0].message).toContain('example/api/app.ts')
  })

  test('says nothing about a link that resolves', () => {
    const root = tree('cite-link-good', {
      'packages/auth/package.json': PKG,
      'packages/auth/README.md':    'Wired in [app.ts](../../example/api/src/app.ts).\n',
      'example/api/src/app.ts':     'export const app = 1\n',
    })
    expect(docCitesDead({ root }).findings).toHaveLength(0)
  })

  test('reports a repo path in prose that has moved', () => {
    const root = tree('cite-path-bad', { 'DESIGN.md': 'The ladder lives in `packages/css/tokens.css`.\n' })
    // `packages/` exists, so the path is addressed at this repo and graded.
    mkdirSync(join(root, 'packages', 'css', 'src'), { recursive: true })
    writeFileSync(join(root, 'packages', 'css', 'src', 'tokens.css'), ':root{}')
    const out = docCitesDead({ root })
    expect(out.findings).toHaveLength(1)
    expect(out.findings[0].message).toContain('packages/css/tokens.css')
  })

  test('an app-relative path is not a claim about this repo', () => {
    const root = tree('cite-path-app', {
      'CLAUDE.md': 'Everything derives from `db/schema.lite`, and the money is `api/src/pricing.ts`.\n',
    })
    expect(docCitesDead({ root }).findings).toHaveLength(0)
  })

  test('a path inside a fence or an import specifier is not a citation', () => {
    const root = tree('cite-fence', {
      'HANDOFF.md': 'It imports `./runtime.js`.\n\n```js\nimport x from \'packages/gone/x.js\'\n```\n',
    })
    expect(docCitesDead({ root }).findings).toHaveLength(0)
  })

  test('reports a register id that resolves nowhere, and not one that does', () => {
    const root = tree('cite-id', {
      'ISSUES.md': '# Issues\n\n## S2 — high\n\n' +
                   '| Id | Pkg | Title | Status | Verified | Detail |\n' +
                   '| --- | --- | --- | --- | --- | --- |\n' +
                   '| <a id="fjs-001"></a>FJS-001 | cli | **A real row** | open | 2026-08-29 | — |\n',
      'NOTES.md':  'See FJS-001, and also FJS-999.\n',
    })
    const out = docCitesDead({ root })
    const ids = out.findings.filter(f => f.message.includes('register'))
    expect(ids).toHaveLength(1)
    expect(ids[0].message).toContain('FJS-999')
  })

  test('a dead `#fjs-` anchor is reported even though the file is there', () => {
    const root = tree('cite-anchor', {
      'ISSUES.md': '# Issues\n\n## S2 — high\n\n' +
                   '| Id | Pkg | Title | Status | Verified | Detail |\n' +
                   '| --- | --- | --- | --- | --- | --- |\n' +
                   '| <a id="fjs-001"></a>FJS-001 | cli | **A real row** | open | 2026-08-29 | — |\n',
      'NOTES.md':  'See [FJS-001](ISSUES.md#fjs-001) and [FJS-002](ISSUES.md#fjs-002).\n',
    })
    const out = docCitesDead({ root })
    expect(out.findings.some(f => f.message.includes('#fjs-002'))).toBe(true)
  })
})

// ─── doc-claims-count ─────────────────────────────────────────────────────────

describe('doc-claims-count', () => {
  const kit = n => Object.fromEntries(
    Array.from({ length: n }, (_, i) => [`packages/ui/components/display/C${i}.mesa`, '<div></div>']))

  test('reports a count the tree no longer answers', () => {
    const root = tree('count-bad', { ...kit(3),
      'packages/ui/README.md': 'Mesa components over the design system. 2 components across forms.\n' })
    const out = docClaimsCount({ root })
    expect(out.findings).toHaveLength(1)
    expect(out.findings[0].message).toContain('the tree has 3')
  })

  test('says nothing when the count is right', () => {
    const root = tree('count-good', { ...kit(3),
      'packages/ui/README.md': 'Mesa components over the design system. 3 components across forms.\n' })
    expect(docClaimsCount({ root }).findings).toHaveLength(0)
  })

  test('a subset is not a total — only the largest claim is graded', () => {
    const root = tree('count-subset', { ...kit(3),
      'packages/ui/README.md': '3 components in all, six of which are forms.\n' +
                               'Fifteen components were opened by the drive.\n' })
    // `Fifteen` is larger than the truth and would be the graded claim, so the
    // subset rule is asserted the only way it can be: with the biggest number
    // being the correct one.
    const out = docClaimsCount({ root })
    expect(out.findings.map(f => f.message)).toEqual(
      [expect.stringContaining('says Fifteen components')])
  })

  test('outside the owning package a count needs its marker', () => {
    const root = tree('count-marker', { ...kit(3),
      'CLAUDE.md': '| email-kit | Table-based email components — 22 components |\n' })
    expect(docClaimsCount({ root }).findings).toHaveLength(0)
  })

  test('the root map IS graded where the marker is there', () => {
    const root = tree('count-root', { ...kit(3),
      'CLAUDE.md': '| ui | Mesa component kit over the design system — 22 components |\n' })
    expect(docClaimsCount({ root }).findings).toHaveLength(1)
  })

  test('a thousands separator is one number, not a claim', () => {
    const root = tree('count-thousands', { ...kit(3),
      'packages/ui/README.md': '3 components, regenerated from 1,377 components of input.\n' })
    expect(docClaimsCount({ root }).findings).toHaveLength(0)
  })

  test('history states what was true and is left alone', () => {
    const root = tree('count-history', { ...kit(3),
      'packages/ui/CHANGES.md': '63 components, all compiling.\n' })
    expect(docClaimsCount({ root }).findings).toHaveLength(0)
  })

  test('with no authority in the tree it skips rather than passing', () => {
    const root = tree('count-none', { 'README.md': '69 components.\n' })
    expect(docClaimsCount({ root }).skipped).toBeTruthy()
  })

  test('every shipped countable names an authority and a marker', () => {
    for (const c of COUNTABLES) {
      expect(typeof c.count).toBe('function')
      expect(c.authority).toBeTruthy()
      expect(c.marker).toBeInstanceOf(RegExp)
      expect(c.owner.endsWith('/')).toBe(true)
    }
  })
})

// ─── doc-invariant-ref ────────────────────────────────────────────────────────

const INVARIANTS = `# Map

## Invariants

1. **Dependency direction** — one way.
2. **Model names are PascalCase singular**.

---

## Something else
`

describe('doc-invariant-ref', () => {
  test('reports a rule citing an invariant that does not exist', () => {
    const root = tree('inv-rule', { 'CLAUDE.md': INVARIANTS })
    const out  = docInvariantRef({ root, rules: [{ id: 'a-rule', invariant: 7 }] })
    expect(out.findings).toHaveLength(1)
    expect(out.findings[0].message).toContain('Invariant 7')
  })

  test('reports a document citing one, and not one in range', () => {
    const root = tree('inv-doc', { 'CLAUDE.md': INVARIANTS,
      'HANDOFF.md': 'Invariant 2 holds. Invariant 40 does not exist.\n' })
    const out = docInvariantRef({ root, rules: [{ id: 'a-rule', invariant: 2 }] })
    expect(out.findings).toHaveLength(1)
    expect(out.findings[0].message).toContain('Invariant 40')
  })

  test('with no numbered section it skips rather than passing', () => {
    const root = tree('inv-none', { 'CLAUDE.md': '# Map\n\nNo invariants here.\n' })
    expect(docInvariantRef({ root, rules: [] }).skipped).toBeTruthy()
  })
})

// ─── the pieces underneath ────────────────────────────────────────────────────

describe('the readers', () => {
  test('readNumber takes digits and English, and refuses the rest', () => {
    expect(readNumber('38')).toBe(38)
    expect(readNumber('thirty-eight')).toBe(38)
    expect(readNumber('Fifteen')).toBe(15)
    expect(readNumber('FOURTEEN')).toBe(14)
    expect(readNumber('eleventy')).toBe(null)
    expect(readNumber('thirty-thirty')).toBe(null)
  })

  test('masking keeps every line number honest', () => {
    const text   = 'one\n```js\ntwo\n```\nfour `five`\n'
    const masked = maskInline(maskFences(text))
    expect(masked.split('\n')).toHaveLength(text.split('\n').length)
    expect(masked).not.toContain('two')
    expect(masked).not.toContain('five')
    expect(masked.startsWith('one')).toBe(true)
  })

  test('the corpus excludes what is generated, executable and historical', () => {
    const root = tree('corpus', {
      'README.md':                        'a',
      'ISSUES.md':                        'b',
      'IDEAS/x.md':                       'c',
      'packages/cli/commands/db/seed.md':  'd',
      'packages/cli/CHANGES.md':           'e',
      'packages/cli/db.snapshot.md':       'f',
    })
    const all = docCorpus(root).map(d => d.rel)
    expect(all).toContain('README.md')
    expect(all).not.toContain(join('packages', 'cli', 'commands', 'db', 'seed.md'))
    expect(all).not.toContain(join('packages', 'cli', 'db.snapshot.md'))

    const strict = docCorpus(root, { history: false, registers: false, proposals: false }).map(d => d.rel)
    expect(strict).not.toContain(join('packages', 'cli', 'CHANGES.md'))
    expect(strict).not.toContain('ISSUES.md')
    expect(strict).not.toContain(join('IDEAS', 'x.md'))
  })

  test('npm scopes are derived from the workspace, not listed', () => {
    const root   = tree('scopes', { 'packages/litestone/package.json': PKG })
    const scopes = npmScopes(root)
    expect(scopes.has('@frontierjs')).toBe(true)
    expect(scopes.has('@nothing')).toBe(false)
  })

  test('invariantCount reads the numbered list and stops at the rule', () => {
    const root = tree('inv-count', { 'CLAUDE.md': INVARIANTS })
    expect(invariantCount(root)).toBe(2)
  })
})
