// ─── project-helpers.test.js — what `fli project:map` and `project:view` read ──
//
// FJS-254: the two viewers used to derive "what is this service" from regexes
// over service source. They could not have been right — junction decides at
// construction whether a key is an option or an action, resolves the hook chain
// through `svc.pipelines()`, and moves every route with `apiPrefix`, none of
// which is a fact about how a file reads. So the surface is READ off the
// committed `surface.snapshot.md`, and what is asserted here is that the read is
// faithful and that its absence is absence rather than a fallback scan.
//
// The resource extractor stays, because a Resource has no committed artefact —
// it is constructed in the browser. What changed there is that it reads the
// `createResource(...)` CALL rather than the file: those tests are the ones
// carrying a `model:` in a comment and a hook block the old sweep miscounted.

import { describe, test, expect, beforeEach, afterEach } from 'bun:test'
import { resolve, dirname, join }                        from 'path'
import { fileURLToPath, pathToFileURL }                  from 'url'
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'fs'

const __dir = dirname(fileURLToPath(import.meta.url))
const ROOT  = resolve(__dir, '..')

global.fliRoot ??= ROOT

// The namespace helpers live in a `<script>` block, which is how the runtime
// gives them to every command in the namespace. Loaded as a real module rather
// than through `new Function`: the block opens with `import … from 'fs'`, which
// is only legal at module scope.
async function loadModuleHelpers() {
  const src = readFileSync(resolve(ROOT, 'commands/project/_module.md'), 'utf8')
  const script = src.match(/<script>([\s\S]+?)<\/script>/)
  if (!script) throw new Error('No <script> block in project/_module.md')

  const file = resolve(ROOT, `.tmp-project-helpers-${process.pid}.mjs`)
  writeFileSync(file, `${script[1]}\nexport { readApiSurface, surfaceMissingHint, extractResourceMeta }\n`)
  try { return await import(pathToFileURL(file).href) }
  finally { rmSync(file, { force: true }) }
}

const { readApiSurface, surfaceMissingHint, extractResourceMeta } = await loadModuleHelpers()

let TMP
beforeEach(() => {
  TMP = resolve(ROOT, `.tmp-project-test-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`)
  mkdirSync(TMP, { recursive: true })
})
afterEach(() => rmSync(TMP, { recursive: true, force: true }))

// A trimmed copy of the real shape `junction surface` writes.
const SNAPSHOT = `# API surface snapshot

<!-- generated by: junction surface --app api/app.ts --export app --services api/services -->

Generated from \`api/app.ts\` by \`junction surface\`. **Do not edit.**

\`\`\`
2 services · 3 routes · 2 plugins · prefix /api
\`\`\`

## App hooks

| Phase | Method | Chain |
| --- | --- | --- |
| around | \`all\` | \`requestId\` → \`timing\` |

## Services

### \`alerts\` · model \`AlertRule\`

- **methods** — \`find\`, \`get\`, \`acknowledge\`
- **custom methods** — \`acknowledge\`
- **broadcasts on** — \`alerts\`

| Phase | Method | Chain |
| --- | --- | --- |
| before | \`find\` | \`gateAuth\` → \`autoFilter\` |
| after | \`find\` | \`publish\` |

### \`portal\`

- **methods** — \`find\`

| Phase | Method | Chain |
| --- | --- | --- |
| before | \`find\` | \`gateAuth\` |

## Routes

| Method | Path | Kind |
| --- | --- | --- |
| GET | \`/api/{service}\` | service |
| POST | \`/api/{service}/{id}\` | service |
| GET | \`/api/health\` | raw |

## Plugins

1. \`health\`
2. \`channels\`
`

const writeSnapshot = (body = SNAPSHOT) =>
  writeFileSync(join(TMP, 'surface.snapshot.md'), body)

// ─── readApiSurface ───────────────────────────────────────────────────────────

describe('readApiSurface', () => {

  test('no snapshot is null, not an empty surface', () => {
    expect(readApiSurface(TMP)).toBeNull()
  })

  // The one thing a caller has to be told, and it is data in the file rather
  // than a string this package would otherwise have to keep in step.
  test('carries the command that wrote it', () => {
    writeSnapshot()
    expect(readApiSurface(TMP).generatedBy)
      .toBe('junction surface --app api/app.ts --export app --services api/services')
  })

  test('reads each service with the model it reports', () => {
    writeSnapshot()
    const { services } = readApiSurface(TMP)
    expect(services.map(s => s.name)).toEqual(['alerts', 'portal'])
    expect(services[0].model).toBe('AlertRule')
  })

  // A service that declares no model reports its own name for the envelope, and
  // the snapshot omits the clause entirely rather than repeating it.
  test('a service with no model clause takes its own name', () => {
    writeSnapshot()
    expect(readApiSurface(TMP).services[1].model).toBe('portal')
  })

  // The distinction the scanner existed to make, and the one it could not:
  // `collectCustomMethods` decided this at construction.
  test('custom methods come from the surface, not from a pattern over source', () => {
    writeSnapshot()
    const alerts = readApiSurface(TMP).services[0]
    expect(alerts.methods).toEqual(['find', 'get', 'acknowledge'])
    expect(alerts.customMethods).toEqual(['acknowledge'])
  })

  test('a service with no custom methods has none rather than a guess', () => {
    writeSnapshot()
    expect(readApiSurface(TMP).services[1].customMethods).toEqual([])
  })

  test('hook chains keep their run order, per phase and method', () => {
    writeSnapshot()
    const alerts = readApiSurface(TMP).services[0]
    expect(alerts.hooks.before.find).toEqual(['gateAuth', 'autoFilter'])
    expect(alerts.hooks.after.find).toEqual(['publish'])
    expect(alerts.hooks.around).toEqual({})
  })

  test('the channel a service broadcasts on is read', () => {
    writeSnapshot()
    expect(readApiSurface(TMP).services[0].channel).toBe('alerts')
    expect(readApiSurface(TMP).services[1].channel).toBeNull()
  })

  // Around EVERY call — the thing no per-service line can show, and the reason
  // an app-level hook was invisible to the scanner: it is in no service file.
  test('app hooks are separate from any service', () => {
    writeSnapshot()
    const { appHooks, services } = readApiSurface(TMP)
    expect(appHooks.around.all).toEqual(['requestId', 'timing'])
    for (const svc of services) expect(svc.hooks.around).toEqual({})
  })

  test('routes and plugins come across whole', () => {
    writeSnapshot()
    const { routes, plugins } = readApiSurface(TMP)
    expect(routes).toHaveLength(3)
    expect(routes[2]).toEqual({ method: 'GET', path: '/api/health', kind: 'raw' })
    expect(plugins).toEqual(['health', 'channels'])
  })

  // A table row under one heading must not be collected under another — the
  // sections share a column shape.
  test('a route row is not read as a hook chain', () => {
    writeSnapshot()
    const { appHooks } = readApiSurface(TMP)
    expect(Object.keys(appHooks.before)).toEqual([])
  })

  test('the hint names the command rather than the file', () => {
    expect(surfaceMissingHint(TMP)).toContain('junction surface')
  })

  // Where it lives. A snapshot belongs in the surface it describes, so `api/`
  // is the answer and is read first; an app that has not moved it still works,
  // because the file is written by a command an app already runs.
  test('reads the snapshot out of api/', () => {
    mkdirSync(join(TMP, 'api'), { recursive: true })
    writeFileSync(join(TMP, 'api', 'surface.snapshot.md'), SNAPSHOT)
    expect(readApiSurface(TMP).services.map(s => s.name)).toEqual(['alerts', 'portal'])
    rmSync(join(TMP, 'api'), { recursive: true, force: true })
  })

  // Two copies is the defect, not a supported layout: they are generated from
  // different working directories and disagree (`scripts/ci-allowances.json`
  // records a real instance, six routes apart). The one beside the API wins,
  // and the `snapshots` phase still rechecks both where they exist.
  test('api/ wins over the app root', () => {
    writeSnapshot(SNAPSHOT.replace('`alerts`', '`stale`'))
    mkdirSync(join(TMP, 'api'), { recursive: true })
    writeFileSync(join(TMP, 'api', 'surface.snapshot.md'), SNAPSHOT)
    expect(readApiSurface(TMP).services.map(s => s.name)).toEqual(['alerts', 'portal'])
    rmSync(join(TMP, 'api'), { recursive: true, force: true })
  })
})

// ─── extractResourceMeta ──────────────────────────────────────────────────────

const resource = (body) => `<script module>\n${body}\n</script>\n`

describe('extractResourceMeta', () => {

  test('the service is the first positional argument', () => {
    const meta = extractResourceMeta(
      resource(`export const people = createResource('people', { model: 'Person' })`),
      '/x/web/src/resources/Person.mesa')
    expect(meta.service).toBe('people')
    expect(meta.model).toBe('Person')
    expect(meta.name).toBe('Person')
  })

  test('no model clause means none — the file name carries it (Invariant 19)', () => {
    const meta = extractResourceMeta(
      resource(`export const orders = createResource('orders')`),
      '/x/Order.mesa')
    expect(meta.model).toBeNull()
    expect(meta.name).toBe('Order')
  })

  // A resource file is mostly prose. Reading `model:` from anywhere in it is the
  // same shape as the body tag written inside a comment — a rule this repo
  // already enforces elsewhere.
  test('a model named in a comment is not a declaration', () => {
    const meta = extractResourceMeta(resource(`
      // The file is named for the MODEL: model: 'Wrong' is what this is NOT.
      /* and a block comment saying model: 'AlsoWrong' */
      export const orders = createResource('orders')
    `), '/x/Order.mesa')
    expect(meta.model).toBeNull()
    expect(meta.service).toBe('orders')
  })

  test('hooks are read per phase and method', () => {
    const meta = extractResourceMeta(resource(`
      export const recipes = createResource('recipes', {
        hooks: { before: { create: [stampWorkspace] } },
      })
    `), '/x/Recipe.mesa')
    expect(meta.hooks).toEqual(['stampWorkspace'])
  })

  // Every case below was measured against the sweep this replaced, and it is
  // wrong on all of them. Its non-greedy block match ends at the first `} }`, so
  // a second phase or a second method on ONE line takes the whole block with it
  // and the answer is empty; and it counts identifiers rather than reading
  // entries, so an inline arrow contributes its argument name.

  test('a second phase on one line is not dropped', () => {
    const meta = extractResourceMeta(resource(
      `export const o = createResource('o', { hooks: { before: { create: [a] }, after: { patch: [b, c] } } })`
    ), '/x/Order.mesa')
    expect(meta.hooks).toEqual(['a', 'b', 'c'])
  })

  test('a second method on one line is not dropped', () => {
    const meta = extractResourceMeta(resource(
      `export const o = createResource('o', { hooks: { before: { create: [a], patch: [b] } } })`
    ), '/x/Order.mesa')
    expect(meta.hooks).toEqual(['a', 'b'])
  })

  test('an option after hooks does not swallow the block', () => {
    const meta = extractResourceMeta(resource(
      `export const o = createResource('o', { hooks: { before: { create: [a] } }, validate: false })`
    ), '/x/Order.mesa')
    expect(meta.hooks).toEqual(['a'])
  })

  // An inline hook has no name. Showing the text of it in a list of names is the
  // same mistake at one remove — the viewer's line reads as a name regardless.
  test('an inline arrow contributes no name', () => {
    const meta = extractResourceMeta(resource(
      `export const o = createResource('o', { hooks: { before: { create: [ctx => stamp(ctx)] } } })`
    ), '/x/Order.mesa')
    expect(meta.hooks).toEqual([])
  })

  test('a qualified hook keeps its whole name', () => {
    const meta = extractResourceMeta(resource(
      `export const o = createResource('o', { hooks: { before: { create: [session.stamp] } } })`
    ), '/x/Order.mesa')
    expect(meta.hooks).toEqual(['session.stamp'])
  })

  test('an option beside hooks is not counted as one', () => {
    const meta = extractResourceMeta(resource(`
      export const apiKeys = createResource('api-keys', {
        model: 'ApiKey',
        validate: false,
        hooks: { before: { create: [stampWorkspace] } },
      })
    `), '/x/ApiKey.mesa')
    expect(meta.hooks).toEqual(['stampWorkspace'])
    expect(meta.model).toBe('ApiKey')
  })

  // The other half of the comment problem: a hooks block written in prose.
  test('a hooks block in a comment declares nothing', () => {
    const meta = extractResourceMeta(resource(`
      // hooks: { before: { create: [nothingReal] } } — what this file does NOT do
      export const orders = createResource('orders')
    `), '/x/Order.mesa')
    expect(meta.hooks).toEqual([])
  })

  test('a file that calls nothing says so rather than half', () => {
    const meta = extractResourceMeta(resource(`export const nothing = 1`), '/x/Thing.mesa')
    expect(meta).toEqual({ name: 'Thing', model: null, service: null, hooks: [] })
  })
})
