// repo-live.test.js — the two facts a committed page cannot hold.
//
// `collectLive` shells out to git and to npm, and both are exercised for real
// every time somebody runs `fli ws:atlas --live` — faking them here would test
// the fake. What is worth pinning is the part that decides what the page SAYS
// about what they answered: the version comparison, and the rule that a live
// page is not a snapshot.
//
// That last one is the whole point of the flag. A live page that names a
// generator gets picked up by the snapshot walker and fails CI on a timestamp,
// which is exactly the failure the separate filename exists to prevent.

import { describe, test, expect } from 'bun:test'

import { compareVersions } from '../core/repo-live.js'
import { renderAtlas }     from '../core/repo-atlas.js'

const model = () => ({
  root: 'ws',
  scripts: [],
  snapshots: [],
  ci: null,
  packages: [{ folder: 'css', name: '@x/css', version: '0.15.1', deps: [], dependents: [], topics: [], sections: [] }],
  apps: [],
  proofs: [],
  fieldTheme: null,
  drives: [],
  ports: { rows: [], global: [] },
  issues: null,
  commands: null,
  registers: [],
})

const live = (rows) => ({
  at: '2026-08-14 09:00',
  git: { branch: 'main', head: 'abc1234', dirty: 3 },
  rows,
})

const row = (over = {}) => ({
  folder: 'css', name: '@x/css', version: '0.15.1', published: '0.15.0',
  ahead: true, behind: false, lastCommit: '2026-08-12', lastSubject: 'tune the tones',
  commits90: 7, dirty: 1, ...over,
})

describe('version comparison', () => {

  test('ahead, behind and level', () => {
    expect(compareVersions('0.15.1', '0.15.0')).toBe(1)
    expect(compareVersions('0.15.0', '0.15.1')).toBe(-1)
    expect(compareVersions('1.1.4', '1.1.4')).toBe(0)
  })

  test('compares numerically, not as text — 0.10 is above 0.9', () => {
    expect(compareVersions('0.10.0', '0.9.0')).toBe(1)
  })

  test('a missing segment is zero, and a prerelease suffix does not decide it', () => {
    expect(compareVersions('1.1', '1.1.0')).toBe(0)
    expect(compareVersions('0.1.1', '0.0.0-beta.0')).toBe(1)
  })
})

describe('the live page', () => {

  test('names no generator — a clock is not checkable', () => {
    const html = renderAtlas(model(), live([row()]))
    expect(html).not.toContain('generated by:')
    expect(html.split('\n')[1]).toContain('not a snapshot')
  })

  test('the snapshot page still names one', () => {
    expect(renderAtlas(model()).split('\n')[1]).toBe('<!-- generated by: fli ws:atlas -->')
  })

  test('a package the tree is ahead of is called out — the register cannot see that class', () => {
    const html = renderAtlas(model(), live([row()]))
    expect(html).toContain('tree ahead')
    expect(html).toContain('1 package(s) differ from the registry')
  })

  test('never published is not the same as behind', () => {
    const html = renderAtlas(model(), live([row({ published: null, ahead: false })]))
    expect(html).toContain('unpublished')
    expect(html).not.toContain('tree behind')
  })

  test('agreement is stated, not left blank', () => {
    const html = renderAtlas(model(), live([row({ published: '0.15.1', ahead: false })]))
    expect(html).toContain('Tree and registry agree')
  })

  test('no live data means no live pane at all', () => {
    expect(renderAtlas(model())).not.toContain('id="live-h"')
  })
})
