// repo-atlas.test.js — the deck, and what each plate is allowed to claim.
//
// The atlas is the same model `repo-map.js` collects, arranged. What is worth
// testing is the arrangement that could be WRONG rather than merely ugly: a
// dossier showing another package's issues, a dependency chip pointing at a
// card that is not in the deck, a filing convention the crossing does not
// understand. A misdrawn icon is cosmetic; a misattributed defect is a lie
// about who owns it.

import { describe, test, expect, beforeAll, afterAll } from 'bun:test'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join }   from 'path'
import { tmpdir } from 'os'

import { collect }                     from '../core/repo-map.js'
import { cards, actions, renderAtlas } from '../core/repo-atlas.js'

let ROOT

// The page carries two stylesheets — the vendored package and its own — so
// "the local CSS" is a claim about which BLOCK, not which position. Slicing at
// the first `<style>` used to mean the local one and now means the bundle, and
// a `not.toMatch` against the wrong slice passes for the wrong reason.
function localStyle(html) {
  const at = html.indexOf('<style id="atlas">')
  if (at === -1) throw new Error('no local stylesheet in the page')
  return html.slice(at, html.indexOf('</style>', at))
}

function workspace(name, extra = {}) {
  const dir = join(ROOT, name)
  const files = {
    'package.json': JSON.stringify({ name: 'ws', scripts: { ci: 'node scripts/ci.mjs' } }),
    'CLAUDE.md': [
      '# Map',
      '',
      '| Package | Realm/Domain | What it is | State |',
      '| --- | --- | --- | --- |',
      '| litestone | Data / D2 | The `.lite` language and its client | v1.1.0 · green |',
      '| sierra | UI meta | File-tree routing and the build | green |',
      '| cli (`fli`) | D1 | The command runtime | green |',
      '',
    ].join('\n'),
    'packages/litestone/package.json': JSON.stringify({ name: '@x/litestone', version: '1.0.0', scripts: { test: 'bun test' } }),
    'packages/sierra/package.json':    JSON.stringify({ name: '@x/sierra', version: '0.1.0', dependencies: { '@x/litestone': 'workspace:*' } }),
    'packages/cli/package.json':       JSON.stringify({ name: '@x/cli', version: '0.1.0' }),
    'packages/sierra/db/routes.snapshot.md': '<!-- generated by: sierra routes --config config/sierra.config.js -->\n',
    'ISSUES.md': [
      '# Issues',
      '',
      '## S2 — high',
      '',
      '| Id | Pkg | Title | Status | Verified | Detail |',
      '| --- | --- | --- | --- | --- | --- |',
      '| FJS-100 | litestone | **A gate refuses, a policy filters** | open | 2026-08-14 | — |',
      '| FJS-200 | cli/auth | **One defect filed against two packages** | open | 2026-08-14 | — |',
      '| FJS-300 | repo | **Something with no package** | open | 2026-08-14 | — |',
      '',
    ].join('\n'),
    ...extra,
  }

  for (const [path, body] of Object.entries(files)) {
    const full = join(dir, path)
    mkdirSync(join(full, '..'), { recursive: true })
    writeFileSync(full, body)
  }
  return collect({ root: dir })
}

const byKey = (deck, key) => deck.find(c => c.key === key)

beforeAll(() => { ROOT = mkdtempSync(join(tmpdir(), 'fli-repo-atlas-')) })
afterAll(()  => { try { rmSync(ROOT, { recursive: true, force: true }) } catch {} })

// ─── the deck ─────────────────────────────────────────────────────────────────

describe('the deck', () => {

  test('a plate carries the realm and the claim the root table states', () => {
    const deck = cards(workspace('deck'))
    const lite = byKey(deck, 'litestone')

    expect(lite.sub).toBe('Data / D2')
    expect(lite.bucket).toBe('data')
    expect(lite.blurb).toBe('The .lite language and its client')
  })

  test('the workspace gets a plate, because the register files things against it', () => {
    const deck = cards(workspace('deck-ws'))
    expect(byKey(deck, 'repo').kind).toBe('workspace')
  })

  test('an app is dealt as an app — a schema or a drive, never published', () => {
    const model = workspace('deck-app', {
      'example/package.json': JSON.stringify({ name: 'example', scripts: { verify: 'node verify.mjs' } }),
      'example/db/schema.lite': 'model Post {\n  id String @id\n}\n',
    })
    expect(byKey(cards(model), 'example').bucket).toBe('app')
  })

  test('a claimed folder is dealt last — a plan is not a part', () => {
    const model = workspace('deck-claimed', { 'packages/toolbelt/README.md': '# planned\n' })
    const deck  = cards(model)
    expect(deck[deck.length - 1].key).toBe('toolbelt')
    expect(deck[deck.length - 1].bucket).toBe('claimed')
  })

  test('plate numbers are positions and every one is unique', () => {
    const deck = cards(workspace('deck-plates'))
    expect(new Set(deck.map(c => c.plate)).size).toBe(deck.length)
    expect(deck[0].plate).toBe('01')
  })

  test('a package the root table never names still gets a plate', () => {
    const model = workspace('deck-unfiled', {
      'packages/orphan/package.json': JSON.stringify({ name: '@x/orphan', version: '0.0.1' }),
    })
    const card = byKey(cards(model), 'orphan')
    expect(card.sub).toBe('unfiled')
    expect(card.bucket).toBe('other')
  })
})

// ─── the crossings ────────────────────────────────────────────────────────────

describe('what a dossier claims', () => {

  test('an issue lands on the package it names, and nowhere else', () => {
    const html = renderAtlas(workspace('cross-issue'))
    const lite = dossierOf(html, 'litestone')
    const cli  = dossierOf(html, 'cli')

    expect(lite).toContain('FJS-100')
    expect(cli).not.toContain('FJS-100')
  })

  test('a row filed against two packages shows on both, not neither', () => {
    const html = renderAtlas(workspace('cross-both'))
    expect(dossierOf(html, 'cli')).toContain('FJS-200')
    expect(dossierOf(html, 'auth') ?? dossierOf(html, 'cli')).toContain('FJS-200')
  })

  test('a row filed against no package lands on the workspace plate', () => {
    const html = renderAtlas(workspace('cross-repo'))
    expect(dossierOf(html, 'repo')).toContain('FJS-300')
    expect(dossierOf(html, 'litestone')).not.toContain('FJS-300')
  })

  test('a snapshot belongs to the directory that holds it', () => {
    const html = renderAtlas(workspace('cross-snap'))
    expect(dossierOf(html, 'sierra')).toContain('routes.snapshot.md')
    expect(dossierOf(html, 'litestone')).not.toContain('routes.snapshot.md')
  })

  test('a dependency chip only links where the deck holds that card', () => {
    const html = renderAtlas(workspace('cross-chip'))
    // Every href the page writes for a card must name a dossier it rendered,
    // or the page is a dead end at exactly the moment it is being used. A route
    // may carry a facet — `part/repo/S2` — and then it is the HEAD that has to
    // name one, with the tail a facet that dossier offers.
    const targets  = [...html.matchAll(/href="#\/([^"]+)"/g)].map(m => m[1])
    const rendered = [...html.matchAll(/data-dossier="([^"]+)"/g)].map(m => m[1])
    const offered  = [...html.matchAll(/data-value="([^"]*)"/g)].map(m => m[1])
    expect(targets.length).toBeGreaterThan(0)
    for (const t of targets) {
      if (rendered.includes(t)) continue
      // A route splits at the SECOND slash — a facet value may hold one.
      const parts = t.split('/')
      expect(rendered).toContain(parts.slice(0, 2).join('/'))
      const facet = decodeURIComponent(parts.slice(2).join('/'))
      expect(offered).toContain(facet.slice(facet.indexOf(':') + 1))
    }
  })
})

// ─── the doors ────────────────────────────────────────────────────────────────

describe('search by action', () => {

  const withRunnables = (name) => workspace(name, {
    'package.json': JSON.stringify({ name: 'ws', scripts: { build: 'bun run --filter * build' } }),
    'packages/cli/commands/deploy/local.md': '---\ntitle: deploy:local\ndescription: Build the image and boot it\n---\n',
    'example/package.json': JSON.stringify({ name: 'example', scripts: { verify: 'node test/verify.mjs' } }),
    'example/db/schema.lite': 'model Post {\n  id String @id\n}\n',
  })

  test('an action gathers commands, scripts, drives and generators alike', () => {
    const deploying = actions(withRunnables('act-pool')).find(a => a.name === 'deploying')
    expect(deploying.hits.map(h => h.label)).toContain('fli deploy:local')

    const testing = actions(withRunnables('act-drive')).find(a => a.name === 'testing')
    expect(testing.hits.some(h => h.kind === 'drive')).toBe(true)
  })

  test('an action nothing answers to is not offered', () => {
    // The vocabulary is curated; the membership is not. A word with no hit in
    // this workspace would be a door onto an empty room.
    const model = workspace('act-empty')
    const names = actions(model).map(a => a.name)
    for (const name of names) expect(actions(model).find(a => a.name === name).hits.length).toBeGreaterThan(0)
  })

  test('every action term on the page has a sheet behind it', () => {
    const html = renderAtlas(withRunnables('act-sheets'))
    const terms  = [...html.matchAll(/data-action="([^"]+)"/g)].map(m => m[1])
    const sheets = [...html.matchAll(/data-dossier="do\/([^"]+)"/g)].map(m => m[1])
    expect(terms.length).toBeGreaterThan(0)
    for (const t of terms) expect(sheets).toContain(t)
  })
})

describe('search by realm', () => {

  test('every realm term matches plates that carry that bucket', () => {
    const html = renderAtlas(workspace('realm-terms'))
    const terms   = [...html.matchAll(/data-realm="([^"]*)"/g)].map(m => m[1]).filter(Boolean)
    const buckets = [...html.matchAll(/data-bucket="([^"]+)"/g)].map(m => m[1])
    expect(terms.length).toBeGreaterThan(0)
    for (const t of terms) expect(buckets).toContain(t)
  })
})

describe('what proves a change', () => {

  const withProofs = (name) => workspace(name, {
    'CLAUDE.md': [
      '# Map',
      '',
      '| Package | Realm/Domain | What it is | State |',
      '| --- | --- | --- | --- |',
      '| litestone | Data / D2 | The .lite language | green |',
      '| sierra | UI meta | Routing | green |',
      '| cli (`fli`) | D1 | The command runtime | green |',
      '',
      '| Changed | Run |',
      '| --- | --- |',
      '| litestone client/policy/gate | `example`: `verify` + `sierra`: `test:safety` |',
      '| sierra · cli | `example`: `verify:build` |',
      '',
    ].join('\n'),
  })

  test('a row lands on the package its *changed* half names', () => {
    const html = renderAtlas(withProofs('proof-one'))
    expect(dossierOf(html, 'litestone')).toContain('What proves a change here')
    expect(dossierOf(html, 'litestone')).toContain('test:safety')
  })

  test('a row naming two packages shows on both — one row, two owners', () => {
    const html = renderAtlas(withProofs('proof-two'))
    expect(dossierOf(html, 'sierra')).toContain('verify:build')
    expect(dossierOf(html, 'cli')).toContain('verify:build')
  })

  test('a package no row names says nothing rather than guessing', () => {
    // `sierra` appears in litestone's row as the drive to RUN, not as the thing
    // changed — matching the wrong half would file it under the wrong package.
    const sierra = dossierOf(renderAtlas(withProofs('proof-half')), 'sierra')
    expect(sierra).not.toContain('test:safety')
  })
})

describe('files an open row names', () => {

  const withEvidence = (name) => workspace(name, {
    'ISSUES.md': [
      '# Issues',
      '',
      '## S2 — high',
      '',
      '| Id | Pkg | Title | Status | Verified | Detail |',
      '| --- | --- | --- | --- | --- | --- |',
      '| FJS-100 | litestone | **A gate refuses** | open | 2026-08-14 | [client.js](packages/litestone/src/core/client.js) · [CLAUDE.md](CLAUDE.md) |',
      '| FJS-101 | litestone | **A policy filters** | open | 2026-08-14 | [client.js](packages/litestone/src/core/client.js) |',
      '',
    ].join('\n'),
  })

  test('counts the files its own rows point at', () => {
    const sheet = dossierOf(renderAtlas(withEvidence('hot')), 'litestone')
    expect(sheet).toContain('Files an open row names')
    expect(sheet).toContain('src/core/client.js')
    expect(sheet).toContain('FJS-100 · FJS-101')
  })

  test('a repo-level document is not filed under the package that linked it', () => {
    // Half the register links the root CLAUDE.md. Counting those per package
    // would make the busiest rows the busiest files everywhere.
    expect(dossierOf(renderAtlas(withEvidence('hot-root')), 'litestone')).not.toContain('>CLAUDE.md<')
  })
})

describe('invariants and their checks', () => {

  const withInvariants = (name) => workspace(name, {
    'CLAUDE.md': [
      '# Map',
      '',
      '| Package | Realm/Domain | What it is | State |',
      '| --- | --- | --- | --- |',
      '| litestone | Data / D2 | The .lite language | green |',
      '',
      '## Invariants',
      '',
      '1. **Dependency direction** — never reverse.',
      '2. **Model names are PascalCase singular** — three resolvers agree.',
      '',
      '---',
    ].join('\n'),
  })

  test('an invariant a rule names is shown as checked', () => {
    // checks.js really carries `model-name-case` against invariant 2.
    const repo = dossierOf(renderAtlas(withInvariants('inv-checked')), 'repo')
    expect(repo).toContain('2 Model names are PascalCase singular')
    expect(repo).toContain('model-name-case')
  })

  test('an invariant no rule names says so — that is the finding', () => {
    const repo = dossierOf(renderAtlas(withInvariants('inv-loose')), 'repo')
    expect(repo).toContain('attention only')
    expect(repo).toMatch(/1 of 2<\/strong> are held up by nothing a machine runs/)
  })
})

describe('the numbers already in files', () => {

  test('a typecheck ceiling is a fact on the plate, and zero says clean', () => {
    const model = workspace('ceiling', {
      'scripts/typecheck-baselines.json': JSON.stringify({ litestone: 12 }),
    })
    expect(dossierOf(renderAtlas(model), 'litestone')).toContain('12 — ratchets down only')
    expect(dossierOf(renderAtlas(model), 'sierra')).toContain('clean')
  })

  test('an app carries the ports the formula gives it', () => {
    const model = workspace('ports', {
      'example/package.json': JSON.stringify({ name: 'example', scripts: { verify: 'node v.mjs' } }),
      'example/db/schema.lite': 'model Post {\n  id String @id\n}\n',
      // The assignment table is a source file of ONE workspace, and the name
      // `example` means project 1 in that one alone — so the fixture holds it,
      // or the page would be printing this repo's numbers over a tree that has
      // never heard of them.
      'packages/cli/core/ports.js': '// the registry lives here\n',
    })
    // `example` is project 1 in the registry: dev front 8010, back 8110.
    expect(dossierOf(renderAtlas(model), 'example')).toContain('8010 front · 8110 back')
  })
})

describe('the heat bar', () => {

  test('a plate carrying open rows shows one segment per severity', () => {
    const html = renderAtlas(workspace('heat'))
    // The register fixture files one S2 against litestone.
    const plate = html.slice(html.indexOf('data-key="litestone"'), html.indexOf('</a>', html.indexOf('data-key="litestone"')))

    expect(plate).toContain('class="h-S2"')
    expect(plate).toContain('1 open')
  })

  test('a plate with nothing open shows no bar at all', () => {
    const html  = renderAtlas(workspace('heat-none'))
    const plate = html.slice(html.indexOf('data-key="sierra"'), html.indexOf('</a>', html.indexOf('data-key="sierra"')))
    expect(plate).not.toContain('atlas-heat')
  })
})

describe('the palette', () => {

  const corpusOf = (html) => JSON.parse(
    html.match(/id="atlas-corpus">([\s\S]*?)<\/script>/)[1].replace(/\\u003c/g, '<'))

  test('indexes every kind of noun the page holds', () => {
    const model = workspace('pal-kinds', {
      'packages/cli/commands/db/seed.md': '---\ntitle: db:seed\ndescription: Run the seeder\n---\n',
      'packages/litestone/docs/encryption.md': '# Encryption\n\nSealed at the boundary.\n',
    })
    const kinds = new Set(corpusOf(renderAtlas(model)).map(row => row[0]))

    for (const kind of ['part', 'issue', 'topic', 'command', 'snapshot', 'register'])
      expect([...kinds]).toContain(kind)
  })

  test('every route it offers names a dossier the page rendered', () => {
    // A palette that lands nowhere is worse than no palette: it is confidently
    // wrong at the moment somebody is lost.
    const html     = renderAtlas(workspace('pal-routes'))
    const rendered = [...html.matchAll(/data-dossier="([^"]+)"/g)].map(m => m[1])

    for (const [, , , href] of corpusOf(html)) {
      if (!href.startsWith('#')) continue
      expect(rendered).toContain(href.replace(/^#\//, ''))
    }
  })

  test('an issue points at the plate that owns it', () => {
    const rows = corpusOf(renderAtlas(workspace('pal-issue')))
    const row  = rows.find(r => r[0] === 'issue' && r[1].startsWith('FJS-100'))
    expect(row[3]).toBe('#/part/litestone')
  })
})

describe('what a package does', () => {

  test('the dossier lists the package’s own docs as its feature set', () => {
    const model = workspace('feat', {
      'packages/litestone/docs/encryption.md': '# Encryption\n\nSealed at the boundary.\n',
      'packages/litestone/README.md': '# litestone\n\n## Row-level policies\n',
    })
    const sheet = dossierOf(renderAtlas(model), 'litestone')

    expect(sheet).toContain('Encryption')
    expect(sheet).toContain('packages/litestone/docs/encryption.md')
    expect(sheet).toContain('Row-level policies')
  })

  // Junction's shape: one file under `docs/` and thirty-two capabilities in the
  // README. The heading list was a row of bare chips, which is not a feature
  // list — the same cards litestone gets, off whatever the section leads on.
  const readmeOnly = (name) => workspace(name, {
    'packages/cli/README.md': [
      '# cli', '',
      '## Idempotency-Key', '',
      'A mutating request carrying the header executes once.', '',
      '## Response helpers', '',
      '```ts', 'ctx.json(data, status?)', '```', '',
    ].join('\n'),
    'packages/cli/src/core/registry.js': 'export const a = 1\n',
    'packages/cli/src/transport/http.js': 'export const b = 2\n',
  })

  test('a package with no docs/ gets its field guide from its README', () => {
    const sheet = dossierOf(renderAtlas(readmeOnly('feat-readme')), 'cli')
    const guide = sheet.slice(sheet.indexOf('Field guide'))

    expect(sheet).toContain('Field guide')
    expect(guide).toContain('Idempotency-Key')
    expect(guide).toContain('A mutating request carrying the header executes once.')
  })

  test('a section that says nothing in prose is named by its example', () => {
    const sheet = dossierOf(renderAtlas(readmeOnly('feat-code')), 'cli')
    expect(sheet).toContain('ctx.json(data, status?)')
  })

  test('the source layout is shown as structure, never as a feature list', () => {
    const sheet = dossierOf(renderAtlas(readmeOnly('feat-src')), 'cli')
    const made  = sheet.slice(sheet.indexOf('What the source is made of'))

    expect(sheet).toContain('What the source is made of')
    expect(made).toContain('core')
    expect(made).toContain('transport')
    expect(made).toContain('Structure, not features')
  })

  test('every README capability is findable by name, not only the docs ones', () => {
    const html = renderAtlas(readmeOnly('feat-corpus'))
    const corpus = JSON.parse(html.match(/<script type="application\/json" id="atlas-corpus">(.+?)<\/script>/s)[1]
      .replace(/\\u003c/g, '<'))

    expect(corpus.some(([kind, title]) => kind === 'topic' && title === 'Idempotency-Key')).toBe(true)
  })
})

// ─── the hub ──────────────────────────────────────────────────────────────────
//
// The workspace is the one plate whose subject is the whole tree, so its
// dossier is the only one allowed to show another card's rows — and that is
// exactly the property worth pinning, because everything else in this file
// exists to stop a dossier doing it.

describe('the hub', () => {

  // Weight, not count: the ordering claim is the whole reason the pane exists,
  // and a bug in it reads as a plausible list rather than as a wrong one.
  const weighted = (name) => workspace(name, {
    'ISSUES.md': [
      '# Issues',
      '',
      '## S2 — high',
      '',
      '| Id | Pkg | Title | Status | Verified | Detail |',
      '| --- | --- | --- | --- | --- | --- |',
      '| FJS-100 | litestone | **One that matters** | open | 2026-08-14 | — |',
      '',
      '## S4 — low',
      '',
      '| Id | Pkg | Title | Status | Verified | Detail |',
      '| --- | --- | --- | --- | --- | --- |',
      '| FJS-201 | sierra | **First of three small ones** | open | 2026-08-14 | — |',
      '| FJS-202 | sierra | **Second** | open | 2026-08-14 | — |',
      '| FJS-203 | sierra | **Third** | open | 2026-08-14 | — |',
      '',
    ].join('\n'),
  })

  // The stylesheet names both panes before either is rendered, so the end is
  // found from the start rather than from the top of the file.
  const hubOf = (html) => {
    const start = html.indexOf('class="pane atlas-hub"')
    return html.slice(start, html.indexOf('id="doors-h"', start))
  }

  // The tiles link a plate too — `runnable` points at the cli — so an ordering
  // claim has to be read off the table that makes it and not off the pane.
  const carryingOf = (html) => {
    const hub = hubOf(html)
    return hub.slice(hub.indexOf('Where it is open'), hub.indexOf('Which file answers'))
  }

  test('the workspace dossier carries every open row, not only its own', () => {
    const sheet = dossierOf(renderAtlas(workspace('hub-all')), 'repo')

    expect(sheet).toContain('FJS-100')   // litestone's
    expect(sheet).toContain('FJS-200')   // cli/auth's
    expect(sheet).toContain('FJS-300')   // the repo's own
  })

  test('a row in the register links the plate it is filed against', () => {
    const sheet = dossierOf(renderAtlas(workspace('hub-link')), 'repo')
    expect(sheet).toMatch(/href="#\/part\/litestone"[^>]*>litestone/)
  })

  test('the repo’s own rows appear once, not once in each of two blocks', () => {
    const sheet = dossierOf(renderAtlas(workspace('hub-once')), 'repo')
    expect(sheet.match(/FJS-300/g)).toHaveLength(1)
  })

  test('a severity is a facet the page offers, and every one present is offered', () => {
    const sheet = dossierOf(renderAtlas(weighted('hub-facets')), 'repo')
    const offered = [...sheet.matchAll(/data-facet="sev" data-value="([^"]*)"/g)].map(m => m[1])

    expect(offered).toContain('')     // all
    expect(offered).toContain('S2')
    expect(offered).toContain('S4')
    expect(offered).not.toContain('S1')
  })

  test('a row carries what it is filed under and against, so a facet can reach it', () => {
    const sheet = dossierOf(renderAtlas(weighted('hub-data')), 'repo')
    expect(sheet).toContain('data-sev="S2" data-pkg="litestone"')
  })

  test('packages are ordered by weight — one S2 outranks three S4s', () => {
    const table = carryingOf(renderAtlas(weighted('hub-weight')))
    const at    = (key) => table.indexOf(`href="#/part/${key}"`)

    expect(at('litestone')).toBeGreaterThan(-1)
    expect(at('litestone')).toBeLessThan(at('sierra'))
  })

  test('a plate with a clean register is not listed — an empty bar says nothing', () => {
    const table = carryingOf(renderAtlas(weighted('hub-clean')))
    expect(table).not.toContain('href="#/part/cli"')
  })

  test('a severity count is a route into the register with the facet applied', () => {
    const hub = hubOf(renderAtlas(weighted('hub-route')))
    expect(hub).toContain('href="#/part/repo/sev:S2"')
  })

  test('the roster holds every plate but the workspace itself', () => {
    const sheet = dossierOf(renderAtlas(workspace('hub-roster')), 'repo')
    const roster = sheet.slice(sheet.indexOf('The deck, in one table'))

    expect(roster).toContain('href="#/part/litestone"')
    expect(roster).toContain('href="#/part/cli"')
    expect(roster).not.toContain('href="#/part/repo"')
  })

  // The three registers are one row because they are read across. What could be
  // wrong is a facet that reaches the wrong table: severity, section, status and
  // wave are four dimensions over one dossier, and a control that filters all of
  // them filters none of them usefully.
  const threeRegisters = (name) => workspace(name, {
    'DECISIONS.md': [
      '# Decisions', '', 'Dated rulings by the project owner.', '',
      '## Naming & vocabulary', '',
      '**2026-08-13 · `FJS-D29` — a fleet server runs an OUTPOST.** It is exact.', '',
    ].join('\n'),
    'IDEAS/overview.md': [
      '# Ideas', '', '## Wave 0 — repairs', '',
      '| # | Item | Effort | Payoff | Edge | Realms | Status | Source |',
      '| --- | --- | --- | --- | --- | --- | --- | --- |',
      '| 0.2 | **Live-store filter leak** | S | ●●●○ | — | A U | **defect** | `live-queries.md` |', '',
    ].join('\n'),
    'IDEAS/live-queries.md': '# Idea — Live queries: scoped to a query\n\n**Status: IDEA.** Dated 2026-08-04.\n',
  })

  test('the hub offers three registers, not one', () => {
    const hub = hubOf(renderAtlas(threeRegisters('hub-three')))

    expect(hub).toContain('ISSUES.md')
    expect(hub).toContain('DECISIONS.md')
    expect(hub).toContain('IDEAS/overview.md')
  })

  test('a ruling reaches the dossier with its date, its id and its domain', () => {
    const sheet = dossierOf(renderAtlas(threeRegisters('hub-ruling')), 'repo')

    expect(sheet).toContain('FJS-D29')
    expect(sheet).toContain('2026-08-13')
    expect(sheet).toContain('data-sect="Naming &amp; vocabulary"')
  })

  test('an idea carries its status and its wave, and links the paper it is argued in', () => {
    const sheet = dossierOf(renderAtlas(threeRegisters('hub-idea')), 'repo')

    expect(sheet).toContain('data-stat="defect" data-wave="Wave 0"')
    expect(sheet).toContain('href="IDEAS/live-queries.md"')
    expect(sheet).toContain('Live queries: scoped to a query')   // the paper's own H1
  })

  test('four dimensions, one mechanism — every facet control declares which', () => {
    const sheet = dossierOf(renderAtlas(threeRegisters('hub-dims')), 'repo')
    const dims  = new Set([...sheet.matchAll(/data-facet="(\w+)"/g)].map(m => m[1]))

    expect([...dims].sort()).toEqual(['pkg', 'sect', 'stat', 'wave'].concat('sev').sort())
  })

  test('a dimensioned route names its dimension so it cannot land on the wrong table', () => {
    const hub = hubOf(renderAtlas(threeRegisters('hub-dimroute')))
    expect(hub).toContain('href="#/part/repo/stat:defect"')
    expect(hub).toContain('href="#/part/repo/sev:S2"')
  })

  test('each root register is quoted rather than described', () => {
    const model = workspace('hub-docs', {
      'DECISIONS.md': '# Decisions\n\n**The settled register.** Check before relitigating.\n',
    })
    const sheet = dossierOf(renderAtlas(model), 'repo')

    expect(sheet).toContain('DECISIONS.md')
    expect(sheet).toContain('The settled register.')
  })
})

// ─── the page ─────────────────────────────────────────────────────────────────

describe('the page', () => {

  test('renders one file for one tree — it is committed and rechecked', () => {
    expect(renderAtlas(workspace('page-a'))).toBe(renderAtlas(workspace('page-a')))
  })

  test('names its own generator where the snapshot walker reads it', () => {
    const html = renderAtlas(workspace('page-gen'))
    expect(html.split('\n').slice(0, 2)).toEqual(['<!doctype html>', '<!-- generated by: fli ws:atlas -->'])
  })

  test('writes no color of its own — a tone carries the meaning', () => {
    // Invariant 13. A hex here is a theme that stops working: the nine themes
    // move tokens, and a literal moves with none of them.
    const html  = renderAtlas(workspace('page-tones'))
    const local = localStyle(html)
    // A theme is the one place a color is written; everywhere else reads a
    // token, or the nine themes stop reaching it.
    const outsideTheme = local.replace(/\.theme-field\{[\s\S]*?\n\}/, '')

    expect(outsideTheme).not.toMatch(/#[0-9a-fA-F]{3}\b|#[0-9a-fA-F]{6}\b|rgba?\(|hsla?\(/)
    expect(html).toContain('badge danger')
  })

  test('a realm accent is derived from the tone tokens, never picked', () => {
    // Identity is a second axis the vocabulary has no word for, so the atlas
    // adds one — out of the tokens, so every theme still moves all nine.
    const html  = renderAtlas(workspace('page-realms'))
    const local = localStyle(html)

    for (const bucket of ['data', 'api', 'ui', 'testing', 'tooling', 'cross', 'app', 'other', 'claimed'])
      expect(local).toContain(`.b-${bucket}{--realm:`)

    // Every accent resolves through a token — a literal would survive no theme.
    // A theme may name the nine outright; anything else falls back to a tone.
    for (const [, value] of local.matchAll(/\.b-[a-z]+\{--realm:([^}]+)\}\n/g))
      expect(value).toContain('var(--color-')
  })

  // A css package small enough to assert against, laid out the way the real
  // one is: an order declaration, layered imports, and a comment to strip.
  const CSS_SRC = {
    'packages/css/src/index.css': [
      '@layer reset, tokens, themes, components;',
      "@import './foundation/reset.css'  layer(reset);",
      "@import './foundation/tokens.css' layer(tokens);",
      "@import './themes/field.css'      layer(themes);",
      "@import './components/buttons.css' layer(components);",
      '',
    ].join('\n'),
    'packages/css/src/foundation/reset.css': 'a:where([class]){text-decoration:none}\n',
    'packages/css/src/foundation/tokens.css': '/* the ladder */\n:root{--space-sm:0.5rem}\n',
    'packages/css/src/themes/field.css': '.theme-field{--surface:#141210}\n',
    'packages/css/src/components/buttons.css': '.btn{padding:var(--space-sm);content:"/* not a comment */"}\n',
  }

  test('inlines the styling language instead of fetching it', () => {
    // The page opens from a file:// path and a published Artifact is refused
    // an external request by CSP, so a link is a page that does not render.
    const html = renderAtlas(workspace('page-css-inline', CSS_SRC))

    expect(html).toContain('<style id="fjs-css">')
    expect(html).not.toContain('unpkg.com')
    expect(html).toContain('.btn{padding:var(--space-sm)')
  })

  test('the vendored bundle declares layer order first, and wraps each import', () => {
    // Without the declaration, order falls back to first appearance — which
    // agrees with the declaration only by accident of import order. Measured in
    // packages/css/build.js: move the utilities import up and `.btn.text-lg`
    // goes 16px to 14px in the bundle while the source stays 16px.
    const html   = renderAtlas(workspace('page-css-order', CSS_SRC))
    const bundle = html.slice(html.indexOf('<style id="fjs-css">'), html.indexOf('</style>'))

    expect(bundle.indexOf('@layer reset, tokens, themes, components;'))
      .toBeLessThan(bundle.indexOf('@layer reset {'))
    for (const layer of ['reset', 'tokens', 'themes', 'components'])
      expect(bundle).toContain(`@layer ${layer} {`)
  })

  test('the vendored bundle drops comments and keeps strings that look like them', () => {
    // Comments are ~60% of that package's source and none of it is read here.
    // A stripper that is right by luck is one nobody can safely edit, so the
    // quote case is asserted rather than assumed absent.
    const html   = renderAtlas(workspace('page-css-strip', CSS_SRC))
    const bundle = html.slice(html.indexOf('<style id="fjs-css">'), html.indexOf('</style>'))

    expect(bundle).not.toContain('the ladder')
    expect(bundle).toContain('content:"/* not a comment */"')
  })

  test('a workspace with no styling language falls back to the link', () => {
    // The fallback exists for a tree that cannot read the package at all. For a
    // committed snapshot that never happens, which is what stops the two
    // outputs swapping places on one tree.
    const html = renderAtlas(workspace('page-css-absent'))

    expect(html).toContain('unpkg.com/@frontierjs/css/dist/frontier.min.css')
    expect(html).not.toContain('<style id="fjs-css">')
    // field.css lives in the workspace copy, so the published bundle may not
    // carry the theme yet and the page must not offer it.
    expect(html).not.toContain('<option value="field"')
  })

  test('links the styling language with no version range at all', () => {
    // The range used to be DERIVED from the workspace's own copy, on the
    // reasoning that an exact pin 404s because the local version runs ahead of
    // the published one. A caret does not fix that below 1.0, it hides it:
    // `^0.16` means `>=0.16.0 <0.17.0`, so the moment the tree bumped its minor
    // the link named a version the registry has never had and the page rendered
    // as unstyled markup. Measured that day: `@^0.16` 404, no range 302.
    //
    // So the workspace version must not reach the URL at all — asserted with a
    // version deliberately ahead of anything published.
    const model = workspace('page-css', {
      'packages/css/package.json': JSON.stringify({ name: '@frontierjs/css', version: '9.9.9' }),
    })
    const html = renderAtlas(model)
    expect(html).toContain('unpkg.com/@frontierjs/css/dist/frontier.min.css')
    expect(html).not.toContain('@frontierjs/css@')
  })

  test('offers every theme the styling language ships', () => {
    const html = renderAtlas(workspace('page-themes'))
    for (const theme of ['default', 'dark', 'midnight', 'forest', 'sunset', 'elite', 'basecamp', 'notebook', 'press'])
      expect(html).toContain(`<option value="${theme}"`)
  })

  test('every dossier carries its own search box', () => {
    // A dossier is long — litestone's runs to ninety-odd searchable units — and
    // the deck's box narrows the deck, not what is inside a sheet.
    const html   = renderAtlas(workspace('page-search'))
    const sheets = [...html.matchAll(/data-dossier="/g)].length
    // The rendered inputs, not the selectors the page's own script names.
    const boxes  = [...html.matchAll(/<input[^>]*data-dsearch/g)].length
    expect(boxes).toBe(sheets)
    expect(html).toContain('data-dcount')
  })

  test('escapes the prose it quotes', () => {
    const model = workspace('page-esc', {
      'ISSUES.md': '# Issues\n\n## S2 — high\n\n| Id | Pkg | Title | Status | Verified | Detail |\n| --- | --- | --- | --- | --- | --- |\n| FJS-9 | sierra | **A `<script>` in a claim** | open | 2026-08-14 | — |\n',
    })
    expect(renderAtlas(model)).toContain('&lt;script&gt;')
  })
})

/** The dossier for one card, as rendered — everything between its marker and the next. */
function dossierOf(html, key) {
  // Routes are namespaced (`part/…`, `do/…`); a bare key means a part.
  const start = html.indexOf(`data-dossier="${key.includes('/') ? key : `part/${key}`}"`)
  if (start < 0) return null
  // A dossier is a <dialog>; the next one begins where this one ends.
  const end = html.indexOf('<dialog', start + 1)
  return html.slice(start, end < 0 ? undefined : end)
}
