// snapshots.test.js — finding and validating committed snapshots.
//
// The engine behind both `fli test:snapshots` and the framework repo's own CI
// phase. These tests cover the half that decides WHETHER to run something: the
// header parse, the binary allow-list and the argument shape. The half that
// runs it is exercised for real every time either caller runs — and cannot be
// faked here without spawning a subprocess that would reach the network.
//
// The rule the refusals encode: a header is data, and data this executes is a
// supply chain.

import { describe, test, expect, beforeAll, afterAll } from 'bun:test'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'fs'
import { join }   from 'path'
import { tmpdir } from 'os'

import { findSnapshots, formatSnapshotResults, SNAPSHOT_BINS } from '../core/snapshots.js'

let ROOT

function tree(name, files) {
  const dir = join(ROOT, name)
  for (const [path, body] of Object.entries(files)) {
    const full = join(dir, path)
    mkdirSync(join(full, '..'), { recursive: true })
    writeFileSync(full, body)
  }
  return dir
}

const find = (dir) => findSnapshots({ root: dir })
const only = (dir) => find(dir)[0]

beforeAll(() => { ROOT = mkdtempSync(join(tmpdir(), 'fli-snapshots-')) })
afterAll(()  => { try { rmSync(ROOT, { recursive: true, force: true }) } catch {} })

describe('finding snapshots', () => {

  test('reads the generator out of a markdown header', () => {
    const dir = tree('md', {
      'db/access.snapshot.md': '# Access snapshot\n\n<!-- generated by: litestone access --schema schema.lite -->\n\nprose\n',
    })
    expect(only(dir).argv).toEqual(['litestone', 'access', '--schema', 'schema.lite'])
    expect(only(dir).dir).toBe('db')
  })

  test('reads it out of a SQL comment too — the extension is the renderer’s choice', () => {
    const dir = tree('sql', {
      'db/ddl.snapshot.sql': '-- Schema snapshot — DDL\n--\n-- generated by: litestone ddl --schema schema.lite\n--\nCREATE TABLE x (id INTEGER);\n',
    })
    expect(only(dir).argv).toEqual(['litestone', 'ddl', '--schema', 'schema.lite'])
  })

  test('and out of a JSON string, where a comment cannot go', () => {
    const dir = tree('json', {
      'db/x.snapshot.json': '{\n  "$comment": "generated by: litestone access --schema schema.lite",\n  "a": 1\n}\n',
    })
    expect(only(dir).argv).toEqual(['litestone', 'access', '--schema', 'schema.lite'])
  })

  test('finds every snapshot in the tree, sorted, and nothing else', () => {
    const dir = tree('many', {
      'db/access.snapshot.md':  '<!-- generated by: litestone access --schema schema.lite -->\n',
      'web/routes.snapshot.md': '<!-- generated by: sierra routes --config config/sierra.config.js -->\n',
      'db/schema.lite':         'model User { id Int @id }\n',
      'README.md':              '# not a snapshot\n',
    })
    expect(find(dir).map(s => s.file)).toEqual(['db/access.snapshot.md', 'web/routes.snapshot.md'])
  })

  test('skips node_modules — another package’s snapshot is that package’s gate', () => {
    const dir = tree('vendor', {
      'db/access.snapshot.md': '<!-- generated by: litestone access --schema schema.lite -->\n',
      'node_modules/@frontierjs/thing/db/access.snapshot.md': '<!-- generated by: litestone access --schema schema.lite -->\n',
    })
    expect(find(dir).map(s => s.file)).toEqual(['db/access.snapshot.md'])
  })
})

describe('refusing to run the wrong thing', () => {

  test('a snapshot naming no generator is an error, not a skip', () => {
    const dir = tree('bare', { 'db/a.snapshot.md': '# Snapshot\n\nno header here\n' })
    const s = only(dir)
    expect(s.argv).toBeNull()
    // A generated file nothing can recheck looks like a guarantee in review and
    // holds nobody to anything — so it fails rather than being counted as fine.
    expect(s.error).toContain('names no generator')
  })

  test('a generator outside the allow-list is refused by name', () => {
    const dir = tree('evil', { 'db/b.snapshot.md': '<!-- generated by: rm -rf / -->\n' })
    const s = only(dir)
    expect(s.argv).toBeNull()
    expect(s.error).toContain('`rm`')
    expect(SNAPSHOT_BINS.has('rm')).toBe(false)
  })

  test('shell syntax in an argument is refused', () => {
    const dir = tree('shell', { 'db/c.snapshot.md': '<!-- generated by: litestone access --schema $(evil) -->\n' })
    const s = only(dir)
    expect(s.argv).toBeNull()
    expect(s.error).toContain('$(evil)')
  })

  test('every allowed binary is a framework CLI, not a shell', () => {
    // The list is the whole protection. A general-purpose runner here (`bash`,
    // `node`, `npx`) would make the header arbitrary code.
    expect([...SNAPSHOT_BINS.keys()].sort()).toEqual(['fli', 'junction', 'litestone', 'sierra'])
  })
})

describe('reporting', () => {

  test('a failure prints the command that fixes it, with its directory', () => {
    const out = formatSnapshotResults([
      { file: 'db/ddl.snapshot.sql', dir: 'db', argv: ['litestone', 'ddl', '--schema', 'schema.lite'], ok: false, error: 'no longer matches its source' },
      { file: 'db/access.snapshot.md', dir: 'db', argv: ['litestone', 'access'], ok: true, error: null },
    ])
    expect(out.join('\n')).toContain('cd db && bunx litestone ddl --schema schema.lite')
    // A passing snapshot prints nothing — a green line beside a red one is how a
    // failure gets read as noise.
    expect(out.join('\n')).not.toContain('access')
  })
})
